In [31]:
#Importing the required libraries
import pandas as pd

## Exctracting Overnight Mutual Fund's Historical Investment Returns Data

Data in this table: Get Absolute historical returns for ₹1000 investment. If 1Y column value is 1234.5 that means, your ₹1000 investment 1 year back would have grown to ₹1234.5.

In [32]:
overnight_lump_sum_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/returns/overnight-fund.html")
df1 = pd.DataFrame(overnight_lump_sum_rtn[0])

In [33]:
#Renaming historical returns column names
df1.rename({'1W': '1W_RTN(%)', '1M': '1M_RTN(%)', '3M': '3M_RTN(%)', '6M': '6M_RTN(%)',
                 'YTD': 'YTD_RTN(%)', '1Y': '1Y_RTN(%)', '2Y': '2Y_RTN(%)', '3Y': '3Y_RTN(%)',
                 '5Y': '5Y_RTN(%)', '10Y': '10Y_RTN(%)'
          }, axis=1, inplace=True)
print("Shape of the dataframe:", df1.shape)
df1.head()

Shape of the dataframe: (60, 13)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%)
0,Mirae Asset Overnight Fund - Direct Plan - Gro...,-,453.81,0.06%,0.27%,0.77%,1.55%,0.39%,3.15%,-,-,-,-
1,BOI AXA Overnight Fund - Direct Plan - GrowthO...,-,24.81,0.06%,0.26%,0.77%,1.55%,0.39%,3.19%,-,-,-,-
2,PGIM India Overnight Fund - Direct Plan - Grow...,-,137.03,0.06%,0.26%,0.77%,1.54%,0.39%,3.13%,-,-,-,-
3,LIC MF Overnight Fund - Direct Plan - GrowthOv...,-,271.75,0.06%,0.26%,0.76%,1.51%,0.38%,3.05%,-,-,-,-
4,Mahindra Manulife Overnight Fund - Direct Plan...,-,48.63,0.06%,0.27%,0.77%,1.53%,0.39%,3.11%,-,-,-,-

## Exctracting Overnight Mutual Fund's Monthly Returns Data

Data in this table: Get monthly returns. If Jan month column value is 5.4% that means, fund has given 5.4% returns in Jan month.

In [34]:
overnight_monthly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/monthly-returns/overnight-fund.html")
df2 = pd.DataFrame(overnight_monthly_rtn[0])

In [35]:
#Renaming df1 column names
df1.rename({"Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            'MTD': 'MTD_RTN(%)', "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)"
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df2.shape)
df2.head()

Shape of the dataframe: (60, 14)

,Scheme Name,Crisil Rank,MTD,Apr'21,Mar'21,Feb'21,Jan'21,Dec'20,Nov'20,Oct'20,Sep'20,Aug'20,Jul'20,Jun'20
0,BNP Paribas Overnight Fund - Regular Plan - Gr...,-,0.11%,0.25%,0.25%,0.21%,0.25%,0.24%,0.20%,0.23%,0.24%,0.25%,0.24%,0.22%
1,BNP Paribas Overnight Fund - Direct Plan - Gro...,-,0.11%,0.25%,0.26%,0.22%,0.25%,0.25%,0.20%,0.23%,0.25%,0.26%,0.25%,0.23%
2,IDFC Overnight Fund - Regular Plan - GrowthOve...,-,0.10%,0.24%,0.25%,0.20%,0.24%,0.24%,0.18%,0.23%,0.24%,0.24%,0.24%,0.22%
3,IDFC Overnight Fund - Direct Plan - GrowthOver...,-,0.10%,0.25%,0.26%,0.21%,0.25%,0.25%,0.19%,0.24%,0.25%,0.25%,0.25%,0.23%
4,Axis Overnight Fund - Regular Plan - GrowthOve...,-,0.10%,0.24%,0.26%,0.21%,0.25%,0.25%,0.19%,0.23%,0.24%,0.25%,0.25%,0.23%

## Exctracting Overnight Mutual Fund's Quarterly Returns Data

Data in this table: Get quarterly returns. If Q1 column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Mar.

In [36]:
overnight_quarterly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/quarterly-returns/overnight-fund.html")
df3 = pd.DataFrame(overnight_quarterly_rtn[0])

In [37]:
print("Shape of the dataframe:", df3.shape)
df3.head()

Shape of the dataframe: (60, 14)

,Scheme Name,Crisil Rank,QTD,Q1'21,Q4'20,Q3'20,Q2'20,Q1'20,Q4'19,Q3'19,Q2'19,Q1'19,Q4'18,Q3'18
0,ITI Overnight Fund - Regular Plan - GrowthOver...,-,0.34%,0.70%,0.69%,0.73%,0.70%,1.06%,-,-,-,-,-,-
1,ITI Overnight Fund - Direct Plan - GrowthOvern...,-,0.35%,0.73%,0.72%,0.75%,0.72%,1.08%,-,-,-,-,-,-
2,YES Overnight Fund - Direct Plan - GrowthOvern...,-,0.36%,0.72%,0.71%,0.74%,0.67%,1.09%,1.26%,-,-,-,-,-
3,YES Overnight Fund - Regular Plan - GrowthOver...,-,0.35%,0.71%,0.69%,0.72%,0.65%,1.07%,1.25%,-,-,-,-,-
4,Franklin India Overnight Fund - Regular Plan -...,-,0.36%,0.72%,0.71%,0.74%,0.65%,1.03%,1.16%,1.31%,-,-,-,-

## Exctracting Overnight Mutual Fund's Annual Investment Returns Data

Data in this table: Get annual returns. If 2018 year column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Dec/Last date.

In [38]:
overnight_annual_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/annual-returns/overnight-fund.html")
df4 = pd.DataFrame(overnight_annual_rtn[0])

In [39]:
#Renaming yearly returns column names
df4.rename({'2020': '2020_RTN(%)', '2019': '2019_RTN(%)', '2018': '2018_RTN(%)', '2017': '2017_RTN(%)',
                 '2016': '2016_RTN(%)', '2015': '2015_RTN(%)', '2014': '2014_RTN(%)', '2013': '2013_RTN(%)',
                 '2012': '2012_RTN(%)', '2011': '2011_RTN(%)', '2010': '2010_RTN(%)'
               }, axis=1, inplace=True)

print("Shape of the dataframe:", df4.shape)
df4.head()

Shape of the dataframe: (60, 14)

,Scheme Name,Crisil Rank,YTD,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%),2015_RTN(%),2014_RTN(%),2013_RTN(%),2012_RTN(%),2011_RTN(%),2010_RTN(%)
0,ITI Overnight Fund - Regular Plan - Growth Ove...,-,1.06%,3.22%,0.80%,-,-,-,-,-,-,-,-,-
1,ITI Overnight Fund - Direct Plan - Growth Over...,-,1.10%,3.33%,0.82%,-,-,-,-,-,-,-,-,-
2,YES Overnight Fund - Direct Plan - Growth Over...,-,1.09%,3.25%,1.81%,-,-,-,-,-,-,-,-,-
3,YES Overnight Fund - Regular Plan - Growth Ove...,-,1.06%,3.18%,1.79%,-,-,-,-,-,-,-,-,-
4,Franklin India Overnight Fund - Regular Plan -...,-,1.08%,3.18%,3.34%,-,-,-,-,-,-,-,-,-

## Exctracting Overnight Mutual Fund's Rank Within Category Data

Data in this table: Get performance rank within category. If 1Y column value is 3/45 that means, Fund ranked 3rd in terms of performance out of 45 funds in that category.

In [40]:
overnight_rank_in_category = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/ranks/overnight-fund.html")
df5 = pd.DataFrame(overnight_rank_in_category[0])

In [41]:
#Renaming df5 column names
df5.rename({'1W': '1W_Rank', '1M': '1M_Rank', '3M': '3M_Rank', '6M': '6M_Rank', 'YTD': 'YTD_Rank',
            '1Y': '1Y_Rank', '2Y': '2Y_Rank', '3Y': '3Y_Rank', '5Y': '5Y_Rank', '10Y': '10Y_Rank'
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df5.shape)
df5.head()

Shape of the dataframe: (60, 12)

,Scheme Name,Crisil Rank,1W_Rank,1M_Rank,3M_Rank,6M_Rank,YTD_Rank,1Y_Rank,2Y_Rank,3Y_Rank,5Y_Rank,10Y_Rank
0,BOI AXA Overnight Fund - Direct Plan - GrowthO...,-,2/30,5/30,3/30,3/30,5/30,1/30,0/0,0/0,0/0,0/0
1,BOI AXA Overnight Fund - Regular Plan - Growth...,-,2/30,5/30,3/30,4/30,4/30,1/30,0/0,0/0,0/0,0/0
2,Mirae Asset Overnight Fund - Direct Plan - Gro...,-,1/30,3/30,4/30,1/30,3/30,2/30,0/0,0/0,0/0,0/0
3,Edelweiss Overnight Fund - Regular Plan - Grow...,-,19/30,13/30,15/30,8/30,22/30,2/30,0/0,0/0,0/0,0/0
4,Edelweiss Overnight Fund - Direct Plan - Growt...,-,25/30,23/30,25/30,12/30,27/30,3/30,0/0,0/0,0/0,0/0

## Exctracting Overnight Mutual Fund's Risk Ratios Data

Data in this table: Get values of risk ratios calculated on daily returns for last 3 years.

In [42]:
overnight_risk_ratio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/risk-ratios/overnight-fund.html")
df6 = pd.DataFrame(overnight_risk_ratio[0])

In [43]:
#Droping the 'Category' column
df6.drop('Category', inplace=True, axis=1)
print("Shape of the dataframe:", df6.shape)
df6.head()

Shape of the dataframe: (1, 8)

,Scheme Name,Crisil Rank,AuM (Cr),Standard Deviation,Beta,Sharpe Ratio,Jension's Alpha,Treynor's Ratio
0,UTI Overnight Fund - Growth,-,4686.31,0.09,0.0,14.04,1.21,4.69

## Exctracting Overnight Mutual Fund's Portfolio Data

Data in this table: Compare how schemes have invested money across various asset class and number of instruments.

In [44]:
overnight_portfolio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/portfolioassets/overnight-fund.html")
df7 = pd.DataFrame(overnight_portfolio[0])

In [45]:
#Renaming SIP returns column names
df7.rename({'Turnover ratio': 'Turnover ratio(%)'}, axis=1, inplace=True)

print("Shape of the dataframe:", df7.shape)
df7.head()

Shape of the dataframe: (60, 10)

,Scheme Name,Crisil Rank,Turnover ratio(%),% Equity Holding,No of stocks in portfolio,% Debt Holding,No of instruments in portfolio,% MF Holding,% Cash Holding,% Other Holding
0,ICICI Prudential Overnight Fund - Direct Plan ...,-,-,-,-,-,-,-,100.00%,-
1,Union Overnight Fund - Direct Plan - GrowthOve...,-,-,-,-,-,-,-,100.00%,-
2,Baroda Overnight Fund - Direct Plan - GrowthOv...,-,-,-,-,-,-,-,100.00%,-
3,Sundaram Overnight Fund - Direct Plan - Growth...,-,-,-,-,-,-,-,100.00%,-
4,BOI AXA Overnight Fund - Regular Plan - Growth...,-,-,-,-,-,-,-,100.00%,-

## Exctracting Overnight Mutual Fund's Latest NAV Data

Data in this table: Get the latest values of NAV for the mutual funds.

In [46]:
overnight_nav = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/navs/overnight-fund.html")
df8 = pd.DataFrame(overnight_nav[0])

In [47]:
df8.rename({'1D Change' : '1D Change(%)'}, axis=1, inplace=True)
print("Shape of the dataframe:", df8.shape)
df8.head()

Shape of the dataframe: (60, 10)

,Scheme Name,Crisil Rank,AuM (Cr),NAV,1D Change(%),NAV Date,52W High,52WH as on,52W Low,52WL as on
0,SBI Overnight Fund - Direct Plan - GrowthOvern...,-,16581.28,3364.1596,0.01%,13-May-21,3364.1596,13-May-21,3265.6748,17-May-20
1,SBI Overnight Fund - Regular Plan - GrowthOver...,3,16581.28,3331.3592,0.01%,13-May-21,3331.3592,13-May-21,3236.0747,17-May-20
2,HDFC Overnight Fund - Direct Plan - GrowthOver...,-,15706.55,3069.2902,0.01%,13-May-21,3069.2902,13-May-21,2979.9468,17-May-20
3,HDFC Overnight Fund - GrowthOvernight Fund,-,15706.55,3051.1122,0.01%,13-May-21,3051.1122,13-May-21,2965.2373,17-May-20
4,UTI Overnight Fund - Direct Plan - GrowthOvern...,-,4686.31,2828.0099,0.01%,13-May-21,2828.0099,13-May-21,2744.7003,17-May-20

## Exctracting Overnight Mutual Fund's SIP Returns Data

Data in this table: Get absolute SIP returns. If 1Y column value is 10%, that means fund has given 10% returns on your SIP investments started 1 year back from latest NAV date.

In [48]:
overnight_sip_rtns = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/sip-returns/overnight-fund.html")
df9 = pd.DataFrame(overnight_sip_rtns[0])

In [49]:
#Renaming SIP returns column names
df9.rename({'1Y': '1Y_SIP_RTN(%)', '2Y': '2Y_SIP_RTN(%)', '3Y': '3Y_SIP_RTN(%)',
                  '5Y': '5Y_SIP_RTN(%)', '10Y': '10Y_SIP_RTN(%)', 'YTD' : 'YTD_SIP_RTN(%)'
           }, axis=1, inplace=True)

print("Shape of the dataframe:", df9.shape)
df9.head()

Shape of the dataframe: (60, 8)

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,BOI AXA Overnight Fund - Direct Plan - GrowthO...,-,24.81,1.58%,-,-,-,-
1,Mirae Asset Overnight Fund - Direct Plan - Gro...,-,453.81,1.57%,-,-,-,-
2,PGIM India Overnight Fund - Direct Plan - Grow...,-,137.03,1.56%,-,-,-,-
3,HSBC Overnight Fund - Direct Plan - GrowthOver...,-,463.68,1.56%,-,-,-,-
4,JM Overnight Fund - Direct Plan - GrowthOverni...,-,191.07,1.56%,-,-,-,-

In [50]:
df_final = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9],axis=1,sort=False)
print("Shape of the dataframe:", df_final.shape)

Shape of the dataframe: (60, 103)

In [51]:
# Remove duplicate columns by name in Pandas
df_final = df_final.loc[:,~df_final.columns.duplicated()]

# Removing spaces in the column names
#df_final.columns = df_final.columns.str.replace(' ','_')

print("Shape of the dataframe:", df_final.shape)
df_final.head()

Shape of the dataframe: (60, 84)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,NAV Date,52W High,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,Mirae Asset Overnight Fund - Direct Plan - Gro...,-,453.81,0.06%,0.27%,0.77%,1.55%,0.39%,3.15%,-,...,13-May-21,3364.1596,13-May-21,3265.6748,17-May-20,1.58%,-,-,-,-
1,BOI AXA Overnight Fund - Direct Plan - GrowthO...,-,24.81,0.06%,0.26%,0.77%,1.55%,0.39%,3.19%,-,...,13-May-21,3331.3592,13-May-21,3236.0747,17-May-20,1.57%,-,-,-,-
2,PGIM India Overnight Fund - Direct Plan - Grow...,-,137.03,0.06%,0.26%,0.77%,1.54%,0.39%,3.13%,-,...,13-May-21,3069.2902,13-May-21,2979.9468,17-May-20,1.56%,-,-,-,-
3,LIC MF Overnight Fund - Direct Plan - GrowthOv...,-,271.75,0.06%,0.26%,0.76%,1.51%,0.38%,3.05%,-,...,13-May-21,3051.1122,13-May-21,2965.2373,17-May-20,1.56%,-,-,-,-
4,Mahindra Manulife Overnight Fund - Direct Plan...,-,48.63,0.06%,0.27%,0.77%,1.53%,0.39%,3.11%,-,...,13-May-21,2828.0099,13-May-21,2744.7003,17-May-20,1.56%,-,-,-,-

In [52]:
#Exporting the consolidated bpsu mf data as a  csv file
#print("Shape of the dataframe:", df_final.shape)
#df_final.to_csv('bpsu_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + ').csv',
#               index=False)

#Exporting the bpsu mf data columns with its datatype as a  csv file
#df_dtypes.to_csv('bpsu_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')