In [55]:
# Importing respective modules
import pandas as pd
import re

In [56]:
# Reading elss mutual funds csv file
mc_mf = pd.read_csv('mc_mf_data(11-May-2021 13:27:54).csv')

In [57]:
# Extracting a plan from "Scheme Name" column
scheme_name = list(mc_mf['Scheme Name'])
plan = []
for i in scheme_name:
    #print(type(i))
    plan.append(re.findall("Direct|Regular", str(i)))
#plan
for p in plan:
    if len(p) == 0:
        #print(type(p))
        p.append("Regular")
mc_mf['Plan'] = plan

In [58]:
# Extracting a category from "Scheme Name" column
scheme_name = list(mc_mf['Scheme Name'])
category = []
for i in scheme_name:
    #print(type(i))
    category.append(re.findall("Mid Cap Fund", str(i)))
mc_mf['Category'] = category

In [59]:
# Modifiying 'Scheme Name' column
mc_mf['Scheme Name'] = mc_mf['Scheme Name'].str.replace(' - GrowthMid Cap Fund', '')

In [60]:
#Replacing "']" & "['" string with "" in Plan columns
mc_mf['Plan'] = mc_mf['Plan'].astype(str).str.replace("\['","", regex=True)
mc_mf['Plan'] = mc_mf['Plan'].astype(str).str.replace("']","", regex=True)

#Replacing "']" & "['" string with "" in Category columns
mc_mf['Category'] = mc_mf['Category'].astype(str).str.replace("\['","", regex=True)
mc_mf['Category'] = mc_mf['Category'].astype(str).str.replace("']","", regex=True)

In [61]:
#Replacing "ELSS', 'ELSS" string with "ELSS" in Category columns
mc_mf['Category'] = mc_mf['Category'].astype(str).str.replace("Mid Cap Fund', 'Mid Cap Fund","Mid Cap Fund",
                                                              regex=True)

#Replacing "%" string with "" in Crisil Rank, % Debt Holding, No of instruments in portfolio,
# % MF Holding, % Other Holding, Turnover ratio, MTD, 10Y_SIP_RTN(%) & 5Y_SIP_RTN(%) columns
mc_mf[['% Debt Holding', 'No of instruments in portfolio',
          '% MF Holding', '% Other Holding', 'Turnover ratio(%)',
          'MTD', '10Y_SIP_RTN(%)', '5Y_SIP_RTN(%)'         
         ]] = mc_mf[['% Debt Holding', 'No of instruments in portfolio',
                        '% MF Holding', '% Other Holding', 'Turnover ratio(%)',
                        'MTD', '10Y_SIP_RTN(%)', '5Y_SIP_RTN(%)'
                        ]].replace("%", "", regex=True)

#Replacing "-" string with "0" in Crisil Rank columns
mc_mf['Crisil Rank'] = mc_mf['Crisil Rank'].replace("-", "", regex=True)

In [62]:
#Replacing "-" string with "0" in Crisil Rank columns
mc_mf['Crisil Rank'] = mc_mf['Crisil Rank'].replace("", "0", regex=True)

#Replacing "%" with '' in the column
mc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding', '% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)',
         "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20",
         "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19",
         "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)"
         ]] = mc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)"
                       ]].replace("%", "", regex=True)
print("Shape of the dataframe:", mc_mf.shape)
mc_mf.head()

Shape of the dataframe: (54, 86)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
0,Quant Mid Cap Fund - Direct Plan,0,35.85,5.65,6.90,21.96,49.22,24.96,95.42,37.50,...,04-Mar-21,907.5022,18-May-20,48.34,68.60,72.16,84.85,-,Direct,Mid Cap Fund
1,Quant Mid Cap Fund,1,35.85,5.59,6.67,21.30,47.99,24.06,92.14,35.26,...,04-Mar-21,862.3686,18-May-20,46.83,65.40,67.93,79.12,132.94,Regular,Mid Cap Fund
2,Edelweiss Mid Cap Fund - Direct Plan,4,1245.66,2.40,1.43,6.48,37.51,20.27,86.30,28.71,...,10-May-21,210.1800,18-May-20,46.83,72.19,78.34,87.53,-,Direct,Mid Cap Fund
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,2.37,1.30,6.13,36.57,19.67,83.55,26.73,...,10-May-21,197.4700,18-May-20,45.20,68.73,73.41,79.42,-,Regular,Mid Cap Fund
4,Baroda Mid-cap Fund - Plan B (Direct),3,55.70,2.16,1.43,7.10,28.68,14.91,78.25,25.14,...,04-Mar-21,347.4057,18-May-20,41.51,-,-,-,-,Direct,Mid Cap Fund

In [63]:
#Sorting a mc_mf dataframe by "Crisil Rank Column"
mc_mf.sort_values(by=['Crisil Rank', 'Scheme Name', 'AuM (Cr)'], inplace=True, ascending=False)
print("Shape of the dataframe:", mc_mf.shape)
mc_mf.head()

Shape of the dataframe: (54, 86)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
16,PGIM India Midcap Opportunities Fund - Direct ...,5,1107.77,1.76,2.86,9.29,42.76,23.76,113.37,41.28,...,10-May-21,23.3120,18-May-20,35.14,43.20,43.34,50.66,-,Direct,Mid Cap Fund
17,PGIM India Midcap Opportunities Fund,5,1107.77,1.74,2.71,8.80,41.40,22.96,109.55,38.90,...,10-May-21,21.5250,18-May-20,34.75,46.10,50.25,57.10,-,Regular,Mid Cap Fund
48,BNP Paribas Mid Cap Fund - Direct Plan,5,872.66,0.14,-0.08,8.17,37.53,18.44,78.52,26.95,...,06-May-21,9.7667,20-Apr-21,26.33,28.98,29.95,32.53,-,Direct,Mid Cap Fund
49,BNP Paribas Mid Cap Fund,5,872.66,0.11,-0.20,7.78,36.49,17.81,75.85,25.12,...,06-May-21,9.7377,20-Apr-21,26.01,37.62,44.77,65.03,176.27,Regular,Mid Cap Fund
44,UTI Mid Cap Fund,4,5204.57,0.42,-1.08,4.04,29.23,11.67,79.30,25.46,...,03-Mar-21,8.5000,18-May-20,27.49,29.90,27.83,28.85,114.72,Regular,Mid Cap Fund

In [64]:
#Replacing "-" with 'None' in the columns
mc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding', '% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)',
         "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20",
         "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19",
         "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)"
         ]] = mc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)"]].replace({'-' : None})

In [65]:
#Replacing "" with '0' in the columns

mc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding','% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)',
         '10Y_SIP_RTN(%)', "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20",
         "Sep'20", "Aug'20", "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20",
         "Q4'19", "Q3'19", "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)",
         "Standard Deviation", "Beta", "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio", 'Crisil Rank'
         ]] = mc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',\
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)", "Standard Deviation", "Beta",
                       "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio", 'Crisil Rank']].fillna(value='0')

In [66]:
#Changing the datatype of the return & risk ratio columns

mc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding','% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)',
         '10Y_SIP_RTN(%)', "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20",
         "Sep'20", "Aug'20", "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20",
         "Q4'19", "Q3'19", "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)",
         "Standard Deviation", "Beta", "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio"
         ]] = mc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)", "Standard Deviation", "Beta",
                       "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio"]].apply(pd.to_numeric)

In [67]:
#Changing the datatype of the 'Crisil Rank' columns
mc_mf['Crisil Rank'] = mc_mf['Crisil Rank'].astype('int')

In [68]:
#Removing white spaces at both ends in all over the dataframe:

mc_mf.columns = mc_mf.columns.str.strip()

#Checking the data type of all columns in the DataFrame
mc_mf_dtype = mc_mf.dtypes

df_dtypes = pd.DataFrame(mc_mf_dtype)

In [69]:
#Using pandas dataframe.round()function to round off all the decimal values to 2 decimal places
mc_mf = mc_mf.round(2)

In [70]:
# #Exporting the consolidated elss mf data as a  csv file
# print("Shape of the dataframe:", mc_mf.shape)
#mc_mf.to_csv('final_mc_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)',
#                 index=False)

# #Exporting the elss mf data columns with its datatype as a  csv file
# df_dtypes.to_csv('mc_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')

In [71]:
#Exctracting regular mutual funds
regular_mf = mc_mf.loc[mc_mf['Plan'] == 'Regular']
regular_mf.head()

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
17,PGIM India Midcap Opportunities Fund,5,1107.77,1.74,2.71,8.80,41.40,22.96,109.55,38.90,...,10-May-21,21.52,18-May-20,34.75,46.10,50.25,57.10,0.00,Regular,Mid Cap Fund
49,BNP Paribas Mid Cap Fund,5,872.66,0.11,-0.20,7.78,36.49,17.81,75.85,25.12,...,06-May-21,9.74,20-Apr-21,26.01,37.62,44.77,65.03,176.27,Regular,Mid Cap Fund
44,UTI Mid Cap Fund,4,5204.57,0.42,-1.08,4.04,29.23,11.67,79.30,25.46,...,03-Mar-21,8.50,18-May-20,27.49,29.90,27.83,28.85,114.72,Regular,Mid Cap Fund
47,SBI Magnum Midcap Fund - Regular Plan,4,5004.92,0.33,0.31,6.89,42.38,19.28,95.16,25.64,...,08-Apr-21,11.39,18-May-20,27.00,39.69,47.95,71.01,0.00,Regular,Mid Cap Fund
26,Kotak Emerging Equity,4,11430.03,1.11,-0.24,6.29,36.44,19.26,85.64,26.45,...,04-Mar-21,26.23,18-May-20,32.40,0.00,0.00,0.00,0.00,Regular,Mid Cap Fund

In [72]:
# Basic statistics of regular mutual fund df
regular_mf.describe()

,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),...,% Other Holding,NAV,1D Change(%),52W High,52W Low,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
count,27.000000,27.000000,27.000000,27.000000,27.00000,27.000000,27.000000,27.000000,27.000000,27.000000,...,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000,27.000000
mean,2.481481,4360.614444,1.272222,0.795185,5.91000,31.080741,15.094444,75.079630,19.673704,9.408519,...,0.014815,197.444074,0.505926,201.190741,108.962222,31.998148,35.475185,37.283704,36.319259,50.322593
std,1.477273,5763.969670,1.130341,1.744901,4.19172,8.786794,5.017736,18.996107,10.000654,5.329417,...,0.047505,380.910438,0.457781,389.388762,207.262645,8.530411,19.205008,20.394623,28.384186,73.353023
min,0.000000,35.850000,-0.280000,-1.480000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,10.100000,-0.550000,10.160000,7.390000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.500000,501.755000,0.545000,-0.260000,3.80500,27.435000,11.935000,68.020000,16.500000,7.195000,...,0.000000,27.345000,0.265000,27.525000,13.535000,28.410000,32.615000,33.350000,0.000000,0.000000
50%,3.000000,1892.660000,1.110000,0.540000,5.70000,31.280000,14.620000,75.850000,21.970000,9.660000,...,0.000000,63.610000,0.520000,63.610000,37.190000,32.400000,39.690000,43.950000,48.160000,0.000000
75%,3.000000,6273.780000,1.795000,1.340000,6.97000,36.465000,18.535000,83.445000,25.550000,12.755000,...,0.000000,153.860000,0.725000,155.480000,83.030000,36.840000,45.700000,48.345000,56.415000,137.075000
max,5.000000,26471.110000,5.590000,6.670000,21.30000,47.990000,24.060000,109.550000,38.900000,19.220000,...,0.220000,1611.830000,1.890000,1624.720000,862.370000,46.830000,68.730000,73.410000,79.420000,178.080000

In [73]:
# Extracting funds which have 3Y Return', '5Y Return' & '10Y Return' greater than 10%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10) &
                            (regular_mf['10Y_RTN(%)'] > 10)]
print("No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is:", len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV']]

No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is: 11 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV
49,BNP Paribas Mid Cap Fund,5,872.66,75.85,12.49,14.08,17.71,10.10
47,SBI Magnum Midcap Fund - Regular Plan,4,5004.92,95.16,10.97,12.18,17.43,21.32
26,Kotak Emerging Equity,4,11430.03,85.64,13.40,16.94,18.20,47.74
41,Axis Midcap Fund,4,10431.65,59.34,16.65,18.10,18.50,13.24
20,Taurus Discovery (Midcap) Fund,3,67.47,65.24,11.51,17.06,16.17,63.61
31,Tata Mid Cap Growth Fund - Regular Plan,3,1152.49,72.70,13.38,15.52,16.94,83.32
19,Nippon India Growth Fund,3,9123.18,80.81,12.51,16.08,13.53,66.11
29,Invesco India Mid Cap Fund,3,1389.34,66.56,13.00,15.81,17.45,33.37
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,83.55,11.23,16.91,18.20,363.61
35,DSP Midcap Fund - Regular Plan,3,11248.89,61.01,11.06,16.30,16.22,178.31
1,Quant Mid Cap Fund,1,35.85,92.14,19.22,16.32,13.24,1611.83

In [74]:
# Extracting  last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'
#greater than 10%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10) &
                            (regular_mf['10Y_RTN(%)'] > 10)]
print("Last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'greater than 10% is:",
      len(mf_rtn_com.index), '\nFunds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

Last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'greater than 10% is: 11
Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
49,BNP Paribas Mid Cap Fund,5,872.66,10.10,20.04,-0.57,-10.97,53.66,9.56
47,SBI Magnum Midcap Fund - Regular Plan,4,5004.92,21.32,12.12,-0.06,-14.54,41.78,11.28
26,Kotak Emerging Equity,4,11430.03,47.74,21.96,4.59,-17.32,49.01,-1.99
41,Axis Midcap Fund,4,10431.65,13.24,33.14,0.30,-13.76,43.32,3.81
20,Taurus Discovery (Midcap) Fund,3,67.47,63.61,24.15,3.33,-5.16,44.32,0.45
31,Tata Mid Cap Growth Fund - Regular Plan,3,1152.49,83.32,23.60,-2.45,-14.27,24.40,0.00
19,Nippon India Growth Fund,3,9123.18,66.11,22.33,6.81,-10.63,45.32,3.87
29,Invesco India Mid Cap Fund,3,1389.34,33.37,25.15,8.23,-12.04,50.95,-2.11
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,363.61,25.75,1.77,-6.35,46.63,3.24
35,DSP Midcap Fund - Regular Plan,3,11248.89,178.31,47.48,2.20,-15.74,36.96,-2.54
1,Quant Mid Cap Fund,1,35.85,1611.83,0.00,0.00,0.00,0.00,0.00

In [75]:
# Extracting funds which have '3Y Return' & '5Y Return' greater than 12%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 12) & (regular_mf['5Y_RTN(%)'] > 12)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 12% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return' & '5Y Return' greater than 12% is: 8 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
17,PGIM India Midcap Opportunities Fund,5,1107.77,109.55,18.20,18.06,0.00,40.77,0.74,0.00,16.70,0.72
49,BNP Paribas Mid Cap Fund,5,872.66,75.85,12.49,14.08,17.71,10.10,0.00,0.00,0.00,0.00
26,Kotak Emerging Equity,4,11430.03,85.64,13.40,16.94,18.20,47.74,0.00,0.00,0.00,0.00
41,Axis Midcap Fund,4,10431.65,59.34,16.65,18.10,18.50,13.24,0.00,10.24,0.00,0.00
31,Tata Mid Cap Growth Fund - Regular Plan,3,1152.49,72.70,13.38,15.52,16.94,83.32,0.00,0.00,0.00,0.00
19,Nippon India Growth Fund,3,9123.18,80.81,12.51,16.08,13.53,66.11,0.30,61.00,18.79,0.57
29,Invesco India Mid Cap Fund,3,1389.34,66.56,13.00,15.81,17.45,33.37,0.00,0.00,0.00,0.00
1,Quant Mid Cap Fund,1,35.85,92.14,19.22,16.32,13.24,1611.83,0.31,653.00,18.65,0.80

In [76]:
# Extracting last five years annual return for funds which have 3Y Return', '5Y Return' greater than 12%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 12) & (regular_mf['5Y_RTN(%)'] > 12)]
print("Last five years annual return for funds which have '5Y Return' & '10Y Return'greater than 10% is:",
      len(mf_rtn_com.index), '\nFunds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

Last five years annual return for funds which have '5Y Return' & '10Y Return'greater than 10% is: 8
Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
17,PGIM India Midcap Opportunities Fund,5,1107.77,40.77,30.69,0.35,-17.10,35.02,5.98
49,BNP Paribas Mid Cap Fund,5,872.66,10.10,20.04,-0.57,-10.97,53.66,9.56
26,Kotak Emerging Equity,4,11430.03,47.74,21.96,4.59,-17.32,49.01,-1.99
41,Axis Midcap Fund,4,10431.65,13.24,33.14,0.30,-13.76,43.32,3.81
31,Tata Mid Cap Growth Fund - Regular Plan,3,1152.49,83.32,23.60,-2.45,-14.27,24.40,0.00
19,Nippon India Growth Fund,3,9123.18,66.11,22.33,6.81,-10.63,45.32,3.87
29,Invesco India Mid Cap Fund,3,1389.34,33.37,25.15,8.23,-12.04,50.95,-2.11
1,Quant Mid Cap Fund,1,35.85,1611.83,0.00,0.00,0.00,0.00,0.00

In [77]:
# Extracting funds which have '3Y Return' & '5Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 15) & (regular_mf['5Y_RTN(%)'] > 15)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
            'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return' & '5Y Return' greater than 15% is: 3 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
17,PGIM India Midcap Opportunities Fund,5,1107.77,109.55,18.20,18.06,0.00,40.77,0.74,0.00,16.70,0.72
41,Axis Midcap Fund,4,10431.65,59.34,16.65,18.10,18.50,13.24,0.00,10.24,0.00,0.00
1,Quant Mid Cap Fund,1,35.85,92.14,19.22,16.32,13.24,1611.83,0.31,653.00,18.65,0.80

In [78]:
# Extracting last five years annual return for funds which have 3Y Return', '5Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 15) & (regular_mf['5Y_RTN(%)'] > 15)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

No. of funds having '3Y Return' & '5Y Return' greater than 15% is: 3 Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
17,PGIM India Midcap Opportunities Fund,5,1107.77,40.77,30.69,0.35,-17.10,35.02,5.98
41,Axis Midcap Fund,4,10431.65,13.24,33.14,0.30,-13.76,43.32,3.81
1,Quant Mid Cap Fund,1,35.85,1611.83,0.00,0.00,0.00,0.00,0.00

In [79]:
# Extracting funds which have '5Y Return' & '10Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 15) & (regular_mf['10Y_RTN(%)'] > 15)]
print("No. of funds having '5Y Return' & '10Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
            'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '5Y Return' & '10Y Return' greater than 15% is: 9 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
26,Kotak Emerging Equity,4,11430.03,85.64,13.40,16.94,18.20,47.74,0.00,0.00,0.00,0.00
41,Axis Midcap Fund,4,10431.65,59.34,16.65,18.10,18.50,13.24,0.00,10.24,0.00,0.00
20,Taurus Discovery (Midcap) Fund,3,67.47,65.24,11.51,17.06,16.17,63.61,0.66,0.00,19.89,1.21
31,Tata Mid Cap Growth Fund - Regular Plan,3,1152.49,72.70,13.38,15.52,16.94,83.32,0.00,0.00,0.00,0.00
29,Invesco India Mid Cap Fund,3,1389.34,66.56,13.00,15.81,17.45,33.37,0.00,0.00,0.00,0.00
23,HDFC Mid-Cap Opportunities Fund,3,26471.11,82.28,9.38,15.18,17.29,53.36,0.00,0.00,0.00,0.00
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,83.55,11.23,16.91,18.20,363.61,0.51,0.00,18.50,0.80
35,DSP Midcap Fund - Regular Plan,3,11248.89,61.01,11.06,16.30,16.22,178.31,0.00,138.00,0.00,0.00
37,L&T Midcap Fund,2,6395.46,65.35,7.35,15.70,16.54,14.18,0.00,0.00,0.00,0.00

In [80]:
# Extracting last five years annual return for funds which have 5Y Return', '10Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 15) & (regular_mf['10Y_RTN(%)'] > 15)]
print("No. of funds having '5Y Return' & '10Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

No. of funds having '5Y Return' & '10Y Return' greater than 15% is: 9 Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
26,Kotak Emerging Equity,4,11430.03,47.74,21.96,4.59,-17.32,49.01,-1.99
41,Axis Midcap Fund,4,10431.65,13.24,33.14,0.30,-13.76,43.32,3.81
20,Taurus Discovery (Midcap) Fund,3,67.47,63.61,24.15,3.33,-5.16,44.32,0.45
31,Tata Mid Cap Growth Fund - Regular Plan,3,1152.49,83.32,23.60,-2.45,-14.27,24.40,0.00
29,Invesco India Mid Cap Fund,3,1389.34,33.37,25.15,8.23,-12.04,50.95,-2.11
23,HDFC Mid-Cap Opportunities Fund,3,26471.11,53.36,16.28,-3.16,-15.01,46.25,5.82
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,363.61,25.75,1.77,-6.35,46.63,3.24
35,DSP Midcap Fund - Regular Plan,3,11248.89,178.31,47.48,2.20,-15.74,36.96,-2.54
37,L&T Midcap Fund,2,6395.46,14.18,24.37,10.49,-9.04,41.03,11.03

## Portfolio Turnover Ratio(PTR)

Portfolio Turnover Ratio is the frequency in which the assets held under a fund has changed over the years. In simpler words, PTR provides a measurement on how many times the fund managers bought or sold the assets under a fund over a period of time. PTR is often determined by the market conditions and fund management style.

Suppose an equity fund purchased stocks worth Rs. 375 crore and sold stocks worth Rs. 450 crore. The average AUM of the fund is Rs.1500 crore. In this case, the Portfolio turnover ratio of the fund is 25%, which means one-fourth of the stocks were traded.

Funds that have higher turnover ratios, for example, can trigger higher costs for investors. First, a fund thatâ€™s actively managed may charge a higher expense ratio to cover the fund managerâ€™s services. The expense ratio represents the percentage you pay to own the fund on an annualized basis. At the low end, you can find index funds with expense ratios around 0.50% to 0.10%. But the most expensive funds can easily have expense ratios over 1%.

Turnover ratio can also give you an idea of what the fundâ€™s investment strategy is, which is important for choosing funds that align with your goals and objectives. A growth mutual fund, for instance, may have a higher turnover ratio if the fund manager is constantly looking for the best growth stocks to drive returns. But a fund that uses a value investing approach may have a lower turnover ratio if the fund manager is buying assets that have the potential to appreciate over time.

In [81]:
# Top 10 low turnover ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Turnover ratio(%)'] > 0)]
print("Top 10 low turnover ratio regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Turnover ratio(%)']].nsmallest(10, 'Turnover ratio(%)')

Top 10 low turnover ratio regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Turnover ratio(%)
41,Axis Midcap Fund,4,10431.65,59.34,16.65,18.10,18.50,13.24,10.24
40,Franklin India Prima Fund,2,7194.82,72.14,8.55,13.24,16.73,14.48,10.24
51,Motilal Oswal Midcap 30 Fund,1,1892.66,68.60,8.28,10.56,0.00,61.62,28.00
19,Nippon India Growth Fund,3,9123.18,80.81,12.51,16.08,13.53,66.11,61.00
35,DSP Midcap Fund - Regular Plan,3,11248.89,61.01,11.06,16.30,16.22,178.31,138.00
1,Quant Mid Cap Fund,1,35.85,92.14,19.22,16.32,13.24,1611.83,653.00

In [82]:
# Top 10 high turnover ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Turnover ratio(%)'] > 0)]
print("Top 10 high turnover ratio regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Turnover ratio(%)']].nlargest(10, 'Turnover ratio(%)')

Top 10 high turnover ratio regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Turnover ratio(%)
1,Quant Mid Cap Fund,1,35.85,92.14,19.22,16.32,13.24,1611.83,653.00
35,DSP Midcap Fund - Regular Plan,3,11248.89,61.01,11.06,16.30,16.22,178.31,138.00
19,Nippon India Growth Fund,3,9123.18,80.81,12.51,16.08,13.53,66.11,61.00
51,Motilal Oswal Midcap 30 Fund,1,1892.66,68.60,8.28,10.56,0.00,61.62,28.00
41,Axis Midcap Fund,4,10431.65,59.34,16.65,18.10,18.50,13.24,10.24
40,Franklin India Prima Fund,2,7194.82,72.14,8.55,13.24,16.73,14.48,10.24

## Standard Deviation (SD)

The standard deviation of a stock or a mutual fund represents the riskiness of the stock or the mutual fund.

Standard Deviation is a percentage, expressed as an annualised figure.

Higher the standard Deviation, higher is the volatility of the asset. Higher the volatility, higher is the risk.

Do note, volatility or Standard Deviation should not worry you. Markets are volatile, and equities are volatile, mutual funds are volatile; this is the very nature of markets. So if you canâ€™t fathom watching your investment see-saw between gains and loss, then perhaps you should reconsider your investment decision inequities.

In [83]:
# Top 10 low standard deviation regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Standard Deviation'] > 0)]
print("Top 10 low standard deviation regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Standard Deviation']].nsmallest(10, 'Standard Deviation')

Top 10 low standard deviation regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Standard Deviation
17,PGIM India Midcap Opportunities Fund,5,1107.77,109.55,18.20,18.06,0.00,40.77,16.70
11,Mirae Asset Midcap Fund - Regular Plan,0,4539.66,94.98,0.00,0.00,0.00,159.14,18.22
15,ICICI Prudential MidCap Fund,3,2375.17,91.34,8.83,14.55,15.34,201.18,18.23
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,83.55,11.23,16.91,18.20,363.61,18.50
1,Quant Mid Cap Fund,1,35.85,92.14,19.22,16.32,13.24,1611.83,18.65
19,Nippon India Growth Fund,3,9123.18,80.81,12.51,16.08,13.53,66.11,18.79
7,Baroda Mid-cap Fund - Plan A,3,55.70,76.93,9.43,14.97,4.15,1261.53,19.24
6,Mahindra Manulife Mid Cap Unnati Yojana - Regu...,3,649.85,74.16,13.36,0.00,0.00,577.91,19.36
9,Aditya Birla Sun Life Midcap Fund - Regular Plan,2,2697.22,77.47,4.97,11.00,13.15,97.26,19.55
20,Taurus Discovery (Midcap) Fund,3,67.47,65.24,11.51,17.06,16.17,63.61,19.89

In [84]:
# Top 10 high standard deviation regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Standard Deviation'] > 0)]
print("Top 10 high standard deviation regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Standard Deviation']].nlargest(10, 'Standard Deviation')

Top 10 high standard deviation regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Standard Deviation
13,Principal Midcap Fund - Regular Plan,0,353.66,71.44,0.00,0.00,0.00,148.58,19.98
20,Taurus Discovery (Midcap) Fund,3,67.47,65.24,11.51,17.06,16.17,63.61,19.89
9,Aditya Birla Sun Life Midcap Fund - Regular Plan,2,2697.22,77.47,4.97,11.00,13.15,97.26,19.55
6,Mahindra Manulife Mid Cap Unnati Yojana - Regu...,3,649.85,74.16,13.36,0.00,0.00,577.91,19.36
7,Baroda Mid-cap Fund - Plan A,3,55.70,76.93,9.43,14.97,4.15,1261.53,19.24
19,Nippon India Growth Fund,3,9123.18,80.81,12.51,16.08,13.53,66.11,18.79
1,Quant Mid Cap Fund,1,35.85,92.14,19.22,16.32,13.24,1611.83,18.65
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,83.55,11.23,16.91,18.20,363.61,18.50
15,ICICI Prudential MidCap Fund,3,2375.17,91.34,8.83,14.55,15.34,201.18,18.23
11,Mirae Asset Midcap Fund - Regular Plan,0,4539.66,94.98,0.00,0.00,0.00,159.14,18.22

## Beta Ratios

A Beta Ratio in Mutual Funds offers investors the data on the degree of the volatility a Mutual Fund displays in response to market fluctuations. An investor can determine which fund would be best suited to meet his/her financial objectives.

Suppose, the beta ratio of a specific Mutual Fund is 0.7 or 70%; it means the fund is 0.3 or 30% less volatile than the benchmark index. A Beta ratio value of 1 indicates a lower risk and lower growth potential compared to ratios at par or above 1.

Investors with a low-risk appetite would always prefer a lower beta ratio in Mutual Funds as it indicates a steadier response to a volatile market condition. Similarly, investors with the investment objective of higher returns would prefer beta ratios of 1 or more than 1.

In [85]:
# Top 10 low beta regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 0)]
print("Top 10 low beta regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']].nsmallest(10, 'Beta')

Top 10 low beta regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
19,Nippon India Growth Fund,3,9123.18,80.81,12.51,16.08,13.53,66.11,0.57
17,PGIM India Midcap Opportunities Fund,5,1107.77,109.55,18.20,18.06,0.00,40.77,0.72
15,ICICI Prudential MidCap Fund,3,2375.17,91.34,8.83,14.55,15.34,201.18,0.78
11,Mirae Asset Midcap Fund - Regular Plan,0,4539.66,94.98,0.00,0.00,0.00,159.14,0.78
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,83.55,11.23,16.91,18.20,363.61,0.80
7,Baroda Mid-cap Fund - Plan A,3,55.70,76.93,9.43,14.97,4.15,1261.53,0.80
1,Quant Mid Cap Fund,1,35.85,92.14,19.22,16.32,13.24,1611.83,0.80
9,Aditya Birla Sun Life Midcap Fund - Regular Plan,2,2697.22,77.47,4.97,11.00,13.15,97.26,0.84
13,Principal Midcap Fund - Regular Plan,0,353.66,71.44,0.00,0.00,0.00,148.58,0.85
6,Mahindra Manulife Mid Cap Unnati Yojana - Regu...,3,649.85,74.16,13.36,0.00,0.00,577.91,0.89

In [86]:
# Top 10 high beta regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 0)]
print("Top 10 high beta regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']].nlargest(10, 'Beta')

Top 10 high beta regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
20,Taurus Discovery (Midcap) Fund,3,67.47,65.24,11.51,17.06,16.17,63.61,1.21
6,Mahindra Manulife Mid Cap Unnati Yojana - Regu...,3,649.85,74.16,13.36,0.00,0.00,577.91,0.89
13,Principal Midcap Fund - Regular Plan,0,353.66,71.44,0.00,0.00,0.00,148.58,0.85
9,Aditya Birla Sun Life Midcap Fund - Regular Plan,2,2697.22,77.47,4.97,11.00,13.15,97.26,0.84
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,83.55,11.23,16.91,18.20,363.61,0.80
7,Baroda Mid-cap Fund - Plan A,3,55.70,76.93,9.43,14.97,4.15,1261.53,0.80
1,Quant Mid Cap Fund,1,35.85,92.14,19.22,16.32,13.24,1611.83,0.80
15,ICICI Prudential MidCap Fund,3,2375.17,91.34,8.83,14.55,15.34,201.18,0.78
11,Mirae Asset Midcap Fund - Regular Plan,0,4539.66,94.98,0.00,0.00,0.00,159.14,0.78
17,PGIM India Midcap Opportunities Fund,5,1107.77,109.55,18.20,18.06,0.00,40.77,0.72

In [87]:
# Funds with 'Beta' lesser than 1.00
mf_tr = regular_mf.loc[(regular_mf['Beta'] < 1.00) & (regular_mf['Beta'] != 0.00)]
print("Funds with 'Beta' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']]

Funds with 'Beta' lesser than 1.00 are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
17,PGIM India Midcap Opportunities Fund,5,1107.77,109.55,18.20,18.06,0.00,40.77,0.72
19,Nippon India Growth Fund,3,9123.18,80.81,12.51,16.08,13.53,66.11,0.57
6,Mahindra Manulife Mid Cap Unnati Yojana - Regu...,3,649.85,74.16,13.36,0.00,0.00,577.91,0.89
15,ICICI Prudential MidCap Fund,3,2375.17,91.34,8.83,14.55,15.34,201.18,0.78
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,83.55,11.23,16.91,18.20,363.61,0.80
7,Baroda Mid-cap Fund - Plan A,3,55.70,76.93,9.43,14.97,4.15,1261.53,0.80
9,Aditya Birla Sun Life Midcap Fund - Regular Plan,2,2697.22,77.47,4.97,11.00,13.15,97.26,0.84
1,Quant Mid Cap Fund,1,35.85,92.14,19.22,16.32,13.24,1611.83,0.80
13,Principal Midcap Fund - Regular Plan,0,353.66,71.44,0.00,0.00,0.00,148.58,0.85
11,Mirae Asset Midcap Fund - Regular Plan,0,4539.66,94.98,0.00,0.00,0.00,159.14,0.78

In [88]:
# Funds with 'Beta' greater than 1.00
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 1.00) & (regular_mf['Beta'] != 0.00)]
print("Funds with 'Beta' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']]

Funds with 'Beta' lesser than 1.00 are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
20,Taurus Discovery (Midcap) Fund,3,67.47,65.24,11.51,17.06,16.17,63.61,1.21

## What is Sharpe Ratio?

Sharpe Ratio of a mutual fund reveals its potential risk-adjusted returns. The risk-adjusted returns are the returns earned by an investment over the returns generated by any risk-free asset such as a fixed deposit. However, higher returns indicate extra risk. Higher Sharpe Ratio means greater returns from an investment but with a higher risk level. Therefore, it justifies the underlying volatility of the funds. The investors aiming for higher returns will have to invest in funds with higher risk factors.

Investments with less than 1.00 Sharpe Ratio do not generate high returns. Contrarily, investment with Sharpe Ratio of 1.00 to 3.00 or above have higher returns subsequently.

In [89]:
# Top 10 low sharpe ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 0)]
print("Top 10 low 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']].nsmallest(10, 'Sharpe Ratio')

Top 10 low 'Sharpe Ratio' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
9,Aditya Birla Sun Life Midcap Fund - Regular Plan,2,2697.22,77.47,4.97,11.00,13.15,97.26,0.09
13,Principal Midcap Fund - Regular Plan,0,353.66,71.44,0.00,0.00,0.00,148.58,0.19
19,Nippon India Growth Fund,3,9123.18,80.81,12.51,16.08,13.53,66.11,0.30
1,Quant Mid Cap Fund,1,35.85,92.14,19.22,16.32,13.24,1611.83,0.31
6,Mahindra Manulife Mid Cap Unnati Yojana - Regu...,3,649.85,74.16,13.36,0.00,0.00,577.91,0.39
15,ICICI Prudential MidCap Fund,3,2375.17,91.34,8.83,14.55,15.34,201.18,0.42
7,Baroda Mid-cap Fund - Plan A,3,55.70,76.93,9.43,14.97,4.15,1261.53,0.45
11,Mirae Asset Midcap Fund - Regular Plan,0,4539.66,94.98,0.00,0.00,0.00,159.14,0.48
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,83.55,11.23,16.91,18.20,363.61,0.51
20,Taurus Discovery (Midcap) Fund,3,67.47,65.24,11.51,17.06,16.17,63.61,0.66

In [90]:
# Top 10 high sharpe ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 0)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']].nlargest(10, 'Sharpe Ratio')

Top 10 high 'Sharpe Ratio' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
17,PGIM India Midcap Opportunities Fund,5,1107.77,109.55,18.20,18.06,0.00,40.77,0.74
20,Taurus Discovery (Midcap) Fund,3,67.47,65.24,11.51,17.06,16.17,63.61,0.66
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,83.55,11.23,16.91,18.20,363.61,0.51
11,Mirae Asset Midcap Fund - Regular Plan,0,4539.66,94.98,0.00,0.00,0.00,159.14,0.48
7,Baroda Mid-cap Fund - Plan A,3,55.70,76.93,9.43,14.97,4.15,1261.53,0.45
15,ICICI Prudential MidCap Fund,3,2375.17,91.34,8.83,14.55,15.34,201.18,0.42
6,Mahindra Manulife Mid Cap Unnati Yojana - Regu...,3,649.85,74.16,13.36,0.00,0.00,577.91,0.39
1,Quant Mid Cap Fund,1,35.85,92.14,19.22,16.32,13.24,1611.83,0.31
19,Nippon India Growth Fund,3,9123.18,80.81,12.51,16.08,13.53,66.11,0.30
13,Principal Midcap Fund - Regular Plan,0,353.66,71.44,0.00,0.00,0.00,148.58,0.19

In [91]:
# Funds with 'Sharpe Ratio' greater than or equal to 3.00
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] >= 3.00)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [92]:
# Funds with 'Sharpe Ratio' greater than to 2.00 & lesser than 2.99
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 2.00) & (regular_mf['Sharpe Ratio'] < 2.99)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [93]:
# Funds with 'Sharpe Ratio' greater than to 1.00 & lesser than 1.99
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 1.00) & (regular_mf['Sharpe Ratio'] < 1.99)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [94]:
# Funds with 'Sharpe Ratio' lesser than 1.00
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] != 0.00) & (regular_mf['Sharpe Ratio'] < 1.00)]
print("Funds with 'Sharpe Ratio' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Funds with 'Sharpe Ratio' lesser than 1.00 are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
17,PGIM India Midcap Opportunities Fund,5,1107.77,109.55,18.20,18.06,0.00,40.77,0.74
20,Taurus Discovery (Midcap) Fund,3,67.47,65.24,11.51,17.06,16.17,63.61,0.66
19,Nippon India Growth Fund,3,9123.18,80.81,12.51,16.08,13.53,66.11,0.30
6,Mahindra Manulife Mid Cap Unnati Yojana - Regu...,3,649.85,74.16,13.36,0.00,0.00,577.91,0.39
15,ICICI Prudential MidCap Fund,3,2375.17,91.34,8.83,14.55,15.34,201.18,0.42
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,83.55,11.23,16.91,18.20,363.61,0.51
7,Baroda Mid-cap Fund - Plan A,3,55.70,76.93,9.43,14.97,4.15,1261.53,0.45
9,Aditya Birla Sun Life Midcap Fund - Regular Plan,2,2697.22,77.47,4.97,11.00,13.15,97.26,0.09
1,Quant Mid Cap Fund,1,35.85,92.14,19.22,16.32,13.24,1611.83,0.31
13,Principal Midcap Fund - Regular Plan,0,353.66,71.44,0.00,0.00,0.00,148.58,0.19
11,Mirae Asset Midcap Fund - Regular Plan,0,4539.66,94.98,0.00,0.00,0.00,159.14,0.48

In [95]:
# Extracting funds which have 3Y Return', '5Y Return' & '10Y Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_SIP_RTN(%)'] > 25) & (regular_mf['5Y_SIP_RTN(%)'] > 25) &
                            (regular_mf['10Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '3Y SIP Return', '5Y SIP Return' & '10Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y SIP Return', '5Y SIP Return' & '10Y SIP Return' greater than 25% is: 9 Funds

,Scheme Name,Crisil Rank,AuM (Cr),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
49,BNP Paribas Mid Cap Fund,5,872.66,44.77,65.03,176.27,10.10,0.00,0.0,0.00,0.00
44,UTI Mid Cap Fund,4,5204.57,27.83,28.85,114.72,15.53,0.00,0.0,0.00,0.00
31,Tata Mid Cap Growth Fund - Regular Plan,3,1152.49,44.99,48.67,153.27,83.32,0.00,0.0,0.00,0.00
15,ICICI Prudential MidCap Fund,3,2375.17,41.36,46.45,141.21,201.18,0.42,0.0,18.23,0.78
35,DSP Midcap Fund - Regular Plan,3,11248.89,43.63,54.03,152.17,178.31,0.00,138.0,0.00,0.00
7,Baroda Mid-cap Fund - Plan A,3,55.70,51.61,51.14,155.59,1261.53,0.45,0.0,19.24,0.80
1,Quant Mid Cap Fund,1,35.85,67.93,79.12,132.94,1611.83,0.31,653.0,18.65,0.80
51,Motilal Oswal Midcap 30 Fund,1,1892.66,38.82,48.16,154.46,61.62,0.00,28.0,0.00,0.00
11,Mirae Asset Midcap Fund - Regular Plan,0,4539.66,50.41,59.13,178.08,159.14,0.48,0.0,18.22,0.78

In [96]:
# Extracting funds which have 3Y Return' & '5Y Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_SIP_RTN(%)'] > 25) & (regular_mf['5Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '3Y SIP Return' & '5Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y SIP Return' & '5Y SIP Return' greater than 25% is: 18 Funds

,Scheme Name,Crisil Rank,AuM (Cr),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
17,PGIM India Midcap Opportunities Fund,5,1107.77,50.25,57.10,0.00,40.77,0.74,0.00,16.70,0.72
49,BNP Paribas Mid Cap Fund,5,872.66,44.77,65.03,176.27,10.10,0.00,0.00,0.00,0.00
44,UTI Mid Cap Fund,4,5204.57,27.83,28.85,114.72,15.53,0.00,0.00,0.00,0.00
47,SBI Magnum Midcap Fund - Regular Plan,4,5004.92,47.95,71.01,0.00,21.32,0.00,0.00,0.00,0.00
41,Axis Midcap Fund,4,10431.65,43.95,58.66,0.00,13.24,0.00,10.24,0.00,0.00
20,Taurus Discovery (Midcap) Fund,3,67.47,45.84,55.73,0.00,63.61,0.66,0.00,19.89,1.21
31,Tata Mid Cap Growth Fund - Regular Plan,3,1152.49,44.99,48.67,153.27,83.32,0.00,0.00,0.00,0.00
29,Invesco India Mid Cap Fund,3,1389.34,47.04,52.19,0.00,33.37,0.00,0.00,0.00,0.00
15,ICICI Prudential MidCap Fund,3,2375.17,41.36,46.45,141.21,201.18,0.42,0.00,18.23,0.78
23,HDFC Mid-Cap Opportunities Fund,3,26471.11,34.21,35.59,0.00,53.36,0.00,0.00,0.00,0.00
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,73.41,79.42,0.00,363.61,0.51,0.00,18.50,0.80
35,DSP Midcap Fund - Regular Plan,3,11248.89,43.63,54.03,152.17,178.31,0.00,138.00,0.00,0.00
7,Baroda Mid-cap Fund - Plan A,3,55.70,51.61,51.14,155.59,1261.53,0.45,0.00,19.24,0.80
25,IDBI Midcap Fund,2,186.27,46.21,53.43,0.00,64.86,0.00,0.00,0.00,0.00
1,Quant Mid Cap Fund,1,35.85,67.93,79.12,132.94,1611.83,0.31,653.00,18.65,0.80
51,Motilal Oswal Midcap 30 Fund,1,1892.66,38.82,48.16,154.46,61.62,0.00,28.00,0.00,0.00
11,Mirae Asset Midcap Fund - Regular Plan,0,4539.66,50.41,59.13,178.08,159.14,0.48,0.00,18.22,0.78
45,ITI Mid Cap Fund - Regular Plan,0,259.72,32.49,36.91,0.00,14.45,0.00,0.00,0.00,0.00

In [104]:
# Extracting funds which have '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['1Y_SIP_RTN(%)'] > 25) & (regular_mf['2Y_SIP_RTN(%)'] > 25) &
                            (regular_mf['3Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25% is: 21 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
17,PGIM India Midcap Opportunities Fund,5,1107.77,34.75,46.10,50.25,40.77,0.74,0.00,16.70,0.72
49,BNP Paribas Mid Cap Fund,5,872.66,26.01,37.62,44.77,10.10,0.00,0.00,0.00,0.00
44,UTI Mid Cap Fund,4,5204.57,27.49,29.90,27.83,15.53,0.00,0.00,0.00,0.00
47,SBI Magnum Midcap Fund - Regular Plan,4,5004.92,27.00,39.69,47.95,21.32,0.00,0.00,0.00,0.00
41,Axis Midcap Fund,4,10431.65,28.20,39.55,43.95,13.24,0.00,10.24,0.00,0.00
20,Taurus Discovery (Midcap) Fund,3,67.47,33.67,42.34,45.84,63.61,0.66,0.00,19.89,1.21
31,Tata Mid Cap Growth Fund - Regular Plan,3,1152.49,31.37,43.86,44.99,83.32,0.00,0.00,0.00,0.00
29,Invesco India Mid Cap Fund,3,1389.34,32.09,45.30,47.04,33.37,0.00,0.00,0.00,0.00
15,ICICI Prudential MidCap Fund,3,2375.17,36.51,42.29,41.36,201.18,0.42,0.00,18.23,0.78
23,HDFC Mid-Cap Opportunities Fund,3,26471.11,32.98,36.74,34.21,53.36,0.00,0.00,0.00,0.00
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,45.20,68.73,73.41,363.61,0.51,0.00,18.50,0.80
35,DSP Midcap Fund - Regular Plan,3,11248.89,29.69,41.50,43.63,178.31,0.00,138.00,0.00,0.00
7,Baroda Mid-cap Fund - Plan A,3,55.70,40.18,50.99,51.61,1261.53,0.45,0.00,19.24,0.80
37,L&T Midcap Fund,2,6395.46,29.13,37.87,37.28,14.18,0.00,0.00,0.00,0.00
25,IDBI Midcap Fund,2,186.27,32.40,44.46,46.21,64.86,0.00,0.00,0.00,0.00
40,Franklin India Prima Fund,2,7194.82,28.62,36.75,35.29,14.48,0.00,10.24,0.00,0.00
9,Aditya Birla Sun Life Midcap Fund - Regular Plan,2,2697.22,38.46,48.83,52.65,97.26,0.09,0.00,19.55,0.84
1,Quant Mid Cap Fund,1,35.85,46.83,65.40,67.93,1611.83,0.31,653.00,18.65,0.80
13,Principal Midcap Fund - Regular Plan,0,353.66,37.17,46.24,48.74,148.58,0.19,0.00,19.98,0.85
11,Mirae Asset Midcap Fund - Regular Plan,0,4539.66,37.39,48.44,50.41,159.14,0.48,0.00,18.22,0.78
45,ITI Mid Cap Fund - Regular Plan,0,259.72,27.31,30.73,32.49,14.45,0.00,0.00,0.00,0.00

In [98]:
# Top 10 high AuM (Cr) regular mutual funds are
#mf_tr = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 0)]
print("Top 10 high 'AuM (Cr)' regular mutual funds are :")
mf_tr =  mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)',
       'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']].nlargest(10, 'AuM (Cr)')
mf_tr

Top 10 high 'AuM (Cr)' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
19,Nippon India Growth Fund,3,9123.18,80.81,12.51,16.08,13.53,0.30,61.0,18.79,0.57
11,Mirae Asset Midcap Fund - Regular Plan,0,4539.66,94.98,0.00,0.00,0.00,0.48,0.0,18.22,0.78
9,Aditya Birla Sun Life Midcap Fund - Regular Plan,2,2697.22,77.47,4.97,11.00,13.15,0.09,0.0,19.55,0.84
15,ICICI Prudential MidCap Fund,3,2375.17,91.34,8.83,14.55,15.34,0.42,0.0,18.23,0.78
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,83.55,11.23,16.91,18.20,0.51,0.0,18.50,0.80
17,PGIM India Midcap Opportunities Fund,5,1107.77,109.55,18.20,18.06,0.00,0.74,0.0,16.70,0.72
6,Mahindra Manulife Mid Cap Unnati Yojana - Regu...,3,649.85,74.16,13.36,0.00,0.00,0.39,0.0,19.36,0.89
13,Principal Midcap Fund - Regular Plan,0,353.66,71.44,0.00,0.00,0.00,0.19,0.0,19.98,0.85
20,Taurus Discovery (Midcap) Fund,3,67.47,65.24,11.51,17.06,16.17,0.66,0.0,19.89,1.21
7,Baroda Mid-cap Fund - Plan A,3,55.70,76.93,9.43,14.97,4.15,0.45,0.0,19.24,0.80

In [99]:
# Top 10 low AuM (Cr) regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 0)]
print("Top 10 low 'AuM (Cr)' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)',
       'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']].nsmallest(10, 'AuM (Cr)')

Top 10 low 'AuM (Cr)' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
1,Quant Mid Cap Fund,1,35.85,92.14,19.22,16.32,13.24,0.31,653.0,18.65,0.80
7,Baroda Mid-cap Fund - Plan A,3,55.70,76.93,9.43,14.97,4.15,0.45,0.0,19.24,0.80
20,Taurus Discovery (Midcap) Fund,3,67.47,65.24,11.51,17.06,16.17,0.66,0.0,19.89,1.21
49,BNP Paribas Mid Cap Fund,5,872.66,75.85,12.49,14.08,17.71,0.00,0.0,0.00,0.00
17,PGIM India Midcap Opportunities Fund,5,1107.77,109.55,18.20,18.06,0.00,0.74,0.0,16.70,0.72
31,Tata Mid Cap Growth Fund - Regular Plan,3,1152.49,72.70,13.38,15.52,16.94,0.00,0.0,0.00,0.00
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,83.55,11.23,16.91,18.20,0.51,0.0,18.50,0.80
29,Invesco India Mid Cap Fund,3,1389.34,66.56,13.00,15.81,17.45,0.00,0.0,0.00,0.00
51,Motilal Oswal Midcap 30 Fund,1,1892.66,68.60,8.28,10.56,0.00,0.00,28.0,0.00,0.00
15,ICICI Prudential MidCap Fund,3,2375.17,91.34,8.83,14.55,15.34,0.42,0.0,18.23,0.78

In [100]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 0) & (regular_mf['AuM (Cr)'] < 500) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds returns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds eturns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs is: 2 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
20,Taurus Discovery (Midcap) Fund,3,67.47,65.24,11.51,17.06,16.17,63.61,0.66,0.0,19.89,1.21
1,Quant Mid Cap Fund,1,35.85,92.14,19.22,16.32,13.24,1611.83,0.31,653.0,18.65,0.80

In [101]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 500Crs to 1000Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 500) & (regular_mf['AuM (Cr)'] < 1000) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is:", len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is: 1 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
49,BNP Paribas Mid Cap Fund,5,872.66,75.85,12.49,14.08,17.71,10.1,0.0,0.0,0.0,0.0

In [102]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 1000) & (regular_mf['AuM (Cr)'] < 1500) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs is: 4 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
17,PGIM India Midcap Opportunities Fund,5,1107.77,109.55,18.20,18.06,0.00,40.77,0.74,0.0,16.7,0.72
31,Tata Mid Cap Growth Fund - Regular Plan,3,1152.49,72.70,13.38,15.52,16.94,83.32,0.00,0.0,0.0,0.00
29,Invesco India Mid Cap Fund,3,1389.34,66.56,13.00,15.81,17.45,33.37,0.00,0.0,0.0,0.00
3,Edelweiss Mid Cap Fund - Regular Plan,3,1245.66,83.55,11.23,16.91,18.20,363.61,0.51,0.0,18.5,0.80

In [103]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 1500 to 20000Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 1500) & (regular_mf['AuM (Cr)'] < 20000) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds returns 10% in 3year & 5year period which have AuM in between 1500Crs to 20000Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds returns 10% in 3year & 5year period which have AuM in between 1500Crs to 20000Crs is: 5 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
47,SBI Magnum Midcap Fund - Regular Plan,4,5004.92,95.16,10.97,12.18,17.43,21.32,0.0,0.00,0.00,0.00
26,Kotak Emerging Equity,4,11430.03,85.64,13.40,16.94,18.20,47.74,0.0,0.00,0.00,0.00
41,Axis Midcap Fund,4,10431.65,59.34,16.65,18.10,18.50,13.24,0.0,10.24,0.00,0.00
19,Nippon India Growth Fund,3,9123.18,80.81,12.51,16.08,13.53,66.11,0.3,61.00,18.79,0.57
35,DSP Midcap Fund - Regular Plan,3,11248.89,61.01,11.06,16.30,16.22,178.31,0.0,138.00,0.00,0.00