In [25]:
#Importing the required libraries
import pandas as pd

## Equity Savings Fund

Equity Savings funds invest in Equity and Equity Arbitrage positions and Debt. 65% exposure is maintained in Equity Funds.

## Exctracting Equity Savings Mutual Fund's Historical Investment Returns Data

Data in this table: Get Absolute historical returns for ₹1000 investment. If 1Y column value is 1234.5 that means, your ₹1000 investment 1 year back would have grown to ₹1234.5.

In [26]:
es_lump_sum_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/returns/equity-savings.html")
df1 = pd.DataFrame(es_lump_sum_rtn[0])

In [27]:
#Renaming historical returns column names
df1.rename({'1W': '1W_RTN(%)', '1M': '1M_RTN(%)', '3M': '3M_RTN(%)', '6M': '6M_RTN(%)',
                 'YTD': 'YTD_RTN(%)', '1Y': '1Y_RTN(%)', '2Y': '2Y_RTN(%)', '3Y': '3Y_RTN(%)',
                 '5Y': '5Y_RTN(%)', '10Y': '10Y_RTN(%)'
          }, axis=1, inplace=True)
print("Shape of the dataframe:", df1.shape)
df1.head()

Shape of the dataframe: (48, 13)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%)
0,Principal Equity Savings Fund - Direct Plan - ...,-,62.07,0.59%,2.28%,0.36%,10.68%,1.83%,31.62%,13.27%,10.24%,10.15%,-
1,Principal Equity Savings Fund - Growth Accumul...,1,62.07,0.56%,2.16%,-0.01%,9.91%,1.64%,29.92%,11.90%,8.81%,8.92%,7.64%
2,HDFC Equity Savings Fund - Direct Plan - Growt...,-,2304.80,0.47%,2.60%,1.69%,13.22%,2.50%,30.04%,10.41%,8.86%,11.65%,-
3,HDFC Equity Savings Fund - GrowthEquity Savings,-,2304.80,0.46%,2.53%,1.51%,12.79%,2.40%,29.04%,9.60%,7.84%,10.35%,9.24%
4,DSP Equity Savings Fund - Direct Plan - Growth...,-,361.43,0.37%,1.31%,2.21%,10.58%,1.21%,30.94%,11.19%,8.21%,9.61%,-

## Exctracting Equity Savings Mutual Fund's Monthly Returns Data

Data in this table: Get monthly returns. If Jan month column value is 5.4% that means, fund has given 5.4% returns in Jan month.

In [28]:
es_monthly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/monthly-returns/equity-savings.html")
df2 = pd.DataFrame(es_monthly_rtn[0])

In [29]:
#Renaming df1 column names
df1.rename({"Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            'MTD': 'MTD_RTN(%)', "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)"
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df2.shape)
df2.head()

Shape of the dataframe: (48, 14)

,Scheme Name,Crisil Rank,MTD,Apr'21,Mar'21,Feb'21,Jan'21,Dec'20,Nov'20,Oct'20,Sep'20,Aug'20,Jul'20,Jun'20
0,IDFC Equity Savings Fund - Regular Plan - Grow...,-,0.65%,-0.35%,-0.17%,0.88%,0.40%,1.67%,3.23%,0.38%,-0.14%,1.53%,2.05%,3.08%
1,IDFC Equity Savings Fund - Direct Plan - Growt...,-,0.69%,-0.28%,-0.08%,0.95%,0.50%,1.79%,3.31%,0.49%,-0.09%,1.63%,2.13%,3.11%
2,Axis Equity Saver Fund - GrowthEquity Savings,-,0.72%,-0.65%,0.26%,0.73%,-2.06%,3.16%,5.46%,1.85%,-0.60%,0.91%,2.71%,3.04%
3,Axis Equity Saver Fund - Direct Plan - GrowthE...,-,0.74%,-0.49%,0.43%,0.75%,-2.00%,3.29%,5.61%,1.95%,-0.49%,0.92%,2.85%,3.10%
4,Aditya Birla Sun Life Equity Savings Fund - Re...,-,-0.25%,-0.12%,0.12%,2.17%,-0.83%,2.64%,5.96%,0.71%,-,3.08%,1.64%,2.60%

## Exctracting Equity Savings Mutual Fund's Quarterly Returns Data

Data in this table: Get quarterly returns. If Q1 column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Mar.

In [30]:
es_quarterly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/quarterly-returns/equity-savings.html")
df3 = pd.DataFrame(es_quarterly_rtn[0])

In [31]:
print("Shape of the dataframe:", df3.shape)
df3.head()

Shape of the dataframe: (48, 14)

,Scheme Name,Crisil Rank,QTD,Q1'21,Q4'20,Q3'20,Q2'20,Q1'20,Q4'19,Q3'19,Q2'19,Q1'19,Q4'18,Q3'18
0,IDFC Equity Savings Fund - Regular Plan - Grow...,-,0.30%,2.17%,5.92%,3.61%,12.86%,-10.93%,2.50%,-1.37%,1.85%,2.15%,0.72%,0.52%
1,IDFC Equity Savings Fund - Direct Plan - Growt...,-,0.41%,2.46%,6.21%,3.84%,13.11%,-10.65%,2.76%,-1.17%,2.06%,2.31%,1.04%,0.91%
2,Axis Equity Saver Fund - GrowthEquity Savings,-,0.07%,1.47%,11.28%,3.64%,9.16%,-10.85%,2.36%,1.54%,1.48%,2.90%,1.14%,0.33%
3,Axis Equity Saver Fund - Direct Plan - GrowthE...,-,0.24%,1.81%,11.65%,3.95%,9.48%,-10.59%,2.61%,1.61%,1.72%,3.17%,1.41%,0.55%
4,Aditya Birla Sun Life Equity Savings Fund - Re...,-,-0.37%,3.53%,9.89%,5.22%,8.95%,-11.40%,4.08%,-0.37%,1.87%,2.23%,1.01%,-1.07%

## Exctracting Equity Savings Mutual Fund's Annual Investment Returns Data

Data in this table: Get annual returns. If 2018 year column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Dec/Last date.

In [32]:
es_annual_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/annual-returns/equity-savings.html")
df4 = pd.DataFrame(es_annual_rtn[0])

In [33]:
#Renaming yearly returns column names
df4.rename({'2020': '2020_RTN(%)', '2019': '2019_RTN(%)', '2018': '2018_RTN(%)', '2017': '2017_RTN(%)',
                 '2016': '2016_RTN(%)', '2015': '2015_RTN(%)', '2014': '2014_RTN(%)', '2013': '2013_RTN(%)',
                 '2012': '2012_RTN(%)', '2011': '2011_RTN(%)', '2010': '2010_RTN(%)'
               }, axis=1, inplace=True)

print("Shape of the dataframe:", df4.shape)
df4.head()

Shape of the dataframe: (48, 14)

,Scheme Name,Crisil Rank,YTD,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%),2015_RTN(%),2014_RTN(%),2013_RTN(%),2012_RTN(%),2011_RTN(%),2010_RTN(%)
0,IDFC Equity Savings Fund - Regular Plan - Grow...,-,2.79%,9.57%,5.16%,3.09%,4.64%,7.34%,6.63%,7.98%,8.99%,9.07%,6.54%,5.54%
1,IDFC Equity Savings Fund - Direct Plan - Growt...,-,3.22%,10.69%,6.09%,4.36%,5.50%,8.02%,7.41%,8.58%,-,-,-,-
2,Axis Equity Saver Fund - Growth Equity Savings,-,1.93%,11.45%,8.53%,5.44%,14.67%,2.29%,0.50%,-,-,-,-,-
3,Axis Equity Saver Fund - Direct Plan - Growth ...,-,2.43%,12.84%,9.74%,6.60%,16.05%,3.56%,1.00%,-,-,-,-,-
4,Aditya Birla Sun Life Equity Savings Fund - Re...,-,3.40%,10.75%,7.60%,-1.52%,17.29%,7.53%,3.66%,1.00%,-,-,-,-

## Exctracting Equity Savings Mutual Fund's Rank Within Category Data

Data in this table: Get performance rank within category. If 1Y column value is 3/45 that means, Fund ranked 3rd in terms of performance out of 45 funds in that category.

In [34]:
es_rank_in_category = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/ranks/equity-savings.html")
df5 = pd.DataFrame(es_rank_in_category[0])

In [35]:
#Renaming df5 column names
df5.rename({'1W': '1W_Rank', '1M': '1M_Rank', '3M': '3M_Rank', '6M': '6M_Rank', 'YTD': 'YTD_Rank',
            '1Y': '1Y_Rank', '2Y': '2Y_Rank', '3Y': '3Y_Rank', '5Y': '5Y_Rank', '10Y': '10Y_Rank'
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df5.shape)
df5.head()

Shape of the dataframe: (48, 12)

,Scheme Name,Crisil Rank,1W_Rank,1M_Rank,3M_Rank,6M_Rank,YTD_Rank,1Y_Rank,2Y_Rank,3Y_Rank,5Y_Rank,10Y_Rank
0,Mahindra Manulife Equity Savings Dhan Sanchay ...,-,10/24,9/24,9/24,2/24,11/24,1/24,2/22,1/16,0/0,0/0
1,L&T Equity Savings Fund - GrowthEquity Savings,-,5/24,7/24,4/24,3/24,6/24,1/24,14/22,15/16,10/15,0/0
2,L&T Equity Savings Fund - Direct Plan - Growth...,-,5/24,8/24,4/24,4/24,6/24,2/24,13/22,15/16,11/15,0/0
3,Mahindra Manulife Equity Savings Dhan Sanchay ...,-,13/24,9/24,12/24,2/24,11/24,2/24,2/22,1/16,0/0,0/0
4,Mirae Asset Equity Savings Fund - GrowthEquity...,-,12/24,5/24,5/24,7/24,4/24,3/24,1/22,0/0,0/0,0/0

## Exctracting Equity Savings Mutual Fund's Risk Ratios Data

Data in this table: Get values of risk ratios calculated on daily returns for last 3 years.

In [36]:
es_risk_ratio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/risk-ratios/equity-savings.html")
df6 = pd.DataFrame(es_risk_ratio[0])

In [37]:
#Droping the 'Category' column
df6.drop('Category', inplace=True, axis=1)
print("Shape of the dataframe:", df6.shape)
df6.head()

Shape of the dataframe: (18, 8)

,Scheme Name,Crisil Rank,AuM (Cr),Standard Deviation,Beta,Sharpe Ratio,Jension's Alpha,Treynor's Ratio
0,Franklin India Equity Savings Fund - Growth,-,117.77,8.47,0.35,0.29,0.38,0.07
1,ICICI Prudential Equity Savings Fund - Growth,-,1109.98,8.42,-,0.47,-,0.11
2,Principal Equity Savings Fund - Growth Accumul...,1,62.07,7.63,0.34,0.59,1.71,0.13
3,Kotak Equity Savings Fund - Growth,-,1382.75,8.09,-,0.52,-,0.12
4,Mahindra Manulife Equity Savings Dhan Sanchay ...,-,227.44,10.72,-,0.45,-,0.10

## Exctracting Equity Savings Mutual Fund's Portfolio Data

Data in this table: Compare how schemes have invested money across various asset class and number of instruments.

In [38]:
es_portfolio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/portfolioassets/equity-savings.html")
df7 = pd.DataFrame(es_portfolio[0])

In [39]:
#Renaming SIP returns column names
df7.rename({'Turnover ratio': 'Turnover ratio(%)'}, axis=1, inplace=True)

print("Shape of the dataframe:", df7.shape)
df7.head()

Shape of the dataframe: (48, 10)

,Scheme Name,Crisil Rank,Turnover ratio(%),% Equity Holding,No of stocks in portfolio,% Debt Holding,No of instruments in portfolio,% MF Holding,% Cash Holding,% Other Holding
0,PGIM India Equity Savings Fund - Direct Plan -...,-,-,139.50%,110,1.86%,2,19.86%,103.70%,-
1,PGIM India Equity Savings Fund - GrowthEquity ...,3,-,139.50%,110,1.86%,2,19.86%,103.70%,-
2,Aditya Birla Sun Life Equity Savings Fund - Di...,-,-,79.97%,53,3.65%,1,4.13%,12.25%,-
3,Aditya Birla Sun Life Equity Savings Fund - Re...,-,-,79.97%,53,3.65%,1,4.13%,12.25%,-
4,UTI Equity Savings Fund - GrowthEquity Savings,-,-,73.08%,33,12.35%,8,-,14.57%,-

## Exctracting Equity Savings Mutual Fund's Latest NAV Data

Data in this table: Get the latest values of NAV for the mutual funds.

In [40]:
es_nav = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/navs/equity-savings.html")
df8 = pd.DataFrame(es_nav[0])

In [41]:
df8.rename({'1D Change' : '1D Change(%)'}, axis=1, inplace=True)
print("Shape of the dataframe:", df8.shape)
df8.head()

Shape of the dataframe: (48, 10)

,Scheme Name,Crisil Rank,AuM (Cr),NAV,1D Change(%),NAV Date,52W High,52WH as on,52W Low,52WL as on
0,HDFC Equity Savings Fund - Direct Plan - Growt...,-,2304.80,47.1370,0.73%,17-May-21,47.1370,17-May-21,36.0840,20-May-20
1,Principal Equity Savings Fund - Direct Plan - ...,-,62.07,48.3995,0.7%,17-May-21,48.3995,17-May-21,36.7486,26-May-20
2,HDFC Equity Savings Fund - GrowthEquity Savings,-,2304.80,43.7410,0.72%,17-May-21,43.7410,17-May-21,33.7410,20-May-20
3,Principal Equity Savings Fund - Growth Accumul...,1,62.07,44.6377,0.69%,17-May-21,44.7070,03-Mar-21,34.3277,26-May-20
4,Tata Equity Savings Fund - Direct Plan - Growt...,-,99.99,41.6698,0.6%,17-May-21,41.9410,15-Feb-21,33.7504,26-May-20

## Exctracting Equity Savings Mutual Fund's SIP Returns Data

Data in this table: Get absolute SIP returns. If 1Y column value is 10%, that means fund has given 10% returns on your SIP investments started 1 year back from latest NAV date.

In [42]:
es_sip_rtns = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/sip-returns/equity-savings.html")
df9 = pd.DataFrame(es_sip_rtns[0])

In [43]:
#Renaming SIP returns column names
df9.rename({'1Y': '1Y_SIP_RTN(%)', '2Y': '2Y_SIP_RTN(%)', '3Y': '3Y_SIP_RTN(%)',
                  '5Y': '5Y_SIP_RTN(%)', '10Y': '10Y_SIP_RTN(%)', 'YTD' : 'YTD_SIP_RTN(%)'
           }, axis=1, inplace=True)

print("Shape of the dataframe:", df9.shape)
df9.head()

Shape of the dataframe: (48, 8)

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,HDFC Equity Savings Fund - Direct Plan - Growt...,-,2304.80,14.01%,17.83%,20.55%,29.56%,-
1,Mahindra Manulife Equity Savings Dhan Sanchay ...,-,227.44,13.88%,20.81%,25.56%,-,-
2,Mirae Asset Equity Savings Fund - Direct Plan ...,-,219.00,13.62%,20.97%,-,-,-
3,L&T Equity Savings Fund - Direct Plan - Growth...,-,67.20,13.53%,18.09%,19.88%,25.91%,-
4,HDFC Equity Savings Fund - GrowthEquity Savings,-,2304.80,13.51%,16.89%,19.05%,26.12%,61.68%

In [44]:
df_final = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9],axis=1,sort=False)
print("Shape of the dataframe:", df_final.shape)

Shape of the dataframe: (48, 103)

In [45]:
# Remove duplicate columns by name in Pandas
df_final = df_final.loc[:,~df_final.columns.duplicated()]

# Removing spaces in the column names
#df_final.columns = df_final.columns.str.replace(' ','_')

print("Shape of the dataframe:", df_final.shape)
df_final.head()

Shape of the dataframe: (48, 84)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,NAV Date,52W High,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,Principal Equity Savings Fund - Direct Plan - ...,-,62.07,0.59%,2.28%,0.36%,10.68%,1.83%,31.62%,13.27%,...,17-May-21,47.1370,17-May-21,36.0840,20-May-20,14.01%,17.83%,20.55%,29.56%,-
1,Principal Equity Savings Fund - Growth Accumul...,1,62.07,0.56%,2.16%,-0.01%,9.91%,1.64%,29.92%,11.90%,...,17-May-21,48.3995,17-May-21,36.7486,26-May-20,13.88%,20.81%,25.56%,-,-
2,HDFC Equity Savings Fund - Direct Plan - Growt...,-,2304.80,0.47%,2.60%,1.69%,13.22%,2.50%,30.04%,10.41%,...,17-May-21,43.7410,17-May-21,33.7410,20-May-20,13.62%,20.97%,-,-,-
3,HDFC Equity Savings Fund - GrowthEquity Savings,-,2304.80,0.46%,2.53%,1.51%,12.79%,2.40%,29.04%,9.60%,...,17-May-21,44.7070,03-Mar-21,34.3277,26-May-20,13.53%,18.09%,19.88%,25.91%,-
4,DSP Equity Savings Fund - Direct Plan - Growth...,-,361.43,0.37%,1.31%,2.21%,10.58%,1.21%,30.94%,11.19%,...,17-May-21,41.9410,15-Feb-21,33.7504,26-May-20,13.51%,16.89%,19.05%,26.12%,61.68%

In [46]:
#Exporting the consolidated Equity Savings mf data as a  csv file
#print("Shape of the dataframe:", df_final.shape)
df_final.to_csv('es_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + ').csv',
               index=False)

#Exporting the Equity Savings mf data columns with its datatype as a  csv file
#df_dtypes.to_csv('es_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')