In [1]:
#Importing the required libraries
import pandas as pd

## Multi Asset Allocation Fund

These mutual funds invest in atleast 3 asset classes with atleast 10% in each asset classes.

## Exctracting Multi Asset Allocation Mutual Fund's Historical Investment Returns Data

Data in this table: Get Absolute historical returns for ₹1000 investment. If 1Y column value is 1234.5 that means, your ₹1000 investment 1 year back would have grown to ₹1234.5.

In [2]:
maa_lump_sum_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/returns/multi-asset-allocation.html")
df1 = pd.DataFrame(maa_lump_sum_rtn[0])

In [3]:
#Renaming historical returns column names
df1.rename({'1W': '1W_RTN(%)', '1M': '1M_RTN(%)', '3M': '3M_RTN(%)', '6M': '6M_RTN(%)',
                 'YTD': 'YTD_RTN(%)', '1Y': '1Y_RTN(%)', '2Y': '2Y_RTN(%)', '3Y': '3Y_RTN(%)',
                 '5Y': '5Y_RTN(%)', '10Y': '10Y_RTN(%)'
          }, axis=1, inplace=True)
print("Shape of the dataframe:", df1.shape)
df1.head()

Shape of the dataframe: (19, 13)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%)
0,Quant Multi Asset Fund - Direct Plan - GrowthM...,-,29.28,0.52%,12.89%,31.02%,40.08%,24.52%,95.67%,35.38%,25.31%,16.70%,-
1,Quant Multi Asset Fund - GrowthMulti Asset All...,-,29.28,0.48%,12.59%,30.26%,39.01%,24.06%,93.96%,34.70%,25.05%,16.56%,11.89%
2,HDFC Multi-Asset Fund - Direct Plan - GrowthMu...,-,761.75,0.45%,2.38%,2.05%,13.00%,3.35%,46.13%,17.43%,11.58%,10.87%,-
3,SBI Multi Asset Allocation Fund - Direct Plan ...,-,346.13,0.44%,3.27%,2.71%,9.50%,4.45%,24.02%,15.56%,10.48%,10.15%,-
4,SBI Multi Asset Allocation Fund - Regular Plan...,-,346.13,0.42%,3.19%,2.50%,9.09%,4.34%,23.15%,14.84%,9.60%,9.17%,9.84%

## Exctracting Multi Asset Allocation Mutual Fund's Monthly Returns Data

Data in this table: Get monthly returns. If Jan month column value is 5.4% that means, fund has given 5.4% returns in Jan month.

In [4]:
maa_monthly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/monthly-returns/multi-asset-allocation.html")
df2 = pd.DataFrame(maa_monthly_rtn[0])

In [5]:
#Renaming df1 column names
df1.rename({"Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            'MTD': 'MTD_RTN(%)', "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)"
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df2.shape)
df2.head()

Shape of the dataframe: (22, 14)

,Scheme Name,Crisil Rank,MTD,Apr'21,Mar'21,Feb'21,Jan'21,Dec'20,Nov'20,Oct'20,Sep'20,Aug'20,Jul'20,Jun'20
0,Axis Triple Advantage Fund - GrowthMulti Asset...,-,1.38%,0.48%,-0.18%,1.06%,-3.32%,4.77%,9.17%,1.75%,-1.60%,2.28%,4.83%,4.28%
1,Axis Triple Advantage Fund - Direct Plan - Gro...,-,1.46%,0.61%,-0.04%,1.17%,-3.20%,4.89%,9.30%,1.88%,-1.48%,2.41%,4.96%,4.40%
2,Quant Multi Asset Fund - GrowthMulti Asset All...,-,9.68%,10.76%,1.40%,4.67%,-1.74%,3.88%,1.67%,3.05%,1.50%,3.92%,18.06%,5.35%
3,Quant Multi Asset Fund - Direct Plan - GrowthM...,-,9.78%,11.06%,1.57%,4.81%,-1.66%,3.87%,1.68%,3.05%,1.51%,3.87%,18.22%,5.36%
4,HDFC Multi-Asset Fund - GrowthMulti Asset Allo...,-,1.79%,0.49%,-0.05%,0.84%,-2.57%,7.29%,5.45%,0.21%,-1.05%,2.19%,7.09%,5.53%

## Exctracting Multi Asset Allocation Mutual Fund's Quarterly Returns Data

Data in this table: Get quarterly returns. If Q1 column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Mar.

In [6]:
maa_quarterly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/quarterly-returns/multi-asset-allocation.html")
df3 = pd.DataFrame(maa_quarterly_rtn[0])

In [7]:
print("Shape of the dataframe:", df3.shape)
df3.head()

Shape of the dataframe: (22, 14)

,Scheme Name,Crisil Rank,QTD,Q1'21,Q4'20,Q3'20,Q2'20,Q1'20,Q4'19,Q3'19,Q2'19,Q1'19,Q4'18,Q3'18
0,Axis Triple Advantage Fund - GrowthMulti Asset...,-,1.86%,0.88%,17.04%,6.41%,16.54%,-18.60%,4.91%,2.54%,4.78%,2.03%,3.10%,-1.90%
1,Axis Triple Advantage Fund - Direct Plan - Gro...,-,2.08%,1.28%,17.48%,6.81%,16.93%,-18.34%,5.24%,2.85%,5.09%,2.22%,3.39%,-1.61%
2,Quant Multi Asset Fund - GrowthMulti Asset All...,-,21.48%,6.36%,9.46%,24.93%,15.76%,-22.42%,3.36%,3.65%,1.26%,1.74%,3.49%,1.40%
3,Quant Multi Asset Fund - Direct Plan - GrowthM...,-,21.92%,6.79%,9.47%,25.05%,15.79%,-22.40%,3.38%,3.67%,1.39%,1.96%,2.77%,1.40%
4,HDFC Multi-Asset Fund - GrowthMulti Asset Allo...,-,2.29%,1.14%,14.01%,8.80%,19.40%,-18.48%,5.47%,-0.69%,0.01%,4.65%,-0.12%,-0.36%

## Exctracting Multi Asset Allocation Mutual Fund's Annual Investment Returns Data

Data in this table: Get annual returns. If 2018 year column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Dec/Last date.

In [8]:
maa_annual_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/annual-returns/multi-asset-allocation.html")
df4 = pd.DataFrame(maa_annual_rtn[0])

In [9]:
#Renaming yearly returns column names
df4.rename({'2020': '2020_RTN(%)', '2019': '2019_RTN(%)', '2018': '2018_RTN(%)', '2017': '2017_RTN(%)',
                 '2016': '2016_RTN(%)', '2015': '2015_RTN(%)', '2014': '2014_RTN(%)', '2013': '2013_RTN(%)',
                 '2012': '2012_RTN(%)', '2011': '2011_RTN(%)', '2010': '2010_RTN(%)'
               }, axis=1, inplace=True)

print("Shape of the dataframe:", df4.shape)
df4.head()

Shape of the dataframe: (22, 14)

,Scheme Name,Crisil Rank,YTD,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%),2015_RTN(%),2014_RTN(%),2013_RTN(%),2012_RTN(%),2011_RTN(%),2010_RTN(%)
0,Axis Triple Advantage Fund - Growth Multi Asse...,-,3.76%,17.82%,15.35%,1.91%,15.91%,6.69%,-0.36%,16.56%,-0.34%,19.39%,0.71%,4.85%
1,Axis Triple Advantage Fund - Direct Plan - Gro...,-,4.40%,19.48%,16.80%,2.92%,17.62%,7.62%,0.51%,18.20%,0.13%,-,-,-
2,Quant Multi Asset Fund - Growth Multi Asset Al...,-,31.95%,27.12%,10.99%,4.56%,1.99%,12.72%,7.39%,7.38%,6.63%,8.20%,6.14%,5.93%
3,Quant Multi Asset Fund - Direct Plan - Growth ...,-,32.97%,27.60%,11.41%,3.84%,1.99%,12.72%,7.39%,7.38%,6.51%,-,-,-
4,HDFC Multi-Asset Fund - Growth Multi Asset All...,-,4.29%,20.37%,8.76%,-1.93%,11.83%,8.72%,4.56%,20.39%,6.40%,11.84%,6.11%,9.72%

## Exctracting Multi Asset Allocation Mutual Fund's Rank Within Category Data

Data in this table: Get performance rank within category. If 1Y column value is 3/45 that means, Fund ranked 3rd in terms of performance out of 45 funds in that category.

In [10]:
maa_rank_in_category = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/ranks/multi-asset-allocation.html")
df5 = pd.DataFrame(maa_rank_in_category[0])

In [11]:
#Renaming df5 column names
df5.rename({'1W': '1W_Rank', '1M': '1M_Rank', '3M': '3M_Rank', '6M': '6M_Rank', 'YTD': 'YTD_Rank',
            '1Y': '1Y_Rank', '2Y': '2Y_Rank', '3Y': '3Y_Rank', '5Y': '5Y_Rank', '10Y': '10Y_Rank'
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df5.shape)
df5.head()

Shape of the dataframe: (16, 12)

,Scheme Name,Crisil Rank,1W_Rank,1M_Rank,3M_Rank,6M_Rank,YTD_Rank,1Y_Rank,2Y_Rank,3Y_Rank,5Y_Rank,10Y_Rank
0,Quant Multi Asset Fund - GrowthMulti Asset All...,-,1/10,1/10,1/10,1/10,1/10,1/8,1/7,1/7,1/7,2/7
1,Quant Multi Asset Fund - Direct Plan - GrowthM...,-,1/10,1/10,1/10,1/10,1/10,1/8,1/7,1/7,1/7,0/0
2,ICICI Prudential Multi-Asset Fund - Direct Pla...,4,4/10,2/10,2/10,2/10,2/10,2/8,4/7,3/7,2/7,0/0
3,ICICI Prudential Multi-Asset Fund - GrowthMult...,3,4/10,2/10,2/10,2/10,2/10,2/8,3/7,3/7,2/7,1/7
4,HDFC Multi-Asset Fund - GrowthMulti Asset Allo...,-,3/10,6/10,4/10,4/10,4/10,3/8,4/7,4/7,4/7,3/7

## Exctracting Multi Asset Allocation Mutual Fund's Risk Ratios Data

Data in this table: Get values of risk ratios calculated on daily returns for last 3 years.

In [12]:
maa_risk_ratio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/risk-ratios/multi-asset-allocation.html")
df6 = pd.DataFrame(maa_risk_ratio[0])

In [13]:
#Droping the 'Category' column
df6.drop('Category', inplace=True, axis=1)
print("Shape of the dataframe:", df6.shape)
df6.head()

Shape of the dataframe: (3, 8)

,Scheme Name,Crisil Rank,AuM (Cr),Standard Deviation,Beta,Sharpe Ratio,Jension's Alpha,Treynor's Ratio
0,ICICI Prudential Multi-Asset Fund - Growth,3,11108.27,15.88,-,0.41,-,0.10
1,UTI Multi Asset Fund - Regular Plan - Growth,-,687.29,13.04,-,0.22,-,0.05
2,Quant Multi Asset Fund - Growth,-,29.28,13.63,-,1.22,-,0.25

## Exctracting Multi Asset Allocation Mutual Fund's Portfolio Data

Data in this table: Compare how schemes have invested money across various asset class and number of instruments.

In [14]:
maa_portfolio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/portfolioassets/multi-asset-allocation.html")
df7 = pd.DataFrame(maa_portfolio[0])

In [15]:
#Renaming SIP returns column names
df7.rename({'Turnover ratio': 'Turnover ratio(%)'}, axis=1, inplace=True)

print("Shape of the dataframe:", df7.shape)
df7.head()

Shape of the dataframe: (20, 10)

,Scheme Name,Crisil Rank,Turnover ratio(%),% Equity Holding,No of stocks in portfolio,% Debt Holding,No of instruments in portfolio,% MF Holding,% Cash Holding,% Other Holding
0,ICICI Prudential Multi-Asset Fund - GrowthMult...,3,-,75.16%,56,8.69%,15,6.72%,4.55%,6.17%
1,ICICI Prudential Multi-Asset Fund - Direct Pla...,4,-,75.16%,56,8.69%,15,6.72%,4.55%,6.17%
2,Axis Triple Advantage Fund - GrowthMulti Asset...,-,-,72.02%,40,15.19%,18,10.24%,2.01%,-
3,Axis Triple Advantage Fund - Direct Plan - Gro...,-,-,72.02%,40,15.19%,18,10.24%,2.01%,-
4,UTI Multi Asset Fund - Regular Plan - GrowthMu...,-,-,69.34%,48,12.43%,6,10.53%,7.70%,-

## Exctracting Multi Asset Allocation Mutual Fund's Latest NAV Data

Data in this table: Get the latest values of NAV for the mutual funds.

In [16]:
maa_nav = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/navs/multi-asset-allocation.html")
df8 = pd.DataFrame(maa_nav[0])

In [17]:
df8.rename({'1D Change' : '1D Change(%)'}, axis=1, inplace=True)
print("Shape of the dataframe:", df8.shape)
df8.head()

Shape of the dataframe: (19, 10)

,Scheme Name,Crisil Rank,AuM (Cr),NAV,1D Change(%),NAV Date,52W High,52WH as on,52W Low,52WL as on
0,ICICI Prudential Multi-Asset Fund - Direct Pla...,4,11108.27,376.4220,0.89%,17-May-21,377.8506,11-May-21,247.6969,26-May-20
1,ICICI Prudential Multi-Asset Fund - GrowthMult...,3,11108.27,352.1366,0.89%,17-May-21,353.5096,11-May-21,233.1492,26-May-20
2,HDFC Multi-Asset Fund - Direct Plan - GrowthMu...,-,761.75,44.8060,1.01%,17-May-21,44.8060,17-May-21,30.2980,26-May-20
3,HDFC Multi-Asset Fund - GrowthMulti Asset Allo...,-,761.75,42.3230,1%,17-May-21,42.3230,17-May-21,28.9540,26-May-20
4,Axis Triple Advantage Fund - Direct Plan - Gro...,-,965.82,29.0202,1.31%,17-May-21,29.0853,10-May-21,19.7820,26-May-20

## Exctracting Multi Asset Allocation Mutual Fund's SIP Returns Data

Data in this table: Get absolute SIP returns. If 1Y column value is 10%, that means fund has given 10% returns on your SIP investments started 1 year back from latest NAV date.

In [18]:
maa_sip_rtns = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/sip-returns/multi-asset-allocation.html")
df9 = pd.DataFrame(maa_sip_rtns[0])

In [19]:
#Renaming SIP returns column names
df9.rename({'1Y': '1Y_SIP_RTN(%)', '2Y': '2Y_SIP_RTN(%)', '3Y': '3Y_SIP_RTN(%)',
                  '5Y': '5Y_SIP_RTN(%)', '10Y': '10Y_SIP_RTN(%)', 'YTD' : 'YTD_SIP_RTN(%)'
           }, axis=1, inplace=True)

print("Shape of the dataframe:", df9.shape)
df9.head()

Shape of the dataframe: (16, 8)

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,Quant Multi Asset Fund - Direct Plan - GrowthM...,-,29.28,48.29%,64.06%,72.89%,83.70%,-
1,Quant Multi Asset Fund - GrowthMulti Asset All...,-,29.28,47.22%,62.69%,71.49%,82.37%,121.87%
2,ICICI Prudential Multi-Asset Fund - Direct Pla...,4,11108.27,26.04%,31.61%,34.40%,45.25%,-
3,ICICI Prudential Multi-Asset Fund - GrowthMult...,3,11108.27,25.60%,30.73%,33.00%,42.27%,106.07%
4,Tata Multi Asset Opportunities Fund - Direct P...,-,681.28,18.66%,-,-,-,-

In [20]:
df_final = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9],axis=1,sort=False)
print("Shape of the dataframe:", df_final.shape)

Shape of the dataframe: (22, 103)

In [21]:
# Remove duplicate columns by name in Pandas
df_final = df_final.loc[:,~df_final.columns.duplicated()]

# Removing spaces in the column names
#df_final.columns = df_final.columns.str.replace(' ','_')

print("Shape of the dataframe:", df_final.shape)
df_final.head()

Shape of the dataframe: (22, 84)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,NAV Date,52W High,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,Quant Multi Asset Fund - Direct Plan - GrowthM...,-,29.28,0.52%,12.89%,31.02%,40.08%,24.52%,95.67%,35.38%,...,17-May-21,377.8506,11-May-21,247.6969,26-May-20,48.29%,64.06%,72.89%,83.70%,-
1,Quant Multi Asset Fund - GrowthMulti Asset All...,-,29.28,0.48%,12.59%,30.26%,39.01%,24.06%,93.96%,34.70%,...,17-May-21,353.5096,11-May-21,233.1492,26-May-20,47.22%,62.69%,71.49%,82.37%,121.87%
2,HDFC Multi-Asset Fund - Direct Plan - GrowthMu...,-,761.75,0.45%,2.38%,2.05%,13.00%,3.35%,46.13%,17.43%,...,17-May-21,44.8060,17-May-21,30.2980,26-May-20,26.04%,31.61%,34.40%,45.25%,-
3,SBI Multi Asset Allocation Fund - Direct Plan ...,-,346.13,0.44%,3.27%,2.71%,9.50%,4.45%,24.02%,15.56%,...,17-May-21,42.3230,17-May-21,28.9540,26-May-20,25.60%,30.73%,33.00%,42.27%,106.07%
4,SBI Multi Asset Allocation Fund - Regular Plan...,-,346.13,0.42%,3.19%,2.50%,9.09%,4.34%,23.15%,14.84%,...,17-May-21,29.0853,10-May-21,19.7820,26-May-20,18.66%,-,-,-,-

In [23]:
#Exporting the consolidated Multi Asset Allocation mf data as a  csv file
#print("Shape of the dataframe:", df_final.shape)
#df_final.to_csv('maa_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + ').csv',
#               index=False)

#Exporting the Multi Asset Allocation mf data columns with its datatype as a  csv file
#df_dtypes.to_csv('maa_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')