In [1]:
#Importing the required libraries
import pandas as pd

## Aggressive Hybrid Fund

These mutual funds invest in both Stocks and Debt/Bonds. However focus on stocks is higher with 65-80% of total investments in stocks and rest in bonds.

## Exctracting Aggressive Hybrid Mutual Fund's Historical Investment Returns Data

Data in this table: Get Absolute historical returns for ₹1000 investment. If 1Y column value is 1234.5 that means, your ₹1000 investment 1 year back would have grown to ₹1234.5.

In [2]:
ah_lump_sum_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/returns/aggressive-hybrid-fund.html")
df1 = pd.DataFrame(ah_lump_sum_rtn[0])

In [3]:
#Renaming historical returns column names
df1.rename({'1W': '1W_RTN(%)', '1M': '1M_RTN(%)', '3M': '3M_RTN(%)', '6M': '6M_RTN(%)',
                 'YTD': 'YTD_RTN(%)', '1Y': '1Y_RTN(%)', '2Y': '2Y_RTN(%)', '3Y': '3Y_RTN(%)',
                 '5Y': '5Y_RTN(%)', '10Y': '10Y_RTN(%)'
          }, axis=1, inplace=True)
print("Shape of the dataframe:", df1.shape)
df1.head()

Shape of the dataframe: (74, 13)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%)
0,HDFC Hybrid Equity Fund - Direct Plan - Growth...,3,17216.70,0.64%,4.32%,0.21%,18.82%,3.27%,56.63%,15.61%,10.80%,13.07%,-
1,HDFC Hybrid Equity Fund - Growth (Adjusted NAV...,-,17216.70,0.63%,4.26%,0.06%,18.46%,3.19%,55.65%,14.90%,10.37%,12.88%,13.60%
2,HSBC Equity Hybrid Fund - Direct - GrowthAggre...,-,487.28,0.56%,2.46%,-1.27%,12.59%,1.86%,45.03%,16.72%,-,-,-
3,DSP Equity & Bond Fund - Direct Plan - GrowthA...,4,6444.84,0.56%,2.98%,1.26%,16.95%,2.65%,49.31%,19.48%,13.27%,14.79%,-
4,DSP Equity & Bond Fund - Regular Plan - Growth...,4,6444.84,0.54%,2.89%,1.01%,16.36%,2.51%,47.82%,18.30%,12.14%,13.60%,12.29%

## Exctracting Aggressive Hybrid Mutual Fund's Monthly Returns Data

Data in this table: Get monthly returns. If Jan month column value is 5.4% that means, fund has given 5.4% returns in Jan month.

In [4]:
ah_monthly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/monthly-returns/aggressive-hybrid-fund.html")
df2 = pd.DataFrame(ah_monthly_rtn[0])

In [5]:
#Renaming df1 column names
df1.rename({"Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            'MTD': 'MTD_RTN(%)', "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)"
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df2.shape)
df2.head()

Shape of the dataframe: (76, 14)

,Scheme Name,Crisil Rank,MTD,Apr'21,Mar'21,Feb'21,Jan'21,Dec'20,Nov'20,Oct'20,Sep'20,Aug'20,Jul'20,Jun'20
0,BNP Paribas Substantial Equity Hybrid Fund - G...,4,2.31%,1.04%,-1.70%,2.83%,-0.31%,4.83%,8.39%,0.64%,-2.47%,1.44%,5.03%,2.42%
1,BNP Paribas Substantial Equity Hybrid Fund - D...,4,2.39%,1.19%,-1.55%,2.96%,-0.18%,4.97%,8.50%,0.78%,-2.35%,1.58%,5.21%,2.55%
2,Aditya Birla Sun Life Equity Hybrid 95 Fund - ...,2,1.15%,-0.08%,0.19%,2.82%,-1.74%,4.80%,10.14%,1.61%,0.22%,3.07%,4.54%,4.52%
3,IDFC Hybrid Equity Fund - Regular Plan - Growt...,3,1.60%,0.77%,-0.56%,2.04%,-0.90%,4.56%,8.31%,0.52%,1.05%,4.05%,5.95%,3.54%
4,IDFC Hybrid Equity Fund - Direct plan - Growth...,3,1.69%,0.85%,-0.46%,2.19%,-0.77%,4.65%,8.38%,0.65%,1.07%,4.17%,6.08%,3.64%

## Exctracting Aggressive Hybrid Mutual Fund's Quarterly Returns Data

Data in this table: Get quarterly returns. If Q1 column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Mar.

In [6]:
ah_quarterly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/quarterly-returns/aggressive-hybrid-fund.html")
df3 = pd.DataFrame(ah_quarterly_rtn[0])

In [7]:
print("Shape of the dataframe:", df3.shape)
df3.head()

Shape of the dataframe: (76, 14)

,Scheme Name,Crisil Rank,QTD,Q1'21,Q4'20,Q3'20,Q2'20,Q1'20,Q4'19,Q3'19,Q2'19,Q1'19,Q4'18,Q3'18
0,BNP Paribas Substantial Equity Hybrid Fund - G...,4,3.38%,4.87%,15.60%,4.60%,14.23%,-15.99%,5.32%,2.28%,2.94%,4.56%,2.38%,-0.23%
1,BNP Paribas Substantial Equity Hybrid Fund - D...,4,3.61%,5.32%,16.05%,5.06%,14.70%,-15.69%,5.73%,2.67%,3.29%,4.91%,2.74%,0.16%
2,Aditya Birla Sun Life Equity Hybrid 95 Fund - ...,2,1.07%,5.70%,18.14%,8.70%,17.76%,-25.63%,4.38%,-2.35%,-0.38%,3.43%,1.19%,-2.26%
3,IDFC Hybrid Equity Fund - Regular Plan - Growt...,3,2.38%,5.60%,14.64%,12.28%,15.99%,-22.97%,3.82%,-2.57%,0.09%,3.40%,0.54%,-1.84%
4,IDFC Hybrid Equity Fund - Direct plan - Growth...,3,2.56%,5.89%,15.00%,12.62%,16.33%,-22.67%,4.15%,-2.30%,0.33%,3.70%,0.96%,-1.49%

## Exctracting Aggressive Hybrid Mutual Fund's Annual Investment Returns Data

Data in this table: Get annual returns. If 2018 year column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Dec/Last date.

In [8]:
ah_annual_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/annual-returns/aggressive-hybrid-fund.html")
df4 = pd.DataFrame(ah_annual_rtn[0])

In [9]:
#Renaming yearly returns column names
df4.rename({'2020': '2020_RTN(%)', '2019': '2019_RTN(%)', '2018': '2018_RTN(%)', '2017': '2017_RTN(%)',
                 '2016': '2016_RTN(%)', '2015': '2015_RTN(%)', '2014': '2014_RTN(%)', '2013': '2013_RTN(%)',
                 '2012': '2012_RTN(%)', '2011': '2011_RTN(%)', '2010': '2010_RTN(%)'
               }, axis=1, inplace=True)

print("Shape of the dataframe:", df4.shape)
df4.head()

Shape of the dataframe: (74, 14)

,Scheme Name,Crisil Rank,YTD,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%),2015_RTN(%),2014_RTN(%),2013_RTN(%),2012_RTN(%),2011_RTN(%),2010_RTN(%)
0,BNP Paribas Substantial Equity Hybrid Fund - G...,4,9.51%,14.47%,16.48%,0.73%,11.18%,-,-,-,-,-,-,-
1,BNP Paribas Substantial Equity Hybrid Fund - D...,4,10.23%,16.32%,18.19%,2.31%,12.50%,-,-,-,-,-,-,-
2,Aditya Birla Sun Life Equity Hybrid 95 Fund - ...,2,7.95%,10.93%,4.55%,-4.64%,25.91%,8.36%,2.97%,48.54%,5.24%,24.60%,-13.86%,19.66%
3,IDFC Hybrid Equity Fund - Regular Plan - Growt...,3,9.12%,13.49%,4.74%,-3.64%,16.15%,-,-,-,-,-,-,-
4,IDFC Hybrid Equity Fund - Direct plan - Growth...,3,9.61%,15.03%,6.12%,-2.13%,18.54%,-,-,-,-,-,-,-

## Exctracting Aggressive Hybrid Mutual Fund's Rank Within Category Data

Data in this table: Get performance rank within category. If 1Y column value is 3/45 that means, Fund ranked 3rd in terms of performance out of 45 funds in that category.

In [10]:
ah_rank_in_category = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/ranks/aggressive-hybrid-fund.html")
df5 = pd.DataFrame(ah_rank_in_category[0])

In [11]:
#Renaming df5 column names
df5.rename({'1W': '1W_Rank', '1M': '1M_Rank', '3M': '3M_Rank', '6M': '6M_Rank', 'YTD': 'YTD_Rank',
            '1Y': '1Y_Rank', '2Y': '2Y_Rank', '3Y': '3Y_Rank', '5Y': '5Y_Rank', '10Y': '10Y_Rank'
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df5.shape)
df5.head()

Shape of the dataframe: (70, 12)

,Scheme Name,Crisil Rank,1W_Rank,1M_Rank,3M_Rank,6M_Rank,YTD_Rank,1Y_Rank,2Y_Rank,3Y_Rank,5Y_Rank,10Y_Rank
0,Quant Absolute Fund - GrowthAggressive Hybrid ...,-,36/37,1/37,1/36,1/35,1/37,1/35,1/33,1/28,1/23,2/20
1,Quant Absolute Fund - Direct Plan - GrowthAggr...,-,36/37,1/37,1/36,1/35,1/37,1/35,1/33,1/28,1/23,0/0
2,JM Equity Hybrid Fund - GrowthAggressive Hybri...,3,24/37,5/37,5/36,8/35,7/37,2/35,13/33,10/28,16/23,12/20
3,JM Equity Hybrid Fund - (Direct) - GrowthAggre...,3,24/37,5/37,6/36,8/35,7/37,2/35,14/33,11/28,17/23,0/0
4,BOI AXA Mid & Small Cap Equity & Debt Fund - D...,5,13/37,3/37,2/36,3/35,2/37,3/35,2/33,23/28,0/0,0/0

## Exctracting Aggressive Hybrid Mutual Fund's Risk Ratios Data

Data in this table: Get values of risk ratios calculated on daily returns for last 3 years.

In [12]:
ah_risk_ratio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/risk-ratios/aggressive-hybrid-fund.html")
df6 = pd.DataFrame(ah_risk_ratio[0])

In [13]:
#Droping the 'Category' column
df6.drop('Category', inplace=True, axis=1)
print("Shape of the dataframe:", df6.shape)
df6.head()

Shape of the dataframe: (26, 8)

,Scheme Name,Crisil Rank,AuM (Cr),Standard Deviation,Beta,Sharpe Ratio,Jension's Alpha,Treynor's Ratio
0,Franklin India Equity Hybrid Fund - Growth,3,1349.74,14.85,1.05,0.47,-2.02,0.07
1,ICICI Prudential Equity & Debt Fund - Growth,3,16454.29,16.27,1.10,0.48,-1.54,0.07
2,Principal Hybrid Equity Fund - Growth,4,1052.17,15.28,1.10,0.28,-5.06,0.04
3,JM Equity Hybrid Fund - Growth,3,7.47,20.66,1.12,0.38,-1.65,0.07
4,IDFC Hybrid Equity Fund - Regular Plan - Growth,3,508.18,15.54,-,0.30,-,0.07

## Exctracting Aggressive Hybrid Mutual Fund's Portfolio Data

Data in this table: Compare how schemes have invested money across various asset class and number of instruments.

In [14]:
ah_portfolio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/portfolioassets/aggressive-hybrid-fund.html")
df7 = pd.DataFrame(ah_portfolio[0])

In [15]:
#Renaming SIP returns column names
df7.rename({'Turnover ratio': 'Turnover ratio(%)'}, axis=1, inplace=True)

print("Shape of the dataframe:", df7.shape)
df7.head()

Shape of the dataframe: (74, 10)

,Scheme Name,Crisil Rank,Turnover ratio(%),% Equity Holding,No of stocks in portfolio,% Debt Holding,No of instruments in portfolio,% MF Holding,% Cash Holding,% Other Holding
0,PGIM India Hybrid Equity Fund - GrowthAggressi...,3,-,122.90%,86,16.46%,6,30.02%,21.98%,-
1,PGIM India Hybrid Equity Fund - Direct Plan - ...,3,-,122.90%,86,16.46%,6,30.02%,21.98%,-
2,BOI AXA Mid & Small Cap Equity & Debt Fund - D...,5,132.00%,82.63%,52,7.27%,6,-,10.10%,-
3,BOI AXA Mid & Small Cap Equity & Debt Fund - G...,5,132.00%,82.63%,52,7.27%,6,-,10.10%,-
4,Aditya Birla Sun Life Equity Hybrid 95 Fund - ...,2,-,78.95%,59,14.16%,48,0.51%,4.66%,1.72%

## Exctracting Aggressive Hybrid Mutual Fund's Latest NAV Data

Data in this table: Get the latest values of NAV for the mutual funds.

In [16]:
ah_nav = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/navs/aggressive-hybrid-fund.html")
df8 = pd.DataFrame(ah_nav[0])

In [17]:
df8.rename({'1D Change' : '1D Change(%)'}, axis=1, inplace=True)
print("Shape of the dataframe:", df8.shape)
df8.head()

Shape of the dataframe: (74, 10)

,Scheme Name,Crisil Rank,AuM (Cr),NAV,1D Change(%),NAV Date,52W High,52WH as on,52W Low,52WL as on
0,Aditya Birla Sun Life Equity Hybrid 95 Fund - ...,2,7631.52,1009.0600,1.33%,17-May-21,1012.8700,10-May-21,642.8400,22-May-20
1,Aditya Birla Sun Life Equity Hybrid 95 Fund - ...,2,7631.52,931.0100,1.32%,17-May-21,934.6800,10-May-21,597.6200,22-May-20
2,Tata Hybrid Equity Fund - Direct Plan - Growth...,1,3211.90,282.3201,1.21%,17-May-21,288.1958,03-Mar-21,187.2278,20-May-20
3,DSP Equity & Bond Fund - Direct Plan - GrowthA...,4,6444.84,223.5300,1.47%,17-May-21,223.5300,17-May-21,147.9800,26-May-20
4,Tata Hybrid Equity Fund - Regular Plan - Growt...,1,3211.90,261.6110,1.2%,17-May-21,267.5926,03-Mar-21,175.2769,20-May-20

## Exctracting Aggressive Hybrid Mutual Fund's SIP Returns Data

Data in this table: Get absolute SIP returns. If 1Y column value is 10%, that means fund has given 10% returns on your SIP investments started 1 year back from latest NAV date.

In [18]:
ah_sip_rtns = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/sip-returns/aggressive-hybrid-fund.html")
df9 = pd.DataFrame(ah_sip_rtns[0])

In [19]:
#Renaming SIP returns column names
df9.rename({'1Y': '1Y_SIP_RTN(%)', '2Y': '2Y_SIP_RTN(%)', '3Y': '3Y_SIP_RTN(%)',
                  '5Y': '5Y_SIP_RTN(%)', '10Y': '10Y_SIP_RTN(%)', 'YTD' : 'YTD_SIP_RTN(%)'
           }, axis=1, inplace=True)

print("Shape of the dataframe:", df9.shape)
df9.head()

Shape of the dataframe: (68, 8)

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,Quant Absolute Fund - Direct Plan - GrowthAggr...,-,24.02,43.93%,61.84%,69.81%,84.18%,-
1,Quant Absolute Fund - GrowthAggressive Hybrid ...,-,24.02,43.75%,60.56%,67.49%,80.41%,159.15%
2,BOI AXA Mid & Small Cap Equity & Debt Fund - D...,5,308.88,32.70%,45.77%,45.17%,-,-
3,BOI AXA Mid & Small Cap Equity & Debt Fund - G...,5,308.88,32.03%,44.39%,43.18%,-,-
4,ICICI Prudential Equity & Debt Fund - Direct P...,3,16454.29,30.20%,35.02%,37.82%,48.73%,-

In [20]:
df_final = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9],axis=1,sort=False)
print("Shape of the dataframe:", df_final.shape)

Shape of the dataframe: (76, 103)

In [21]:
# Remove duplicate columns by name in Pandas
df_final = df_final.loc[:,~df_final.columns.duplicated()]

# Removing spaces in the column names
#df_final.columns = df_final.columns.str.replace(' ','_')

print("Shape of the dataframe:", df_final.shape)
df_final.head()

Shape of the dataframe: (76, 84)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,NAV Date,52W High,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,HDFC Hybrid Equity Fund - Direct Plan - Growth...,3,17216.70,0.64%,4.32%,0.21%,18.82%,3.27%,56.63%,15.61%,...,17-May-21,1012.8700,10-May-21,642.8400,22-May-20,43.93%,61.84%,69.81%,84.18%,-
1,HDFC Hybrid Equity Fund - Growth (Adjusted NAV...,-,17216.70,0.63%,4.26%,0.06%,18.46%,3.19%,55.65%,14.90%,...,17-May-21,934.6800,10-May-21,597.6200,22-May-20,43.75%,60.56%,67.49%,80.41%,159.15%
2,HSBC Equity Hybrid Fund - Direct - GrowthAggre...,-,487.28,0.56%,2.46%,-1.27%,12.59%,1.86%,45.03%,16.72%,...,17-May-21,288.1958,03-Mar-21,187.2278,20-May-20,32.70%,45.77%,45.17%,-,-
3,DSP Equity & Bond Fund - Direct Plan - GrowthA...,4,6444.84,0.56%,2.98%,1.26%,16.95%,2.65%,49.31%,19.48%,...,17-May-21,223.5300,17-May-21,147.9800,26-May-20,32.03%,44.39%,43.18%,-,-
4,DSP Equity & Bond Fund - Regular Plan - Growth...,4,6444.84,0.54%,2.89%,1.01%,16.36%,2.51%,47.82%,18.30%,...,17-May-21,267.5926,03-Mar-21,175.2769,20-May-20,30.20%,35.02%,37.82%,48.73%,-

In [23]:
#Exporting the consolidated Aggressive Hybrid mf data as a  csv file
#print("Shape of the dataframe:", df_final.shape)
#df_final.to_csv('ah_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + ').csv',
#               index=False)

#Exporting the Aggressive Hybrid mf data columns with its datatype as a  csv file
#df_dtypes.to_csv('ah_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')