In [368]:
# Importing respective modules
import pandas as pd
import re

In [320]:
# Reading elss mutual funds csv file
lc_mf = pd.read_csv('lc_mf_data(11-May-2021 13:32:01).csv')

In [321]:
# Extracting a plan from "Scheme Name" column
scheme_name = list(lc_mf['Scheme Name'])
plan = []
for i in scheme_name:
    #print(type(i))
    plan.append(re.findall("Direct|Regular", str(i)))
#plan
for p in plan:
    if len(p) == 0:
        #print(type(p))
        p.append("Regular")
lc_mf['Plan'] = plan

In [322]:
# Extracting a category from "Scheme Name" column
scheme_name = list(lc_mf['Scheme Name'])
category = []
for i in scheme_name:
    #print(type(i))
    category.append(re.findall("Large Cap Fund", str(i)))
lc_mf['Category'] = category

In [323]:
# Modifiying 'Scheme Name' column
lc_mf['Scheme Name'] = lc_mf['Scheme Name'].str.replace(' - GrowthLarge Cap Fund', '')

In [324]:
#Replacing "']" & "['" string with "" in Plan columns
lc_mf['Plan'] = lc_mf['Plan'].astype(str).str.replace("\['","", regex=True)
lc_mf['Plan'] = lc_mf['Plan'].astype(str).str.replace("']","", regex=True)

#Replacing "']" & "['" string with "" in Category columns
lc_mf['Category'] = lc_mf['Category'].astype(str).str.replace("\['","", regex=True)
lc_mf['Category'] = lc_mf['Category'].astype(str).str.replace("']","", regex=True)

In [325]:
#Replacing "ELSS', 'ELSS" string with "ELSS" in Category columns
lc_mf['Category'] = lc_mf['Category'].astype(str).str.replace("Large Cap Fund', 'Large Cap Fund","Large Cap Fund", regex=True)

#Replacing "%" string with "" in Crisil Rank, % Debt Holding, No of instruments in portfolio,
# % MF Holding, % Other Holding, Turnover ratio, MTD, 10Y_SIP_RTN(%) & 5Y_SIP_RTN(%) columns
lc_mf[['% Debt Holding', 'No of instruments in portfolio',
          '% MF Holding', '% Other Holding', 'Turnover ratio(%)',
          'MTD', '10Y_SIP_RTN(%)', '5Y_SIP_RTN(%)'         
         ]] = lc_mf[['% Debt Holding', 'No of instruments in portfolio',
                        '% MF Holding', '% Other Holding', 'Turnover ratio(%)',
                        'MTD', '10Y_SIP_RTN(%)', '5Y_SIP_RTN(%)'
                        ]].replace("%", "", regex=True)

#Replacing "-" string with "0" in Crisil Rank columns
lc_mf['Crisil Rank'] = lc_mf['Crisil Rank'].replace("-", "", regex=True)

In [326]:
#Replacing "-" string with "0" in Crisil Rank columns
lc_mf['Crisil Rank'] = lc_mf['Crisil Rank'].replace("", "0", regex=True)

#Replacing "%" with '' in the column
lc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding', '% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)',
         "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20",
         "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19",
         "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)"
         ]] = lc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)"
                       ]].replace("%", "", regex=True)
print("Shape of the dataframe:", lc_mf.shape)
lc_mf.head()

Shape of the dataframe: (66, 86)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
0,HDFC Top 100 Fund - Direct Plan,1,18445.21,3.41,2.44,-0.74,25.03,11.57,63.04,11.13,...,03-Mar-21,364.9760,18-May-20,31.63,37.09,38.16,45.37,-,Direct,Large Cap Fund
1,HDFC Top 100 Fund,1,18445.21,3.40,2.40,-0.87,24.69,11.36,62.11,10.51,...,03-Mar-21,347.8820,18-May-20,31.07,36.02,36.54,42.38,93.07,Regular,Large Cap Fund
2,PGIM India Large Cap Fund - Direct Plan,3,308.64,3.39,2.52,2.01,20.87,9.22,58.26,17.91,...,03-Mar-21,368.2100,18-May-20,28.02,34.07,-,-,-,Direct,Large Cap Fund
3,PGIM India Large Cap Fund,3,308.64,3.36,2.39,1.63,19.96,8.63,55.89,16.28,...,03-Mar-21,346.3501,18-May-20,26.79,27.44,27.88,38.92,-,Regular,Large Cap Fund
4,Mahindra Manulife Large Cap Pragati Yojana - D...,0,108.26,3.11,3.21,2.42,26.11,13.62,61.97,19.51,...,10-May-21,146.7900,18-May-20,26.71,31.46,-,-,-,Direct,Large Cap Fund

In [327]:
#Sorting a lc_mf dataframe by "Crisil Rank Column"
lc_mf.sort_values(by=['Crisil Rank', 'Scheme Name', 'AuM (Cr)'], inplace=True, ascending=False)
print("Shape of the dataframe:", lc_mf.shape)
lc_mf.head()

Shape of the dataframe: (66, 86)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
41,UTI Mastershare Unit Scheme - Direct Plan,5,7734.48,1.78,0.66,-0.04,20.79,7.95,61.80,18.80,...,15-Feb-21,22.15,18-May-20,19.54,25.80,29.91,41.70,-,Direct,Large Cap Fund
43,UTI Mastershare Unit Scheme,5,7734.48,1.76,0.58,-0.26,20.25,7.60,60.32,17.77,...,15-Feb-21,26.04,18-May-20,19.54,22.87,24.16,29.12,-,Regular,Large Cap Fund
64,Kotak Bluechip Fund - Direct Plan,5,2411.04,1.37,-0.10,-0.36,19.58,8.07,62.47,19.61,...,03-Mar-21,10.00,24-Dec-20,NaN,NaN,NaN,NaN,NaN,Direct,Large Cap Fund
65,Kotak Bluechip Fund,5,2411.04,1.35,-0.20,-0.65,18.87,7.60,60.58,18.27,...,15-Feb-21,9.86,30-Oct-20,NaN,NaN,NaN,NaN,NaN,Regular,Large Cap Fund
39,Canara Robeco Bluechip Equity Fund - Regular Plan,5,2476.82,1.85,0.62,-1.22,18.73,7.00,55.13,21.96,...,03-Mar-21,19.94,18-May-20,20.57,23.30,25.60,32.49,76.38,Regular,Large Cap Fund

In [328]:
#Replacing "-" with 'None' in the columns
lc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding', '% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)',
         "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20",
         "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19",
         "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)"
         ]] = lc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)"]].replace({'-' : None})

In [329]:
#Replacing "" with '0' in the columns

lc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding','% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)',
         '10Y_SIP_RTN(%)', "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20",
         "Sep'20", "Aug'20", "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20",
         "Q4'19", "Q3'19", "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)",
         "Standard Deviation", "Beta", "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio", 'Crisil Rank'
         ]] = lc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',\
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)", "Standard Deviation", "Beta",
                       "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio", 'Crisil Rank']].fillna(value='0')

In [330]:
#Changing the datatype of the return & risk ratio columns

lc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding','% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)',
         '10Y_SIP_RTN(%)', "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20",
         "Sep'20", "Aug'20", "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20",
         "Q4'19", "Q3'19", "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)",
         "Standard Deviation", "Beta", "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio"
         ]] = lc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)", "Standard Deviation", "Beta",
                       "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio"]].apply(pd.to_numeric)

In [331]:
#Changing the datatype of the 'Crisil Rank' columns
lc_mf['Crisil Rank'] = lc_mf['Crisil Rank'].astype('int')

In [332]:
#Removing white spaces at both ends in all over the dataframe:

lc_mf.columns = lc_mf.columns.str.strip()

#Checking the data type of all columns in the DataFrame
lc_mf_dtype = lc_mf.dtypes

df_dtypes = pd.DataFrame(lc_mf_dtype)

In [333]:
#Using pandas dataframe.round()function to round off all the decimal values to 2 decimal places
lc_mf = lc_mf.round(2)

In [334]:
# #Exporting the consolidated elss mf data as a  csv file
# print("Shape of the dataframe:", lc_mf.shape)
#lc_mf.to_csv('final_lc_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)',
#                 index=False)

# #Exporting the elss mf data columns with its datatype as a  csv file
# df_dtypes.to_csv('lc_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')

In [335]:
#Exctracting regular mutual funds
regular_mf = lc_mf.loc[lc_mf['Plan'] == 'Regular']
regular_mf.head()

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
43,UTI Mastershare Unit Scheme,5,7734.48,1.76,0.58,-0.26,20.25,7.60,60.32,17.77,...,15-Feb-21,26.04,18-May-20,19.54,22.87,24.16,29.12,0.00,Regular,Large Cap Fund
65,Kotak Bluechip Fund,5,2411.04,1.35,-0.20,-0.65,18.87,7.60,60.58,18.27,...,15-Feb-21,9.86,30-Oct-20,0.00,0.00,0.00,0.00,0.00,Regular,Large Cap Fund
39,Canara Robeco Bluechip Equity Fund - Regular Plan,5,2476.82,1.85,0.62,-1.22,18.73,7.00,55.13,21.96,...,03-Mar-21,19.94,18-May-20,20.57,23.30,25.60,32.49,76.38,Regular,Large Cap Fund
31,SBI Blue Chip Fund - Regular Plan,4,26464.26,2.08,0.25,-1.91,22.01,8.05,63.25,17.02,...,15-Feb-21,39.60,18-May-20,21.52,27.31,30.79,38.83,80.00,Regular,Large Cap Fund
56,JM Large Cap Fund,4,54.20,1.53,0.71,-0.83,11.62,4.32,37.15,12.97,...,10-May-21,8.09,18-May-20,14.75,22.04,25.61,35.11,0.00,Regular,Large Cap Fund

In [336]:
# Basic statistics of regular mutual fund df
regular_mf.describe()

,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),...,% Other Holding,NAV,1D Change(%),52W High,52W Low,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
count,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,...,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000
mean,2.545455,5386.746667,2.140606,0.998182,-0.810303,17.674242,7.398485,48.955758,13.693333,9.035455,...,0.064545,121.971212,0.793636,124.650000,73.707576,19.211515,23.854545,26.643939,34.494545,43.473333
std,1.522558,8894.539550,0.610829,1.059055,1.343127,5.849743,2.860044,19.549153,5.743022,4.242322,...,0.236922,157.219455,0.201585,160.682012,90.831807,7.980760,9.604400,10.829072,16.213769,49.993555
min,0.000000,0.000000,1.350000,-0.960000,-4.260000,0.000000,2.700000,0.000000,0.000000,0.000000,...,0.000000,10.840000,0.440000,11.260000,8.090000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,181.900000,1.690000,0.490000,-1.560000,16.070000,6.000000,48.860000,12.970000,8.570000,...,0.000000,25.070000,0.660000,26.030000,16.320000,18.670000,23.110000,25.610000,32.490000,0.000000
50%,3.000000,689.710000,1.970000,0.780000,-0.810000,18.420000,7.060000,55.130000,15.370000,10.030000,...,0.000000,46.800000,0.830000,48.110000,28.390000,21.290000,26.310000,28.880000,38.370000,0.000000
75%,4.000000,5910.590000,2.590000,1.460000,-0.170000,20.250000,8.060000,60.320000,16.980000,11.290000,...,0.000000,164.490000,0.870000,167.050000,98.350000,23.830000,28.490000,32.840000,44.210000,93.070000
max,5.000000,26464.260000,3.400000,3.630000,1.990000,27.740000,15.910000,71.850000,21.960000,15.810000,...,1.240000,619.920000,1.340000,626.030000,347.880000,31.070000,36.020000,41.700000,60.610000,131.810000

In [337]:
# Extracting funds which have 3Y Return', '5Y Return' & '10Y Return' greater than 10%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10) &
                            (regular_mf['10Y_RTN(%)'] > 10)]
print("No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is:", len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV']]

No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is: 15 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV
43,UTI Mastershare Unit Scheme,5,7734.48,60.32,11.91,13.64,11.88,40.94
65,Kotak Bluechip Fund,5,2411.04,60.58,12.35,13.35,12.07,12.43
39,Canara Robeco Bluechip Equity Fund - Regular Plan,5,2476.82,55.13,15.81,16.34,13.23,32.53
31,SBI Blue Chip Fund - Regular Plan,4,26464.26,63.25,10.54,12.59,13.90,66.29
6,Franklin India Bluechip Fund,4,5910.59,71.85,11.26,12.00,11.26,220.12
38,Edelweiss Large Cap Fund,4,235.51,57.24,11.21,13.76,12.97,39.52
3,PGIM India Large Cap Fund,3,308.64,55.89,10.91,12.50,11.45,619.92
48,Mirae Asset Large Cap Fund - Regular,3,23993.39,59.25,12.06,15.74,15.02,34.38
33,L&T India Large Cap Fund,3,626.07,52.75,10.03,12.31,11.22,46.80
36,IDFC Large Cap - Regular Plan,3,714.08,51.96,10.41,13.13,10.25,35.62
19,ICICI Prudential Bluechip Fund,3,26082.64,60.93,11.03,14.23,13.03,90.57
53,BNP Paribas Large Cap Fund,3,1029.84,49.69,12.43,12.67,13.53,14.16
44,Axis Bluechip Fund,3,24598.26,47.31,14.85,15.80,13.93,34.97
28,Tata Large Cap Fund - Regular Plan,2,892.44,61.50,10.48,12.25,11.43,83.99
59,LIC MF Large Cap Fund,2,506.24,48.86,11.29,12.16,10.44,12.51

In [338]:
# Extracting  last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'
#greater than 10%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10) &
                            (regular_mf['10Y_RTN(%)'] > 10)]
print("Last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'greater than 10% is:",
      len(mf_rtn_com.index), '\nFunds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

Last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'greater than 10% is: 15
Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
43,UTI Mastershare Unit Scheme,5,7734.48,40.94,7.54,15.05,-1.89,26.48,4.16
65,Kotak Bluechip Fund,5,2411.04,12.43,0.09,0.00,0.00,0.00,0.00
39,Canara Robeco Bluechip Equity Fund - Regular Plan,5,2476.82,32.53,13.24,15.03,-2.89,28.16,2.35
31,SBI Blue Chip Fund - Regular Plan,4,26464.26,66.29,9.09,13.28,-1.60,31.62,4.26
6,Franklin India Bluechip Fund,4,5910.59,220.12,13.71,10.83,0.78,33.92,8.40
38,Edelweiss Large Cap Fund,4,235.51,39.52,14.90,16.44,-1.41,30.37,3.84
3,PGIM India Large Cap Fund,3,308.64,619.92,10.17,9.27,-4.99,26.49,-0.51
48,Mirae Asset Large Cap Fund - Regular,3,23993.39,34.38,24.38,17.35,5.26,32.77,2.41
33,L&T India Large Cap Fund,3,626.07,46.80,16.81,16.63,-1.67,31.47,8.46
36,IDFC Large Cap - Regular Plan,3,714.08,35.62,14.88,12.39,-4.79,6.49,0.00
19,ICICI Prudential Bluechip Fund,3,26082.64,90.57,18.68,12.05,-2.85,35.48,7.07
53,BNP Paribas Large Cap Fund,3,1029.84,14.16,18.36,10.85,0.34,29.57,3.23
44,Axis Bluechip Fund,3,24598.26,34.97,8.39,15.90,-1.21,27.37,4.89
28,Tata Large Cap Fund - Regular Plan,2,892.44,83.99,16.64,17.88,-3.37,37.05,-6.06
59,LIC MF Large Cap Fund,2,506.24,12.51,13.05,14.13,-0.38,30.49,0.95

In [339]:
# Extracting funds which have '3Y Return' & '5Y Return' greater than 12%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 12) & (regular_mf['5Y_RTN(%)'] > 12)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 12% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return' & '5Y Return' greater than 12% is: 5 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
65,Kotak Bluechip Fund,5,2411.04,60.58,12.35,13.35,12.07,12.43,0.0,0.0,0.0,0.0
39,Canara Robeco Bluechip Equity Fund - Regular Plan,5,2476.82,55.13,15.81,16.34,13.23,32.53,0.0,0.0,0.0,0.0
48,Mirae Asset Large Cap Fund - Regular,3,23993.39,59.25,12.06,15.74,15.02,34.38,0.0,0.0,0.0,0.0
53,BNP Paribas Large Cap Fund,3,1029.84,49.69,12.43,12.67,13.53,14.16,0.0,57.0,0.0,0.0
44,Axis Bluechip Fund,3,24598.26,47.31,14.85,15.80,13.93,34.97,0.0,0.0,0.0,0.0

In [340]:
# Extracting last five years annual return for funds which have 3Y Return', '5Y Return' greater than 12%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 12) & (regular_mf['5Y_RTN(%)'] > 12)]
print("Last five years annual return for funds which have '5Y Return' & '10Y Return'greater than 10% is:",
      len(mf_rtn_com.index), '\nFunds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

Last five years annual return for funds which have '5Y Return' & '10Y Return'greater than 10% is: 5
Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
65,Kotak Bluechip Fund,5,2411.04,12.43,0.09,0.00,0.00,0.00,0.00
39,Canara Robeco Bluechip Equity Fund - Regular Plan,5,2476.82,32.53,13.24,15.03,-2.89,28.16,2.35
48,Mirae Asset Large Cap Fund - Regular,3,23993.39,34.38,24.38,17.35,5.26,32.77,2.41
53,BNP Paribas Large Cap Fund,3,1029.84,14.16,18.36,10.85,0.34,29.57,3.23
44,Axis Bluechip Fund,3,24598.26,34.97,8.39,15.90,-1.21,27.37,4.89

In [341]:
# Extracting funds which have '3Y Return' & '5Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 15) & (regular_mf['5Y_RTN(%)'] > 15)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
            'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return' & '5Y Return' greater than 15% is: 1 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
39,Canara Robeco Bluechip Equity Fund - Regular Plan,5,2476.82,55.13,15.81,16.34,13.23,32.53,0.0,0.0,0.0,0.0

In [342]:
# Extracting last five years annual return for funds which have 3Y Return', '5Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 15) & (regular_mf['5Y_RTN(%)'] > 15)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

No. of funds having '3Y Return' & '5Y Return' greater than 15% is: 1 Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
39,Canara Robeco Bluechip Equity Fund - Regular Plan,5,2476.82,32.53,13.24,15.03,-2.89,28.16,2.35

In [343]:
# Extracting funds which have '5Y Return' & '10Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 15) & (regular_mf['10Y_RTN(%)'] > 15)]
print("No. of funds having '5Y Return' & '10Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
            'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '5Y Return' & '10Y Return' greater than 15% is: 1 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
48,Mirae Asset Large Cap Fund - Regular,3,23993.39,59.25,12.06,15.74,15.02,34.38,0.0,0.0,0.0,0.0

In [344]:
# Extracting last five years annual return for funds which have 5Y Return', '10Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 15) & (regular_mf['10Y_RTN(%)'] > 15)]
print("No. of funds having '5Y Return' & '10Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

No. of funds having '5Y Return' & '10Y Return' greater than 15% is: 1 Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
48,Mirae Asset Large Cap Fund - Regular,3,23993.39,34.38,24.38,17.35,5.26,32.77,2.41

## Portfolio Turnover Ratio(PTR)

Portfolio Turnover Ratio is the frequency in which the assets held under a fund has changed over the years. In simpler words, PTR provides a measurement on how many times the fund managers bought or sold the assets under a fund over a period of time. PTR is often determined by the market conditions and fund management style.

Suppose an equity fund purchased stocks worth Rs. 375 crore and sold stocks worth Rs. 450 crore. The average AUM of the fund is Rs.1500 crore. In this case, the Portfolio turnover ratio of the fund is 25%, which means one-fourth of the stocks were traded.

Funds that have higher turnover ratios, for example, can trigger higher costs for investors. First, a fund thatâ€™s actively managed may charge a higher expense ratio to cover the fund managerâ€™s services. The expense ratio represents the percentage you pay to own the fund on an annualized basis. At the low end, you can find index funds with expense ratios around 0.50% to 0.10%. But the most expensive funds can easily have expense ratios over 1%.

Turnover ratio can also give you an idea of what the fundâ€™s investment strategy is, which is important for choosing funds that align with your goals and objectives. A growth mutual fund, for instance, may have a higher turnover ratio if the fund manager is constantly looking for the best growth stocks to drive returns. But a fund that uses a value investing approach may have a lower turnover ratio if the fund manager is buying assets that have the potential to appreciate over time.

In [345]:
# Top 10 low turnover ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Turnover ratio(%)'] > 0)]
print("Top 10 low turnover ratio regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Turnover ratio(%)']].nsmallest(10, 'Turnover ratio(%)')

Top 10 low turnover ratio regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Turnover ratio(%)
53,BNP Paribas Large Cap Fund,3,1029.84,49.69,12.43,12.67,13.53,14.16,57.00
50,Navi Large Cap Equity Fund,3,95.55,56.01,9.33,12.01,0.00,20.18,66.00
51,HSBC Large Cap Equity Fund,3,689.71,53.65,9.92,13.37,10.29,19.02,66.00
25,IDBI India Top 100 Equity Fund,4,425.99,55.49,11.33,11.91,0.00,91.85,67.68
12,Taurus Largecap Equity Fund,2,29.13,49.89,7.98,9.54,8.05,289.75,84.00
1,HDFC Top 100 Fund,1,18445.21,62.11,9.70,13.23,10.90,589.93,199.00

In [346]:
# Top 10 high turnover ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Turnover ratio(%)'] > 0)]
print("Top 10 high turnover ratio regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Turnover ratio(%)']].nlargest(10, 'Turnover ratio(%)')

Top 10 high turnover ratio regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Turnover ratio(%)
1,HDFC Top 100 Fund,1,18445.21,62.11,9.70,13.23,10.90,589.93,199.00
12,Taurus Largecap Equity Fund,2,29.13,49.89,7.98,9.54,8.05,289.75,84.00
25,IDBI India Top 100 Equity Fund,4,425.99,55.49,11.33,11.91,0.00,91.85,67.68
50,Navi Large Cap Equity Fund,3,95.55,56.01,9.33,12.01,0.00,20.18,66.00
51,HSBC Large Cap Equity Fund,3,689.71,53.65,9.92,13.37,10.29,19.02,66.00
53,BNP Paribas Large Cap Fund,3,1029.84,49.69,12.43,12.67,13.53,14.16,57.00

## Standard Deviation (SD)

The standard deviation of a stock or a mutual fund represents the riskiness of the stock or the mutual fund.

Standard Deviation is a percentage, expressed as an annualised figure.

Higher the standard Deviation, higher is the volatility of the asset. Higher the volatility, higher is the risk.

Do note, volatility or Standard Deviation should not worry you. Markets are volatile, and equities are volatile, mutual funds are volatile; this is the very nature of markets. So if you canâ€™t fathom watching your investment see-saw between gains and loss, then perhaps you should reconsider your investment decision inequities.

In [347]:
# Top 10 low standard deviation regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Standard Deviation'] > 0)]
print("Top 10 low standard deviation regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Standard Deviation']].nsmallest(10, 'Standard Deviation')

Top 10 low standard deviation regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Standard Deviation
3,PGIM India Large Cap Fund,3,308.64,55.89,10.91,12.50,11.45,619.92,18.34
15,Nippon India Large Cap Fund,2,9828.19,65.07,8.57,13.26,12.39,257.65,19.40
23,Union Largecap Fund,3,181.90,56.16,9.33,0.00,0.00,59.08,19.76
11,ITI Large Cap Fund - Regular Plan,0,163.77,0.00,0.00,0.00,0.00,281.26,20.05
6,Franklin India Bluechip Fund,4,5910.59,71.85,11.26,12.00,11.26,220.12,20.46
1,HDFC Top 100 Fund,1,18445.21,62.11,9.70,13.23,10.90,589.93,20.48
19,ICICI Prudential Bluechip Fund,3,26082.64,60.93,11.03,14.23,13.03,90.57,20.58
12,Taurus Largecap Equity Fund,2,29.13,49.89,7.98,9.54,8.05,289.75,20.70
17,Baroda Large Cap Fund - Plan A,4,40.90,54.39,11.46,12.87,7.64,164.49,20.96
10,ITI Large Cap Fund - Regular Plan,0,0.00,0.00,0.00,0.00,0.00,316.33,21.01

In [348]:
# Top 10 high standard deviation regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Standard Deviation'] > 0)]
print("Top 10 high standard deviation regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Standard Deviation']].nlargest(10, 'Standard Deviation')

Top 10 high standard deviation regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Standard Deviation
7,Mahindra Manulife Large Cap Pragati Yojana - R...,0,108.26,59.15,0.00,0.00,0.00,287.31,22.71
25,IDBI India Top 100 Equity Fund,4,425.99,55.49,11.33,11.91,0.00,91.85,21.96
21,Aditya Birla Sun Life Frontline Equity Fund - ...,2,19292.47,61.24,9.61,12.48,12.72,119.75,21.12
10,ITI Large Cap Fund - Regular Plan,0,0.00,0.00,0.00,0.00,0.00,316.33,21.01
17,Baroda Large Cap Fund - Plan A,4,40.90,54.39,11.46,12.87,7.64,164.49,20.96
12,Taurus Largecap Equity Fund,2,29.13,49.89,7.98,9.54,8.05,289.75,20.70
19,ICICI Prudential Bluechip Fund,3,26082.64,60.93,11.03,14.23,13.03,90.57,20.58
1,HDFC Top 100 Fund,1,18445.21,62.11,9.70,13.23,10.90,589.93,20.48
6,Franklin India Bluechip Fund,4,5910.59,71.85,11.26,12.00,11.26,220.12,20.46
11,ITI Large Cap Fund - Regular Plan,0,163.77,0.00,0.00,0.00,0.00,281.26,20.05

## Beta Ratios

A Beta Ratio in Mutual Funds offers investors the data on the degree of the volatility a Mutual Fund displays in response to market fluctuations. An investor can determine which fund would be best suited to meet his/her financial objectives.

Suppose, the beta ratio of a specific Mutual Fund is 0.7 or 70%; it means the fund is 0.3 or 30% less volatile than the benchmark index. A Beta ratio value of 1 indicates a lower risk and lower growth potential compared to ratios at par or above 1.

Investors with a low-risk appetite would always prefer a lower beta ratio in Mutual Funds as it indicates a steadier response to a volatile market condition. Similarly, investors with the investment objective of higher returns would prefer beta ratios of 1 or more than 1.

In [349]:
# Top 10 low beta regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 0)]
print("Top 10 low beta regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']].nsmallest(10, 'Beta')

Top 10 low beta regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
3,PGIM India Large Cap Fund,3,308.64,55.89,10.91,12.50,11.45,619.92,0.81
15,Nippon India Large Cap Fund,2,9828.19,65.07,8.57,13.26,12.39,257.65,0.85
23,Union Largecap Fund,3,181.90,56.16,9.33,0.00,0.00,59.08,0.91
6,Franklin India Bluechip Fund,4,5910.59,71.85,11.26,12.00,11.26,220.12,0.92
1,HDFC Top 100 Fund,1,18445.21,62.11,9.70,13.23,10.90,589.93,0.92
19,ICICI Prudential Bluechip Fund,3,26082.64,60.93,11.03,14.23,13.03,90.57,0.93
12,Taurus Largecap Equity Fund,2,29.13,49.89,7.98,9.54,8.05,289.75,0.93
11,ITI Large Cap Fund - Regular Plan,0,163.77,0.00,0.00,0.00,0.00,281.26,0.93
21,Aditya Birla Sun Life Frontline Equity Fund - ...,2,19292.47,61.24,9.61,12.48,12.72,119.75,0.96
25,IDBI India Top 100 Equity Fund,4,425.99,55.49,11.33,11.91,0.00,91.85,0.97

In [350]:
# Top 10 high beta regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 0)]
print("Top 10 high beta regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']].nlargest(10, 'Beta')

Top 10 high beta regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
7,Mahindra Manulife Large Cap Pragati Yojana - R...,0,108.26,59.15,0.00,0.00,0.00,287.31,1.01
10,ITI Large Cap Fund - Regular Plan,0,0.00,0.00,0.00,0.00,0.00,316.33,0.98
25,IDBI India Top 100 Equity Fund,4,425.99,55.49,11.33,11.91,0.00,91.85,0.97
17,Baroda Large Cap Fund - Plan A,4,40.90,54.39,11.46,12.87,7.64,164.49,0.97
21,Aditya Birla Sun Life Frontline Equity Fund - ...,2,19292.47,61.24,9.61,12.48,12.72,119.75,0.96
19,ICICI Prudential Bluechip Fund,3,26082.64,60.93,11.03,14.23,13.03,90.57,0.93
12,Taurus Largecap Equity Fund,2,29.13,49.89,7.98,9.54,8.05,289.75,0.93
11,ITI Large Cap Fund - Regular Plan,0,163.77,0.00,0.00,0.00,0.00,281.26,0.93
6,Franklin India Bluechip Fund,4,5910.59,71.85,11.26,12.00,11.26,220.12,0.92
1,HDFC Top 100 Fund,1,18445.21,62.11,9.70,13.23,10.90,589.93,0.92

In [351]:
# Funds with 'Beta' lesser than 1.00
mf_tr = regular_mf.loc[(regular_mf['Beta'] < 1.00) & (regular_mf['Beta'] != 0.00)]
print("Funds with 'Beta' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']]

Funds with 'Beta' lesser than 1.00 are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
25,IDBI India Top 100 Equity Fund,4,425.99,55.49,11.33,11.91,0.00,91.85,0.97
6,Franklin India Bluechip Fund,4,5910.59,71.85,11.26,12.00,11.26,220.12,0.92
17,Baroda Large Cap Fund - Plan A,4,40.90,54.39,11.46,12.87,7.64,164.49,0.97
23,Union Largecap Fund,3,181.90,56.16,9.33,0.00,0.00,59.08,0.91
3,PGIM India Large Cap Fund,3,308.64,55.89,10.91,12.50,11.45,619.92,0.81
19,ICICI Prudential Bluechip Fund,3,26082.64,60.93,11.03,14.23,13.03,90.57,0.93
12,Taurus Largecap Equity Fund,2,29.13,49.89,7.98,9.54,8.05,289.75,0.93
15,Nippon India Large Cap Fund,2,9828.19,65.07,8.57,13.26,12.39,257.65,0.85
21,Aditya Birla Sun Life Frontline Equity Fund - ...,2,19292.47,61.24,9.61,12.48,12.72,119.75,0.96
1,HDFC Top 100 Fund,1,18445.21,62.11,9.70,13.23,10.90,589.93,0.92
11,ITI Large Cap Fund - Regular Plan,0,163.77,0.00,0.00,0.00,0.00,281.26,0.93
10,ITI Large Cap Fund - Regular Plan,0,0.00,0.00,0.00,0.00,0.00,316.33,0.98

In [352]:
# Funds with 'Beta' greater than 1.00
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 1.00) & (regular_mf['Beta'] != 0.00)]
print("Funds with 'Beta' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']]

Funds with 'Beta' lesser than 1.00 are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
7,Mahindra Manulife Large Cap Pragati Yojana - R...,0,108.26,59.15,0.0,0.0,0.0,287.31,1.01

## What is Sharpe Ratio?

Sharpe Ratio of a mutual fund reveals its potential risk-adjusted returns. The risk-adjusted returns are the returns earned by an investment over the returns generated by any risk-free asset such as a fixed deposit. However, higher returns indicate extra risk. Higher Sharpe Ratio means greater returns from an investment but with a higher risk level. Therefore, it justifies the underlying volatility of the funds. The investors aiming for higher returns will have to invest in funds with higher risk factors.

Investments with less than 1.00 Sharpe Ratio do not generate high returns. Contrarily, investment with Sharpe Ratio of 1.00 to 3.00 or above have higher returns subsequently.

In [353]:
# Top 10 low sharpe ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 0)]
print("Top 10 low 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']].nsmallest(10, 'Sharpe Ratio')

Top 10 low 'Sharpe Ratio' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
23,Union Largecap Fund,3,181.90,56.16,9.33,0.00,0.00,59.08,0.22
12,Taurus Largecap Equity Fund,2,29.13,49.89,7.98,9.54,8.05,289.75,0.22
7,Mahindra Manulife Large Cap Pragati Yojana - R...,0,108.26,59.15,0.00,0.00,0.00,287.31,0.28
25,IDBI India Top 100 Equity Fund,4,425.99,55.49,11.33,11.91,0.00,91.85,0.31
1,HDFC Top 100 Fund,1,18445.21,62.11,9.70,13.23,10.90,589.93,0.33
10,ITI Large Cap Fund - Regular Plan,0,0.00,0.00,0.00,0.00,0.00,316.33,0.35
21,Aditya Birla Sun Life Frontline Equity Fund - ...,2,19292.47,61.24,9.61,12.48,12.72,119.75,0.36
6,Franklin India Bluechip Fund,4,5910.59,71.85,11.26,12.00,11.26,220.12,0.38
19,ICICI Prudential Bluechip Fund,3,26082.64,60.93,11.03,14.23,13.03,90.57,0.39
11,ITI Large Cap Fund - Regular Plan,0,163.77,0.00,0.00,0.00,0.00,281.26,0.40

In [354]:
# Top 10 high sharpe ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 0)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']].nlargest(10, 'Sharpe Ratio')

Top 10 high 'Sharpe Ratio' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
3,PGIM India Large Cap Fund,3,308.64,55.89,10.91,12.50,11.45,619.92,0.61
17,Baroda Large Cap Fund - Plan A,4,40.90,54.39,11.46,12.87,7.64,164.49,0.45
15,Nippon India Large Cap Fund,2,9828.19,65.07,8.57,13.26,12.39,257.65,0.41
11,ITI Large Cap Fund - Regular Plan,0,163.77,0.00,0.00,0.00,0.00,281.26,0.40
19,ICICI Prudential Bluechip Fund,3,26082.64,60.93,11.03,14.23,13.03,90.57,0.39
6,Franklin India Bluechip Fund,4,5910.59,71.85,11.26,12.00,11.26,220.12,0.38
21,Aditya Birla Sun Life Frontline Equity Fund - ...,2,19292.47,61.24,9.61,12.48,12.72,119.75,0.36
10,ITI Large Cap Fund - Regular Plan,0,0.00,0.00,0.00,0.00,0.00,316.33,0.35
1,HDFC Top 100 Fund,1,18445.21,62.11,9.70,13.23,10.90,589.93,0.33
25,IDBI India Top 100 Equity Fund,4,425.99,55.49,11.33,11.91,0.00,91.85,0.31

In [355]:
# Funds with 'Sharpe Ratio' greater than or equal to 3.00
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] >= 3.00)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [356]:
# Funds with 'Sharpe Ratio' greater than to 2.00 & lesser than 2.99
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 2.00) & (regular_mf['Sharpe Ratio'] < 2.99)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [357]:
# Funds with 'Sharpe Ratio' greater than to 1.00 & lesser than 1.99
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 1.00) & (regular_mf['Sharpe Ratio'] < 1.99)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [358]:
# Funds with 'Sharpe Ratio' lesser than 1.00
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] != 0.00) & (regular_mf['Sharpe Ratio'] < 1.00)]
print("Funds with 'Sharpe Ratio' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Funds with 'Sharpe Ratio' lesser than 1.00 are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
25,IDBI India Top 100 Equity Fund,4,425.99,55.49,11.33,11.91,0.00,91.85,0.31
6,Franklin India Bluechip Fund,4,5910.59,71.85,11.26,12.00,11.26,220.12,0.38
17,Baroda Large Cap Fund - Plan A,4,40.90,54.39,11.46,12.87,7.64,164.49,0.45
23,Union Largecap Fund,3,181.90,56.16,9.33,0.00,0.00,59.08,0.22
3,PGIM India Large Cap Fund,3,308.64,55.89,10.91,12.50,11.45,619.92,0.61
19,ICICI Prudential Bluechip Fund,3,26082.64,60.93,11.03,14.23,13.03,90.57,0.39
12,Taurus Largecap Equity Fund,2,29.13,49.89,7.98,9.54,8.05,289.75,0.22
15,Nippon India Large Cap Fund,2,9828.19,65.07,8.57,13.26,12.39,257.65,0.41
21,Aditya Birla Sun Life Frontline Equity Fund - ...,2,19292.47,61.24,9.61,12.48,12.72,119.75,0.36
1,HDFC Top 100 Fund,1,18445.21,62.11,9.70,13.23,10.90,589.93,0.33
7,Mahindra Manulife Large Cap Pragati Yojana - R...,0,108.26,59.15,0.00,0.00,0.00,287.31,0.28
11,ITI Large Cap Fund - Regular Plan,0,163.77,0.00,0.00,0.00,0.00,281.26,0.40
10,ITI Large Cap Fund - Regular Plan,0,0.00,0.00,0.00,0.00,0.00,316.33,0.35

In [359]:
# Extracting funds which have 3Y Return', '5Y Return' & '10Y Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_SIP_RTN(%)'] > 25) & (regular_mf['5Y_SIP_RTN(%)'] > 25) &
                            (regular_mf['10Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '3Y SIP Return', '5Y SIP Return' & '10Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y SIP Return', '5Y SIP Return' & '10Y SIP Return' greater than 25% is: 13 Funds

,Scheme Name,Crisil Rank,AuM (Cr),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
39,Canara Robeco Bluechip Equity Fund - Regular Plan,5,2476.82,25.60,32.49,76.38,32.53,0.00,0.00,0.00,0.00
31,SBI Blue Chip Fund - Regular Plan,4,26464.26,30.79,38.83,80.00,66.29,0.00,0.00,0.00,0.00
25,IDBI India Top 100 Equity Fund,4,425.99,33.88,44.21,103.51,91.85,0.31,67.68,21.96,0.97
6,Franklin India Bluechip Fund,4,5910.59,26.19,35.53,100.37,220.12,0.38,0.00,20.46,0.92
17,Baroda Large Cap Fund - Plan A,4,40.90,29.91,37.51,101.28,164.49,0.45,0.00,20.96,0.97
50,Navi Large Cap Equity Fund,3,95.55,32.39,52.32,123.35,20.18,0.00,66.00,0.00,0.00
48,Mirae Asset Large Cap Fund - Regular,3,23993.39,31.54,42.73,107.84,34.38,0.00,0.00,0.00,0.00
33,L&T India Large Cap Fund,3,626.07,30.73,44.53,131.81,46.80,0.00,0.00,0.00,0.00
51,HSBC Large Cap Equity Fund,3,689.71,27.63,37.73,86.94,19.02,0.00,66.00,0.00,0.00
53,BNP Paribas Large Cap Fund,3,1029.84,28.03,38.37,83.17,14.16,0.00,57.00,0.00,0.00
21,Aditya Birla Sun Life Frontline Equity Fund - ...,2,19292.47,31.31,40.28,95.98,119.75,0.36,0.00,21.12,0.96
1,HDFC Top 100 Fund,1,18445.21,36.54,42.38,93.07,589.93,0.33,199.00,20.48,0.92
11,ITI Large Cap Fund - Regular Plan,0,163.77,33.12,41.54,114.78,281.26,0.40,0.00,20.05,0.93

In [360]:
# Extracting funds which have 3Y Return' & '5Y Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_SIP_RTN(%)'] > 25) & (regular_mf['5Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '3Y SIP Return' & '5Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y SIP Return' & '5Y SIP Return' greater than 25% is: 25 Funds

,Scheme Name,Crisil Rank,AuM (Cr),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
39,Canara Robeco Bluechip Equity Fund - Regular Plan,5,2476.82,25.60,32.49,76.38,32.53,0.00,0.00,0.00,0.00
31,SBI Blue Chip Fund - Regular Plan,4,26464.26,30.79,38.83,80.00,66.29,0.00,0.00,0.00,0.00
56,JM Large Cap Fund,4,54.20,25.61,35.11,0.00,13.59,0.00,0.00,0.00,0.00
25,IDBI India Top 100 Equity Fund,4,425.99,33.88,44.21,103.51,91.85,0.31,67.68,21.96,0.97
6,Franklin India Bluechip Fund,4,5910.59,26.19,35.53,100.37,220.12,0.38,0.00,20.46,0.92
17,Baroda Large Cap Fund - Plan A,4,40.90,29.91,37.51,101.28,164.49,0.45,0.00,20.96,0.97
23,Union Largecap Fund,3,181.90,41.70,60.61,0.00,59.08,0.22,0.00,19.76,0.91
3,PGIM India Large Cap Fund,3,308.64,27.88,38.92,0.00,619.92,0.61,0.00,18.34,0.81
50,Navi Large Cap Equity Fund,3,95.55,32.39,52.32,123.35,20.18,0.00,66.00,0.00,0.00
48,Mirae Asset Large Cap Fund - Regular,3,23993.39,31.54,42.73,107.84,34.38,0.00,0.00,0.00,0.00
33,L&T India Large Cap Fund,3,626.07,30.73,44.53,131.81,46.80,0.00,0.00,0.00,0.00
36,IDFC Large Cap - Regular Plan,3,714.08,27.09,35.10,0.00,35.62,0.00,0.00,0.00,0.00
19,ICICI Prudential Bluechip Fund,3,26082.64,36.33,48.81,0.00,90.57,0.39,0.00,20.58,0.93
51,HSBC Large Cap Equity Fund,3,689.71,27.63,37.73,86.94,19.02,0.00,66.00,0.00,0.00
53,BNP Paribas Large Cap Fund,3,1029.84,28.03,38.37,83.17,14.16,0.00,57.00,0.00,0.00
12,Taurus Largecap Equity Fund,2,29.13,32.84,45.40,0.00,289.75,0.22,84.00,20.70,0.93
28,Tata Large Cap Fund - Regular Plan,2,892.44,33.03,48.60,0.00,83.99,0.00,0.00,0.00,0.00
15,Nippon India Large Cap Fund,2,9828.19,35.54,48.41,0.00,257.65,0.41,0.00,19.40,0.85
21,Aditya Birla Sun Life Frontline Equity Fund - ...,2,19292.47,31.31,40.28,95.98,119.75,0.36,0.00,21.12,0.96
1,HDFC Top 100 Fund,1,18445.21,36.54,42.38,93.07,589.93,0.33,199.00,20.48,0.92
29,Sundaram Bluechip Fund - Regular Plan,0,982.45,28.16,35.45,0.00,50.40,0.00,0.00,0.00,0.00
47,Principal Large Cap Fund - Regular Plan,0,413.00,30.20,42.30,0.00,32.86,0.00,0.00,0.00,0.00
7,Mahindra Manulife Large Cap Pragati Yojana - R...,0,108.26,28.06,37.81,0.00,287.31,0.28,0.00,22.71,1.01
11,ITI Large Cap Fund - Regular Plan,0,163.77,33.12,41.54,114.78,281.26,0.40,0.00,20.05,0.93
10,ITI Large Cap Fund - Regular Plan,0,0.00,34.76,44.82,0.00,316.33,0.35,0.00,21.01,0.98

In [361]:
# Extracting funds which have '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['1Y_SIP_RTN(%)'] > 25) & (regular_mf['2Y_SIP_RTN(%)'] > 25) &
                            (regular_mf['3Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']].nlargest(10, 'AuM (Cr)')

No. of funds having '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25% is: 4 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
1,HDFC Top 100 Fund,1,18445.21,31.07,36.02,36.54,589.93,0.33,199.0,20.48,0.92
6,Franklin India Bluechip Fund,4,5910.59,26.18,26.31,26.19,220.12,0.38,0.0,20.46,0.92
3,PGIM India Large Cap Fund,3,308.64,26.79,27.44,27.88,619.92,0.61,0.0,18.34,0.81
7,Mahindra Manulife Large Cap Pragati Yojana - R...,0,108.26,25.86,26.96,28.06,287.31,0.28,0.0,22.71,1.01

In [362]:
# Top 10 high AuM (Cr) regular mutual funds are
#mf_tr = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 0)]
print("Top 10 high 'AuM (Cr)' regular mutual funds are :")
mf_tr =  mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)',
       'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']].nlargest(10, 'AuM (Cr)')
mf_tr

Top 10 high 'AuM (Cr)' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
19,ICICI Prudential Bluechip Fund,3,26082.64,60.93,11.03,14.23,13.03,0.39,0.00,20.58,0.93
21,Aditya Birla Sun Life Frontline Equity Fund - ...,2,19292.47,61.24,9.61,12.48,12.72,0.36,0.00,21.12,0.96
1,HDFC Top 100 Fund,1,18445.21,62.11,9.70,13.23,10.90,0.33,199.00,20.48,0.92
15,Nippon India Large Cap Fund,2,9828.19,65.07,8.57,13.26,12.39,0.41,0.00,19.40,0.85
6,Franklin India Bluechip Fund,4,5910.59,71.85,11.26,12.00,11.26,0.38,0.00,20.46,0.92
25,IDBI India Top 100 Equity Fund,4,425.99,55.49,11.33,11.91,0.00,0.31,67.68,21.96,0.97
3,PGIM India Large Cap Fund,3,308.64,55.89,10.91,12.50,11.45,0.61,0.00,18.34,0.81
23,Union Largecap Fund,3,181.90,56.16,9.33,0.00,0.00,0.22,0.00,19.76,0.91
11,ITI Large Cap Fund - Regular Plan,0,163.77,0.00,0.00,0.00,0.00,0.40,0.00,20.05,0.93
7,Mahindra Manulife Large Cap Pragati Yojana - R...,0,108.26,59.15,0.00,0.00,0.00,0.28,0.00,22.71,1.01

In [363]:
# Top 10 low AuM (Cr) regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 0)]
print("Top 10 low 'AuM (Cr)' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)',
       'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']].nsmallest(10, 'AuM (Cr)')

Top 10 low 'AuM (Cr)' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
12,Taurus Largecap Equity Fund,2,29.13,49.89,7.98,9.54,8.05,0.22,84.00,20.70,0.93
17,Baroda Large Cap Fund - Plan A,4,40.90,54.39,11.46,12.87,7.64,0.45,0.00,20.96,0.97
56,JM Large Cap Fund,4,54.20,37.15,9.34,10.13,9.18,0.00,0.00,0.00,0.00
50,Navi Large Cap Equity Fund,3,95.55,56.01,9.33,12.01,0.00,0.00,66.00,0.00,0.00
63,Indiabulls Bluechip Fund - Regular Plan,1,112.18,46.13,7.14,11.43,0.00,0.00,0.00,0.00,0.00
38,Edelweiss Large Cap Fund,4,235.51,57.24,11.21,13.76,12.97,0.00,0.00,0.00,0.00
57,Invesco India Largecap Fund,2,290.74,48.20,9.54,12.15,11.56,0.00,0.00,0.00,0.00
3,PGIM India Large Cap Fund,3,308.64,55.89,10.91,12.50,11.45,0.61,0.00,18.34,0.81
25,IDBI India Top 100 Equity Fund,4,425.99,55.49,11.33,11.91,0.00,0.31,67.68,21.96,0.97
59,LIC MF Large Cap Fund,2,506.24,48.86,11.29,12.16,10.44,0.00,0.00,0.00,0.00

In [364]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 0) & (regular_mf['AuM (Cr)'] < 500) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds eturns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds eturns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs is: 4 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
25,IDBI India Top 100 Equity Fund,4,425.99,55.49,11.33,11.91,0.00,91.85,0.31,67.68,21.96,0.97
38,Edelweiss Large Cap Fund,4,235.51,57.24,11.21,13.76,12.97,39.52,0.00,0.00,0.00,0.00
17,Baroda Large Cap Fund - Plan A,4,40.90,54.39,11.46,12.87,7.64,164.49,0.45,0.00,20.96,0.97
3,PGIM India Large Cap Fund,3,308.64,55.89,10.91,12.50,11.45,619.92,0.61,0.00,18.34,0.81

In [365]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 500Crs to 1000Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 500) & (regular_mf['AuM (Cr)'] < 1000) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is:", len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is: 4 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
33,L&T India Large Cap Fund,3,626.07,52.75,10.03,12.31,11.22,46.80,0.0,0.0,0.0,0.0
36,IDFC Large Cap - Regular Plan,3,714.08,51.96,10.41,13.13,10.25,35.62,0.0,0.0,0.0,0.0
28,Tata Large Cap Fund - Regular Plan,2,892.44,61.50,10.48,12.25,11.43,83.99,0.0,0.0,0.0,0.0
59,LIC MF Large Cap Fund,2,506.24,48.86,11.29,12.16,10.44,12.51,0.0,0.0,0.0,0.0

In [366]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 1000) & (regular_mf['AuM (Cr)'] < 1500) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs is: 1 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
53,BNP Paribas Large Cap Fund,3,1029.84,49.69,12.43,12.67,13.53,14.16,0.0,57.0,0.0,0.0

In [367]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 1500 to 20000Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 1500) & (regular_mf['AuM (Cr)'] < 20000) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds returns 10% in 3year & 5year period which have AuM in between 1500Crs to 20000Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds returns 10% in 3year & 5year period which have AuM in between 1500Crs to 20000Crs is: 4 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
43,UTI Mastershare Unit Scheme,5,7734.48,60.32,11.91,13.64,11.88,40.94,0.00,0.0,0.00,0.00
65,Kotak Bluechip Fund,5,2411.04,60.58,12.35,13.35,12.07,12.43,0.00,0.0,0.00,0.00
39,Canara Robeco Bluechip Equity Fund - Regular Plan,5,2476.82,55.13,15.81,16.34,13.23,32.53,0.00,0.0,0.00,0.00
6,Franklin India Bluechip Fund,4,5910.59,71.85,11.26,12.00,11.26,220.12,0.38,0.0,20.46,0.92