In [50]:
# Importing respective modules
import pandas as pd
import re

In [51]:
# Reading elss mutual funds csv file
fc_mf = pd.read_csv('fc_mf_data(10-May-2021 21:28:01).csv')

In [52]:
# Extracting a plan from "Scheme Name" column
scheme_name = list(fc_mf['Scheme Name'])
plan = []
for i in scheme_name:
    #print(type(i))
    plan.append(re.findall("Direct|Regular", str(i)))
#plan
for p in plan:
    if len(p) == 0:
        #print(type(p))
        p.append("Regular")
fc_mf['Plan'] = plan

In [53]:
# Extracting a category from "Scheme Name" column
scheme_name = list(fc_mf['Scheme Name'])
category = []
for i in scheme_name:
    #print(type(i))
    category.append(re.findall("Flexi Cap Fund", str(i)))
fc_mf['Category'] = category

In [54]:
# Modifiying 'Scheme Name' column
fc_mf['Scheme Name'] = fc_mf['Scheme Name'].str.replace(' - GrowthFlexi Cap Fund', '')

In [55]:
#Replacing "']" & "['" string with "" in Plan columns
fc_mf['Plan'] = fc_mf['Plan'].astype(str).str.replace("\['","", regex=True)
fc_mf['Plan'] = fc_mf['Plan'].astype(str).str.replace("']","", regex=True)

#Replacing "']" & "['" string with "" in Category columns
fc_mf['Category'] = fc_mf['Category'].astype(str).str.replace("\['","", regex=True)
fc_mf['Category'] = fc_mf['Category'].astype(str).str.replace("']","", regex=True)

In [56]:
#Replacing "ELSS', 'ELSS" string with "ELSS" in Category columns
fc_mf['Category'] = fc_mf['Category'].astype(str).str.replace("Flexi Cap Fund', 'Flexi Cap Fund",
                                                              "Flexi Cap Fund", regex=True)

#Replacing "%" string with "" in Crisil Rank, % Debt Holding, No of instruments in portfolio,
# % MF Holding, % Other Holding, Turnover ratio, MTD, 10Y_SIP_RTN(%) & 5Y_SIP_RTN(%) columns
fc_mf[['% Debt Holding', 'No of instruments in portfolio',
          '% MF Holding', '% Other Holding', 'Turnover ratio(%)',
          'MTD', '10Y_SIP_RTN(%)', '5Y_SIP_RTN(%)'         
         ]] = fc_mf[['% Debt Holding', 'No of instruments in portfolio',
                        '% MF Holding', '% Other Holding', 'Turnover ratio(%)',
                        'MTD', '10Y_SIP_RTN(%)', '5Y_SIP_RTN(%)'
                        ]].replace("%", "", regex=True)

#Replacing "-" string with "0" in Crisil Rank columns
fc_mf['Crisil Rank'] = fc_mf['Crisil Rank'].replace("-", "", regex=True)

In [57]:
#Replacing "-" string with "0" in Crisil Rank columns
fc_mf['Crisil Rank'] = fc_mf['Crisil Rank'].replace("", "0", regex=True)

#Replacing "%" with '' in the column
fc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding', '% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)',
         "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20",
         "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19",
         "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)"
         ]] = fc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)"
                       ]].replace("%", "", regex=True)
print("Shape of the dataframe:", fc_mf.shape)
fc_mf.head()

Shape of the dataframe: (50, 86)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
0,HDFC Flexi Cap Fund - Direct Plan,2,23128.13,2.46,1.56,1.11,35.30,14.19,69.40,11.92,...,03-Mar-21,489.0460,19-May-20,34.62,52.19,59.88,75.36,-,Direct,Flexi Cap Fund
1,Motilal Oswal Flexi Cap Fund - Direct Plan,1,11872.55,2.45,-0.37,1.82,19.58,6.00,56.93,12.52,...,03-Mar-21,462.3730,19-May-20,33.00,48.86,54.86,66.50,-,Direct,Flexi Cap Fund
2,HDFC Flexi Cap Fund,2,23128.13,2.44,1.51,0.95,34.91,13.95,68.41,11.29,...,03-Mar-21,459.8922,18-May-20,30.32,36.55,37.06,44.76,-,Regular,Flexi Cap Fund
3,Motilal Oswal Flexi Cap Fund,1,11872.55,2.44,-0.45,1.59,19.07,5.67,55.47,11.50,...,03-Mar-21,429.5256,18-May-20,30.02,30.96,31.53,40.92,-,Regular,Flexi Cap Fund
4,Franklin India Flexi Cap Fund - Direct,3,9459.36,2.33,1.17,1.17,31.86,14.26,76.63,16.18,...,07-May-21,597.8700,18-May-20,29.74,35.44,35.39,41.50,110.75,Direct,Flexi Cap Fund

In [58]:
#Sorting a fc_mf dataframe by "Crisil Rank Column"
fc_mf.sort_values(by=['Crisil Rank', 'Scheme Name', 'AuM (Cr)'], inplace=True, ascending=False)
print("Shape of the dataframe:", fc_mf.shape)
fc_mf.head()

Shape of the dataframe: (50, 86)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
46,UTI Flexi Cap Fund - Direct Plan,5,16717.24,0.45,-1.13,0.67,24.72,6.58,74.40,24.37,...,03-Mar-21,27.800,18-May-20,15.55,18.86,22.05,27.89,61.44,Direct,Flexi Cap Fund
47,UTI Flexi Cap Fund,5,16717.24,0.44,-1.19,0.49,24.30,6.32,73.16,23.58,...,03-Mar-21,29.881,18-May-20,15.20,18.92,-,-,-,Regular,Flexi Cap Fund
24,PGIM India Flexi Cap Fund - Direct Plan,5,774.12,1.34,2.89,7.01,31.99,14.40,87.26,30.50,...,03-Mar-21,18.530,18-May-20,22.92,29.98,32.57,42.56,-,Direct,Flexi Cap Fund
25,PGIM India Flexi Cap Fund,5,774.12,1.27,2.68,6.40,30.61,13.55,83.58,28.05,...,15-Feb-21,17.100,18-May-20,22.77,32.71,38.87,56.60,-,Regular,Flexi Cap Fund
35,Union Flexi Cap Fund - Direct Plan,4,496.06,1.05,0.63,2.48,23.83,9.13,63.13,19.61,...,15-Feb-21,33.110,18-May-20,21.04,23.22,23.46,28.59,94.26,Direct,Flexi Cap Fund

In [59]:
#Replacing "-" with 'None' in the columns
fc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding', '% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)',
         "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20",
         "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19",
         "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)"
         ]] = fc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)"]].replace({'-' : None})

In [60]:
#Replacing "" with '0' in the columns

fc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding','% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)',
         '10Y_SIP_RTN(%)', "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20",
         "Sep'20", "Aug'20", "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20",
         "Q4'19", "Q3'19", "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)",
         "Standard Deviation", "Beta", "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio", 'Crisil Rank'
         ]] = fc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',\
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)", "Standard Deviation", "Beta",
                       "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio", 'Crisil Rank']].fillna(value='0')

In [61]:
#Changing the datatype of the return & risk ratio columns

fc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding','% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)',
         '10Y_SIP_RTN(%)', "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20",
         "Sep'20", "Aug'20", "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20",
         "Q4'19", "Q3'19", "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)",
         "Standard Deviation", "Beta", "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio"
         ]] = fc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)", "Standard Deviation", "Beta",
                       "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio"]].apply(pd.to_numeric)

In [62]:
#Changing the datatype of the 'Crisil Rank' columns
fc_mf['Crisil Rank'] = fc_mf['Crisil Rank'].astype('int')

In [63]:
#Removing white spaces at both ends in all over the dataframe:

fc_mf.columns = fc_mf.columns.str.strip()

#Checking the data type of all columns in the DataFrame
fc_mf_dtype = fc_mf.dtypes

df_dtypes = pd.DataFrame(fc_mf_dtype)

In [64]:
#Using pandas dataframe.round()function to round off all the decimal values to 2 decimal places
fc_mf = fc_mf.round(2)

In [99]:
# #Exporting the consolidated elss mf data as a  csv file
# print("Shape of the dataframe:", fc_mf.shape)
#fc_mf.to_csv('final_fc_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)',
#                 index=False)

# #Exporting the elss mf data columns with its datatype as a  csv file
# df_dtypes.to_csv('fc_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')

In [66]:
#Exctracting regular mutual funds
regular_mf = fc_mf.loc[fc_mf['Plan'] == 'Regular']
regular_mf.head()

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
47,UTI Flexi Cap Fund,5,16717.24,0.44,-1.19,0.49,24.30,6.32,73.16,23.58,...,03-Mar-21,29.88,18-May-20,15.20,18.92,0.00,0.00,0.00,Regular,Flexi Cap Fund
25,PGIM India Flexi Cap Fund,5,774.12,1.27,2.68,6.40,30.61,13.55,83.58,28.05,...,15-Feb-21,17.10,18-May-20,22.77,32.71,38.87,56.60,0.00,Regular,Flexi Cap Fund
39,Union Flexi Cap Fund,4,496.06,1.00,0.52,2.25,23.32,8.79,61.79,18.72,...,15-Feb-21,64.43,18-May-20,19.48,23.18,24.62,33.46,0.00,Regular,Flexi Cap Fund
15,JM Flexi Cap Fund,4,164.37,1.85,-0.51,0.47,29.87,9.40,60.77,16.94,...,16-Feb-21,25.68,18-May-20,26.35,33.55,39.44,52.02,123.18,Regular,Flexi Cap Fund
32,DSP Flexi Cap Fund - Regular Plan,4,4982.77,1.09,1.11,3.41,26.76,10.15,64.07,20.74,...,07-May-21,10.00,29-Jun-20,21.75,27.12,27.04,32.11,92.44,Regular,Flexi Cap Fund

In [67]:
# Basic statistics of regular mutual fund df
regular_mf.describe()

,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),...,% Other Holding,NAV,1D Change(%),52W High,52W Low,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
count,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,...,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000
mean,2.400000,6352.808400,1.405200,0.812400,2.177200,23.498800,8.625200,57.498400,15.360800,8.960800,...,0.091200,160.566800,0.289600,163.525200,92.198800,22.404000,27.608400,25.726000,33.790000,24.803200
std,1.581139,8556.340171,0.655586,1.367895,2.669528,5.266455,3.631182,15.680122,5.881215,5.438264,...,0.315652,273.501805,0.409812,278.049598,152.096073,6.378511,8.561737,15.146008,20.694484,46.726677
min,0.000000,63.080000,-0.190000,-1.190000,-1.610000,14.530000,2.120000,0.000000,0.000000,0.000000,...,0.000000,12.510000,-0.380000,13.010000,8.250000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,358.980000,1.030000,-0.450000,0.490000,20.390000,6.320000,52.220000,12.030000,5.710000,...,0.000000,23.520000,0.020000,23.520000,12.240000,19.750000,22.450000,19.860000,22.740000,0.000000
50%,3.000000,2610.560000,1.270000,0.540000,1.590000,23.320000,8.790000,59.330000,15.290000,9.560000,...,0.000000,42.580000,0.230000,43.790000,25.680000,22.770000,28.490000,29.140000,37.210000,0.000000
75%,3.000000,9459.360000,1.900000,1.510000,3.190000,26.760000,10.400000,64.070000,18.080000,12.790000,...,0.000000,115.290000,0.410000,119.980000,71.630000,26.630000,32.710000,37.060000,48.340000,0.000000
max,5.000000,34744.360000,2.440000,4.020000,10.510000,34.910000,14.440000,83.580000,28.050000,20.040000,...,1.140000,977.890000,1.450000,977.890000,558.660000,30.320000,44.120000,52.040000,72.180000,135.130000

In [68]:
# Extracting funds which have 3Y Return', '5Y Return' & '10Y Return' greater than 10%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10) &
                            (regular_mf['10Y_RTN(%)'] > 10)]
print("No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is:", len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV']]

No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is: 8 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV
47,UTI Flexi Cap Fund,5,16717.24,73.16,15.68,16.88,14.67,49.09
15,JM Flexi Cap Fund,4,164.37,60.77,11.82,16.26,12.28,42.58
32,DSP Flexi Cap Fund - Regular Plan,4,4982.77,64.07,13.38,16.70,13.12,16.03
37,Canara Robeco Flexi Cap Fund - Regular Plan,4,3817.92,56.23,14.03,16.75,13.10,27.23
23,SBI Flexi Cap Fund - Regular Plan,3,11829.39,63.86,10.14,14.12,14.07,113.04
45,Kotak Flexi Cap Fund,3,34744.36,57.81,10.97,15.09,14.71,14.04
5,Franklin India Flexi Cap Fund,3,9459.36,75.32,10.05,12.39,13.61,977.89
13,Aditya Birla Sun Life Flexi Cap Fund - Regular...,3,13025.82,67.75,10.57,15.57,14.51,186.23

In [69]:
# Extracting  last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'
#greater than 10%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10) &
                            (regular_mf['10Y_RTN(%)'] > 10)]
print("Last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'greater than 10% is:",
      len(mf_rtn_com.index), '\nFunds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

Last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'greater than 10% is: 8
Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
47,UTI Flexi Cap Fund,5,16717.24,49.09,30.73,11.66,4.37,30.09,0.74
15,JM Flexi Cap Fund,4,164.37,42.58,15.70,6.67,-9.96,40.27,5.13
32,DSP Flexi Cap Fund - Regular Plan,4,4982.77,16.03,36.14,10.17,-7.26,36.62,-1.47
37,Canara Robeco Flexi Cap Fund - Regular Plan,4,3817.92,27.23,14.37,11.76,-4.09,38.57,6.20
23,SBI Flexi Cap Fund - Regular Plan,3,11829.39,113.04,11.74,12.38,-0.34,34.31,8.67
45,Kotak Flexi Cap Fund,3,34744.36,14.04,20.41,11.83,-2.83,27.54,0.60
5,Franklin India Flexi Cap Fund,3,9459.36,977.89,37.90,0.00,0.00,0.00,0.00
13,Aditya Birla Sun Life Flexi Cap Fund - Regular...,3,13025.82,186.23,13.01,5.18,-4.03,34.19,3.13

In [70]:
# Extracting funds which have '3Y Return' & '5Y Return' greater than 12%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 12) & (regular_mf['5Y_RTN(%)'] > 12)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 12% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return' & '5Y Return' greater than 12% is: 6 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
47,UTI Flexi Cap Fund,5,16717.24,73.16,15.68,16.88,14.67,49.09,0.0,61.00,0.0,0.0
25,PGIM India Flexi Cap Fund,5,774.12,83.58,16.95,17.93,0.00,27.68,0.0,10.00,0.0,0.0
39,Union Flexi Cap Fund,4,496.06,61.79,12.79,14.00,0.00,107.47,0.0,173.00,0.0,0.0
32,DSP Flexi Cap Fund - Regular Plan,4,4982.77,64.07,13.38,16.70,13.12,16.03,0.0,0.00,0.0,0.0
37,Canara Robeco Flexi Cap Fund - Regular Plan,4,3817.92,56.23,14.03,16.75,13.10,27.23,0.0,0.00,0.0,0.0
27,Parag Parikh Flexi Cap Fund,0,8181.79,72.24,20.04,19.23,0.00,18.97,0.0,18.93,0.0,0.0

In [71]:
# Extracting last five years annual return for funds which have 3Y Return', '5Y Return' greater than 12%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 12) & (regular_mf['5Y_RTN(%)'] > 12)]
print("Last five years annual return for funds which have '5Y Return' & '10Y Return'greater than 10% is:",
      len(mf_rtn_com.index), '\nFunds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

Last five years annual return for funds which have '5Y Return' & '10Y Return'greater than 10% is: 6
Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
47,UTI Flexi Cap Fund,5,16717.24,49.09,30.73,11.66,4.37,30.09,0.74
25,PGIM India Flexi Cap Fund,5,774.12,27.68,15.72,3.17,-3.79,30.63,4.48
39,Union Flexi Cap Fund,4,496.06,107.47,14.14,8.74,2.05,0.00,0.00
32,DSP Flexi Cap Fund - Regular Plan,4,4982.77,16.03,36.14,10.17,-7.26,36.62,-1.47
37,Canara Robeco Flexi Cap Fund - Regular Plan,4,3817.92,27.23,14.37,11.76,-4.09,38.57,6.20
27,Parag Parikh Flexi Cap Fund,0,8181.79,18.97,9.90,13.91,-7.49,25.65,1.56

In [72]:
# Extracting funds which have '3Y Return' & '5Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 15) & (regular_mf['5Y_RTN(%)'] > 15)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
            'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return' & '5Y Return' greater than 15% is: 3 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
47,UTI Flexi Cap Fund,5,16717.24,73.16,15.68,16.88,14.67,49.09,0.0,61.00,0.0,0.0
25,PGIM India Flexi Cap Fund,5,774.12,83.58,16.95,17.93,0.00,27.68,0.0,10.00,0.0,0.0
27,Parag Parikh Flexi Cap Fund,0,8181.79,72.24,20.04,19.23,0.00,18.97,0.0,18.93,0.0,0.0

In [73]:
# Extracting last five years annual return for funds which have 3Y Return', '5Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 15) & (regular_mf['5Y_RTN(%)'] > 15)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

No. of funds having '3Y Return' & '5Y Return' greater than 15% is: 3 Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
47,UTI Flexi Cap Fund,5,16717.24,49.09,30.73,11.66,4.37,30.09,0.74
25,PGIM India Flexi Cap Fund,5,774.12,27.68,15.72,3.17,-3.79,30.63,4.48
27,Parag Parikh Flexi Cap Fund,0,8181.79,18.97,9.90,13.91,-7.49,25.65,1.56

In [74]:
# Extracting funds which have '5Y Return' & '10Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 15) & (regular_mf['10Y_RTN(%)'] > 15)]
print("No. of funds having '5Y Return' & '10Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
            'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '5Y Return' & '10Y Return' greater than 15% is: 0 Funds

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio, Turnover ratio(%), Standard Deviation, Beta]
Index: []

In [75]:
# Extracting last five years annual return for funds which have 5Y Return', '10Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 15) & (regular_mf['10Y_RTN(%)'] > 15)]
print("No. of funds having '5Y Return' & '10Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

No. of funds having '5Y Return' & '10Y Return' greater than 15% is: 0 Funds

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), NAV, 2020_RTN(%), 2019_RTN(%), 2018_RTN(%), 2017_RTN(%), 2016_RTN(%)]
Index: []

## Portfolio Turnover Ratio(PTR)

Portfolio Turnover Ratio is the frequency in which the assets held under a fund has changed over the years. In simpler words, PTR provides a measurement on how many times the fund managers bought or sold the assets under a fund over a period of time. PTR is often determined by the market conditions and fund management style.

Suppose an equity fund purchased stocks worth Rs. 375 crore and sold stocks worth Rs. 450 crore. The average AUM of the fund is Rs.1500 crore. In this case, the Portfolio turnover ratio of the fund is 25%, which means one-fourth of the stocks were traded.

Funds that have higher turnover ratios, for example, can trigger higher costs for investors. First, a fund thatâ€™s actively managed may charge a higher expense ratio to cover the fund managerâ€™s services. The expense ratio represents the percentage you pay to own the fund on an annualized basis. At the low end, you can find index funds with expense ratios around 0.50% to 0.10%. But the most expensive funds can easily have expense ratios over 1%.

Turnover ratio can also give you an idea of what the fundâ€™s investment strategy is, which is important for choosing funds that align with your goals and objectives. A growth mutual fund, for instance, may have a higher turnover ratio if the fund manager is constantly looking for the best growth stocks to drive returns. But a fund that uses a value investing approach may have a lower turnover ratio if the fund manager is buying assets that have the potential to appreciate over time.

In [76]:
# Top 10 low turnover ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Turnover ratio(%)'] > 0)]
print("Top 10 low turnover ratio regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Turnover ratio(%)']].nsmallest(10, 'Turnover ratio(%)')

Top 10 low turnover ratio regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Turnover ratio(%)
25,PGIM India Flexi Cap Fund,5,774.12,83.58,16.95,17.93,0.00,27.68,10.00
5,Franklin India Flexi Cap Fund,3,9459.36,75.32,10.05,12.39,13.61,977.89,17.41
27,Parag Parikh Flexi Cap Fund,0,8181.79,72.24,20.04,19.23,0.00,18.97,18.93
19,Edelweiss Flexi Cap Fund - Regular Plan,3,679.38,62.01,9.15,15.35,0.00,40.38,26.00
2,HDFC Flexi Cap Fund,2,23128.13,68.41,9.56,14.15,11.34,842.00,35.40
3,Motilal Oswal Flexi Cap Fund,1,11872.55,55.47,5.71,12.75,0.00,780.74,35.40
23,SBI Flexi Cap Fund - Regular Plan,3,11829.39,63.86,10.14,14.12,14.07,113.04,36.00
17,LIC MF Flexi Cap Fund,2,358.98,41.30,8.27,9.91,8.16,42.47,41.00
11,BOI AXA Flexi Cap Fund - Regular Plan,0,70.90,0.00,0.00,0.00,0.00,31.61,48.00
15,JM Flexi Cap Fund,4,164.37,60.77,11.82,16.26,12.28,42.58,50.00

In [77]:
# Top 10 high turnover ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Turnover ratio(%)'] > 0)]
print("Top 10 high turnover ratio regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Turnover ratio(%)']].nlargest(10, 'Turnover ratio(%)')

Top 10 high turnover ratio regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Turnover ratio(%)
49,Tata Flexi Cap Fund,0,1828.76,45.37,0.00,0.00,0.00,220.94,1316.00
39,Union Flexi Cap Fund,4,496.06,61.79,12.79,14.00,0.00,107.47,173.00
38,Axis Flexi Cap Fund,3,7625.95,48.77,13.71,0.00,0.00,115.29,173.00
41,Navi Flexi Cap Fund,0,186.59,57.31,0.00,0.00,0.00,13.31,121.00
43,HSBC Flexi Cap Fund,2,362.33,60.17,6.44,11.69,11.97,12.51,105.00
13,Aditya Birla Sun Life Flexi Cap Fund - Regular...,3,13025.82,67.75,10.57,15.57,14.51,186.23,93.62
7,L&T Flexi Cap Fund,3,2610.56,59.33,6.98,12.45,11.46,128.44,74.00
21,Taurus Flexi Cap Fund,1,235.46,49.98,4.09,9.15,8.40,57.28,68.00
47,UTI Flexi Cap Fund,5,16717.24,73.16,15.68,16.88,14.67,49.09,61.00
15,JM Flexi Cap Fund,4,164.37,60.77,11.82,16.26,12.28,42.58,50.00

## Standard Deviation (SD)

The standard deviation of a stock or a mutual fund represents the riskiness of the stock or the mutual fund.

Standard Deviation is a percentage, expressed as an annualised figure.

Higher the standard Deviation, higher is the volatility of the asset. Higher the volatility, higher is the risk.

Do note, volatility or Standard Deviation should not worry you. Markets are volatile, and equities are volatile, mutual funds are volatile; this is the very nature of markets. So if you canâ€™t fathom watching your investment see-saw between gains and loss, then perhaps you should reconsider your investment decision inequities.

In [78]:
# Top 10 low standard deviation regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Standard Deviation'] > 0)]
print("Top 10 low standard deviation regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Standard Deviation']].nsmallest(10, 'Standard Deviation')

Top 10 low standard deviation regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Standard Deviation
11,BOI AXA Flexi Cap Fund - Regular Plan,0,70.90,0.00,0.00,0.00,0.00,31.61,18.15
19,Edelweiss Flexi Cap Fund - Regular Plan,3,679.38,62.01,9.15,15.35,0.00,40.38,18.20
17,LIC MF Flexi Cap Fund,2,358.98,41.30,8.27,9.91,8.16,42.47,18.51
15,JM Flexi Cap Fund,4,164.37,60.77,11.82,16.26,12.28,42.58,18.65
5,Franklin India Flexi Cap Fund,3,9459.36,75.32,10.05,12.39,13.61,977.89,18.98
13,Aditya Birla Sun Life Flexi Cap Fund - Regular...,3,13025.82,67.75,10.57,15.57,14.51,186.23,20.36
2,HDFC Flexi Cap Fund,2,23128.13,68.41,9.56,14.15,11.34,842.00,20.38
8,IDBI Flexi Cap Fund - Regular Plan,3,315.35,56.83,8.00,11.34,0.00,109.66,21.13
7,L&T Flexi Cap Fund,3,2610.56,59.33,6.98,12.45,11.46,128.44,21.27
21,Taurus Flexi Cap Fund,1,235.46,49.98,4.09,9.15,8.40,57.28,21.28

In [79]:
# Top 10 high standard deviation regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Standard Deviation'] > 0)]
print("Top 10 high standard deviation regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Standard Deviation']].nlargest(10, 'Standard Deviation')

Top 10 high standard deviation regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Standard Deviation
3,Motilal Oswal Flexi Cap Fund,1,11872.55,55.47,5.71,12.75,0.00,780.74,22.59
21,Taurus Flexi Cap Fund,1,235.46,49.98,4.09,9.15,8.40,57.28,21.28
7,L&T Flexi Cap Fund,3,2610.56,59.33,6.98,12.45,11.46,128.44,21.27
8,IDBI Flexi Cap Fund - Regular Plan,3,315.35,56.83,8.00,11.34,0.00,109.66,21.13
2,HDFC Flexi Cap Fund,2,23128.13,68.41,9.56,14.15,11.34,842.00,20.38
13,Aditya Birla Sun Life Flexi Cap Fund - Regular...,3,13025.82,67.75,10.57,15.57,14.51,186.23,20.36
5,Franklin India Flexi Cap Fund,3,9459.36,75.32,10.05,12.39,13.61,977.89,18.98
15,JM Flexi Cap Fund,4,164.37,60.77,11.82,16.26,12.28,42.58,18.65
17,LIC MF Flexi Cap Fund,2,358.98,41.30,8.27,9.91,8.16,42.47,18.51
19,Edelweiss Flexi Cap Fund - Regular Plan,3,679.38,62.01,9.15,15.35,0.00,40.38,18.20

## Beta Ratios

A Beta Ratio in Mutual Funds offers investors the data on the degree of the volatility a Mutual Fund displays in response to market fluctuations. An investor can determine which fund would be best suited to meet his/her financial objectives.

Suppose, the beta ratio of a specific Mutual Fund is 0.7 or 70%; it means the fund is 0.3 or 30% less volatile than the benchmark index. A Beta ratio value of 1 indicates a lower risk and lower growth potential compared to ratios at par or above 1.

Investors with a low-risk appetite would always prefer a lower beta ratio in Mutual Funds as it indicates a steadier response to a volatile market condition. Similarly, investors with the investment objective of higher returns would prefer beta ratios of 1 or more than 1.

In [80]:
# Top 10 low beta regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 0)]
print("Top 10 low beta regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']].nsmallest(10, 'Beta')

Top 10 low beta regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
19,Edelweiss Flexi Cap Fund - Regular Plan,3,679.38,62.01,9.15,15.35,0.00,40.38,0.80
17,LIC MF Flexi Cap Fund,2,358.98,41.30,8.27,9.91,8.16,42.47,0.81
11,BOI AXA Flexi Cap Fund - Regular Plan,0,70.90,0.00,0.00,0.00,0.00,31.61,0.83
5,Franklin India Flexi Cap Fund,3,9459.36,75.32,10.05,12.39,13.61,977.89,0.88
15,JM Flexi Cap Fund,4,164.37,60.77,11.82,16.26,12.28,42.58,0.91
13,Aditya Birla Sun Life Flexi Cap Fund - Regular...,3,13025.82,67.75,10.57,15.57,14.51,186.23,0.92
8,IDBI Flexi Cap Fund - Regular Plan,3,315.35,56.83,8.00,11.34,0.00,109.66,0.93
2,HDFC Flexi Cap Fund,2,23128.13,68.41,9.56,14.15,11.34,842.00,0.95
3,Motilal Oswal Flexi Cap Fund,1,11872.55,55.47,5.71,12.75,0.00,780.74,0.97
7,L&T Flexi Cap Fund,3,2610.56,59.33,6.98,12.45,11.46,128.44,1.00

In [81]:
# Top 10 high beta regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 0)]
print("Top 10 high beta regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']].nlargest(10, 'Beta')

Top 10 high beta regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
21,Taurus Flexi Cap Fund,1,235.46,49.98,4.09,9.15,8.40,57.28,1.03
7,L&T Flexi Cap Fund,3,2610.56,59.33,6.98,12.45,11.46,128.44,1.00
3,Motilal Oswal Flexi Cap Fund,1,11872.55,55.47,5.71,12.75,0.00,780.74,0.97
2,HDFC Flexi Cap Fund,2,23128.13,68.41,9.56,14.15,11.34,842.00,0.95
8,IDBI Flexi Cap Fund - Regular Plan,3,315.35,56.83,8.00,11.34,0.00,109.66,0.93
13,Aditya Birla Sun Life Flexi Cap Fund - Regular...,3,13025.82,67.75,10.57,15.57,14.51,186.23,0.92
15,JM Flexi Cap Fund,4,164.37,60.77,11.82,16.26,12.28,42.58,0.91
5,Franklin India Flexi Cap Fund,3,9459.36,75.32,10.05,12.39,13.61,977.89,0.88
11,BOI AXA Flexi Cap Fund - Regular Plan,0,70.90,0.00,0.00,0.00,0.00,31.61,0.83
17,LIC MF Flexi Cap Fund,2,358.98,41.30,8.27,9.91,8.16,42.47,0.81

In [82]:
# Funds with 'Beta' lesser than 1.00
mf_tr = regular_mf.loc[(regular_mf['Beta'] < 1.00) & (regular_mf['Beta'] != 0.00)]
print("Funds with 'Beta' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']]

Funds with 'Beta' lesser than 1.00 are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
15,JM Flexi Cap Fund,4,164.37,60.77,11.82,16.26,12.28,42.58,0.91
8,IDBI Flexi Cap Fund - Regular Plan,3,315.35,56.83,8.00,11.34,0.00,109.66,0.93
5,Franklin India Flexi Cap Fund,3,9459.36,75.32,10.05,12.39,13.61,977.89,0.88
19,Edelweiss Flexi Cap Fund - Regular Plan,3,679.38,62.01,9.15,15.35,0.00,40.38,0.80
13,Aditya Birla Sun Life Flexi Cap Fund - Regular...,3,13025.82,67.75,10.57,15.57,14.51,186.23,0.92
17,LIC MF Flexi Cap Fund,2,358.98,41.30,8.27,9.91,8.16,42.47,0.81
2,HDFC Flexi Cap Fund,2,23128.13,68.41,9.56,14.15,11.34,842.00,0.95
3,Motilal Oswal Flexi Cap Fund,1,11872.55,55.47,5.71,12.75,0.00,780.74,0.97
11,BOI AXA Flexi Cap Fund - Regular Plan,0,70.90,0.00,0.00,0.00,0.00,31.61,0.83

In [83]:
# Funds with 'Beta' greater than 1.00
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 1.00) & (regular_mf['Beta'] != 0.00)]
print("Funds with 'Beta' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']]

Funds with 'Beta' lesser than 1.00 are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
21,Taurus Flexi Cap Fund,1,235.46,49.98,4.09,9.15,8.4,57.28,1.03

## What is Sharpe Ratio?

Sharpe Ratio of a mutual fund reveals its potential risk-adjusted returns. The risk-adjusted returns are the returns earned by an investment over the returns generated by any risk-free asset such as a fixed deposit. However, higher returns indicate extra risk. Higher Sharpe Ratio means greater returns from an investment but with a higher risk level. Therefore, it justifies the underlying volatility of the funds. The investors aiming for higher returns will have to invest in funds with higher risk factors.

Investments with less than 1.00 Sharpe Ratio do not generate high returns. Contrarily, investment with Sharpe Ratio of 1.00 to 3.00 or above have higher returns subsequently.

In [84]:
# Top 10 low sharpe ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 0)]
print("Top 10 low 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']].nsmallest(10, 'Sharpe Ratio')

Top 10 low 'Sharpe Ratio' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
8,IDBI Flexi Cap Fund - Regular Plan,3,315.35,56.83,8.00,11.34,0.00,109.66,0.13
5,Franklin India Flexi Cap Fund,3,9459.36,75.32,10.05,12.39,13.61,977.89,0.18
11,BOI AXA Flexi Cap Fund - Regular Plan,0,70.90,0.00,0.00,0.00,0.00,31.61,0.27
17,LIC MF Flexi Cap Fund,2,358.98,41.30,8.27,9.91,8.16,42.47,0.29
3,Motilal Oswal Flexi Cap Fund,1,11872.55,55.47,5.71,12.75,0.00,780.74,0.32
15,JM Flexi Cap Fund,4,164.37,60.77,11.82,16.26,12.28,42.58,0.35
7,L&T Flexi Cap Fund,3,2610.56,59.33,6.98,12.45,11.46,128.44,0.37
21,Taurus Flexi Cap Fund,1,235.46,49.98,4.09,9.15,8.40,57.28,0.41
2,HDFC Flexi Cap Fund,2,23128.13,68.41,9.56,14.15,11.34,842.00,0.42
19,Edelweiss Flexi Cap Fund - Regular Plan,3,679.38,62.01,9.15,15.35,0.00,40.38,0.58

In [85]:
# Top 10 high sharpe ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 0)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']].nlargest(10, 'Sharpe Ratio')

Top 10 high 'Sharpe Ratio' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
13,Aditya Birla Sun Life Flexi Cap Fund - Regular...,3,13025.82,67.75,10.57,15.57,14.51,186.23,0.66
19,Edelweiss Flexi Cap Fund - Regular Plan,3,679.38,62.01,9.15,15.35,0.00,40.38,0.58
2,HDFC Flexi Cap Fund,2,23128.13,68.41,9.56,14.15,11.34,842.00,0.42
21,Taurus Flexi Cap Fund,1,235.46,49.98,4.09,9.15,8.40,57.28,0.41
7,L&T Flexi Cap Fund,3,2610.56,59.33,6.98,12.45,11.46,128.44,0.37
15,JM Flexi Cap Fund,4,164.37,60.77,11.82,16.26,12.28,42.58,0.35
3,Motilal Oswal Flexi Cap Fund,1,11872.55,55.47,5.71,12.75,0.00,780.74,0.32
17,LIC MF Flexi Cap Fund,2,358.98,41.30,8.27,9.91,8.16,42.47,0.29
11,BOI AXA Flexi Cap Fund - Regular Plan,0,70.90,0.00,0.00,0.00,0.00,31.61,0.27
5,Franklin India Flexi Cap Fund,3,9459.36,75.32,10.05,12.39,13.61,977.89,0.18

In [86]:
# Funds with 'Sharpe Ratio' greater than or equal to 3.00
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] >= 3.00)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [87]:
# Funds with 'Sharpe Ratio' greater than to 2.00 & lesser than 2.99
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 2.00) & (regular_mf['Sharpe Ratio'] < 2.99)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [88]:
# Funds with 'Sharpe Ratio' greater than to 1.00 & lesser than 1.99
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 1.00) & (regular_mf['Sharpe Ratio'] < 1.99)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [89]:
# Funds with 'Sharpe Ratio' lesser than 1.00
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] != 0.00) & (regular_mf['Sharpe Ratio'] < 1.00)]
print("Funds with 'Sharpe Ratio' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Funds with 'Sharpe Ratio' lesser than 1.00 are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
15,JM Flexi Cap Fund,4,164.37,60.77,11.82,16.26,12.28,42.58,0.35
7,L&T Flexi Cap Fund,3,2610.56,59.33,6.98,12.45,11.46,128.44,0.37
8,IDBI Flexi Cap Fund - Regular Plan,3,315.35,56.83,8.00,11.34,0.00,109.66,0.13
5,Franklin India Flexi Cap Fund,3,9459.36,75.32,10.05,12.39,13.61,977.89,0.18
19,Edelweiss Flexi Cap Fund - Regular Plan,3,679.38,62.01,9.15,15.35,0.00,40.38,0.58
13,Aditya Birla Sun Life Flexi Cap Fund - Regular...,3,13025.82,67.75,10.57,15.57,14.51,186.23,0.66
17,LIC MF Flexi Cap Fund,2,358.98,41.30,8.27,9.91,8.16,42.47,0.29
2,HDFC Flexi Cap Fund,2,23128.13,68.41,9.56,14.15,11.34,842.00,0.42
21,Taurus Flexi Cap Fund,1,235.46,49.98,4.09,9.15,8.40,57.28,0.41
3,Motilal Oswal Flexi Cap Fund,1,11872.55,55.47,5.71,12.75,0.00,780.74,0.32
11,BOI AXA Flexi Cap Fund - Regular Plan,0,70.90,0.00,0.00,0.00,0.00,31.61,0.27

In [90]:
# Extracting funds which have 3Y Return', '5Y Return' & '10Y Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_SIP_RTN(%)'] > 25) & (regular_mf['5Y_SIP_RTN(%)'] > 25) &
                            (regular_mf['10Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '3Y SIP Return', '5Y SIP Return' & '10Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y SIP Return', '5Y SIP Return' & '10Y SIP Return' greater than 25% is: 5 Funds

,Scheme Name,Crisil Rank,AuM (Cr),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
15,JM Flexi Cap Fund,4,164.37,39.44,52.02,123.18,42.58,0.35,50.00,18.65,0.91
32,DSP Flexi Cap Fund - Regular Plan,4,4982.77,27.04,32.11,92.44,16.03,0.00,0.00,0.00,0.00
5,Franklin India Flexi Cap Fund,3,9459.36,30.33,38.41,97.11,977.89,0.18,17.41,18.98,0.88
31,IDFC Flexi Cap Fund - Regular Plan,2,5288.99,36.19,52.16,113.88,23.52,0.00,0.00,0.00,0.00
11,BOI AXA Flexi Cap Fund - Regular Plan,0,70.90,44.21,60.48,135.13,31.61,0.27,48.00,18.15,0.83

In [91]:
# Extracting funds which have 3Y Return' & '5Y Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_SIP_RTN(%)'] > 25) & (regular_mf['5Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '3Y SIP Return' & '5Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y SIP Return' & '5Y SIP Return' greater than 25% is: 14 Funds

,Scheme Name,Crisil Rank,AuM (Cr),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
25,PGIM India Flexi Cap Fund,5,774.12,38.87,56.60,0.00,27.68,0.00,10.00,0.00,0.00
15,JM Flexi Cap Fund,4,164.37,39.44,52.02,123.18,42.58,0.35,50.00,18.65,0.91
32,DSP Flexi Cap Fund - Regular Plan,4,4982.77,27.04,32.11,92.44,16.03,0.00,0.00,0.00,0.00
23,SBI Flexi Cap Fund - Regular Plan,3,11829.39,29.14,37.21,0.00,113.04,0.00,36.00,0.00,0.00
7,L&T Flexi Cap Fund,3,2610.56,37.35,48.34,0.00,128.44,0.37,74.00,21.27,1.00
8,IDBI Flexi Cap Fund - Regular Plan,3,315.35,52.04,72.18,0.00,109.66,0.13,0.00,21.13,0.93
5,Franklin India Flexi Cap Fund,3,9459.36,30.33,38.41,97.11,977.89,0.18,17.41,18.98,0.88
19,Edelweiss Flexi Cap Fund - Regular Plan,3,679.38,38.49,49.46,0.00,40.38,0.58,26.00,18.20,0.80
13,Aditya Birla Sun Life Flexi Cap Fund - Regular...,3,13025.82,34.63,46.20,0.00,186.23,0.66,93.62,20.36,0.92
17,LIC MF Flexi Cap Fund,2,358.98,31.40,43.39,0.00,42.47,0.29,41.00,18.51,0.81
31,IDFC Flexi Cap Fund - Regular Plan,2,5288.99,36.19,52.16,113.88,23.52,0.00,0.00,0.00,0.00
2,HDFC Flexi Cap Fund,2,23128.13,37.06,44.76,0.00,842.00,0.42,35.40,20.38,0.95
3,Motilal Oswal Flexi Cap Fund,1,11872.55,31.53,40.92,0.00,780.74,0.32,35.40,22.59,0.97
11,BOI AXA Flexi Cap Fund - Regular Plan,0,70.90,44.21,60.48,135.13,31.61,0.27,48.00,18.15,0.83

In [92]:
# Extracting funds which have '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['1Y_SIP_RTN(%)'] > 25) & (regular_mf['2Y_SIP_RTN(%)'] > 25) &
                            (regular_mf['3Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25% is: 9 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
15,JM Flexi Cap Fund,4,164.37,26.35,33.55,39.44,42.58,0.35,50.00,18.65,0.91
7,L&T Flexi Cap Fund,3,2610.56,28.32,34.79,37.35,128.44,0.37,74.00,21.27,1.00
8,IDBI Flexi Cap Fund - Regular Plan,3,315.35,27.90,44.12,52.04,109.66,0.13,0.00,21.13,0.93
5,Franklin India Flexi Cap Fund,3,9459.36,29.57,30.17,30.33,977.89,0.18,17.41,18.98,0.88
13,Aditya Birla Sun Life Flexi Cap Fund - Regular...,3,13025.82,26.63,31.19,34.63,186.23,0.66,93.62,20.36,0.92
17,LIC MF Flexi Cap Fund,2,358.98,25.08,29.64,31.40,42.47,0.29,41.00,18.51,0.81
2,HDFC Flexi Cap Fund,2,23128.13,30.32,36.55,37.06,842.00,0.42,35.40,20.38,0.95
3,Motilal Oswal Flexi Cap Fund,1,11872.55,30.02,30.96,31.53,780.74,0.32,35.40,22.59,0.97
11,BOI AXA Flexi Cap Fund - Regular Plan,0,70.90,27.34,39.15,44.21,31.61,0.27,48.00,18.15,0.83

In [93]:
# Top 10 high AuM (Cr) regular mutual funds are
#mf_tr = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 0)]
print("Top 10 high 'AuM (Cr)' regular mutual funds are :")
mf_tr =  mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)',
       'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']].nlargest(10, 'AuM (Cr)')
mf_tr

Top 10 high 'AuM (Cr)' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
2,HDFC Flexi Cap Fund,2,23128.13,68.41,9.56,14.15,11.34,0.42,35.40,20.38,0.95
13,Aditya Birla Sun Life Flexi Cap Fund - Regular...,3,13025.82,67.75,10.57,15.57,14.51,0.66,93.62,20.36,0.92
3,Motilal Oswal Flexi Cap Fund,1,11872.55,55.47,5.71,12.75,0.00,0.32,35.40,22.59,0.97
5,Franklin India Flexi Cap Fund,3,9459.36,75.32,10.05,12.39,13.61,0.18,17.41,18.98,0.88
7,L&T Flexi Cap Fund,3,2610.56,59.33,6.98,12.45,11.46,0.37,74.00,21.27,1.00
19,Edelweiss Flexi Cap Fund - Regular Plan,3,679.38,62.01,9.15,15.35,0.00,0.58,26.00,18.20,0.80
17,LIC MF Flexi Cap Fund,2,358.98,41.30,8.27,9.91,8.16,0.29,41.00,18.51,0.81
8,IDBI Flexi Cap Fund - Regular Plan,3,315.35,56.83,8.00,11.34,0.00,0.13,0.00,21.13,0.93
21,Taurus Flexi Cap Fund,1,235.46,49.98,4.09,9.15,8.40,0.41,68.00,21.28,1.03
15,JM Flexi Cap Fund,4,164.37,60.77,11.82,16.26,12.28,0.35,50.00,18.65,0.91

In [94]:
# Top 10 low AuM (Cr) regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 0)]
print("Top 10 low 'AuM (Cr)' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)',
       'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']].nsmallest(10, 'AuM (Cr)')

Top 10 low 'AuM (Cr)' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
15,JM Flexi Cap Fund,4,164.37,60.77,11.82,16.26,12.28,0.35,50.0,18.65,0.91
21,Taurus Flexi Cap Fund,1,235.46,49.98,4.09,9.15,8.40,0.41,68.0,21.28,1.03
8,IDBI Flexi Cap Fund - Regular Plan,3,315.35,56.83,8.00,11.34,0.00,0.13,0.0,21.13,0.93
17,LIC MF Flexi Cap Fund,2,358.98,41.30,8.27,9.91,8.16,0.29,41.0,18.51,0.81
43,HSBC Flexi Cap Fund,2,362.33,60.17,6.44,11.69,11.97,0.00,105.0,0.00,0.00
39,Union Flexi Cap Fund,4,496.06,61.79,12.79,14.00,0.00,0.00,173.0,0.00,0.00
19,Edelweiss Flexi Cap Fund - Regular Plan,3,679.38,62.01,9.15,15.35,0.00,0.58,26.0,18.20,0.80
25,PGIM India Flexi Cap Fund,5,774.12,83.58,16.95,17.93,0.00,0.00,10.0,0.00,0.00
7,L&T Flexi Cap Fund,3,2610.56,59.33,6.98,12.45,11.46,0.37,74.0,21.27,1.00
37,Canara Robeco Flexi Cap Fund - Regular Plan,4,3817.92,56.23,14.03,16.75,13.10,0.00,0.0,0.00,0.00

In [95]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 0) & (regular_mf['AuM (Cr)'] < 500) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds returns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds returns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs is: 2 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
39,Union Flexi Cap Fund,4,496.06,61.79,12.79,14.00,0.00,107.47,0.00,173.0,0.00,0.00
15,JM Flexi Cap Fund,4,164.37,60.77,11.82,16.26,12.28,42.58,0.35,50.0,18.65,0.91

In [96]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 500Crs to 1000Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 500) & (regular_mf['AuM (Cr)'] < 1000) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is:", len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is: 1 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
25,PGIM India Flexi Cap Fund,5,774.12,83.58,16.95,17.93,0.0,27.68,0.0,10.0,0.0,0.0

In [97]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 1000) & (regular_mf['AuM (Cr)'] < 1500) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs is: 0 Funds

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio, Turnover ratio(%), Standard Deviation, Beta]
Index: []

In [98]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 1500 to 20000Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 1500) & (regular_mf['AuM (Cr)'] < 20000) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds returns 10% in 3year & 5year period which have AuM in between 1500Crs to 20000Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds returns 10% in 3year & 5year period which have AuM in between 1500Crs to 20000Crs is: 7 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
47,UTI Flexi Cap Fund,5,16717.24,73.16,15.68,16.88,14.67,49.09,0.00,61.00,0.00,0.00
32,DSP Flexi Cap Fund - Regular Plan,4,4982.77,64.07,13.38,16.70,13.12,16.03,0.00,0.00,0.00,0.00
37,Canara Robeco Flexi Cap Fund - Regular Plan,4,3817.92,56.23,14.03,16.75,13.10,27.23,0.00,0.00,0.00,0.00
23,SBI Flexi Cap Fund - Regular Plan,3,11829.39,63.86,10.14,14.12,14.07,113.04,0.00,36.00,0.00,0.00
5,Franklin India Flexi Cap Fund,3,9459.36,75.32,10.05,12.39,13.61,977.89,0.18,17.41,18.98,0.88
13,Aditya Birla Sun Life Flexi Cap Fund - Regular...,3,13025.82,67.75,10.57,15.57,14.51,186.23,0.66,93.62,20.36,0.92
27,Parag Parikh Flexi Cap Fund,0,8181.79,72.24,20.04,19.23,0.00,18.97,0.00,18.93,0.00,0.00