In [24]:
#Importing the required libraries
import pandas as pd

## Exctracting Medium to Long Duration  Mutual Fund's Historical Investment Returns Data

Data in this table: Get Absolute historical returns for ₹1000 investment. If 1Y column value is 1234.5 that means, your ₹1000 investment 1 year back would have grown to ₹1234.5.

In [25]:
mld_lump_sum_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/returns/medium-to-long-duration-fund.html")
df1 = pd.DataFrame(mld_lump_sum_rtn[0])

In [26]:
#Renaming historical returns column names
df1.rename({'1W': '1W_RTN(%)', '1M': '1M_RTN(%)', '3M': '3M_RTN(%)', '6M': '6M_RTN(%)',
                 'YTD': 'YTD_RTN(%)', '1Y': '1Y_RTN(%)', '2Y': '2Y_RTN(%)', '3Y': '3Y_RTN(%)',
                 '5Y': '5Y_RTN(%)', '10Y': '10Y_RTN(%)'
          }, axis=1, inplace=True)
print("Shape of the dataframe:", df1.shape)
df1.head()

Shape of the dataframe: (29, 13)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%)
0,UTI Bond Fund (Segregated - 17022020) - Direct...,-,15.55,0.21%,0.98%,2.84%,-20.27%,1.35%,-16.79%,-,-,-,-
1,UTI Bond Fund (Segregated - 17022020) - Regula...,-,15.55,0.21%,0.98%,2.84%,-20.44%,1.35%,-16.96%,-,-,-,-
2,Kotak Bond - Direct Plan - GrowthMedium to Lon...,4,1863.79,0.15%,0.71%,0.90%,1.71%,1.00%,6.87%,10.42%,9.99%,8.36%,-
3,SBI Magnum Income Fund - Direct Plan - GrowthM...,3,1709.60,0.13%,0.64%,1.69%,1.87%,1.06%,8.73%,11.52%,10.21%,9.55%,-
4,Kotak Bond - Regular Plan - GrowthMedium to Lo...,4,1863.79,0.13%,0.62%,0.63%,1.16%,0.87%,5.71%,9.24%,8.87%,7.32%,8.21%

## Exctracting Medium to Long Duration  Mutual Fund's Monthly Returns Data

Data in this table: Get monthly returns. If Jan month column value is 5.4% that means, fund has given 5.4% returns in Jan month.

In [27]:
mld_monthly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/monthly-returns/medium-to-long-duration-fund.html")
df2 = pd.DataFrame(mld_monthly_rtn[0])

In [28]:
#Renaming df1 column names
df1.rename({"Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            'MTD': 'MTD_RTN(%)', "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)"
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df2.shape)
df2.head()

Shape of the dataframe: (29, 14)

,Scheme Name,Crisil Rank,MTD,Apr'21,Mar'21,Feb'21,Jan'21,Dec'20,Nov'20,Oct'20,Sep'20,Aug'20,Jul'20,Jun'20
0,ICICI Prudential Bond Fund - GrowthMedium to L...,3,0.25%,0.87%,1.10%,-0.81%,-0.20%,0.28%,0.61%,1.65%,-0.26%,-0.61%,1.60%,1.52%
1,ICICI Prudential Bond Fund - Direct Plan - Gro...,3,0.27%,0.93%,1.16%,-0.77%,-0.16%,0.33%,0.66%,1.69%,-0.21%,-0.56%,1.65%,1.56%
2,Kotak Bond - Regular Plan - GrowthMedium to Lo...,4,0.37%,0.48%,0.59%,-1.65%,0.20%,1.06%,0.83%,1.52%,-0.26%,-1.55%,1.00%,1.11%
3,Kotak Bond - Direct Plan - GrowthMedium to Lon...,4,0.41%,0.57%,0.69%,-1.57%,0.28%,1.15%,0.91%,1.60%,-0.17%,-1.45%,1.09%,1.20%
4,HDFC Income Fund - GrowthMedium to Long Durati...,2,0.34%,0.63%,0.57%,-0.83%,0.13%,0.47%,0.60%,1.33%,-0.25%,-0.91%,1.04%,0.89%

## Exctracting Medium to Long Duration  Mutual Fund's Quarterly Returns Data

Data in this table: Get quarterly returns. If Q1 column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Mar.

In [29]:
mld_quarterly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/quarterly-returns/medium-to-long-duration-fund.html")
df3 = pd.DataFrame(mld_quarterly_rtn[0])

In [30]:
print("Shape of the dataframe:", df3.shape)
df3.head()

Shape of the dataframe: (29, 14)

,Scheme Name,Crisil Rank,QTD,Q1'21,Q4'20,Q3'20,Q2'20,Q1'20,Q4'19,Q3'19,Q2'19,Q1'19,Q4'18,Q3'18
0,ICICI Prudential Bond Fund - GrowthMedium to L...,3,1.12%,-0.46%,2.52%,1.49%,3.93%,2.87%,2.42%,3.02%,2.27%,2.78%,2.90%,1.14%
1,ICICI Prudential Bond Fund - Direct Plan - Gro...,3,1.20%,-0.30%,2.67%,1.63%,4.05%,3.00%,2.55%,3.16%,2.41%,2.93%,3.05%,1.29%
2,Kotak Bond - Regular Plan - GrowthMedium to Lo...,4,0.85%,-1.55%,3.46%,0.39%,3.94%,3.22%,1.38%,2.51%,2.97%,2.92%,3.42%,0.96%
3,Kotak Bond - Direct Plan - GrowthMedium to Lon...,4,0.98%,-1.28%,3.73%,0.67%,4.22%,3.49%,1.64%,2.78%,3.22%,3.18%,3.67%,1.16%
4,HDFC Income Fund - GrowthMedium to Long Durati...,2,0.98%,-0.78%,2.41%,0.81%,2.71%,2.48%,1.63%,2.21%,2.48%,2.04%,2.94%,0.91%

## Exctracting Medium to Long Duration  Mutual Fund's Annual Investment Returns Data

Data in this table: Get annual returns. If 2018 year column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Dec/Last date.

In [31]:
mld_annual_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/annual-returns/medium-to-long-duration-fund.html")
df4 = pd.DataFrame(mld_annual_rtn[0])

In [32]:
#Renaming yearly returns column names
df4.rename({'2020': '2020_RTN(%)', '2019': '2019_RTN(%)', '2018': '2018_RTN(%)', '2017': '2017_RTN(%)',
                 '2016': '2016_RTN(%)', '2015': '2015_RTN(%)', '2014': '2014_RTN(%)', '2013': '2013_RTN(%)',
                 '2012': '2012_RTN(%)', '2011': '2011_RTN(%)', '2010': '2010_RTN(%)'
               }, axis=1, inplace=True)

print("Shape of the dataframe:", df4.shape)
df4.head()

Shape of the dataframe: (29, 14)

,Scheme Name,Crisil Rank,YTD,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%),2015_RTN(%),2014_RTN(%),2013_RTN(%),2012_RTN(%),2011_RTN(%),2010_RTN(%)
0,ICICI Prudential Bond Fund - Growth Medium to ...,3,0.65%,11.37%,10.95%,4.53%,5.29%,11.23%,8.42%,14.50%,3.89%,11.27%,6.98%,4.14%
1,ICICI Prudential Bond Fund - Direct Plan - Gro...,3,0.89%,11.97%,11.55%,5.14%,5.91%,11.71%,8.75%,14.79%,4.06%,-,-,-
2,Kotak Bond - Regular Plan - Growth Medium to L...,4,-0.71%,11.88%,10.53%,5.13%,0.89%,14.18%,4.80%,15.29%,1.67%,12.93%,8.28%,4.37%
3,Kotak Bond - Direct Plan - Growth Medium to Lo...,4,-0.29%,13.03%,11.66%,6.06%,1.80%,15.11%,5.64%,16.02%,2.31%,-,-,-
4,HDFC Income Fund - Growth Medium to Long Durat...,2,0.17%,8.93%,8.81%,3.50%,1.30%,14.37%,5.40%,15.76%,1.73%,10.51%,6.29%,5.50%

## Exctracting Medium to Long Duration  Mutual Fund's Rank Within Category Data

Data in this table: Get performance rank within category. If 1Y column value is 3/45 that means, Fund ranked 3rd in terms of performance out of 45 funds in that category.

In [33]:
mld_rank_in_category = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/ranks/medium-to-long-duration-fund.html")
df5 = pd.DataFrame(mld_rank_in_category[0])

In [34]:
#Renaming df5 column names
df5.rename({'1W': '1W_Rank', '1M': '1M_Rank', '3M': '3M_Rank', '6M': '6M_Rank', 'YTD': 'YTD_Rank',
            '1Y': '1Y_Rank', '2Y': '2Y_Rank', '3Y': '3Y_Rank', '5Y': '5Y_Rank', '10Y': '10Y_Rank'
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df5.shape)
df5.head()

Shape of the dataframe: (29, 12)

,Scheme Name,Crisil Rank,1W_Rank,1M_Rank,3M_Rank,6M_Rank,YTD_Rank,1Y_Rank,2Y_Rank,3Y_Rank,5Y_Rank,10Y_Rank
0,SBI Magnum Income Fund - Regular Plan - Growth...,3,3/15,11/15,6/15,3/15,10/15,1/15,1/14,3/14,1/14,1/14
1,SBI Magnum Income Fund - Direct Plan - GrowthM...,3,3/14,9/14,5/14,2/14,10/14,1/14,1/13,3/13,1/13,0/0
2,Aditya Birla Sun Life Income Fund - Direct Pla...,3,7/14,10/14,2/14,1/14,3/14,2/14,2/13,2/13,3/13,0/0
3,Aditya Birla Sun Life Income Fund - Regular Pl...,3,8/15,10/15,3/15,2/15,4/15,3/15,3/14,2/14,4/14,5/14
4,Aditya Birla Sun Life Income Fund - Regular Pl...,-,8/15,10/15,3/15,2/15,4/15,3/15,3/14,2/14,4/14,5/14

## Exctracting Medium to Long Duration  Mutual Fund's Risk Ratios Data

Data in this table: Get values of risk ratios calculated on daily returns for last 3 years.

In [35]:
mld_risk_ratio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/risk-ratios/medium-to-long-duration-fund.html")
df6 = pd.DataFrame(mld_risk_ratio[0])

In [36]:
#Droping the 'Category' column
df6.drop('Category', inplace=True, axis=1)
print("Shape of the dataframe:", df6.shape)
df6.head()

Shape of the dataframe: (13, 8)

,Scheme Name,Crisil Rank,AuM (Cr),Standard Deviation,Beta,Sharpe Ratio,Jension's Alpha,Treynor's Ratio
0,ICICI Prudential Bond Fund - Growth,3,3366.05,3.11,0.83,1.71,0.36,0.06
1,Kotak Bond - Regular Plan - Growth,4,1863.79,3.39,0.96,1.48,-0.67,0.05
2,HDFC Income Fund - Growth,2,664.94,2.85,0.82,1.31,-1.14,0.05
3,JM Income Fund - Growth,1,16.99,6.63,0.76,-0.16,-5.56,-0.01
4,IDFC Bond Fund - Income Plan - Regular Plan - ...,5,689.78,3.84,1.06,1.43,-0.76,0.05

## Exctracting Medium to Long Duration  Mutual Fund's Portfolio Data

Data in this table: Compare how schemes have invested money across various asset class and number of instruments.

In [37]:
mld_portfolio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/portfolioassets/medium-to-long-duration-fund.html")
df7 = pd.DataFrame(mld_portfolio[0])

In [38]:
#Renaming SIP returns column names
df7.rename({'Turnover ratio': 'Turnover ratio(%)'}, axis=1, inplace=True)

print("Shape of the dataframe:", df7.shape)
df7.head()

Shape of the dataframe: (29, 10)

,Scheme Name,Crisil Rank,Turnover ratio(%),% Equity Holding,No of stocks in portfolio,% Debt Holding,No of instruments in portfolio,% MF Holding,% Cash Holding,% Other Holding
0,Canara Robeco Income Fund - Regular Plan - Gro...,3,-,-,-,92.78%,19,-,7.22%,-
1,ICICI Prudential Bond Fund - GrowthMedium to L...,3,-,-,-,95.59%,62,-,4.41%,-
2,UTI Bond Fund (Segregated - 17022020) - Direct...,-,-,-,-,97.11%,1,-,2.89%,-
3,Kotak Bond - Direct Plan - GrowthMedium to Lon...,4,-,-,-,97.86%,26,-,2.14%,-
4,IDFC Bond Fund - Income Plan - Direct Plan - G...,5,-,-,-,93.93%,7,-,6.07%,-

## Exctracting Medium to Long Duration  Mutual Fund's Latest NAV Data

Data in this table: Get the latest values of NAV for the mutual funds.

In [39]:
mld_nav = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/navs/medium-to-long-duration-fund.html")
df8 = pd.DataFrame(mld_nav[0])

In [40]:
df8.rename({'1D Change' : '1D Change(%)'}, axis=1, inplace=True)
print("Shape of the dataframe:", df8.shape)
df8.head()

Shape of the dataframe: (29, 10)

,Scheme Name,Crisil Rank,AuM (Cr),NAV,1D Change(%),NAV Date,52W High,52WH as on,52W Low,52WL as on
0,Aditya Birla Sun Life Income Fund - Direct Pla...,3,1254.23,104.6827,0.03%,12-May-21,104.6827,12-May-21,96.9041,18-May-20
1,JM Income Fund - (Direct) - GrowthMedium to Lo...,-,16.99,54.3884,0.06%,12-May-21,54.6697,05-Jan-21,51.5480,18-May-20
2,Aditya Birla Sun Life Income Fund - Regular Pl...,3,1254.23,98.8208,0.03%,12-May-21,98.8208,12-May-21,91.8805,18-May-20
3,JM Income Fund - GrowthMedium to Long Duration...,1,16.99,50.0348,0.06%,12-May-21,50.4689,05-Jan-21,47.8905,18-May-20
4,LIC MF Bond Fund - Direct Plan - GrowthMedium ...,4,170.77,59.9994,0.05%,12-May-21,60.0723,05-Jan-21,57.3397,18-May-20

## Exctracting Medium to Long Duration  Mutual Fund's SIP Returns Data

Data in this table: Get absolute SIP returns. If 1Y column value is 10%, that means fund has given 10% returns on your SIP investments started 1 year back from latest NAV date.

In [41]:
mld_sip_rtns = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/sip-returns/medium-to-long-duration-fund.html")
df9 = pd.DataFrame(mld_sip_rtns[0])

In [42]:
#Renaming SIP returns column names
df9.rename({'1Y': '1Y_SIP_RTN(%)', '2Y': '2Y_SIP_RTN(%)', '3Y': '3Y_SIP_RTN(%)',
                  '5Y': '5Y_SIP_RTN(%)', '10Y': '10Y_SIP_RTN(%)', 'YTD' : 'YTD_SIP_RTN(%)'
           }, axis=1, inplace=True)

print("Shape of the dataframe:", df9.shape)
df9.head()

Shape of the dataframe: (29, 8)

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,SBI Magnum Income Fund - Direct Plan - GrowthM...,3,1709.60,3.43%,9.94%,16.62%,26.69%,-
1,Aditya Birla Sun Life Income Fund - Direct Pla...,3,1254.23,3.12%,9.16%,15.77%,24.64%,-
2,ICICI Prudential Bond Fund - Direct Plan - Gro...,3,3366.05,2.94%,8.90%,15.21%,24.40%,-
3,Aditya Birla Sun Life Income Fund - Regular Pl...,3,1254.23,2.89%,8.60%,14.73%,22.54%,52.56%
4,Aditya Birla Sun Life Income Fund - Regular Pl...,-,1254.23,2.89%,8.60%,14.74%,22.55%,52.58%

In [43]:
df_final = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9],axis=1,sort=False)
print("Shape of the dataframe:", df_final.shape)

Shape of the dataframe: (29, 103)

In [44]:
# Remove duplicate columns by name in Pandas
df_final = df_final.loc[:,~df_final.columns.duplicated()]

# Removing spaces in the column names
#df_final.columns = df_final.columns.str.replace(' ','_')

print("Shape of the dataframe:", df_final.shape)
df_final.head()

Shape of the dataframe: (29, 84)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,NAV Date,52W High,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,UTI Bond Fund (Segregated - 17022020) - Direct...,-,15.55,0.21%,0.98%,2.84%,-20.27%,1.35%,-16.79%,-,...,12-May-21,104.6827,12-May-21,96.9041,18-May-20,3.43%,9.94%,16.62%,26.69%,-
1,UTI Bond Fund (Segregated - 17022020) - Regula...,-,15.55,0.21%,0.98%,2.84%,-20.44%,1.35%,-16.96%,-,...,12-May-21,54.6697,05-Jan-21,51.5480,18-May-20,3.12%,9.16%,15.77%,24.64%,-
2,Kotak Bond - Direct Plan - GrowthMedium to Lon...,4,1863.79,0.15%,0.71%,0.90%,1.71%,1.00%,6.87%,10.42%,...,12-May-21,98.8208,12-May-21,91.8805,18-May-20,2.94%,8.90%,15.21%,24.40%,-
3,SBI Magnum Income Fund - Direct Plan - GrowthM...,3,1709.60,0.13%,0.64%,1.69%,1.87%,1.06%,8.73%,11.52%,...,12-May-21,50.4689,05-Jan-21,47.8905,18-May-20,2.89%,8.60%,14.73%,22.54%,52.56%
4,Kotak Bond - Regular Plan - GrowthMedium to Lo...,4,1863.79,0.13%,0.62%,0.63%,1.16%,0.87%,5.71%,9.24%,...,12-May-21,60.0723,05-Jan-21,57.3397,18-May-20,2.89%,8.60%,14.74%,22.55%,52.58%

In [45]:
#Exporting the consolidated mld mf data as a  csv file
#print("Shape of the dataframe:", df_final.shape)
#df_final.to_csv('mld_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + ').csv',
#               index=False)

#Exporting the mld mf data columns with its datatype as a  csv file
#df_dtypes.to_csv('mld_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')