In [3]:
import re
import pandas as pd
import numpy as np
%matplotlib inline

In [4]:
# Reading elss mutual funds csv file
elss_mf = pd.read_csv('elss_mf_data(10-May-2021 18:19:46).csv')

In [5]:
# Extracting a plan from "Scheme Name" column
scheme_name = list(elss_mf['Scheme Name'])
plan = []
for i in scheme_name:
    #print(type(i))
    plan.append(re.findall("Direct|Regular", str(i)))
#plan
for p in plan:
    if len(p) == 0:
        #print(type(p))
        p.append("Regular")
elss_mf['Plan'] = plan

In [6]:
# Extracting a category from "Scheme Name" column
scheme_name = list(elss_mf['Scheme Name'])
category = []
for i in scheme_name:
    #print(type(i))
    category.append(re.findall("ELSS", str(i)))
elss_mf['Category'] = category

In [7]:
# Modifiying 'Scheme Name' column
elss_mf['Scheme Name'] = elss_mf['Scheme Name'].str.rstrip(' - GrowthELSS')

In [8]:
#Replacing "']" & "['" string with "" in Plan columns
elss_mf['Plan'] = elss_mf['Plan'].astype(str).str.replace("\['","", regex=True)
elss_mf['Plan'] = elss_mf['Plan'].astype(str).str.replace("']","", regex=True)

#Replacing "']" & "['" string with "" in Category columns
elss_mf['Category'] = elss_mf['Category'].astype(str).str.replace("\['","", regex=True)
elss_mf['Category'] = elss_mf['Category'].astype(str).str.replace("']","", regex=True)

In [9]:
#Replacing "ELSS', 'ELSS" string with "ELSS" in Category columns
elss_mf['Category'] = elss_mf['Category'].astype(str).str.replace("ELSS', 'ELSS","ELSS", regex=True)

#Replacing "%" string with "" in Crisil Rank, % Debt Holding, No of instruments in portfolio,
# % MF Holding, % Other Holding, Turnover ratio, MTD, 10Y_SIP_RTN(%) & 5Y_SIP_RTN(%) columns
elss_mf[['% Debt Holding', 'No of instruments in portfolio',
          '% MF Holding', '% Other Holding', 'Turnover ratio(%)',
          'MTD', '10Y_SIP_RTN(%)', '5Y_SIP_RTN(%)'         
         ]] = elss_mf[['% Debt Holding', 'No of instruments in portfolio',
                        '% MF Holding', '% Other Holding', 'Turnover ratio(%)',
                        'MTD', '10Y_SIP_RTN(%)', '5Y_SIP_RTN(%)'
                        ]].replace("%", "", regex=True)

#Replacing "-" string with "0" in Crisil Rank columns
elss_mf['Crisil Rank'] = elss_mf['Crisil Rank'].replace("-", "", regex=True)

In [10]:
#Replacing "-" string with "0" in Crisil Rank columns
elss_mf['Crisil Rank'] = elss_mf['Crisil Rank'].replace("", "0", regex=True)

#Replacing "%" with '' in the column
elss_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding', '% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)',
         "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20",
         "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19",
         "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)"
         ]] = elss_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)"
                       ]].replace("%", "", regex=True)
print("Shape of the dataframe:", elss_mf.shape)
elss_mf.head()

Shape of the dataframe: (128, 86)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
0,Quant Tax Plan - Direct Plan,5,106.05,6.05,10.05,24.16,55.08,32.23,131.26,43.55,...,03-Mar-21,308.8600,18-May-20,59.12,84.32,92.16,109.87,-,Direct,ELSS
1,Quant Tax Plan,5,106.05,6.00,9.87,23.50,53.42,31.24,126.70,41.01,...,03-Mar-21,424.6445,18-May-20,57.16,80.35,86.86,102.63,218.21,Regular,ELSS
2,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,37.10,4.12,6.74,16.47,50.65,23.93,104.47,15.92,...,03-Mar-21,288.1000,18-May-20,47.25,49.68,41.15,-,-,Direct,ELSS
3,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,37.10,4.11,6.72,16.40,50.42,23.81,103.83,15.56,...,03-Mar-21,397.6326,18-May-20,47.25,48.62,39.60,-,-,Regular,ELSS
4,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,38.37,3.90,7.10,16.99,50.67,24.66,105.11,14.93,...,07-May-21,81.3329,18-May-20,47.01,48.19,38.75,-,-,Direct,ELSS

In [11]:
#Sorting a elss_mf dataframe by "Crisil Rank Column"
elss_mf.sort_values(by=['Crisil Rank', 'Scheme Name', 'AuM (Cr)'], inplace=True, ascending=False)
print("Shape of the dataframe:", elss_mf.shape)
elss_mf.head()

Shape of the dataframe: (128, 86)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
0,Quant Tax Plan - Direct Plan,5,106.05,6.05,10.05,24.16,55.08,32.23,131.26,43.55,...,03-Mar-21,308.8600,18-May-20,59.12,84.32,92.16,109.87,-,Direct,ELSS
1,Quant Tax Plan,5,106.05,6.00,9.87,23.50,53.42,31.24,126.70,41.01,...,03-Mar-21,424.6445,18-May-20,57.16,80.35,86.86,102.63,218.21,Regular,ELSS
31,Mirae Asset Tax Saver Fund - Regular Plan,5,6934.49,1.92,1.46,3.84,27.38,12.70,76.36,22.74,...,03-Mar-21,32.6030,18-May-20,31.43,46.99,53.67,69.82,-,Regular,ELSS
30,Mirae Asset Tax Saver Fund - Direct Plan,5,6934.49,1.94,1.57,4.22,28.35,13.29,79.05,24.68,...,03-Mar-21,34.4720,18-May-20,31.53,46.90,49.89,-,-,Direct,ELSS
65,Canara Robeco Equity Tax Saver - Regular Plan,5,2044.06,1.22,0.82,0.42,24.71,10.16,64.73,22.47,...,03-Mar-21,14.1904,18-May-20,25.60,-,-,-,-,Regular,ELSS

In [12]:
#Replacing "-" with 'None' in the columns
elss_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding', '% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)',
         "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20",
         "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19",
         "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)"
         ]] = elss_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)"]].replace({'-' : None})

In [13]:
#Replacing "" with '0' in the columns

elss_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding','% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)',
         '10Y_SIP_RTN(%)', "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20",
         "Sep'20", "Aug'20", "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20",
         "Q4'19", "Q3'19", "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)",
         "Standard Deviation", "Beta", "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio", 'Crisil Rank'
         ]] = elss_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',\
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)", "Standard Deviation", "Beta",
                       "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio", 'Crisil Rank']].fillna(value='0')

In [14]:
#Changing the datatype of the return & risk ratio columns

elss_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding','% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)',
         '10Y_SIP_RTN(%)', "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20",
         "Sep'20", "Aug'20", "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20",
         "Q4'19", "Q3'19", "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)",
         "Standard Deviation", "Beta", "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio"
         ]] = elss_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)", "Standard Deviation", "Beta",
                       "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio"]].apply(pd.to_numeric)

In [15]:
#Changing the datatype of the 'Crisil Rank' columns
elss_mf['Crisil Rank'] = elss_mf['Crisil Rank'].astype('int')

In [16]:
#Removing white spaces at both ends in all over the dataframe:

elss_mf.columns = elss_mf.columns.str.strip()

#Checking the data type of all columns in the DataFrame
elss_mf_dtype = elss_mf.dtypes

df_dtypes = pd.DataFrame(elss_mf_dtype)

In [17]:
#Using pandas dataframe.round()function to round off all the decimal values to 2 decimal places
elss_mf = elss_mf.round(2)

In [18]:
# #Exporting the consolidated elss mf data as a  csv file
# print("Shape of the dataframe:", elss_mf.shape)
#elss_mf.to_csv('final_elss_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)',
#                 index=False)

# #Exporting the elss mf data columns with its datatype as a  csv file
# df_dtypes.to_csv('elss_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')

In [19]:
#Exctracting regular mutual funds
regular_mf = elss_mf.loc[elss_mf['Plan'] == 'Regular']
regular_mf.head()

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
1,Quant Tax Plan,5,106.05,6.00,9.87,23.50,53.42,31.24,126.70,41.01,...,03-Mar-21,424.64,18-May-20,57.16,80.35,86.86,102.63,218.21,Regular,ELSS
31,Mirae Asset Tax Saver Fund - Regular Plan,5,6934.49,1.92,1.46,3.84,27.38,12.70,76.36,22.74,...,03-Mar-21,32.60,18-May-20,31.43,46.99,53.67,69.82,0.00,Regular,ELSS
65,Canara Robeco Equity Tax Saver - Regular Plan,5,2044.06,1.22,0.82,0.42,24.71,10.16,64.73,22.47,...,03-Mar-21,14.19,18-May-20,25.60,0.00,0.00,0.00,0.00,Regular,ELSS
108,BOI AXA Tax Advantage Fund - Regular Plan,5,417.39,0.64,2.71,8.19,27.18,13.05,69.21,29.51,...,15-Feb-21,6.77,18-May-20,20.41,28.35,34.33,45.47,0.00,Regular,ELSS
91,Union Long Term Equity Fund,4,335.59,0.96,0.00,1.24,22.62,7.60,61.27,18.37,...,07-May-21,5.56,19-May-20,23.15,31.65,35.41,43.55,0.00,Regular,ELSS

In [20]:
# Basic statistics of regular mutual fund df
regular_mf.describe()

,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),...,% Other Holding,NAV,1D Change(%),52W High,52W Low,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
count,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000,...,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000
mean,1.723077,1972.964154,1.493538,1.513231,4.163846,27.706462,11.335538,68.686000,16.553846,8.058462,...,0.027077,77.847538,0.247231,79.544308,44.776000,27.762769,33.232000,31.593692,32.523077,28.469538
std,1.736625,4405.958195,1.103339,2.220913,5.434483,9.041373,5.873693,16.619267,7.407031,5.828225,...,0.202567,146.999840,0.360345,150.614196,83.919819,8.509979,12.142924,16.522172,25.699389,52.925595
min,0.000000,12.610000,-0.230000,-1.820000,-2.400000,12.560000,2.020000,40.710000,0.000000,-1.000000,...,0.000000,10.570000,-0.990000,10.750000,5.020000,13.880000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,62.270000,0.890000,0.030000,0.420000,21.910000,7.890000,58.600000,12.720000,4.650000,...,0.000000,13.840000,0.060000,14.240000,8.190000,22.130000,25.960000,25.610000,0.000000,0.000000
50%,2.000000,289.850000,1.240000,0.970000,2.380000,25.370000,9.640000,64.800000,14.800000,7.650000,...,0.000000,24.210000,0.260000,24.780000,14.130000,25.600000,31.390000,31.730000,36.830000,0.000000
75%,3.000000,1836.790000,1.850000,2.160000,7.390000,31.060000,14.490000,76.360000,18.860000,11.040000,...,0.000000,67.960000,0.410000,67.960000,39.330000,30.970000,42.170000,38.610000,45.470000,0.000000
max,5.000000,27870.000000,6.000000,9.870000,23.500000,53.420000,31.240000,126.700000,41.010000,25.650000,...,1.630000,768.570000,1.410000,787.420000,424.640000,57.160000,80.350000,86.860000,102.630000,218.210000

In [21]:
# Extracting funds which have 3Y Return', '5Y Return' & '10Y Return' greater than 10%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10) &
                            (regular_mf['10Y_RTN(%)'] > 10)]
print("No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is:", len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV']]

No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is: 11 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV
1,Quant Tax Plan,5,106.05,126.70,25.65,23.24,14.90,768.57
65,Canara Robeco Equity Tax Saver - Regular Plan,5,2044.06,64.73,16.50,17.18,14.11,25.44
108,BOI AXA Tax Advantage Fund - Regular Plan,5,417.39,69.21,12.22,18.33,14.22,10.97
46,UTI Long Term Equity Fund (Tax Saving),4,1800.13,65.16,11.06,13.98,11.84,25.37
98,Kotak Tax Saver Scheme,4,1836.79,63.83,13.19,15.61,12.72,17.24
105,JM Tax Gain Fund,4,52.53,71.77,11.73,16.50,13.37,49.02
19,DSP Tax Saver Fund - Regular Plan,4,8056.26,69.89,13.37,16.42,15.06,78.88
121,Invesco India Tax Plan,3,1512.41,56.46,10.54,14.85,14.64,66.53
43,ICICI Prudential Long Term Equity Fund (Tax Sa...,3,8310.40,63.98,10.87,13.10,13.33,38.03
69,BNP Paribas Long Term Equity Fund,3,495.33,52.50,11.04,12.40,14.13,13.84
93,Axis Long Term Equity Fund,3,27870.00,55.07,12.65,15.89,17.63,13.39

In [53]:
# Extracting  last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'
#greater than 10%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10) &
                            (regular_mf['10Y_RTN(%)'] > 10)]
print("Last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'greater than 10% is:",
      len(mf_rtn_com.index), '\nFunds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

Last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'greater than 10% is: 11
Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
1,Quant Tax Plan,5,106.05,768.57,13.94,5.80,0.00,0.00,0.00
65,Canara Robeco Equity Tax Saver - Regular Plan,5,2044.06,25.44,11.54,9.77,-6.27,0.00,0.00
108,BOI AXA Tax Advantage Fund - Regular Plan,5,417.39,10.97,18.42,-12.81,-29.13,44.78,1.49
46,UTI Long Term Equity Fund (Tax Saving),4,1800.13,25.37,20.41,10.83,1.06,37.98,4.91
98,Kotak Tax Saver Scheme,4,1836.79,17.24,20.21,15.34,3.27,37.44,-1.23
105,JM Tax Gain Fund,4,52.53,49.02,9.61,6.21,-10.19,38.44,6.26
19,DSP Tax Saver Fund - Regular Plan,4,8056.26,78.88,15.98,6.81,-7.66,27.84,1.27
121,Invesco India Tax Plan,3,1512.41,66.53,17.34,5.11,-13.33,37.19,2.92
43,ICICI Prudential Long Term Equity Fund (Tax Sa...,3,8310.40,38.03,-1.08,-0.65,-20.38,46.04,3.68
69,BNP Paribas Long Term Equity Fund,3,495.33,13.84,17.92,14.38,0.00,0.00,0.00
93,Axis Long Term Equity Fund,3,27870.00,13.39,11.85,-0.68,-14.43,26.47,0.00

In [23]:
# Extracting funds which have '3Y Return' & '5Y Return' greater than 12%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 12) & (regular_mf['5Y_RTN(%)'] > 12)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 12% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return' & '5Y Return' greater than 12% is: 12 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
1,Quant Tax Plan,5,106.05,126.70,25.65,23.24,14.90,768.57,0.29,530.00,19.62,0.87
31,Mirae Asset Tax Saver Fund - Regular Plan,5,6934.49,76.36,16.08,21.29,0.00,51.43,0.26,35.00,19.87,0.94
65,Canara Robeco Equity Tax Saver - Regular Plan,5,2044.06,64.73,16.50,17.18,14.11,25.44,0.00,78.00,0.00,0.00
108,BOI AXA Tax Advantage Fund - Regular Plan,5,417.39,69.21,12.22,18.33,14.22,10.97,0.00,0.00,0.00,0.00
98,Kotak Tax Saver Scheme,4,1836.79,63.83,13.19,15.61,12.72,17.24,0.00,266.00,0.00,0.00
19,DSP Tax Saver Fund - Regular Plan,4,8056.26,69.89,13.37,16.42,15.06,78.88,0.60,0.00,19.72,0.92
93,Axis Long Term Equity Fund,3,27870.00,55.07,12.65,15.89,17.63,13.39,0.00,104.00,0.00,0.00
73,SBI Tax Advantage Fund - Series III - Regular ...,0,25.52,83.16,24.15,23.58,0.00,45.35,0.00,54.00,0.00,0.00
54,SBI Tax Advantage Fund - Series II - Regular Plan,0,35.47,84.97,22.48,23.56,0.00,13.11,0.00,130.00,0.00,0.00
127,SBI Long Term Advantage Fund - Series III - Re...,0,54.36,83.25,14.55,15.04,0.00,91.65,0.00,1019.00,0.00,0.00
125,SBI Long Term Advantage Fund - Series II - Reg...,0,29.02,83.36,13.45,16.45,0.00,14.17,0.00,39.00,0.00,0.00
123,SBI Long Term Advantage Fund - Series I - Regu...,0,34.42,86.24,12.14,15.21,0.00,17.26,0.00,6.03,0.00,0.00

In [52]:
# Extracting last five years annual return for funds which have 3Y Return', '5Y Return' greater than 12%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 12) & (regular_mf['5Y_RTN(%)'] > 12)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 12% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

No. of funds having '3Y Return' & '5Y Return' greater than 12% is: 12 Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
1,Quant Tax Plan,5,106.05,768.57,13.94,5.80,0.00,0.00,0.00
31,Mirae Asset Tax Saver Fund - Regular Plan,5,6934.49,51.43,38.00,21.15,-8.32,45.83,4.94
65,Canara Robeco Equity Tax Saver - Regular Plan,5,2044.06,25.44,11.54,9.77,-6.27,0.00,0.00
108,BOI AXA Tax Advantage Fund - Regular Plan,5,417.39,10.97,18.42,-12.81,-29.13,44.78,1.49
98,Kotak Tax Saver Scheme,4,1836.79,17.24,20.21,15.34,3.27,37.44,-1.23
19,DSP Tax Saver Fund - Regular Plan,4,8056.26,78.88,15.98,6.81,-7.66,27.84,1.27
93,Axis Long Term Equity Fund,3,27870.00,13.39,11.85,-0.68,-14.43,26.47,0.00
73,SBI Tax Advantage Fund - Series III - Regular ...,0,25.52,45.35,15.61,11.44,-7.40,39.19,-1.17
54,SBI Tax Advantage Fund - Series II - Regular Plan,0,35.47,13.11,18.86,16.01,-8.12,43.81,-6.44
127,SBI Long Term Advantage Fund - Series III - Re...,0,54.36,91.65,12.16,9.35,-4.01,32.73,5.98
125,SBI Long Term Advantage Fund - Series II - Reg...,0,29.02,14.17,47.13,2.95,-3.88,36.23,12.90
123,SBI Long Term Advantage Fund - Series I - Regu...,0,34.42,17.26,10.23,9.99,-3.46,36.62,8.72

In [25]:
# Extracting funds which have '3Y Return' & '5Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 15) & (regular_mf['5Y_RTN(%)'] > 15)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
            'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return' & '5Y Return' greater than 15% is: 5 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
1,Quant Tax Plan,5,106.05,126.70,25.65,23.24,14.90,768.57,0.29,530.0,19.62,0.87
31,Mirae Asset Tax Saver Fund - Regular Plan,5,6934.49,76.36,16.08,21.29,0.00,51.43,0.26,35.0,19.87,0.94
65,Canara Robeco Equity Tax Saver - Regular Plan,5,2044.06,64.73,16.50,17.18,14.11,25.44,0.00,78.0,0.00,0.00
73,SBI Tax Advantage Fund - Series III - Regular ...,0,25.52,83.16,24.15,23.58,0.00,45.35,0.00,54.0,0.00,0.00
54,SBI Tax Advantage Fund - Series II - Regular Plan,0,35.47,84.97,22.48,23.56,0.00,13.11,0.00,130.0,0.00,0.00

In [26]:
# Extracting last five years annual return for funds which have 3Y Return', '5Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 15) & (regular_mf['5Y_RTN(%)'] > 15)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

No. of funds having '3Y Return' & '5Y Return' greater than 15% is: 5 Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
1,Quant Tax Plan,5,106.05,768.57,13.94,5.80,0.00,0.00,0.00
31,Mirae Asset Tax Saver Fund - Regular Plan,5,6934.49,51.43,38.00,21.15,-8.32,45.83,4.94
65,Canara Robeco Equity Tax Saver - Regular Plan,5,2044.06,25.44,11.54,9.77,-6.27,0.00,0.00
73,SBI Tax Advantage Fund - Series III - Regular ...,0,25.52,45.35,15.61,11.44,-7.40,39.19,-1.17
54,SBI Tax Advantage Fund - Series II - Regular Plan,0,35.47,13.11,18.86,16.01,-8.12,43.81,-6.44

In [27]:
# Extracting funds which have '5Y Return' & '10Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 15) & (regular_mf['10Y_RTN(%)'] > 15)]
print("No. of funds having '5Y Return' & '10Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
            'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '5Y Return' & '10Y Return' greater than 15% is: 3 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
38,IDFC Tax Advantage (ELSS) Fund - Regular Plan,4,2988.35,89.66,9.74,16.27,15.09,65.26,0.11,11.0,23.63,1.02
19,DSP Tax Saver Fund - Regular Plan,4,8056.26,69.89,13.37,16.42,15.06,78.88,0.60,0.0,19.72,0.92
93,Axis Long Term Equity Fund,3,27870.00,55.07,12.65,15.89,17.63,13.39,0.00,104.0,0.00,0.00

In [28]:
# Extracting last five years annual return for funds which have 5Y Return', '10Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 15) & (regular_mf['10Y_RTN(%)'] > 15)]
print("No. of funds having '5Y Return' & '10Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

No. of funds having '5Y Return' & '10Y Return' greater than 15% is: 3 Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
38,IDFC Tax Advantage (ELSS) Fund - Regular Plan,4,2988.35,65.26,32.40,15.15,-8.60,38.15,0.00
19,DSP Tax Saver Fund - Regular Plan,4,8056.26,78.88,15.98,6.81,-7.66,27.84,1.27
93,Axis Long Term Equity Fund,3,27870.00,13.39,11.85,-0.68,-14.43,26.47,0.00

## Portfolio Turnover Ratio(PTR)

Portfolio Turnover Ratio is the frequency in which the assets held under a fund has changed over the years. In simpler words, PTR provides a measurement on how many times the fund managers bought or sold the assets under a fund over a period of time. PTR is often determined by the market conditions and fund management style.

Suppose an equity fund purchased stocks worth Rs. 375 crore and sold stocks worth Rs. 450 crore. The average AUM of the fund is Rs.1500 crore. In this case, the Portfolio turnover ratio of the fund is 25%, which means one-fourth of the stocks were traded.

Funds that have higher turnover ratios, for example, can trigger higher costs for investors. First, a fund thatâ€™s actively managed may charge a higher expense ratio to cover the fund managerâ€™s services. The expense ratio represents the percentage you pay to own the fund on an annualized basis. At the low end, you can find index funds with expense ratios around 0.50% to 0.10%. But the most expensive funds can easily have expense ratios over 1%.

Turnover ratio can also give you an idea of what the fundâ€™s investment strategy is, which is important for choosing funds that align with your goals and objectives. A growth mutual fund, for instance, may have a higher turnover ratio if the fund manager is constantly looking for the best growth stocks to drive returns. But a fund that uses a value investing approach may have a lower turnover ratio if the fund manager is buying assets that have the potential to appreciate over time.

In [29]:
# Top 10 low turnover ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Turnover ratio(%)'] > 0)]
print("Top 10 low turnover ratio regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Turnover ratio(%)']].nsmallest(10, 'Turnover ratio(%)')

Top 10 low turnover ratio regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Turnover ratio(%)
123,SBI Long Term Advantage Fund - Series I - Regu...,0,34.42,86.24,12.14,15.21,0.00,17.26,6.03
38,IDFC Tax Advantage (ELSS) Fund - Regular Plan,4,2988.35,89.66,9.74,16.27,15.09,65.26,11.00
62,HDFC Tax Saver Fund,1,7920.48,54.65,4.59,10.87,9.93,19.87,11.17
61,ITI Long Term Equity Fund,0,75.51,64.22,0.00,0.00,0.00,35.17,11.17
9,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,73.18,95.52,-1.00,0.00,0.00,260.04,12.00
111,ICICI Prudential Long Term Wealth Enhancement ...,0,48.06,64.85,6.80,0.00,0.00,11.37,13.31
75,SBI Long Term Advantage Fund - Series V - Regu...,0,393.50,58.80,9.83,0.00,0.00,11.45,17.00
13,Sundaram Long Term Tax Advantage Fund - Series...,0,51.73,99.88,2.94,0.00,0.00,186.22,21.00
79,Edelweiss Long Term Equity Fund (Tax Savings),3,164.60,57.40,7.65,11.87,12.12,10.75,23.67
85,Tata India Tax Savings Fund - Regular Plan,2,2637.17,57.78,9.39,14.32,0.00,21.48,31.00

In [55]:
# Top 10 high turnover ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Turnover ratio(%)'] > 0)]
print("Top 10 high turnover ratio regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Turnover ratio(%)']].nlargest(10, 'Turnover ratio(%)')

Top 10 high turnover ratio regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Turnover ratio(%)
127,SBI Long Term Advantage Fund - Series III - Re...,0,54.36,83.25,14.55,15.04,0.00,91.65,1019.0
1,Quant Tax Plan,5,106.05,126.70,25.65,23.24,14.90,768.57,530.0
98,Kotak Tax Saver Scheme,4,1836.79,63.83,13.19,15.61,12.72,17.24,266.0
97,Baroda ELSS - 96 - Plan A,3,186.68,64.47,6.96,11.36,0.00,18.86,266.0
53,Principal Tax Saving Fund,3,503.43,63.56,6.88,14.71,13.87,26.06,130.0
54,SBI Tax Advantage Fund - Series II - Regular Plan,0,35.47,84.97,22.48,23.56,0.00,13.11,130.0
101,Motilal Oswal Long Term Equity Fund,1,2048.02,59.42,7.25,14.97,0.00,11.01,124.0
93,Axis Long Term Equity Fund,3,27870.00,55.07,12.65,15.89,17.63,13.39,104.0
29,Franklin India Taxshield Fund,3,4375.42,72.04,8.43,11.44,13.19,95.89,98.0
51,Principal Personal Tax Save,3,289.85,64.43,6.97,11.57,10.28,32.13,97.0

## Standard Deviation (SD)

The standard deviation of a stock or a mutual fund represents the riskiness of the stock or the mutual fund.

Standard Deviation is a percentage, expressed as an annualised figure.

Higher the standard Deviation, higher is the volatility of the asset. Higher the volatility, higher is the risk.

Do note, volatility or Standard Deviation should not worry you. Markets are volatile, and equities are volatile, mutual funds are volatile; this is the very nature of markets. So if you canâ€™t fathom watching your investment see-saw between gains and loss, then perhaps you should reconsider your investment decision inequities.

In [31]:
# Top 10 low standard deviation regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Standard Deviation'] > 0)]
print("Top 10 low standard deviation regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Standard Deviation']].nsmallest(10, 'Standard Deviation')

Top 10 low standard deviation regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Standard Deviation
25,Nippon India Tax Saver Fund,1,11219.23,68.79,2.30,8.25,11.72,67.96,18.08
13,Sundaram Long Term Tax Advantage Fund - Series...,0,51.73,99.88,2.94,0.00,0.00,186.22,18.31
17,SBI Long Term Advantage Fund - Series IV - Reg...,0,156.65,88.63,17.57,0.00,0.00,86.34,18.37
28,PGIM India Long Term Equity Fund,3,352.90,66.49,10.72,14.55,0.00,57.73,18.45
33,SBI Long Term Equity Fund - Regular Plan,3,9257.60,62.59,9.47,11.82,12.15,122.09,18.63
34,Sundaram Long Term Tax Advantage Fund - Series...,0,17.30,66.80,9.52,14.14,0.00,20.77,18.73
29,Franklin India Taxshield Fund,3,4375.42,72.04,8.43,11.44,13.19,95.89,19.02
15,Parag Parikh Tax Saver Fund - Regular Plan,0,179.45,70.49,0.00,0.00,0.00,98.11,19.09
7,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,35.61,99.54,-0.69,0.00,0.00,591.42,19.25
1,Quant Tax Plan,5,106.05,126.70,25.65,23.24,14.90,768.57,19.62

In [54]:
# Top 10 high standard deviation regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Standard Deviation'] > 0)]
print("Top 10 high standard deviation regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Standard Deviation']].nlargest(10, 'Standard Deviation')

Top 10 high standard deviation regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Standard Deviation
38,IDFC Tax Advantage (ELSS) Fund - Regular Plan,4,2988.35,89.66,9.74,16.27,15.09,65.26,23.63
20,Quantum Tax Saving Fund,4,89.11,67.92,8.31,0.00,0.00,128.81,23.15
39,Taurus Taxshield,3,74.85,50.59,7.92,14.22,10.95,46.49,22.28
24,SBI Long Term Advantage Fund - Series VI - Reg...,0,306.41,69.62,0.00,0.00,0.00,67.15,21.08
5,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,38.37,104.56,-0.82,0.00,0.00,181.23,21.03
47,IDBI Equity Advantage Fund,1,506.42,43.82,5.37,10.45,0.00,18.13,20.94
46,UTI Long Term Equity Fund (Tax Saving),4,1800.13,65.16,11.06,13.98,11.84,25.37,20.92
9,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,73.18,95.52,-1.00,0.00,0.00,260.04,20.73
53,Principal Tax Saving Fund,3,503.43,63.56,6.88,14.71,13.87,26.06,20.53
11,Sundaram Long Term Tax Advantage Fund - Series IV,0,34.90,88.78,0.00,0.00,0.00,248.92,20.48

## Beta Ratios

A Beta Ratio in Mutual Funds offers investors the data on the degree of the volatility a Mutual Fund displays in response to market fluctuations. An investor can determine which fund would be best suited to meet his/her financial objectives.

Suppose, the beta ratio of a specific Mutual Fund is 0.7 or 70%; it means the fund is 0.3 or 30% less volatile than the benchmark index. A Beta ratio value of 1 indicates a lower risk and lower growth potential compared to ratios at par or above 1.

Investors with a low-risk appetite would always prefer a lower beta ratio in Mutual Funds as it indicates a steadier response to a volatile market condition. Similarly, investors with the investment objective of higher returns would prefer beta ratios of 1 or more than 1.

In [33]:
# Top 10 low beta regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 0)]
print("Top 10 low beta regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']].nsmallest(10, 'Beta')

Top 10 low beta regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
25,Nippon India Tax Saver Fund,1,11219.23,68.79,2.30,8.25,11.72,67.96,0.77
13,Sundaram Long Term Tax Advantage Fund - Series...,0,51.73,99.88,2.94,0.00,0.00,186.22,0.79
17,SBI Long Term Advantage Fund - Series IV - Reg...,0,156.65,88.63,17.57,0.00,0.00,86.34,0.79
33,SBI Long Term Equity Fund - Regular Plan,3,9257.60,62.59,9.47,11.82,12.15,122.09,0.80
49,Sundaram Long Term Tax Advantage Fund - Series...,0,12.61,64.80,9.77,14.14,0.00,23.28,0.80
34,Sundaram Long Term Tax Advantage Fund - Series...,0,17.30,66.80,9.52,14.14,0.00,20.77,0.80
46,UTI Long Term Equity Fund (Tax Saving),4,1800.13,65.16,11.06,13.98,11.84,25.37,0.83
47,IDBI Equity Advantage Fund,1,506.42,43.82,5.37,10.45,0.00,18.13,0.83
15,Parag Parikh Tax Saver Fund - Regular Plan,0,179.45,70.49,0.00,0.00,0.00,98.11,0.83
28,PGIM India Long Term Equity Fund,3,352.90,66.49,10.72,14.55,0.00,57.73,0.85

In [34]:
# Top 10 high beta regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 0)]
print("Top 10 high beta regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']].nlargest(10, 'Beta')

Top 10 high beta regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
38,IDFC Tax Advantage (ELSS) Fund - Regular Plan,4,2988.35,89.66,9.74,16.27,15.09,65.26,1.02
20,Quantum Tax Saving Fund,4,89.11,67.92,8.31,0.00,0.00,128.81,1.00
24,SBI Long Term Advantage Fund - Series VI - Reg...,0,306.41,69.62,0.00,0.00,0.00,67.15,0.97
39,Taurus Taxshield,3,74.85,50.59,7.92,14.22,10.95,46.49,0.96
5,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,38.37,104.56,-0.82,0.00,0.00,181.23,0.96
9,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,73.18,95.52,-1.00,0.00,0.00,260.04,0.96
31,Mirae Asset Tax Saver Fund - Regular Plan,5,6934.49,76.36,16.08,21.29,0.00,51.43,0.94
53,Principal Tax Saving Fund,3,503.43,63.56,6.88,14.71,13.87,26.06,0.94
43,ICICI Prudential Long Term Equity Fund (Tax Sa...,3,8310.40,63.98,10.87,13.10,13.33,38.03,0.94
11,Sundaram Long Term Tax Advantage Fund - Series IV,0,34.90,88.78,0.00,0.00,0.00,248.92,0.93

In [35]:
# Funds with 'Beta' lesser than 1.00
mf_tr = regular_mf.loc[(regular_mf['Beta'] < 1.00) & (regular_mf['Beta'] != 0.00)]
print("Funds with 'Beta' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']]

Funds with 'Beta' lesser than 1.00 are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
1,Quant Tax Plan,5,106.05,126.70,25.65,23.24,14.90,768.57,0.87
31,Mirae Asset Tax Saver Fund - Regular Plan,5,6934.49,76.36,16.08,21.29,0.00,51.43,0.94
46,UTI Long Term Equity Fund (Tax Saving),4,1800.13,65.16,11.06,13.98,11.84,25.37,0.83
19,DSP Tax Saver Fund - Regular Plan,4,8056.26,69.89,13.37,16.42,15.06,78.88,0.92
39,Taurus Taxshield,3,74.85,50.59,7.92,14.22,10.95,46.49,0.96
33,SBI Long Term Equity Fund - Regular Plan,3,9257.60,62.59,9.47,11.82,12.15,122.09,0.80
53,Principal Tax Saving Fund,3,503.43,63.56,6.88,14.71,13.87,26.06,0.94
51,Principal Personal Tax Save,3,289.85,64.43,6.97,11.57,10.28,32.13,0.86
28,PGIM India Long Term Equity Fund,3,352.90,66.49,10.72,14.55,0.00,57.73,0.85
43,ICICI Prudential Long Term Equity Fund (Tax Sa...,3,8310.40,63.98,10.87,13.10,13.33,38.03,0.94
29,Franklin India Taxshield Fund,3,4375.42,72.04,8.43,11.44,13.19,95.89,0.87
25,Nippon India Tax Saver Fund,1,11219.23,68.79,2.30,8.25,11.72,67.96,0.77
47,IDBI Equity Advantage Fund,1,506.42,43.82,5.37,10.45,0.00,18.13,0.83
41,UTI Long Term Advantage Fund - Series IV,0,113.98,76.48,4.27,0.00,0.00,41.07,0.88
11,Sundaram Long Term Tax Advantage Fund - Series IV,0,34.90,88.78,0.00,0.00,0.00,248.92,0.93
13,Sundaram Long Term Tax Advantage Fund - Series...,0,51.73,99.88,2.94,0.00,0.00,186.22,0.79
49,Sundaram Long Term Tax Advantage Fund - Series...,0,12.61,64.80,9.77,14.14,0.00,23.28,0.80
34,Sundaram Long Term Tax Advantage Fund - Series...,0,17.30,66.80,9.52,14.14,0.00,20.77,0.80
5,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,38.37,104.56,-0.82,0.00,0.00,181.23,0.96
3,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,37.10,103.83,0.38,0.00,0.00,713.45,0.92
7,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,35.61,99.54,-0.69,0.00,0.00,591.42,0.90
9,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,73.18,95.52,-1.00,0.00,0.00,260.04,0.96
24,SBI Long Term Advantage Fund - Series VI - Reg...,0,306.41,69.62,0.00,0.00,0.00,67.15,0.97
17,SBI Long Term Advantage Fund - Series IV - Reg...,0,156.65,88.63,17.57,0.00,0.00,86.34,0.79
15,Parag Parikh Tax Saver Fund - Regular Plan,0,179.45,70.49,0.00,0.00,0.00,98.11,0.83

In [36]:
# Funds with 'Beta' greater than 1.00
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 1.00) & (regular_mf['Beta'] != 0.00)]
print("Funds with 'Beta' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']]

Funds with 'Beta' lesser than 1.00 are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
38,IDFC Tax Advantage (ELSS) Fund - Regular Plan,4,2988.35,89.66,9.74,16.27,15.09,65.26,1.02

## What is Sharpe Ratio?

Sharpe Ratio of a mutual fund reveals its potential risk-adjusted returns. The risk-adjusted returns are the returns earned by an investment over the returns generated by any risk-free asset such as a fixed deposit. However, higher returns indicate extra risk. Higher Sharpe Ratio means greater returns from an investment but with a higher risk level. Therefore, it justifies the underlying volatility of the funds. The investors aiming for higher returns will have to invest in funds with higher risk factors.

Investments with less than 1.00 Sharpe Ratio do not generate high returns. Contrarily, investment with Sharpe Ratio of 1.00 to 3.00 or above have higher returns subsequently.

In [37]:
# Top 10 low sharpe ratio regular mutual funds are
#mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 0)]
print("Top 10 low 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']].nsmallest(10, 'Sharpe Ratio')

Top 10 low 'Sharpe Ratio' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
38,IDFC Tax Advantage (ELSS) Fund - Regular Plan,4,2988.35,89.66,9.74,16.27,15.09,65.26,0.11

In [38]:
# Top 10 high sharpe ratio regular mutual funds are
#mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 0)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']].nlargest(10, 'Sharpe Ratio')

Top 10 high 'Sharpe Ratio' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
38,IDFC Tax Advantage (ELSS) Fund - Regular Plan,4,2988.35,89.66,9.74,16.27,15.09,65.26,0.11

In [39]:
# Funds with 'Sharpe Ratio' greater than or equal to 3.00
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] >= 3.00)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [40]:
# Funds with 'Sharpe Ratio' greater than to 2.00 & lesser than 2.99
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 2.00) & (regular_mf['Sharpe Ratio'] < 2.99)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [41]:
# Funds with 'Sharpe Ratio' greater than to 1.00 & lesser than 1.99
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 1.00) & (regular_mf['Sharpe Ratio'] < 1.99)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [42]:
# Funds with 'Sharpe Ratio' lesser than 1.00
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] != 0.00) & (regular_mf['Sharpe Ratio'] < 1.00)]
print("Funds with 'Sharpe Ratio' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Funds with 'Sharpe Ratio' lesser than 1.00 are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
1,Quant Tax Plan,5,106.05,126.70,25.65,23.24,14.90,768.57,0.29
31,Mirae Asset Tax Saver Fund - Regular Plan,5,6934.49,76.36,16.08,21.29,0.00,51.43,0.26
46,UTI Long Term Equity Fund (Tax Saving),4,1800.13,65.16,11.06,13.98,11.84,25.37,-0.18
20,Quantum Tax Saving Fund,4,89.11,67.92,8.31,0.00,0.00,128.81,0.01
38,IDFC Tax Advantage (ELSS) Fund - Regular Plan,4,2988.35,89.66,9.74,16.27,15.09,65.26,0.11
19,DSP Tax Saver Fund - Regular Plan,4,8056.26,69.89,13.37,16.42,15.06,78.88,0.60
39,Taurus Taxshield,3,74.85,50.59,7.92,14.22,10.95,46.49,0.17
33,SBI Long Term Equity Fund - Regular Plan,3,9257.60,62.59,9.47,11.82,12.15,122.09,0.98
53,Principal Tax Saving Fund,3,503.43,63.56,6.88,14.71,13.87,26.06,0.32
51,Principal Personal Tax Save,3,289.85,64.43,6.97,11.57,10.28,32.13,0.25
28,PGIM India Long Term Equity Fund,3,352.90,66.49,10.72,14.55,0.00,57.73,0.11
43,ICICI Prudential Long Term Equity Fund (Tax Sa...,3,8310.40,63.98,10.87,13.10,13.33,38.03,0.13
29,Franklin India Taxshield Fund,3,4375.42,72.04,8.43,11.44,13.19,95.89,0.19
25,Nippon India Tax Saver Fund,1,11219.23,68.79,2.30,8.25,11.72,67.96,0.11
47,IDBI Equity Advantage Fund,1,506.42,43.82,5.37,10.45,0.00,18.13,-0.13
41,UTI Long Term Advantage Fund - Series IV,0,113.98,76.48,4.27,0.00,0.00,41.07,0.50
11,Sundaram Long Term Tax Advantage Fund - Series IV,0,34.90,88.78,0.00,0.00,0.00,248.92,0.35
13,Sundaram Long Term Tax Advantage Fund - Series...,0,51.73,99.88,2.94,0.00,0.00,186.22,0.97
49,Sundaram Long Term Tax Advantage Fund - Series...,0,12.61,64.80,9.77,14.14,0.00,23.28,0.01
34,Sundaram Long Term Tax Advantage Fund - Series...,0,17.30,66.80,9.52,14.14,0.00,20.77,0.26
5,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,38.37,104.56,-0.82,0.00,0.00,181.23,0.22
3,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,37.10,103.83,0.38,0.00,0.00,713.45,0.40
7,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,35.61,99.54,-0.69,0.00,0.00,591.42,0.53
9,Sundaram Long Term Micro Cap Tax Advantage Fun...,0,73.18,95.52,-1.00,0.00,0.00,260.04,0.13
24,SBI Long Term Advantage Fund - Series VI - Reg...,0,306.41,69.62,0.00,0.00,0.00,67.15,0.20
17,SBI Long Term Advantage Fund - Series IV - Reg...,0,156.65,88.63,17.57,0.00,0.00,86.34,0.72
15,Parag Parikh Tax Saver Fund - Regular Plan,0,179.45,70.49,0.00,0.00,0.00,98.11,0.55

In [43]:
# Extracting funds which have 3Y Return', '5Y Return' & '10Y Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_SIP_RTN(%)'] > 25) & (regular_mf['5Y_SIP_RTN(%)'] > 25) &
                            (regular_mf['10Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '3Y SIP Return', '5Y SIP Return' & '10Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y SIP Return', '5Y SIP Return' & '10Y SIP Return' greater than 25% is: 13 Funds

,Scheme Name,Crisil Rank,AuM (Cr),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
1,Quant Tax Plan,5,106.05,86.86,102.63,218.21,768.57,0.29,530.00,19.62,0.87
98,Kotak Tax Saver Scheme,4,1836.79,33.84,50.34,153.55,17.24,0.00,266.00,0.00,0.00
97,Baroda ELSS - 96 - Plan A,3,186.68,28.22,34.85,91.55,18.86,0.00,266.00,0.00,0.00
99,HSBC Tax Saver Equity Fund,2,169.44,26.62,34.39,87.38,24.21,0.00,33.53,0.00,0.00
117,Aditya Birla Sun Life Tax Relief 96 - Regular ...,2,13647.28,25.26,36.83,91.66,22.52,0.00,0.00,0.00,0.00
47,IDBI Equity Advantage Fund,1,506.42,30.71,36.00,93.40,18.13,-0.13,44.00,20.94,0.83
64,UTI Master Equity Plan Unit Scheme,0,2084.98,36.55,45.35,102.58,19.44,0.00,37.00,0.00,0.00
41,UTI Long Term Advantage Fund - Series IV,0,113.98,40.95,51.49,140.24,41.07,0.50,0.00,19.91,0.88
84,UTI Long Term Advantage Fund - Series III,0,247.95,30.17,38.41,115.60,21.20,0.00,58.00,0.00,0.00
77,Shriram Long Term Equity Fund,0,36.56,32.39,37.79,95.10,13.34,0.00,94.00,0.00,0.00
17,SBI Long Term Advantage Fund - Series IV - Reg...,0,156.65,44.73,54.14,136.90,86.34,0.72,50.00,18.37,0.79
59,BOI AXA Midcap Tax Fund - Series 2 - Regular Plan,0,71.99,43.45,60.14,129.75,12.74,0.00,67.00,0.00,0.00
70,BOI AXA Midcap Tax Fund - Series 1,0,85.66,31.91,41.23,110.08,13.54,0.00,0.00,0.00,0.00

In [44]:
# Extracting funds which have 3Y Return' & '5Y Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_SIP_RTN(%)'] > 25) & (regular_mf['5Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '3Y SIP Return' & '5Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y SIP Return' & '5Y SIP Return' greater than 25% is: 40 Funds

,Scheme Name,Crisil Rank,AuM (Cr),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
1,Quant Tax Plan,5,106.05,86.86,102.63,218.21,768.57,0.29,530.00,19.62,0.87
31,Mirae Asset Tax Saver Fund - Regular Plan,5,6934.49,53.67,69.82,0.00,51.43,0.26,35.00,19.87,0.94
108,BOI AXA Tax Advantage Fund - Regular Plan,5,417.39,34.33,45.47,0.00,10.97,0.00,0.00,0.00,0.00
91,Union Long Term Equity Fund,4,335.59,35.41,43.55,0.00,11.52,0.00,43.24,0.00,0.00
20,Quantum Tax Saving Fund,4,89.11,64.56,83.98,0.00,128.81,0.01,0.00,23.15,1.00
98,Kotak Tax Saver Scheme,4,1836.79,33.84,50.34,153.55,17.24,0.00,266.00,0.00,0.00
19,DSP Tax Saver Fund - Regular Plan,4,8056.26,69.49,92.68,0.00,78.88,0.60,0.00,19.72,0.92
39,Taurus Taxshield,3,74.85,37.01,42.73,0.00,46.49,0.17,0.00,22.28,0.96
33,SBI Long Term Equity Fund - Regular Plan,3,9257.60,49.25,71.96,0.00,122.09,0.98,0.00,18.63,0.80
51,Principal Personal Tax Save,3,289.85,35.75,44.99,0.00,32.13,0.25,97.00,19.78,0.86
58,Mahindra Manulife ELSS Kar Bachat Yojana - Reg...,3,347.46,38.60,48.98,0.00,68.04,0.00,0.00,0.00,0.00
43,ICICI Prudential Long Term Equity Fund (Tax Sa...,3,8310.40,32.49,39.81,0.00,38.03,0.13,0.00,20.39,0.94
79,Edelweiss Long Term Equity Fund (Tax Savings),3,164.60,30.75,35.72,0.00,10.75,0.00,23.67,0.00,0.00
97,Baroda ELSS - 96 - Plan A,3,186.68,28.22,34.85,91.55,18.86,0.00,266.00,0.00,0.00
69,BNP Paribas Long Term Equity Fund,3,495.33,31.47,43.01,0.00,13.84,0.00,0.00,0.00,0.00
93,Axis Long Term Equity Fund,3,27870.00,35.70,54.23,0.00,13.39,0.00,104.00,0.00,0.00
85,Tata India Tax Savings Fund - Regular Plan,2,2637.17,25.61,30.46,0.00,21.48,0.00,31.00,0.00,0.00
68,Sundaram Diversified Equity,2,2304.22,33.02,41.21,0.00,15.25,0.00,93.00,0.00,0.00
89,Navi Long Term Advantage Fund,2,62.27,31.73,40.68,0.00,11.36,0.00,0.00,0.00,0.00
109,Indiabulls Tax Savings Fund,2,54.26,26.20,38.46,0.00,10.57,0.00,0.00,0.00,0.00
99,HSBC Tax Saver Equity Fund,2,169.44,26.62,34.39,87.38,24.21,0.00,33.53,0.00,0.00
117,Aditya Birla Sun Life Tax Relief 96 - Regular ...,2,13647.28,25.26,36.83,91.66,22.52,0.00,0.00,0.00,0.00
25,Nippon India Tax Saver Fund,1,11219.23,49.73,57.73,0.00,67.96,0.11,81.00,18.08,0.77
47,IDBI Equity Advantage Fund,1,506.42,30.71,36.00,93.40,18.13,-0.13,44.00,20.94,0.83
62,HDFC Tax Saver Fund,1,7920.48,33.37,44.37,0.00,19.87,0.00,11.17,0.00,0.00
64,UTI Master Equity Plan Unit Scheme,0,2084.98,36.55,45.35,102.58,19.44,0.00,37.00,0.00,0.00
115,UTI Long Term Advantage Fund Series VII,0,290.01,26.66,39.35,0.00,13.16,0.00,0.00,0.00,0.00
82,UTI Long Term Advantage Fund - Series V,0,119.41,31.23,40.45,0.00,20.30,0.00,0.00,0.00,0.00
41,UTI Long Term Advantage Fund - Series IV,0,113.98,40.95,51.49,140.24,41.07,0.50,0.00,19.91,0.88
84,UTI Long Term Advantage Fund - Series III,0,247.95,30.17,38.41,115.60,21.20,0.00,58.00,0.00,0.00
34,Sundaram Long Term Tax Advantage Fund - Series...,0,17.30,43.15,55.67,0.00,20.77,0.26,0.00,18.73,0.80
77,Shriram Long Term Equity Fund,0,36.56,32.39,37.79,95.10,13.34,0.00,94.00,0.00,0.00
73,SBI Tax Advantage Fund - Series III - Regular ...,0,25.52,31.09,34.33,0.00,45.35,0.00,54.00,0.00,0.00
24,SBI Long Term Advantage Fund - Series VI - Reg...,0,306.41,48.93,55.74,0.00,67.15,0.20,78.00,21.08,0.97
17,SBI Long Term Advantage Fund - Series IV - Reg...,0,156.65,44.73,54.14,136.90,86.34,0.72,50.00,18.37,0.79
15,Parag Parikh Tax Saver Fund - Regular Plan,0,179.45,47.26,58.96,0.00,98.11,0.55,0.00,19.09,0.83
61,ITI Long Term Equity Fund,0,75.51,36.88,51.20,0.00,35.17,0.00,11.17,0.00,0.00
111,ICICI Prudential Long Term Wealth Enhancement ...,0,48.06,26.08,35.53,0.00,11.37,0.00,13.31,0.00,0.00
59,BOI AXA Midcap Tax Fund - Series 2 - Regular Plan,0,71.99,43.45,60.14,129.75,12.74,0.00,67.00,0.00,0.00
70,BOI AXA Midcap Tax Fund - Series 1,0,85.66,31.91,41.23,110.08,13.54,0.00,0.00,0.00,0.00

In [45]:
# Extracting funds which have '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['1Y_SIP_RTN(%)'] > 25) & (regular_mf['2Y_SIP_RTN(%)'] > 25) &
                            (regular_mf['3Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']].nlargest(10, 'AuM (Cr)')

No. of funds having '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25% is: 33 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
25,Nippon India Tax Saver Fund,1,11219.23,33.14,44.52,49.73,67.96,0.11,81.00,18.08,0.77
33,SBI Long Term Equity Fund - Regular Plan,3,9257.60,30.97,42.17,49.25,122.09,0.98,0.00,18.63,0.80
43,ICICI Prudential Long Term Equity Fund (Tax Sa...,3,8310.40,29.81,32.34,32.49,38.03,0.13,0.00,20.39,0.94
19,DSP Tax Saver Fund - Regular Plan,4,8056.26,35.78,55.04,69.49,78.88,0.60,0.00,19.72,0.92
62,HDFC Tax Saver Fund,1,7920.48,25.81,31.02,33.37,19.87,0.00,11.17,0.00,0.00
31,Mirae Asset Tax Saver Fund - Regular Plan,5,6934.49,31.43,46.99,53.67,51.43,0.26,35.00,19.87,0.94
38,IDFC Tax Advantage (ELSS) Fund - Regular Plan,4,2988.35,30.43,33.83,31.48,65.26,0.11,11.00,23.63,1.02
68,Sundaram Diversified Equity,2,2304.22,25.42,31.86,33.02,15.25,0.00,93.00,0.00,0.00
64,UTI Master Equity Plan Unit Scheme,0,2084.98,25.60,33.64,36.55,19.44,0.00,37.00,0.00,0.00
46,UTI Long Term Equity Fund (Tax Saving),4,1800.13,28.61,33.11,31.26,25.37,-0.18,47.00,20.92,0.83

In [46]:
# Top 10 high AuM (Cr) regular mutual funds are
#mf_tr = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 0)]
print("Top 10 high 'AuM (Cr)' regular mutual funds are :")
mf_tr =  mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)',
       'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']].nlargest(10, 'AuM (Cr)')
mf_tr

Top 10 high 'AuM (Cr)' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
25,Nippon India Tax Saver Fund,1,11219.23,68.79,2.30,8.25,11.72,0.11,81.0,18.08,0.77
33,SBI Long Term Equity Fund - Regular Plan,3,9257.60,62.59,9.47,11.82,12.15,0.98,0.0,18.63,0.80
43,ICICI Prudential Long Term Equity Fund (Tax Sa...,3,8310.40,63.98,10.87,13.10,13.33,0.13,0.0,20.39,0.94
19,DSP Tax Saver Fund - Regular Plan,4,8056.26,69.89,13.37,16.42,15.06,0.60,0.0,19.72,0.92
31,Mirae Asset Tax Saver Fund - Regular Plan,5,6934.49,76.36,16.08,21.29,0.00,0.26,35.0,19.87,0.94
29,Franklin India Taxshield Fund,3,4375.42,72.04,8.43,11.44,13.19,0.19,98.0,19.02,0.87
38,IDFC Tax Advantage (ELSS) Fund - Regular Plan,4,2988.35,89.66,9.74,16.27,15.09,0.11,11.0,23.63,1.02
46,UTI Long Term Equity Fund (Tax Saving),4,1800.13,65.16,11.06,13.98,11.84,-0.18,47.0,20.92,0.83
47,IDBI Equity Advantage Fund,1,506.42,43.82,5.37,10.45,0.00,-0.13,44.0,20.94,0.83
53,Principal Tax Saving Fund,3,503.43,63.56,6.88,14.71,13.87,0.32,130.0,20.53,0.94

In [47]:
# Top 10 low AuM (Cr) regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 0)]
print("Top 10 low 'AuM (Cr)' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)',
       'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']].nsmallest(10, 'AuM (Cr)')

Top 10 low 'AuM (Cr)' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
49,Sundaram Long Term Tax Advantage Fund - Series...,0,12.61,64.80,9.77,14.14,0.00,0.01,42.00,20.07,0.80
34,Sundaram Long Term Tax Advantage Fund - Series...,0,17.30,66.80,9.52,14.14,0.00,0.26,0.00,18.73,0.80
73,SBI Tax Advantage Fund - Series III - Regular ...,0,25.52,83.16,24.15,23.58,0.00,0.00,54.00,0.00,0.00
125,SBI Long Term Advantage Fund - Series II - Reg...,0,29.02,83.36,13.45,16.45,0.00,0.00,39.00,0.00,0.00
123,SBI Long Term Advantage Fund - Series I - Regu...,0,34.42,86.24,12.14,15.21,0.00,0.00,6.03,0.00,0.00
54,SBI Tax Advantage Fund - Series II - Regular Plan,0,35.47,84.97,22.48,23.56,0.00,0.00,130.00,0.00,0.00
105,JM Tax Gain Fund,4,52.53,71.77,11.73,16.50,13.37,0.00,40.00,0.00,0.00
127,SBI Long Term Advantage Fund - Series III - Re...,0,54.36,83.25,14.55,15.04,0.00,0.00,1019.00,0.00,0.00
89,Navi Long Term Advantage Fund,2,62.27,54.31,7.43,11.23,0.00,0.00,0.00,0.00,0.00
39,Taurus Taxshield,3,74.85,50.59,7.92,14.22,10.95,0.17,0.00,22.28,0.96

In [48]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 0) & (regular_mf['AuM (Cr)'] < 500) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds eturns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds eturns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs is: 11 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
1,Quant Tax Plan,5,106.05,126.70,25.65,23.24,14.90,768.57,0.29,530.00,19.62,0.87
108,BOI AXA Tax Advantage Fund - Regular Plan,5,417.39,69.21,12.22,18.33,14.22,10.97,0.00,0.00,0.00,0.00
91,Union Long Term Equity Fund,4,335.59,61.27,11.47,12.45,0.00,11.52,0.00,43.24,0.00,0.00
105,JM Tax Gain Fund,4,52.53,71.77,11.73,16.50,13.37,49.02,0.00,40.00,0.00,0.00
28,PGIM India Long Term Equity Fund,3,352.90,66.49,10.72,14.55,0.00,57.73,0.11,42.00,18.45,0.85
69,BNP Paribas Long Term Equity Fund,3,495.33,52.50,11.04,12.40,14.13,13.84,0.00,0.00,0.00,0.00
73,SBI Tax Advantage Fund - Series III - Regular ...,0,25.52,83.16,24.15,23.58,0.00,45.35,0.00,54.00,0.00,0.00
54,SBI Tax Advantage Fund - Series II - Regular Plan,0,35.47,84.97,22.48,23.56,0.00,13.11,0.00,130.00,0.00,0.00
127,SBI Long Term Advantage Fund - Series III - Re...,0,54.36,83.25,14.55,15.04,0.00,91.65,0.00,1019.00,0.00,0.00
125,SBI Long Term Advantage Fund - Series II - Reg...,0,29.02,83.36,13.45,16.45,0.00,14.17,0.00,39.00,0.00,0.00
123,SBI Long Term Advantage Fund - Series I - Regu...,0,34.42,86.24,12.14,15.21,0.00,17.26,0.00,6.03,0.00,0.00

In [49]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 500Crs to 1000Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 500) & (regular_mf['AuM (Cr)'] < 1000) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is:", len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is: 0 Funds

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio, Turnover ratio(%), Standard Deviation, Beta]
Index: []

In [50]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 1000) & (regular_mf['AuM (Cr)'] < 1500) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs is: 0 Funds

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio, Turnover ratio(%), Standard Deviation, Beta]
Index: []

In [51]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 1500 to 20000Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 1500) & (regular_mf['AuM (Cr)'] < 20000) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds returns 10% in 3year & 5year period which have AuM in between 1500Crs to 20000Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds returns 10% in 3year & 5year period which have AuM in between 1500Crs to 1500Crs is: 7 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
31,Mirae Asset Tax Saver Fund - Regular Plan,5,6934.49,76.36,16.08,21.29,0.00,51.43,0.26,35.0,19.87,0.94
65,Canara Robeco Equity Tax Saver - Regular Plan,5,2044.06,64.73,16.50,17.18,14.11,25.44,0.00,78.0,0.00,0.00
46,UTI Long Term Equity Fund (Tax Saving),4,1800.13,65.16,11.06,13.98,11.84,25.37,-0.18,47.0,20.92,0.83
98,Kotak Tax Saver Scheme,4,1836.79,63.83,13.19,15.61,12.72,17.24,0.00,266.0,0.00,0.00
19,DSP Tax Saver Fund - Regular Plan,4,8056.26,69.89,13.37,16.42,15.06,78.88,0.60,0.0,19.72,0.92
121,Invesco India Tax Plan,3,1512.41,56.46,10.54,14.85,14.64,66.53,0.00,0.0,0.00,0.00
43,ICICI Prudential Long Term Equity Fund (Tax Sa...,3,8310.40,63.98,10.87,13.10,13.33,38.03,0.13,0.0,20.39,0.94