In [1]:
# Importing respective modules
import pandas as pd

## Dividend Yield Fund

These mutual funds invest in stocks and follow strategy of investing in stocks which generates higher dividend yield.

## Exctracting Dividend Yield Mutual Fund's Historical Investment Returns Data

Data in this table: Get Absolute historical returns for ₹1000 investment. If 1Y column value is 1234.5 that means, your ₹1000 investment 1 year back would have grown to ₹1234.5.

In [2]:
dy_lump_sum_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/returns/dividend-yield-fund.html")
df1 = pd.DataFrame(dy_lump_sum_rtn[0])

In [3]:
#Renaming historical returns column names
df1.rename({'1W': '1W_RTN(%)', '1M': '1M_RTN(%)', '3M': '3M_RTN(%)', '6M': '6M_RTN(%)',
                 'YTD': 'YTD_RTN(%)', '1Y': '1Y_RTN(%)', '2Y': '2Y_RTN(%)', '3Y': '3Y_RTN(%)',
                 '5Y': '5Y_RTN(%)', '10Y': '10Y_RTN(%)'
          }, axis=1, inplace=True)
print("Shape of the dataframe:", df1.shape)
df1.head()

Shape of the dataframe: (14, 13)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%)
0,UTI Dividend Yield Fund - Direct Plan - Growth...,1,2624.20,4.30%,3.16%,8.98%,29.94%,14.45%,65.49%,19.25%,12.67%,15.03%,-
1,UTI Dividend Yield Fund - GrowthDividend Yield...,1,2624.20,4.29%,3.11%,8.82%,29.57%,14.22%,64.56%,18.59%,12.01%,14.33%,10.70%
2,ICICI Prudential Dividend Yield Equity Fund - ...,-,237.68,4.17%,3.35%,9.40%,38.07%,16.45%,79.86%,14.50%,6.71%,13.53%,-
3,ICICI Prudential Dividend Yield Equity Fund - ...,-,237.68,4.15%,3.28%,9.11%,37.39%,16.07%,78.31%,13.55%,5.83%,12.65%,-
4,Aditya Birla Sun Life Dividend Yield Fund - Di...,1,741.90,3.52%,4.21%,10.67%,26.65%,12.22%,64.24%,18.22%,7.74%,11.36%,-

## Exctracting Dividend Yield Mutual Fund's Monthly Returns Data

Data in this table: Get monthly returns. If Jan month column value is 5.4% that means, fund has given 5.4% returns in Jan month.

In [4]:
dy_monthly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/monthly-returns/dividend-yield-fund.html")
df2 = pd.DataFrame(dy_monthly_rtn[0])

In [5]:
#Renaming df1 column names
df1.rename({"Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            'MTD': 'MTD_RTN(%)', "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)"
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df2.shape)
df2.head()

Shape of the dataframe: (14, 14)

,Scheme Name,Crisil Rank,MTD,Apr'21,Mar'21,Feb'21,Jan'21,Dec'20,Nov'20,Oct'20,Sep'20,Aug'20,Jul'20,Jun'20
0,Aditya Birla Sun Life Dividend Yield Fund - Re...,1,4.28%,2.97%,0.41%,3.75%,-4.04%,5.86%,9.94%,-0.32%,-0.22%,4.34%,6.09%,5.96%
1,Aditya Birla Sun Life Dividend Yield Fund - Di...,1,4.30%,3.02%,0.45%,3.79%,-4.00%,5.92%,10.01%,-0.26%,-0.16%,4.40%,6.16%,6.02%
2,HDFC Dividend Yield Fund - Regular Plan - Grow...,-,3.60%,-1.28%,-0.07%,5.34%,-1.19%,0.42%,-,-,-,-,-,-
3,HDFC Dividend Yield Fund - Direct Plan - Growt...,-,3.65%,-1.16%,0.07%,5.46%,-1.06%,0.27%,-,-,-,-,-,-
4,IDBI Dividend Yield Fund - Regular Plan - Grow...,-,2.05%,-0.21%,1.30%,1.11%,-2.44%,5.42%,8.54%,0.70%,0.35%,2.63%,7.93%,4.08%

## Exctracting Dividend Yield Mutual Fund's Quarterly Returns Data

Data in this table: Get quarterly returns. If Q1 column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Mar.

In [6]:
dy_quarterly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/quarterly-returns/dividend-yield-fund.html")
df3 = pd.DataFrame(dy_quarterly_rtn[0])

In [7]:
print("Shape of the dataframe:", df3.shape)
df3.head()

Shape of the dataframe: (14, 14)

,Scheme Name,Crisil Rank,QTD,Q1'21,Q4'20,Q3'20,Q2'20,Q1'20,Q4'19,Q3'19,Q2'19,Q1'19,Q4'18,Q3'18
0,Aditya Birla Sun Life Dividend Yield Fund - Re...,1,7.38%,2.05%,17.23%,10.31%,24.13%,-26.56%,6.70%,-1.66%,-2.72%,1.70%,-0.45%,-3.68%
1,Aditya Birla Sun Life Dividend Yield Fund - Di...,1,7.46%,2.20%,17.44%,10.52%,24.37%,-26.42%,6.82%,-1.84%,-2.56%,1.87%,-0.29%,-3.52%
2,HDFC Dividend Yield Fund - Regular Plan - Grow...,-,2.28%,8.34%,-,-,-,-,-,-,-,-,-,-
3,HDFC Dividend Yield Fund - Direct Plan - Growt...,-,2.46%,8.80%,-,-,-,-,-,-,-,-,-,-
4,IDBI Dividend Yield Fund - Regular Plan - Grow...,-,1.84%,3.77%,16.68%,11.85%,21.14%,-19.96%,4.45%,2.96%,-0.30%,1.50%,-,-

## Exctracting Dividend Yield Mutual Fund's Annual Investment Returns Data

Data in this table: Get annual returns. If 2018 year column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Dec/Last date.

In [8]:
dy_annual_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/annual-returns/dividend-yield-fund.html")
df4 = pd.DataFrame(dy_annual_rtn[0])

In [9]:
#Renaming yearly returns column names
df4.rename({'2020': '2020_RTN(%)', '2019': '2019_RTN(%)', '2018': '2018_RTN(%)', '2017': '2017_RTN(%)',
                 '2016': '2016_RTN(%)', '2015': '2015_RTN(%)', '2014': '2014_RTN(%)', '2013': '2013_RTN(%)',
                 '2012': '2012_RTN(%)', '2011': '2011_RTN(%)', '2010': '2010_RTN(%)'
               }, axis=1, inplace=True)

print("Shape of the dataframe:", df4.shape)
df4.head()

Shape of the dataframe: (14, 14)

,Scheme Name,Crisil Rank,YTD,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%),2015_RTN(%),2014_RTN(%),2013_RTN(%),2012_RTN(%),2011_RTN(%),2010_RTN(%)
0,Aditya Birla Sun Life Dividend Yield Fund - Re...,1,11.20%,15.54%,2.97%,-14.35%,33.19%,2.08%,-5.62%,55.81%,-3.89%,29.39%,-18.81%,29.85%
1,Aditya Birla Sun Life Dividend Yield Fund - Di...,1,11.44%,16.42%,3.82%,-13.72%,34.25%,2.93%,-4.83%,57.03%,-3.71%,-,-,-
2,HDFC Dividend Yield Fund - Regular Plan - Grow...,-,10.13%,0.74%,-,-,-,-,-,-,-,-,-,-
3,HDFC Dividend Yield Fund - Direct Plan - Growt...,-,10.79%,0.80%,-,-,-,-,-,-,-,-,-,-
4,IDBI Dividend Yield Fund - Regular Plan - Grow...,-,6.58%,24.12%,8.08%,0.20%,-,-,-,-,-,-,-,-

## Exctracting Dividend Yield Mutual Fund's Rank Within Category Data

Data in this table: Get performance rank within category. If 1Y column value is 3/45 that means, Fund ranked 3rd in terms of performance out of 45 funds in that category.

In [10]:
dy_rank_in_category = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/ranks/dividend-yield-fund.html")
df5 = pd.DataFrame(dy_rank_in_category[0])

In [11]:
#Renaming df5 column names
df5.rename({'1W': '1W_Rank', '1M': '1M_Rank', '3M': '3M_Rank', '6M': '6M_Rank', 'YTD': 'YTD_Rank',
            '1Y': '1Y_Rank', '2Y': '2Y_Rank', '3Y': '3Y_Rank', '5Y': '5Y_Rank', '10Y': '10Y_Rank'
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df5.shape)
df5.head()

Shape of the dataframe: (12, 12)

,Scheme Name,Crisil Rank,1W_Rank,1M_Rank,3M_Rank,6M_Rank,YTD_Rank,1Y_Rank,2Y_Rank,3Y_Rank,5Y_Rank,10Y_Rank
0,Templeton India Equity Income Fund - GrowthDiv...,-,7/7,4/7,4/7,2/6,1/7,1/6,1/6,3/5,2/5,2/4
1,Templeton India Equity Income Fund - Direct - ...,-,7/7,4/7,4/7,2/6,1/7,1/6,2/6,2/5,2/5,0/0
2,ICICI Prudential Dividend Yield Equity Fund - ...,-,2/7,2/7,2/7,1/6,2/7,2/6,6/6,5/5,4/5,0/0
3,ICICI Prudential Dividend Yield Equity Fund - ...,-,2/7,2/7,2/7,1/6,2/7,2/6,6/6,5/5,4/5,0/0
4,UTI Dividend Yield Fund - GrowthDividend Yield...,1,1/7,3/7,3/7,3/6,3/7,3/6,4/6,1/5,3/5,3/4

## Exctracting Dividend Yield Mutual Fund's Risk Ratios Data

Data in this table: Get values of risk ratios calculated on daily returns for last 3 years.

In [12]:
dy_risk_ratio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/risk-ratios/dividend-yield-fund.html")
df6 = pd.DataFrame(dy_risk_ratio[0])

In [13]:
#Droping the 'Category' column
df6.drop('Category', inplace=True, axis=1)
print("Shape of the dataframe:", df6.shape)
df6.head()

Shape of the dataframe: (5, 8)

,Scheme Name,Crisil Rank,AuM (Cr),Standard Deviation,Beta,Sharpe Ratio,Jension's Alpha,Treynor's Ratio
0,Templeton India Equity Income Fund - Growth,-,1000.39,17.09,0.69,0.45,1.30,0.11
1,ICICI Prudential Dividend Yield Equity Fund - ...,-,237.68,18.36,0.89,0.09,-0.29,0.02
2,Principal Dividend Yield Fund - Growth,3,201.93,18.55,0.92,0.42,5.92,0.09
3,Aditya Birla Sun Life Dividend Yield Fund - Re...,1,741.90,17.08,0.75,0.17,-2.73,0.04
4,UTI Dividend Yield Fund - Growth,1,2624.20,17.77,0.76,0.41,0.94,0.10

## Exctracting Dividend Yield Mutual Fund's Portfolio Data

Data in this table: Compare how schemes have invested money across various asset class and number of instruments.

In [14]:
dy_portfolio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/portfolioassets/dividend-yield-fund.html")
df7 = pd.DataFrame(dy_portfolio[0])

In [15]:
#Renaming SIP returns column names
df7.rename({'Turnover ratio': 'Turnover ratio(%)'}, axis=1, inplace=True)

print("Shape of the dataframe:", df7.shape)
df7.head()

Shape of the dataframe: (14, 10)

,Scheme Name,Crisil Rank,Turnover ratio(%),% Equity Holding,No of stocks in portfolio,% Debt Holding,No of instruments in portfolio,% MF Holding,% Cash Holding,% Other Holding
0,UTI Dividend Yield Fund - Direct Plan - Growth...,1,-,99.75%,48,-,-,-,0.25%,-
1,UTI Dividend Yield Fund - GrowthDividend Yield...,1,-,99.75%,48,-,-,-,0.25%,-
2,ICICI Prudential Dividend Yield Equity Fund - ...,-,-,98.91%,34,-,-,-,1.09%,-
3,ICICI Prudential Dividend Yield Equity Fund - ...,-,-,98.91%,34,-,-,-,1.09%,-
4,Principal Dividend Yield Fund - GrowthDividend...,3,-,98.86%,46,0.02%,1,-,1.12%,-

## Exctracting Dividend Yield Mutual Fund's Latest NAV Data

Data in this table: Get the latest values of NAV for the mutual funds.

In [16]:
dy_nav = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/navs/dividend-yield-fund.html")
df8 = pd.DataFrame(dy_nav[0])

In [17]:
df8.rename({'1D Change' : '1D Change(%)'}, axis=1, inplace=True)
print("Shape of the dataframe:", df8.shape)
df8.head()

Shape of the dataframe: (14, 10)

,Scheme Name,Crisil Rank,AuM (Cr),NAV,1D Change(%),NAV Date,52W High,52WH as on,52W Low,52WL as on
0,Aditya Birla Sun Life Dividend Yield Fund - Di...,1,741.90,225.8400,1.71%,10-May-21,225.8400,10-May-21,133.4200,18-May-20
1,Aditya Birla Sun Life Dividend Yield Fund - Re...,1,741.90,212.2600,1.71%,10-May-21,212.2600,10-May-21,126.2500,18-May-20
2,UTI Dividend Yield Fund - Direct Plan - Growth...,1,2624.20,93.8391,1.12%,10-May-21,93.8391,10-May-21,55.4093,18-May-20
3,UTI Dividend Yield Fund - GrowthDividend Yield...,1,2624.20,89.1734,1.12%,10-May-21,89.1734,10-May-21,52.9472,18-May-20
4,Templeton India Equity Income Fund - Direct - ...,-,1000.39,70.2004,1.12%,10-May-21,70.2004,10-May-21,37.1376,18-May-20

## Exctracting Dividend Yield Mutual Fund's SIP Returns Data

Data in this table: Get absolute SIP returns. If 1Y column value is 10%, that means fund has given 10% returns on your SIP investments started 1 year back from latest NAV date.

In [18]:
dy_sip_rtns = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/sip-returns/dividend-yield-fund.html")
df9 = pd.DataFrame(dy_sip_rtns[0])

In [19]:
#Renaming SIP returns column names
df9.rename({'1Y': '1Y_SIP_RTN(%)', '2Y': '2Y_SIP_RTN(%)', '3Y': '3Y_SIP_RTN(%)',
                  '5Y': '5Y_SIP_RTN(%)', '10Y': '10Y_SIP_RTN(%)', 'YTD' : 'YTD_SIP_RTN(%)'
           }, axis=1, inplace=True)

print("Shape of the dataframe:", df9.shape)
df9.head()

Shape of the dataframe: (12, 8)

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,Templeton India Equity Income Fund - Direct - ...,-,1000.39,36.50%,44.61%,45.78%,54.93%,-
1,Templeton India Equity Income Fund - GrowthDiv...,-,1000.39,35.80%,43.13%,43.74%,51.54%,112.51%
2,ICICI Prudential Dividend Yield Equity Fund - ...,-,237.68,34.39%,37.75%,35.03%,38.33%,-
3,ICICI Prudential Dividend Yield Equity Fund - ...,-,237.68,33.66%,36.49%,33.32%,35.43%,-
4,UTI Dividend Yield Fund - Direct Plan - Growth...,1,2624.20,28.43%,36.23%,38.27%,49.52%,-

In [20]:
df_final = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9],axis=1,sort=False)
print("Shape of the dataframe:", df_final.shape)

Shape of the dataframe: (14, 103)

In [21]:
# Remove duplicate columns by name in Pandas
df_final = df_final.loc[:,~df_final.columns.duplicated()]

# Removing spaces in the column names
#df_final.columns = df_final.columns.str.replace(' ','_')

print("Shape of the dataframe:", df_final.shape)
df_final.head()

Shape of the dataframe: (14, 84)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,NAV Date,52W High,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,UTI Dividend Yield Fund - Direct Plan - Growth...,1,2624.20,4.30%,3.16%,8.98%,29.94%,14.45%,65.49%,19.25%,...,10-May-21,225.8400,10-May-21,133.4200,18-May-20,36.50%,44.61%,45.78%,54.93%,-
1,UTI Dividend Yield Fund - GrowthDividend Yield...,1,2624.20,4.29%,3.11%,8.82%,29.57%,14.22%,64.56%,18.59%,...,10-May-21,212.2600,10-May-21,126.2500,18-May-20,35.80%,43.13%,43.74%,51.54%,112.51%
2,ICICI Prudential Dividend Yield Equity Fund - ...,-,237.68,4.17%,3.35%,9.40%,38.07%,16.45%,79.86%,14.50%,...,10-May-21,93.8391,10-May-21,55.4093,18-May-20,34.39%,37.75%,35.03%,38.33%,-
3,ICICI Prudential Dividend Yield Equity Fund - ...,-,237.68,4.15%,3.28%,9.11%,37.39%,16.07%,78.31%,13.55%,...,10-May-21,89.1734,10-May-21,52.9472,18-May-20,33.66%,36.49%,33.32%,35.43%,-
4,Aditya Birla Sun Life Dividend Yield Fund - Di...,1,741.90,3.52%,4.21%,10.67%,26.65%,12.22%,64.24%,18.22%,...,10-May-21,70.2004,10-May-21,37.1376,18-May-20,28.43%,36.23%,38.27%,49.52%,-

In [22]:
#Exporting the consolidated elss mf data as a  csv file
#print("Shape of the dataframe:", df_final.shape)
#df_final.to_csv('dy_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + ').csv',
#               index=False)

#Exporting the elss mf data columns with its datatype as a  csv file
#df_dtypes.to_csv('elss_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')