In [64]:
import re
import pandas as pd
import numpy as np
%matplotlib inline

## Exctracting ELSS Mutual Fund's Historical Investment Returns Data

Data in this table: Get Absolute historical returns for ₹1000 investment. If 1Y column value is 1234.5 that means, your ₹1000 investment 1 year back would have grown to ₹1234.5.

In [65]:
elss_lump_sum_rtn = pd.read_html("https://www.moneycontrol.com/mutual-funds/performance-tracker/returns/elss.html")
df1 = pd.DataFrame(elss_lump_sum_rtn[0])

In [66]:
#Renaming historical returns column names
df1.rename({'1W': '1W_RTN(%)', '1M': '1M_RTN(%)', '3M': '3M_RTN(%)', '6M': '6M_RTN(%)',
                 'YTD': 'YTD_RTN(%)', '1Y': '1Y_RTN(%)', '2Y': '2Y_RTN(%)', '3Y': '3Y_RTN(%)',
                 '5Y': '5Y_RTN(%)', '10Y': '10Y_RTN(%)'
          }, axis=1, inplace=True)
print("Shape of the dataframe:", df1.shape)
df1.head()

Shape of the dataframe: (128, 13)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%)
0,Quant Tax Plan - Direct Plan - GrowthELSS,5,106.05,6.05%,10.05%,24.16%,55.08%,32.23%,131.26%,43.55%,27.41%,24.32%,-
1,Quant Tax Plan - GrowthELSS,5,106.05,6.00%,9.87%,23.50%,53.42%,31.24%,126.70%,41.01%,25.65%,23.24%,14.90%
2,Sundaram Long Term Micro Cap Tax Advantage Fun...,-,37.10,4.12%,6.74%,16.47%,50.65%,23.93%,104.47%,15.92%,0.79%,-,-
3,Sundaram Long Term Micro Cap Tax Advantage Fun...,-,37.10,4.11%,6.72%,16.40%,50.42%,23.81%,103.83%,15.56%,0.38%,-,-
4,Sundaram Long Term Micro Cap Tax Advantage Fun...,-,38.37,3.90%,7.10%,16.99%,50.67%,24.66%,105.11%,14.93%,-0.03%,-,-

## Exctracting ELSS Mutual Fund's Monthly Returns Data

Data in this table: Get monthly returns. If Jan month column value is 5.4% that means, fund has given 5.4% returns in Jan month.

In [67]:
elss_monthly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/monthly-returns/elss.html")
df2 = pd.DataFrame(elss_monthly_rtn[0])

In [68]:
#Renaming df1 column names
df1.rename({"Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            'MTD': 'MTD_RTN(%)', "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)"
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df2.shape)
df2.head()

Shape of the dataframe: (128, 14)

,Scheme Name,Crisil Rank,MTD,Apr'21,Mar'21,Feb'21,Jan'21,Dec'20,Nov'20,Oct'20,Sep'20,Aug'20,Jul'20,Jun'20
0,ITI Long Term Equity Fund - GrowthELSS,-,1.29%,0.61%,-1.05%,5.21%,-1.14%,4.42%,11.10%,0.46%,-1.11%,4.19%,4.12%,6.15%
1,ITI Long Term Equity Fund - Direct Plan - Grow...,-,1.34%,0.78%,-0.87%,5.37%,-0.97%,4.61%,11.28%,0.63%,-0.94%,4.38%,4.31%,6.34%
2,Taurus Taxshield - GrowthELSS,3,1.80%,-0.41%,-0.81%,1.66%,-2.27%,5.59%,7.69%,1.17%,0.77%,1.44%,7.03%,4.59%
3,Taurus Taxshield - Direct Plan - GrowthELSS,3,1.81%,-0.35%,-0.76%,1.69%,-2.23%,5.64%,7.73%,1.21%,0.81%,1.49%,7.12%,4.70%
4,Quantum Tax Saving Fund - Direct Plan - Growth...,4,2.11%,-0.65%,-0.01%,2.63%,0.48%,4.19%,12.84%,2.42%,-0.63%,2.94%,6.85%,4.01%

## Exctracting ELSS Mutual Fund's Quarterly Returns Data

Data in this table: Get quarterly returns. If Q1 column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Mar.

In [69]:
elss_quarterly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/quarterly-returns/elss.html")
df3 = pd.DataFrame(elss_quarterly_rtn[0])

In [70]:
print("Shape of the dataframe:", df3.shape)
df3.head()

Shape of the dataframe: (128, 14)

,Scheme Name,Crisil Rank,QTD,Q1'21,Q4'20,Q3'20,Q2'20,Q1'20,Q4'19,Q3'19,Q2'19,Q1'19,Q4'18,Q3'18
0,BNP Paribas Long Term Equity Fund - GrowthELSS,3,-0.30%,5.27%,18.96%,7.31%,19.37%,-21.62%,4.52%,1.02%,3.72%,4.40%,2.56%,-3.83%
1,BNP Paribas Long Term Equity Fund - Direct Pla...,3,-0.17%,5.61%,19.34%,7.65%,19.71%,-21.38%,4.83%,1.32%,3.99%,4.70%,2.82%,-3.55%
2,IDFC Tax Advantage (ELSS) Fund - Regular Plan ...,4,3.60%,13.15%,20.25%,14.09%,28.34%,-31.95%,5.02%,-6.99%,-0.45%,5.37%,0.37%,-4.01%
3,IDFC Tax Advantage (ELSS) Fund - Direct Plan -...,4,3.70%,13.44%,20.55%,14.40%,28.71%,-31.78%,5.29%,-6.71%,-0.11%,5.78%,0.65%,-3.72%
4,Axis Long Term Equity Fund - GrowthELSS,3,0.69%,1.88%,25.94%,6.79%,16.57%,-21.78%,5.51%,2.11%,4.36%,1.84%,3.15%,-2.77%

## Exctracting ELSS Mutual Fund's Annual Investment Returns Data

Data in this table: Get annual returns. If 2018 year column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Dec/Last date.

In [71]:
elss_annual_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/annual-returns/elss.html")
df4 = pd.DataFrame(elss_annual_rtn[0])

In [72]:
#Renaming yearly returns column names
df4.rename({'2020': '2020_RTN(%)', '2019': '2019_RTN(%)', '2018': '2018_RTN(%)', '2017': '2017_RTN(%)',
                 '2016': '2016_RTN(%)', '2015': '2015_RTN(%)', '2014': '2014_RTN(%)', '2013': '2013_RTN(%)',
                 '2012': '2012_RTN(%)', '2011': '2011_RTN(%)', '2010': '2010_RTN(%)'
               }, axis=1, inplace=True)

print("Shape of the dataframe:", df4.shape)
df4.head()

Shape of the dataframe: (128, 14)

,Scheme Name,Crisil Rank,YTD,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%),2015_RTN(%),2014_RTN(%),2013_RTN(%),2012_RTN(%),2011_RTN(%),2010_RTN(%)
0,ITI Long Term Equity Fund - Growth ELSS,-,10.86%,11.48%,5.34%,-,-,-,-,-,-,-,-,-
1,ITI Long Term Equity Fund - Direct Plan - Grow...,-,11.71%,13.94%,5.80%,-,-,-,-,-,-,-,-,-
2,Taurus Taxshield - Growth ELSS,3,5.81%,13.53%,7.95%,0.33%,38.00%,2.65%,1.83%,34.99%,-0.67%,28.66%,-22.21%,18.88%
3,Taurus Taxshield - Direct Plan - Growth ELSS,3,6.02%,14.48%,8.65%,0.95%,38.61%,3.98%,3.19%,35.47%,-1.49%,-,-,-
4,Quantum Tax Saving Fund - Direct Plan - Growth...,4,12.04%,13.43%,-0.72%,1.04%,22.26%,12.35%,2.26%,40.13%,8.13%,31.36%,-20.92%,28.17%

## Exctracting ELSS Mutual Fund's Rank Within Category Data

Data in this table: Get performance rank within category. If 1Y column value is 3/45 that means, Fund ranked 3rd in terms of performance out of 45 funds in that category.

In [73]:
elss_rank_in_category = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/ranks/elss.html")
df5 = pd.DataFrame(elss_rank_in_category[0])

In [74]:
#Renaming df5 column names
df5.rename({'1W': '1W_Rank', '1M': '1M_Rank', '3M': '3M_Rank', '6M': '6M_Rank', 'YTD': 'YTD_Rank',
            '1Y': '1Y_Rank', '2Y': '2Y_Rank', '3Y': '3Y_Rank', '5Y': '5Y_Rank', '10Y': '10Y_Rank'
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df5.shape)
df5.head()

Shape of the dataframe: (128, 12)

,Scheme Name,Crisil Rank,1W_Rank,1M_Rank,3M_Rank,6M_Rank,YTD_Rank,1Y_Rank,2Y_Rank,3Y_Rank,5Y_Rank,10Y_Rank
0,Quant Tax Plan - GrowthELSS,5,1/68,1/65,1/67,1/68,1/68,1/68,1/66,1/62,3/46,4/30
1,Quant Tax Plan - Direct Plan - GrowthELSS,5,1/63,1/63,1/63,1/63,1/63,1/63,1/61,1/57,1/42,0/0
2,Sundaram Long Term Micro Cap Tax Advantage Fun...,-,3/68,2/65,2/67,2/68,2/68,2/68,37/66,61/62,0/0,0/0
3,Sundaram Long Term Micro Cap Tax Advantage Fun...,-,3/63,2/63,2/63,2/63,2/63,2/63,36/61,55/57,0/0,0/0
4,Sundaram Long Term Micro Cap Tax Advantage Fun...,-,2/68,3/65,3/67,3/68,3/68,3/68,31/66,59/62,0/0,0/0

## Exctracting ELSS Mutual Fund's Risk Ratios Data

Data in this table: Get values of risk ratios calculated on daily returns for last 3 years.

In [75]:
elss_risk_ratio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/risk-ratios/elss.html")
df6 = pd.DataFrame(elss_risk_ratio[0])

In [76]:
#Droping the 'Category' column
df6.drop('Category', inplace=True, axis=1)
print("Shape of the dataframe:", df6.shape)
df6.head()

Shape of the dataframe: (54, 8)

,Scheme Name,Crisil Rank,AuM (Cr),Standard Deviation,Beta,Sharpe Ratio,Jension's Alpha,Treynor's Ratio
0,Taurus Taxshield - Growth,3,74.85,19.31,0.90,0.26,-2.49,0.06
1,Quantum Tax Saving Fund - Growth,4,89.11,19.62,0.87,0.29,-1.57,0.07
2,Franklin India Taxshield Fund - Growth,3,4375.42,20.74,0.97,0.30,-1.16,0.06
3,ICICI Prudential Long Term Equity Fund (Tax Sa...,3,8310.40,19.92,0.92,0.40,1.00,0.09
4,ICICI Prudential Long Term Wealth Enhancement ...,-,48.06,21.72,1.00,0.23,-3.85,0.05

## Exctracting ELSS Mutual Fund's Portfolio Data

Data in this table: Compare how schemes have invested money across various asset class and number of instruments.

In [77]:
elss_portfolio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/portfolioassets/elss.html")
df7 = pd.DataFrame(elss_portfolio[0])

In [78]:
#Renaming SIP returns column names
df7.rename({'Turnover ratio': 'Turnover ratio(%)'}, axis=1, inplace=True)

print("Shape of the dataframe:", df7.shape)
df7.head()

Shape of the dataframe: (128, 10)

,Scheme Name,Crisil Rank,Turnover ratio(%),% Equity Holding,No of stocks in portfolio,% Debt Holding,No of instruments in portfolio,% MF Holding,% Cash Holding,% Other Holding
0,Quant Tax Plan - GrowthELSS,5,530.00%,101.27%,51,-,-,-,-1.27%,-
1,Quant Tax Plan - Direct Plan - GrowthELSS,5,530.00%,101.27%,51,-,-,-,-1.27%,-
2,Sundaram Long Term Tax Advantage Fund - Series...,-,41.00%,99.90%,69,-,-,-,0.10%,-
3,Sundaram Long Term Tax Advantage Fund - Series...,-,41.00%,99.90%,69,-,-,-,0.10%,-
4,Navi Long Term Advantage Fund - GrowthELSS,2,-,99.79%,56,-,-,-,0.21%,-

## Exctracting ELSS Mutual Fund's Latest NAV Data

Data in this table: Get the latest values of NAV for the mutual funds.

In [79]:
elss_nav = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/navs/elss.html")
df8 = pd.DataFrame(elss_nav[0])

In [80]:
df8.rename({'1D Change' : '1D Change(%)'}, axis=1, inplace=True)
print("Shape of the dataframe:", df8.shape)
df8.head()

Shape of the dataframe: (128, 10)

,Scheme Name,Crisil Rank,AuM (Cr),NAV,1D Change(%),NAV Date,52W High,52WH as on,52W Low,52WL as on
0,ICICI Prudential Long Term Equity Fund (Tax Sa...,3,8310.40,527.0200,0.65%,07-May-21,539.6200,03-Mar-21,308.8600,18-May-20
1,Franklin India Taxshield Fund - Direct - Growt...,3,4375.42,768.5667,0.42%,07-May-21,787.4202,03-Mar-21,424.6445,18-May-20
2,ICICI Prudential Long Term Equity Fund (Tax Sa...,3,8310.40,488.2300,0.65%,07-May-21,500.2800,03-Mar-21,288.1000,18-May-20
3,Franklin India Taxshield Fund - GrowthELSS,3,4375.42,713.4535,0.41%,07-May-21,732.0924,03-Mar-21,397.6326,18-May-20
4,Quant Tax Plan - Direct Plan - GrowthELSS,5,106.05,191.0612,1.42%,07-May-21,191.0612,07-May-21,81.3329,18-May-20

## Exctracting ELSS Mutual Fund's SIP Returns Data

Data in this table: Get absolute SIP returns. If 1Y column value is 10%, that means fund has given 10% returns on your SIP investments started 1 year back from latest NAV date.

In [81]:
elss_sip_rtns = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/sip-returns/elss.html")
df9 = pd.DataFrame(elss_sip_rtns[0])

In [82]:
#Renaming SIP returns column names
df9.rename({'1Y': '1Y_SIP_RTN(%)', '2Y': '2Y_SIP_RTN(%)', '3Y': '3Y_SIP_RTN(%)',
                  '5Y': '5Y_SIP_RTN(%)', '10Y': '10Y_SIP_RTN(%)', 'YTD' : 'YTD_SIP_RTN(%)'
           }, axis=1, inplace=True)

print("Shape of the dataframe:", df9.shape)
df9.head()

Shape of the dataframe: (128, 8)

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,Quant Tax Plan - Direct Plan - GrowthELSS,5,106.05,59.12%,84.32%,92.16%,109.87%,-
1,Quant Tax Plan - GrowthELSS,5,106.05,57.16%,80.35%,86.86%,102.63%,218.21%
2,Sundaram Long Term Micro Cap Tax Advantage Fun...,-,37.10,47.25%,49.68%,41.15%,-,-
3,Sundaram Long Term Micro Cap Tax Advantage Fun...,-,38.37,47.25%,48.62%,39.60%,-,-
4,Sundaram Long Term Micro Cap Tax Advantage Fun...,-,38.37,47.01%,48.19%,38.75%,-,-

In [83]:
df_final = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9],axis=1,sort=False)
print("Shape of the dataframe:", df_final.shape)

Shape of the dataframe: (128, 103)

In [84]:
# Remove duplicate columns by name in Pandas
df_final = df_final.loc[:,~df_final.columns.duplicated()]

# Removing spaces in the column names
#df_final.columns = df_final.columns.str.replace(' ','_')

print("Shape of the dataframe:", df_final.shape)
df_final.head()

Shape of the dataframe: (128, 84)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,NAV Date,52W High,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,Quant Tax Plan - Direct Plan - GrowthELSS,5,106.05,6.05%,10.05%,24.16%,55.08%,32.23%,131.26%,43.55%,...,07-May-21,539.6200,03-Mar-21,308.8600,18-May-20,59.12%,84.32%,92.16%,109.87%,-
1,Quant Tax Plan - GrowthELSS,5,106.05,6.00%,9.87%,23.50%,53.42%,31.24%,126.70%,41.01%,...,07-May-21,787.4202,03-Mar-21,424.6445,18-May-20,57.16%,80.35%,86.86%,102.63%,218.21%
2,Sundaram Long Term Micro Cap Tax Advantage Fun...,-,37.10,4.12%,6.74%,16.47%,50.65%,23.93%,104.47%,15.92%,...,07-May-21,500.2800,03-Mar-21,288.1000,18-May-20,47.25%,49.68%,41.15%,-,-
3,Sundaram Long Term Micro Cap Tax Advantage Fun...,-,37.10,4.11%,6.72%,16.40%,50.42%,23.81%,103.83%,15.56%,...,07-May-21,732.0924,03-Mar-21,397.6326,18-May-20,47.25%,48.62%,39.60%,-,-
4,Sundaram Long Term Micro Cap Tax Advantage Fun...,-,38.37,3.90%,7.10%,16.99%,50.67%,24.66%,105.11%,14.93%,...,07-May-21,191.0612,07-May-21,81.3329,18-May-20,47.01%,48.19%,38.75%,-,-

In [106]:
#Exporting the consolidated elss mf data as a  csv file
#print("Shape of the dataframe:", df_final.shape)
#df_final.to_csv('elss_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + ').csv',
#               index=False)

#Exporting the elss mf data columns with its datatype as a  csv file
#df_dtypes.to_csv('elss_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')

Shape of the dataframe: (128, 84)