In [3]:
# Importing respective modules
import pandas as pd
import re

In [4]:
# Reading elss mutual funds csv file
sc_mf = pd.read_csv('sc_mf_data(11-May-2021 13:09:46).csv')

In [5]:
# Extracting a plan from "Scheme Name" column
scheme_name = list(sc_mf['Scheme Name'])
plan = []
for i in scheme_name:
    #print(type(i))
    plan.append(re.findall("Direct|Regular", str(i)))
#plan
for p in plan:
    if len(p) == 0:
        #print(type(p))
        p.append("Regular")
sc_mf['Plan'] = plan

In [6]:
# Extracting a category from "Scheme Name" column
scheme_name = list(sc_mf['Scheme Name'])
category = []
for i in scheme_name:
    #print(type(i))
    category.append(re.findall("Small Cap Fund", str(i)))
sc_mf['Category'] = category

In [7]:
# Modifiying 'Scheme Name' column
sc_mf['Scheme Name'] = sc_mf['Scheme Name'].str.replace(' - GrowthSmall Cap Fund', '')

In [8]:
#Replacing "']" & "['" string with "" in Plan columns
sc_mf['Plan'] = sc_mf['Plan'].astype(str).str.replace("\['","", regex=True)
sc_mf['Plan'] = sc_mf['Plan'].astype(str).str.replace("']","", regex=True)

#Replacing "']" & "['" string with "" in Category columns
sc_mf['Category'] = sc_mf['Category'].astype(str).str.replace("\['","", regex=True)
sc_mf['Category'] = sc_mf['Category'].astype(str).str.replace("']","", regex=True)

In [9]:
#Replacing "ELSS', 'ELSS" string with "ELSS" in Category columns
sc_mf['Category'] = sc_mf['Category'].astype(str).str.replace("Small Cap Fund', 'Small Cap Fund","Small Cap Fund",
                                                              regex=True)

#Replacing "%" string with "" in Crisil Rank, % Debt Holding, No of instruments in portfolio,
# % MF Holding, % Other Holding, Turnover ratio, MTD, 10Y_SIP_RTN(%) & 5Y_SIP_RTN(%) columns
sc_mf[['% Debt Holding', 'No of instruments in portfolio',
          '% MF Holding', '% Other Holding', 'Turnover ratio(%)',
          'MTD', '10Y_SIP_RTN(%)', '5Y_SIP_RTN(%)'         
         ]] = sc_mf[['% Debt Holding', 'No of instruments in portfolio',
                        '% MF Holding', '% Other Holding', 'Turnover ratio(%)',
                        'MTD', '10Y_SIP_RTN(%)', '5Y_SIP_RTN(%)'
                        ]].replace("%", "", regex=True)

#Replacing "-" string with "0" in Crisil Rank columns
sc_mf['Crisil Rank'] = sc_mf['Crisil Rank'].replace("-", "", regex=True)

In [10]:
#Replacing "-" string with "0" in Crisil Rank columns
sc_mf['Crisil Rank'] = sc_mf['Crisil Rank'].replace("", "0", regex=True)

#Replacing "%" with '' in the column
sc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding', '% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)',
         "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20",
         "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19",
         "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)"
         ]] = sc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)"
                       ]].replace("%", "", regex=True)
print("Shape of the dataframe:", sc_mf.shape)
sc_mf.head()

Shape of the dataframe: (73, 86)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
0,Quant Small Cap,0,170.27,7.58,15.42,36.23,71.98,48.56,205.24,51.09,...,10-May-21,32.866,18-May-20,86.44,124.40,119.33,118.74,-,Regular,Small Cap Fund
1,Sundaram Select Micro Cap - Series XVII - Dire...,0,78.55,3.14,5.20,16.60,52.69,25.08,121.17,19.87,...,10-May-21,58.815,18-May-20,84.75,121.84,116.46,115.24,152.68,Direct,Small Cap Fund
2,Sundaram Select Micro Cap - Series XVII - Regu...,0,78.55,3.13,5.15,16.45,52.28,24.84,119.98,19.23,...,10-May-21,42.497,19-May-20,54.66,70.73,74.69,82.65,-,Regular,Small Cap Fund
3,Sundaram Select Micro Cap - Series XVI - Direc...,0,93.86,3.06,4.70,15.77,51.98,24.28,118.98,20.23,...,10-May-21,40.489,19-May-20,53.28,68.02,70.78,76.02,188.20,Direct,Small Cap Fund
4,Sundaram Select Micro Cap - Series XVI - Regul...,0,93.86,3.05,4.65,15.60,51.54,24.02,117.69,19.53,...,10-May-21,53.644,18-May-20,52.28,55.77,47.15,-,-,Regular,Small Cap Fund

In [11]:
#Sorting a sc_mf dataframe by "Crisil Rank Column"
sc_mf.sort_values(by=['Crisil Rank', 'Scheme Name', 'AuM (Cr)'], inplace=True, ascending=False)
print("Shape of the dataframe:", sc_mf.shape)
sc_mf.head()

Shape of the dataframe: (73, 86)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
53,Kotak Small Cap Fund - Direct Plan,5,3712.14,1.06,2.28,12.70,50.90,28.61,128.07,37.61,...,10-May-21,6.1728,19-May-20,41.45,53.58,53.34,52.19,186.25,Direct,Small Cap Fund
54,Kotak Small Cap Fund,5,3712.14,1.04,2.16,12.30,49.80,27.93,124.78,35.67,...,10-May-21,6.5970,19-May-20,41.36,-,-,-,-,Regular,Small Cap Fund
59,Union Small Cap Fund - Regular Plan,4,445.28,0.80,2.86,13.52,42.85,24.22,96.57,30.56,...,10-May-21,5.5499,19-May-20,38.69,-,-,-,-,Regular,Small Cap Fund
60,Union Small Cap Fund - Direct Plan,4,445.28,0.80,2.92,13.73,43.35,24.56,97.93,31.47,...,10-May-21,5.7162,19-May-20,38.42,48.28,57.59,72.91,-,Direct,Small Cap Fund
43,ICICI Prudential Smallcap Fund - Regular Plan,4,2123.12,1.55,1.90,8.21,42.80,19.83,109.14,25.21,...,10-May-21,8.2163,19-May-20,42.99,45.25,-,-,-,Regular,Small Cap Fund

In [12]:
#Replacing "-" with 'None' in the columns
sc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding', '% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)',
         "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20",
         "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19",
         "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)"
         ]] = sc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)"]].replace({'-' : None})

In [13]:
#Replacing "" with '0' in the columns

sc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding','% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)',
         '10Y_SIP_RTN(%)', "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20",
         "Sep'20", "Aug'20", "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20",
         "Q4'19", "Q3'19", "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)",
         "Standard Deviation", "Beta", "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio", 'Crisil Rank'
         ]] = sc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',\
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)", "Standard Deviation", "Beta",
                       "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio", 'Crisil Rank']].fillna(value='0')

In [14]:
#Changing the datatype of the return & risk ratio columns

sc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding','% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)',
         '10Y_SIP_RTN(%)', "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20",
         "Sep'20", "Aug'20", "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20",
         "Q4'19", "Q3'19", "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)",
         "Standard Deviation", "Beta", "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio"
         ]] = sc_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)", "Standard Deviation", "Beta",
                       "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio"]].apply(pd.to_numeric)

In [15]:
#Changing the datatype of the 'Crisil Rank' columns
sc_mf['Crisil Rank'] = sc_mf['Crisil Rank'].astype('int')

In [16]:
#Removing white spaces at both ends in all over the dataframe:

sc_mf.columns = sc_mf.columns.str.strip()

#Checking the data type of all columns in the DataFrame
sc_mf_dtype = sc_mf.dtypes

df_dtypes = pd.DataFrame(sc_mf_dtype)

In [17]:
#Using pandas dataframe.round()function to round off all the decimal values to 2 decimal places
sc_mf = sc_mf.round(2)

In [18]:
# #Exporting the consolidated elss mf data as a  csv file
# print("Shape of the dataframe:", sc_mf.shape)
sc_mf.to_csv('final_sc_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)',
                 index=False)

# #Exporting the elss mf data columns with its datatype as a  csv file
# df_dtypes.to_csv('sc_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')

In [19]:
#Exctracting regular mutual funds
regular_mf = sc_mf.loc[sc_mf['Plan'] == 'Regular']
regular_mf.head()

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
54,Kotak Small Cap Fund,5,3712.14,1.04,2.16,12.30,49.80,27.93,124.78,35.67,...,10-May-21,6.60,19-May-20,41.36,0.00,0.00,0.00,0.0,Regular,Small Cap Fund
59,Union Small Cap Fund - Regular Plan,4,445.28,0.80,2.86,13.52,42.85,24.22,96.57,30.56,...,10-May-21,5.55,19-May-20,38.69,0.00,0.00,0.00,0.0,Regular,Small Cap Fund
43,ICICI Prudential Smallcap Fund - Regular Plan,4,2123.12,1.55,1.90,8.21,42.80,19.83,109.14,25.21,...,10-May-21,8.22,19-May-20,42.99,45.25,0.00,0.00,0.0,Regular,Small Cap Fund
22,Axis Small Cap Fund,4,4853.73,2.26,3.25,12.34,36.20,19.83,82.20,31.36,...,10-May-21,8.95,19-May-20,46.95,0.00,0.00,0.00,0.0,Regular,Small Cap Fund
56,Nippon India Small Cap Fund,3,13085.04,0.93,4.18,16.24,50.35,27.66,112.35,28.54,...,10-May-21,6.68,19-May-20,39.80,51.03,61.67,79.78,0.0,Regular,Small Cap Fund

In [20]:
# Basic statistics of regular mutual fund df
regular_mf.describe()

,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),...,% Other Holding,NAV,1D Change(%),52W High,52W Low,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
count,38.000000,36.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,...,38.000000,36.000000,38.000000,36.000000,36.000000,38.000000,38.000000,38.000000,38.000000,38.000000
mean,1.026316,1837.541389,1.777895,3.310526,11.873684,40.583158,20.697895,93.987368,19.874211,4.472632,...,0.108684,34.607222,0.657632,34.649444,15.978333,41.569737,43.193947,30.619737,22.111316,20.164211
std,1.568040,3089.681260,1.322228,2.801824,6.099063,14.093053,7.708191,35.124196,11.485818,6.230602,...,0.428941,33.257143,0.473357,33.254551,14.384522,15.222731,25.097798,28.623397,32.167682,54.872788
min,0.000000,26.980000,-0.470000,-1.720000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,11.000000,-0.440000,11.000000,4.790000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,134.225000,0.957500,2.187500,9.697500,38.017500,17.712500,91.555000,16.850000,0.000000,...,0.000000,13.240000,0.432500,13.335000,6.662500,40.190000,44.067500,0.000000,0.000000,0.000000
50%,0.000000,338.660000,1.820000,3.275000,12.025000,44.475000,20.325000,97.285000,18.945000,1.860000,...,0.000000,17.110000,0.495000,17.110000,8.580000,43.710000,48.155000,40.340000,0.000000,0.000000
75%,2.000000,1467.087500,2.350000,4.167500,14.300000,46.710000,24.170000,108.050000,25.945000,6.825000,...,0.000000,49.577500,0.950000,49.577500,25.315000,47.642500,54.862500,46.652500,47.745000,0.000000
max,5.000000,13085.040000,7.580000,15.420000,36.230000,71.980000,48.560000,205.240000,51.090000,27.340000,...,1.900000,125.370000,2.180000,125.370000,53.640000,86.440000,124.400000,119.330000,118.740000,237.360000

In [21]:
# Extracting funds which have 3Y Return', '5Y Return' & '10Y Return' greater than 10%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10) &
                            (regular_mf['10Y_RTN(%)'] > 10)]
print("No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is:", len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV']]

No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is: 3 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV
54,Kotak Small Cap Fund,5,3712.14,124.78,15.81,18.39,17.61,13.29
56,Nippon India Small Cap Fund,3,13085.04,112.35,12.04,19.86,20.58,13.21
0,Quant Small Cap,0,170.27,205.24,27.34,18.09,13.38,104.58

In [22]:
# Extracting  last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'
#greater than 10%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10) &
                            (regular_mf['10Y_RTN(%)'] > 10)]
print("Last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'greater than 10% is:",
      len(mf_rtn_com.index), '\nFunds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

Last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'greater than 10% is: 3
Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
54,Kotak Small Cap Fund,5,3712.14,13.29,17.49,-4.71,-16.74,0.0,0.0
56,Nippon India Small Cap Fund,3,13085.04,13.21,16.30,-3.61,-14.53,0.0,0.0
0,Quant Small Cap,0,170.27,104.58,13.29,0.00,0.00,0.0,0.0

In [23]:
# Extracting funds which have '3Y Return' & '5Y Return' greater than 12%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 12) & (regular_mf['5Y_RTN(%)'] > 12)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 12% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return' & '5Y Return' greater than 12% is: 4 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
54,Kotak Small Cap Fund,5,3712.14,124.78,15.81,18.39,17.61,13.29,0.00,0.0,0.00,0.00
22,Axis Small Cap Fund,4,4853.73,82.20,18.81,18.66,0.00,18.68,0.29,51.0,19.68,0.85
56,Nippon India Small Cap Fund,3,13085.04,112.35,12.04,19.86,20.58,13.21,0.00,47.0,0.00,0.00
0,Quant Small Cap,0,170.27,205.24,27.34,18.09,13.38,104.58,0.09,265.0,19.03,0.75

In [24]:
# Extracting last five years annual return for funds which have 3Y Return', '5Y Return' greater than 12%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 12) & (regular_mf['5Y_RTN(%)'] > 12)]
print("Last five years annual return for funds which have '5Y Return' & '10Y Return'greater than 10% is:",
      len(mf_rtn_com.index), '\nFunds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

Last five years annual return for funds which have '5Y Return' & '10Y Return'greater than 10% is: 4
Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
54,Kotak Small Cap Fund,5,3712.14,13.29,17.49,-4.71,-16.74,0.00,0.00
22,Axis Small Cap Fund,4,4853.73,18.68,26.92,-11.30,-25.20,60.41,0.14
56,Nippon India Small Cap Fund,3,13085.04,13.21,16.30,-3.61,-14.53,0.00,0.00
0,Quant Small Cap,0,170.27,104.58,13.29,0.00,0.00,0.00,0.00

In [25]:
# Extracting funds which have '3Y Return' & '5Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 15) & (regular_mf['5Y_RTN(%)'] > 15)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
            'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return' & '5Y Return' greater than 15% is: 3 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
54,Kotak Small Cap Fund,5,3712.14,124.78,15.81,18.39,17.61,13.29,0.00,0.0,0.00,0.00
22,Axis Small Cap Fund,4,4853.73,82.20,18.81,18.66,0.00,18.68,0.29,51.0,19.68,0.85
0,Quant Small Cap,0,170.27,205.24,27.34,18.09,13.38,104.58,0.09,265.0,19.03,0.75

In [26]:
# Extracting last five years annual return for funds which have 3Y Return', '5Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 15) & (regular_mf['5Y_RTN(%)'] > 15)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

No. of funds having '3Y Return' & '5Y Return' greater than 15% is: 3 Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
54,Kotak Small Cap Fund,5,3712.14,13.29,17.49,-4.71,-16.74,0.00,0.00
22,Axis Small Cap Fund,4,4853.73,18.68,26.92,-11.30,-25.20,60.41,0.14
0,Quant Small Cap,0,170.27,104.58,13.29,0.00,0.00,0.00,0.00

In [27]:
# Extracting funds which have '5Y Return' & '10Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 15) & (regular_mf['10Y_RTN(%)'] > 15)]
print("No. of funds having '5Y Return' & '10Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
            'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '5Y Return' & '10Y Return' greater than 15% is: 2 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
54,Kotak Small Cap Fund,5,3712.14,124.78,15.81,18.39,17.61,13.29,0.0,0.0,0.0,0.0
56,Nippon India Small Cap Fund,3,13085.04,112.35,12.04,19.86,20.58,13.21,0.0,47.0,0.0,0.0

In [28]:
# Extracting last five years annual return for funds which have 5Y Return', '10Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 15) & (regular_mf['10Y_RTN(%)'] > 15)]
print("No. of funds having '5Y Return' & '10Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

No. of funds having '5Y Return' & '10Y Return' greater than 15% is: 2 Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
54,Kotak Small Cap Fund,5,3712.14,13.29,17.49,-4.71,-16.74,0.0,0.0
56,Nippon India Small Cap Fund,3,13085.04,13.21,16.30,-3.61,-14.53,0.0,0.0

## Portfolio Turnover Ratio(PTR)

Portfolio Turnover Ratio is the frequency in which the assets held under a fund has changed over the years. In simpler words, PTR provides a measurement on how many times the fund managers bought or sold the assets under a fund over a period of time. PTR is often determined by the market conditions and fund management style.

Suppose an equity fund purchased stocks worth Rs. 375 crore and sold stocks worth Rs. 450 crore. The average AUM of the fund is Rs.1500 crore. In this case, the Portfolio turnover ratio of the fund is 25%, which means one-fourth of the stocks were traded.

Funds that have higher turnover ratios, for example, can trigger higher costs for investors. First, a fund thatâ€™s actively managed may charge a higher expense ratio to cover the fund managerâ€™s services. The expense ratio represents the percentage you pay to own the fund on an annualized basis. At the low end, you can find index funds with expense ratios around 0.50% to 0.10%. But the most expensive funds can easily have expense ratios over 1%.

Turnover ratio can also give you an idea of what the fundâ€™s investment strategy is, which is important for choosing funds that align with your goals and objectives. A growth mutual fund, for instance, may have a higher turnover ratio if the fund manager is constantly looking for the best growth stocks to drive returns. But a fund that uses a value investing approach may have a lower turnover ratio if the fund manager is buying assets that have the potential to appreciate over time.

In [29]:
# Top 10 low turnover ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Turnover ratio(%)'] > 0)]
print("Top 10 low turnover ratio regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Turnover ratio(%)']].nsmallest(10, 'Turnover ratio(%)')

Top 10 low turnover ratio regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Turnover ratio(%)
70,HSBC Small Cap Equity Fund,3,313.63,97.22,2.52,11.15,12.68,71.21,22.43
71,NaN,0,NaN,0.00,0.00,0.00,0.00,NaN,22.43
44,BOI AXA Small Cap Fund - Regular Plan,0,129.80,107.15,0.00,0.00,0.00,16.37,31.00
26,Principal Small Cap Fund - Regular Plan,0,346.26,105.54,0.00,0.00,0.00,17.81,32.00
38,ITI Small Cap Fund - Regular Plan,0,331.06,90.17,0.00,0.00,0.00,15.81,39.00
28,Aditya Birla Sun Life Small cap Fund - Regular...,2,2549.64,108.35,2.49,11.95,14.62,47.07,44.00
50,L&T Emerging Businesses Fund - Regular Plan,1,6057.56,106.75,5.84,17.89,0.00,13.09,44.00
52,Franklin India Smaller Companies Fund,3,6234.39,95.90,4.66,11.46,17.31,13.52,46.00
59,Union Small Cap Fund - Regular Plan,4,445.28,96.57,11.80,14.14,0.00,11.22,47.00
56,Nippon India Small Cap Fund,3,13085.04,112.35,12.04,19.86,20.58,13.21,47.00

In [30]:
# Top 10 high turnover ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Turnover ratio(%)'] > 0)]
print("Top 10 high turnover ratio regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Turnover ratio(%)']].nlargest(10, 'Turnover ratio(%)')

Top 10 high turnover ratio regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Turnover ratio(%)
0,Quant Small Cap,0,170.27,205.24,27.34,18.09,13.38,104.58,265.0
21,Sundaram Emerging Small Cap - Series 3,0,188.87,97.35,0.00,0.00,0.00,19.35,69.0
36,Tata Small Cap Fund - Regular Plan,0,1003.54,99.40,0.00,0.00,0.00,11.23,60.0
6,Sundaram Emerging Small Cap - Series 7,0,98.13,79.67,0.00,0.00,0.00,114.61,56.0
22,Axis Small Cap Fund,4,4853.73,82.20,18.81,18.66,0.00,18.68,51.0
32,Sundaram Emerging Small Cap - Series 1,0,197.19,94.37,3.61,0.00,0.00,11.47,51.0
34,Sundaram Emerging Small Cap - Series 2,0,213.89,93.69,4.79,0.00,0.00,11.00,50.0
25,Sundaram Emerging Small Cap - Series 4,0,135.70,93.23,0.00,0.00,0.00,17.40,48.0
59,Union Small Cap Fund - Regular Plan,4,445.28,96.57,11.80,14.14,0.00,11.22,47.0
56,Nippon India Small Cap Fund,3,13085.04,112.35,12.04,19.86,20.58,13.21,47.0

## Standard Deviation (SD)

The standard deviation of a stock or a mutual fund represents the riskiness of the stock or the mutual fund.

Standard Deviation is a percentage, expressed as an annualised figure.

Higher the standard Deviation, higher is the volatility of the asset. Higher the volatility, higher is the risk.

Do note, volatility or Standard Deviation should not worry you. Markets are volatile, and equities are volatile, mutual funds are volatile; this is the very nature of markets. So if you canâ€™t fathom watching your investment see-saw between gains and loss, then perhaps you should reconsider your investment decision inequities.

In [31]:
# Top 10 low standard deviation regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Standard Deviation'] > 0)]
print("Top 10 low standard deviation regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Standard Deviation']].nsmallest(10, 'Standard Deviation')

Top 10 low standard deviation regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Standard Deviation
12,Edelweiss Small Cap Fund - Regular Plan,0,780.11,101.92,0.00,0.00,0.00,45.34,17.24
2,Sundaram Select Micro Cap - Series XVII - Regu...,0,78.55,119.98,1.84,0.00,0.00,89.91,18.18
26,Principal Small Cap Fund - Regular Plan,0,346.26,105.54,0.00,0.00,0.00,17.81,18.24
9,Canara Robeco Small Cap Fund - Regular Plan,0,950.39,109.64,0.00,0.00,0.00,69.16,18.71
0,Quant Small Cap,0,170.27,205.24,27.34,18.09,13.38,104.58,19.03
25,Sundaram Emerging Small Cap - Series 4,0,135.70,93.23,0.00,0.00,0.00,17.40,19.29
22,Axis Small Cap Fund,4,4853.73,82.20,18.81,18.66,0.00,18.68,19.68
21,Sundaram Emerging Small Cap - Series 3,0,188.87,97.35,0.00,0.00,0.00,19.35,20.25
4,Sundaram Select Micro Cap - Series XVI - Regul...,0,93.86,117.69,1.87,0.00,0.00,125.37,20.36
28,Aditya Birla Sun Life Small cap Fund - Regular...,2,2549.64,108.35,2.49,11.95,14.62,47.07,20.38

In [32]:
# Top 10 high standard deviation regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Standard Deviation'] > 0)]
print("Top 10 high standard deviation regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Standard Deviation']].nlargest(10, 'Standard Deviation')

Top 10 high standard deviation regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Standard Deviation
6,Sundaram Emerging Small Cap - Series 7,0,98.13,79.67,0.00,0.00,0.00,114.61,21.29
16,Sundaram Emerging Small Cap - Series 6,0,26.98,94.74,0.00,0.00,0.00,69.79,21.06
8,Sundaram Select Micro Cap - Series XIV - Regul...,0,148.51,112.43,1.85,0.00,0.00,57.10,20.83
18,Sundaram Emerging Small Cap - Series 5,0,50.58,93.30,0.00,0.00,0.00,17.05,20.76
14,Sundaram Select Micro Cap - Series XV - Regula...,0,142.74,109.64,0.65,0.00,0.00,76.26,20.65
28,Aditya Birla Sun Life Small cap Fund - Regular...,2,2549.64,108.35,2.49,11.95,14.62,47.07,20.38
4,Sundaram Select Micro Cap - Series XVI - Regul...,0,93.86,117.69,1.87,0.00,0.00,125.37,20.36
21,Sundaram Emerging Small Cap - Series 3,0,188.87,97.35,0.00,0.00,0.00,19.35,20.25
22,Axis Small Cap Fund,4,4853.73,82.20,18.81,18.66,0.00,18.68,19.68
25,Sundaram Emerging Small Cap - Series 4,0,135.70,93.23,0.00,0.00,0.00,17.40,19.29

## Beta Ratios

A Beta Ratio in Mutual Funds offers investors the data on the degree of the volatility a Mutual Fund displays in response to market fluctuations. An investor can determine which fund would be best suited to meet his/her financial objectives.

Suppose, the beta ratio of a specific Mutual Fund is 0.7 or 70%; it means the fund is 0.3 or 30% less volatile than the benchmark index. A Beta ratio value of 1 indicates a lower risk and lower growth potential compared to ratios at par or above 1.

Investors with a low-risk appetite would always prefer a lower beta ratio in Mutual Funds as it indicates a steadier response to a volatile market condition. Similarly, investors with the investment objective of higher returns would prefer beta ratios of 1 or more than 1.

In [33]:
# Top 10 low beta regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 0)]
print("Top 10 low beta regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']].nsmallest(10, 'Beta')

Top 10 low beta regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
28,Aditya Birla Sun Life Small cap Fund - Regular...,2,2549.64,108.35,2.49,11.95,14.62,47.07,0.61
12,Edelweiss Small Cap Fund - Regular Plan,0,780.11,101.92,0.00,0.00,0.00,45.34,0.64
2,Sundaram Select Micro Cap - Series XVII - Regu...,0,78.55,119.98,1.84,0.00,0.00,89.91,0.72
0,Quant Small Cap,0,170.27,205.24,27.34,18.09,13.38,104.58,0.75
26,Principal Small Cap Fund - Regular Plan,0,346.26,105.54,0.00,0.00,0.00,17.81,0.77
4,Sundaram Select Micro Cap - Series XVI - Regul...,0,93.86,117.69,1.87,0.00,0.00,125.37,0.82
9,Canara Robeco Small Cap Fund - Regular Plan,0,950.39,109.64,0.00,0.00,0.00,69.16,0.82
25,Sundaram Emerging Small Cap - Series 4,0,135.70,93.23,0.00,0.00,0.00,17.40,0.83
22,Axis Small Cap Fund,4,4853.73,82.20,18.81,18.66,0.00,18.68,0.85
6,Sundaram Emerging Small Cap - Series 7,0,98.13,79.67,0.00,0.00,0.00,114.61,0.86

In [34]:
# Top 10 high beta regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 0)]
print("Top 10 high beta regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']].nlargest(10, 'Beta')

Top 10 high beta regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
14,Sundaram Select Micro Cap - Series XV - Regula...,0,142.74,109.64,0.65,0.00,0.0,76.26,0.95
16,Sundaram Emerging Small Cap - Series 6,0,26.98,94.74,0.00,0.00,0.0,69.79,0.95
18,Sundaram Emerging Small Cap - Series 5,0,50.58,93.30,0.00,0.00,0.0,17.05,0.95
8,Sundaram Select Micro Cap - Series XIV - Regul...,0,148.51,112.43,1.85,0.00,0.0,57.10,0.89
21,Sundaram Emerging Small Cap - Series 3,0,188.87,97.35,0.00,0.00,0.0,19.35,0.89
6,Sundaram Emerging Small Cap - Series 7,0,98.13,79.67,0.00,0.00,0.0,114.61,0.86
22,Axis Small Cap Fund,4,4853.73,82.20,18.81,18.66,0.0,18.68,0.85
25,Sundaram Emerging Small Cap - Series 4,0,135.70,93.23,0.00,0.00,0.0,17.40,0.83
4,Sundaram Select Micro Cap - Series XVI - Regul...,0,93.86,117.69,1.87,0.00,0.0,125.37,0.82
9,Canara Robeco Small Cap Fund - Regular Plan,0,950.39,109.64,0.00,0.00,0.0,69.16,0.82

In [35]:
# Funds with 'Beta' lesser than 1.00
mf_tr = regular_mf.loc[(regular_mf['Beta'] < 1.00) & (regular_mf['Beta'] != 0.00)]
print("Funds with 'Beta' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']]

Funds with 'Beta' lesser than 1.00 are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
22,Axis Small Cap Fund,4,4853.73,82.20,18.81,18.66,0.00,18.68,0.85
28,Aditya Birla Sun Life Small cap Fund - Regular...,2,2549.64,108.35,2.49,11.95,14.62,47.07,0.61
2,Sundaram Select Micro Cap - Series XVII - Regu...,0,78.55,119.98,1.84,0.00,0.00,89.91,0.72
4,Sundaram Select Micro Cap - Series XVI - Regul...,0,93.86,117.69,1.87,0.00,0.00,125.37,0.82
14,Sundaram Select Micro Cap - Series XV - Regula...,0,142.74,109.64,0.65,0.00,0.00,76.26,0.95
8,Sundaram Select Micro Cap - Series XIV - Regul...,0,148.51,112.43,1.85,0.00,0.00,57.10,0.89
6,Sundaram Emerging Small Cap - Series 7,0,98.13,79.67,0.00,0.00,0.00,114.61,0.86
16,Sundaram Emerging Small Cap - Series 6,0,26.98,94.74,0.00,0.00,0.00,69.79,0.95
18,Sundaram Emerging Small Cap - Series 5,0,50.58,93.30,0.00,0.00,0.00,17.05,0.95
25,Sundaram Emerging Small Cap - Series 4,0,135.70,93.23,0.00,0.00,0.00,17.40,0.83
21,Sundaram Emerging Small Cap - Series 3,0,188.87,97.35,0.00,0.00,0.00,19.35,0.89
0,Quant Small Cap,0,170.27,205.24,27.34,18.09,13.38,104.58,0.75
26,Principal Small Cap Fund - Regular Plan,0,346.26,105.54,0.00,0.00,0.00,17.81,0.77
12,Edelweiss Small Cap Fund - Regular Plan,0,780.11,101.92,0.00,0.00,0.00,45.34,0.64
9,Canara Robeco Small Cap Fund - Regular Plan,0,950.39,109.64,0.00,0.00,0.00,69.16,0.82

In [36]:
# Funds with 'Beta' greater than 1.00
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 1.00) & (regular_mf['Beta'] != 0.00)]
print("Funds with 'Beta' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']]

Funds with 'Beta' lesser than 1.00 are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Beta]
Index: []

## What is Sharpe Ratio?

Sharpe Ratio of a mutual fund reveals its potential risk-adjusted returns. The risk-adjusted returns are the returns earned by an investment over the returns generated by any risk-free asset such as a fixed deposit. However, higher returns indicate extra risk. Higher Sharpe Ratio means greater returns from an investment but with a higher risk level. Therefore, it justifies the underlying volatility of the funds. The investors aiming for higher returns will have to invest in funds with higher risk factors.

Investments with less than 1.00 Sharpe Ratio do not generate high returns. Contrarily, investment with Sharpe Ratio of 1.00 to 3.00 or above have higher returns subsequently.

In [37]:
# Top 10 low sharpe ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 0)]
print("Top 10 low 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']].nsmallest(10, 'Sharpe Ratio')

Top 10 low 'Sharpe Ratio' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
21,Sundaram Emerging Small Cap - Series 3,0,188.87,97.35,0.00,0.00,0.00,19.35,0.09
0,Quant Small Cap,0,170.27,205.24,27.34,18.09,13.38,104.58,0.09
9,Canara Robeco Small Cap Fund - Regular Plan,0,950.39,109.64,0.00,0.00,0.00,69.16,0.20
16,Sundaram Emerging Small Cap - Series 6,0,26.98,94.74,0.00,0.00,0.00,69.79,0.27
22,Axis Small Cap Fund,4,4853.73,82.20,18.81,18.66,0.00,18.68,0.29
4,Sundaram Select Micro Cap - Series XVI - Regul...,0,93.86,117.69,1.87,0.00,0.00,125.37,0.40
2,Sundaram Select Micro Cap - Series XVII - Regu...,0,78.55,119.98,1.84,0.00,0.00,89.91,0.63
25,Sundaram Emerging Small Cap - Series 4,0,135.70,93.23,0.00,0.00,0.00,17.40,0.66
26,Principal Small Cap Fund - Regular Plan,0,346.26,105.54,0.00,0.00,0.00,17.81,0.77
12,Edelweiss Small Cap Fund - Regular Plan,0,780.11,101.92,0.00,0.00,0.00,45.34,0.80

In [38]:
# Top 10 high sharpe ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 0)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']].nlargest(10, 'Sharpe Ratio')

Top 10 high 'Sharpe Ratio' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
28,Aditya Birla Sun Life Small cap Fund - Regular...,2,2549.64,108.35,2.49,11.95,14.62,47.07,0.97
12,Edelweiss Small Cap Fund - Regular Plan,0,780.11,101.92,0.00,0.00,0.00,45.34,0.80
26,Principal Small Cap Fund - Regular Plan,0,346.26,105.54,0.00,0.00,0.00,17.81,0.77
25,Sundaram Emerging Small Cap - Series 4,0,135.70,93.23,0.00,0.00,0.00,17.40,0.66
2,Sundaram Select Micro Cap - Series XVII - Regu...,0,78.55,119.98,1.84,0.00,0.00,89.91,0.63
4,Sundaram Select Micro Cap - Series XVI - Regul...,0,93.86,117.69,1.87,0.00,0.00,125.37,0.40
22,Axis Small Cap Fund,4,4853.73,82.20,18.81,18.66,0.00,18.68,0.29
16,Sundaram Emerging Small Cap - Series 6,0,26.98,94.74,0.00,0.00,0.00,69.79,0.27
9,Canara Robeco Small Cap Fund - Regular Plan,0,950.39,109.64,0.00,0.00,0.00,69.16,0.20
21,Sundaram Emerging Small Cap - Series 3,0,188.87,97.35,0.00,0.00,0.00,19.35,0.09

In [39]:
# Funds with 'Sharpe Ratio' greater than or equal to 3.00
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] >= 3.00)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [40]:
# Funds with 'Sharpe Ratio' greater than to 2.00 & lesser than 2.99
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 2.00) & (regular_mf['Sharpe Ratio'] < 2.99)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [41]:
# Funds with 'Sharpe Ratio' greater than to 1.00 & lesser than 1.99
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 1.00) & (regular_mf['Sharpe Ratio'] < 1.99)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [42]:
# Funds with 'Sharpe Ratio' lesser than 1.00
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] != 0.00) & (regular_mf['Sharpe Ratio'] < 1.00)]
print("Funds with 'Sharpe Ratio' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Funds with 'Sharpe Ratio' lesser than 1.00 are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
22,Axis Small Cap Fund,4,4853.73,82.20,18.81,18.66,0.00,18.68,0.29
28,Aditya Birla Sun Life Small cap Fund - Regular...,2,2549.64,108.35,2.49,11.95,14.62,47.07,0.97
2,Sundaram Select Micro Cap - Series XVII - Regu...,0,78.55,119.98,1.84,0.00,0.00,89.91,0.63
4,Sundaram Select Micro Cap - Series XVI - Regul...,0,93.86,117.69,1.87,0.00,0.00,125.37,0.40
14,Sundaram Select Micro Cap - Series XV - Regula...,0,142.74,109.64,0.65,0.00,0.00,76.26,-0.09
8,Sundaram Select Micro Cap - Series XIV - Regul...,0,148.51,112.43,1.85,0.00,0.00,57.10,-0.01
16,Sundaram Emerging Small Cap - Series 6,0,26.98,94.74,0.00,0.00,0.00,69.79,0.27
18,Sundaram Emerging Small Cap - Series 5,0,50.58,93.30,0.00,0.00,0.00,17.05,-0.09
25,Sundaram Emerging Small Cap - Series 4,0,135.70,93.23,0.00,0.00,0.00,17.40,0.66
21,Sundaram Emerging Small Cap - Series 3,0,188.87,97.35,0.00,0.00,0.00,19.35,0.09
0,Quant Small Cap,0,170.27,205.24,27.34,18.09,13.38,104.58,0.09
26,Principal Small Cap Fund - Regular Plan,0,346.26,105.54,0.00,0.00,0.00,17.81,0.77
12,Edelweiss Small Cap Fund - Regular Plan,0,780.11,101.92,0.00,0.00,0.00,45.34,0.80
9,Canara Robeco Small Cap Fund - Regular Plan,0,950.39,109.64,0.00,0.00,0.00,69.16,0.20

In [43]:
# Extracting funds which have 3Y Return', '5Y Return' & '10Y Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_SIP_RTN(%)'] > 25) & (regular_mf['5Y_SIP_RTN(%)'] > 25) &
                            (regular_mf['10Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '3Y SIP Return', '5Y SIP Return' & '10Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y SIP Return', '5Y SIP Return' & '10Y SIP Return' greater than 25% is: 5 Funds

,Scheme Name,Crisil Rank,AuM (Cr),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
52,Franklin India Smaller Companies Fund,3,6234.39,38.66,37.56,146.97,13.52,0.00,46.0,0.00,0.00
58,Sundaram Small Cap Fund,2,1248.41,40.66,37.58,117.03,11.49,0.00,47.0,0.00,0.00
28,Aditya Birla Sun Life Small cap Fund - Regular...,2,2549.64,43.19,52.12,140.86,47.07,0.97,44.0,20.38,0.61
32,Sundaram Emerging Small Cap - Series 1,0,197.19,45.88,39.93,124.02,11.47,0.00,51.0,0.00,0.00
9,Canara Robeco Small Cap Fund - Regular Plan,0,950.39,59.98,69.48,237.36,69.16,0.20,0.0,18.71,0.82

In [44]:
# Extracting funds which have 3Y Return' & '5Y Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_SIP_RTN(%)'] > 25) & (regular_mf['5Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '3Y SIP Return' & '5Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y SIP Return' & '5Y SIP Return' greater than 25% is: 14 Funds

,Scheme Name,Crisil Rank,AuM (Cr),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
56,Nippon India Small Cap Fund,3,13085.04,61.67,79.78,0.00,13.21,0.00,47.0,0.00,0.00
52,Franklin India Smaller Companies Fund,3,6234.39,38.66,37.56,146.97,13.52,0.00,46.0,0.00,0.00
48,DSP Small Cap Fund - Regular Plan,3,6688.88,40.56,41.10,0.00,13.48,0.00,47.0,0.00,0.00
58,Sundaram Small Cap Fund,2,1248.41,40.66,37.58,117.03,11.49,0.00,47.0,0.00,0.00
28,Aditya Birla Sun Life Small cap Fund - Regular...,2,2549.64,43.19,52.12,140.86,47.07,0.97,44.0,20.38,0.61
50,L&T Emerging Businesses Fund - Regular Plan,1,6057.56,55.47,55.23,0.00,13.09,0.00,44.0,0.00,0.00
36,Tata Small Cap Fund - Regular Plan,0,1003.54,59.81,62.47,0.00,11.23,0.00,60.0,0.00,0.00
2,Sundaram Select Micro Cap - Series XVII - Regu...,0,78.55,74.69,82.65,0.00,89.91,0.63,0.0,18.18,0.72
14,Sundaram Select Micro Cap - Series XV - Regula...,0,142.74,44.59,49.96,0.00,76.26,-0.09,0.0,20.65,0.95
32,Sundaram Emerging Small Cap - Series 1,0,197.19,45.88,39.93,124.02,11.47,0.00,51.0,0.00,0.00
0,Quant Small Cap,0,170.27,119.33,118.74,0.00,104.58,0.09,265.0,19.03,0.75
40,IDFC Emerging Businesses Fund - Regular Plan,0,998.96,58.08,59.49,0.00,22.67,0.00,0.0,0.00,0.00
12,Edelweiss Small Cap Fund - Regular Plan,0,780.11,47.02,54.14,0.00,45.34,0.80,0.0,17.24,0.64
9,Canara Robeco Small Cap Fund - Regular Plan,0,950.39,59.98,69.48,237.36,69.16,0.20,0.0,18.71,0.82

In [45]:
# Extracting funds which have '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['1Y_SIP_RTN(%)'] > 25) & (regular_mf['2Y_SIP_RTN(%)'] > 25) &
                            (regular_mf['3Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25% is: 23 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
56,Nippon India Small Cap Fund,3,13085.04,39.80,51.03,61.67,13.21,0.00,47.0,0.00,0.00
67,IDBI Small Cap Fund,3,115.06,27.34,31.78,34.74,13.25,0.00,0.0,0.00,0.00
52,Franklin India Smaller Companies Fund,3,6234.39,41.84,43.75,38.66,13.52,0.00,46.0,0.00,0.00
48,DSP Small Cap Fund - Regular Plan,3,6688.88,42.55,45.06,40.56,13.48,0.00,47.0,0.00,0.00
58,Sundaram Small Cap Fund,2,1248.41,39.00,45.75,40.66,11.49,0.00,47.0,0.00,0.00
28,Aditya Birla Sun Life Small cap Fund - Regular...,2,2549.64,45.73,48.87,43.19,47.07,0.97,44.0,20.38,0.61
50,L&T Emerging Businesses Fund - Regular Plan,1,6057.56,42.22,55.10,55.47,13.09,0.00,44.0,0.00,0.00
36,Tata Small Cap Fund - Regular Plan,0,1003.54,43.96,58.31,59.81,11.23,0.00,60.0,0.00,0.00
2,Sundaram Select Micro Cap - Series XVII - Regu...,0,78.55,54.66,70.73,74.69,89.91,0.63,0.0,18.18,0.72
4,Sundaram Select Micro Cap - Series XVI - Regul...,0,93.86,52.28,55.77,47.15,125.37,0.40,0.0,20.36,0.82
14,Sundaram Select Micro Cap - Series XV - Regula...,0,142.74,48.38,50.79,44.59,76.26,-0.09,0.0,20.65,0.95
8,Sundaram Select Micro Cap - Series XIV - Regul...,0,148.51,50.85,54.15,45.62,57.10,-0.01,0.0,20.83,0.89
6,Sundaram Emerging Small Cap - Series 7,0,98.13,51.38,55.13,46.91,114.61,-0.00,56.0,21.29,0.86
18,Sundaram Emerging Small Cap - Series 5,0,50.58,47.86,51.12,43.50,17.05,-0.09,0.0,20.76,0.95
25,Sundaram Emerging Small Cap - Series 4,0,135.70,46.42,48.62,40.12,17.40,0.66,48.0,19.29,0.83
21,Sundaram Emerging Small Cap - Series 3,0,188.87,46.99,49.66,41.54,19.35,0.09,69.0,20.25,0.89
32,Sundaram Emerging Small Cap - Series 1,0,197.19,44.97,50.50,45.88,11.47,0.00,51.0,0.00,0.00
0,Quant Small Cap,0,170.27,86.44,124.40,119.33,104.58,0.09,265.0,19.03,0.75
68,Invesco India Smallcap Fund,0,882.37,27.03,31.01,33.49,12.89,0.00,0.0,0.00,0.00
40,IDFC Emerging Businesses Fund - Regular Plan,0,998.96,43.35,57.06,58.08,22.67,0.00,0.0,0.00,0.00
12,Edelweiss Small Cap Fund - Regular Plan,0,780.11,49.32,52.55,47.02,45.34,0.80,0.0,17.24,0.64
9,Canara Robeco Small Cap Fund - Regular Plan,0,950.39,50.08,61.61,59.98,69.16,0.20,0.0,18.71,0.82
44,BOI AXA Small Cap Fund - Regular Plan,0,129.80,42.89,45.02,40.89,16.37,0.00,31.0,0.00,0.00

In [46]:
# Top 10 high AuM (Cr) regular mutual funds are
#mf_tr = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 0)]
print("Top 10 high 'AuM (Cr)' regular mutual funds are :")
mf_tr =  mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)',
       'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']].nlargest(10, 'AuM (Cr)')
mf_tr

Top 10 high 'AuM (Cr)' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
22,Axis Small Cap Fund,4,4853.73,82.20,18.81,18.66,0.00,0.29,51.0,19.68,0.85
28,Aditya Birla Sun Life Small cap Fund - Regular...,2,2549.64,108.35,2.49,11.95,14.62,0.97,44.0,20.38,0.61
9,Canara Robeco Small Cap Fund - Regular Plan,0,950.39,109.64,0.00,0.00,0.00,0.20,0.0,18.71,0.82
12,Edelweiss Small Cap Fund - Regular Plan,0,780.11,101.92,0.00,0.00,0.00,0.80,0.0,17.24,0.64
26,Principal Small Cap Fund - Regular Plan,0,346.26,105.54,0.00,0.00,0.00,0.77,32.0,18.24,0.77
21,Sundaram Emerging Small Cap - Series 3,0,188.87,97.35,0.00,0.00,0.00,0.09,69.0,20.25,0.89
0,Quant Small Cap,0,170.27,205.24,27.34,18.09,13.38,0.09,265.0,19.03,0.75
8,Sundaram Select Micro Cap - Series XIV - Regul...,0,148.51,112.43,1.85,0.00,0.00,-0.01,0.0,20.83,0.89
14,Sundaram Select Micro Cap - Series XV - Regula...,0,142.74,109.64,0.65,0.00,0.00,-0.09,0.0,20.65,0.95
25,Sundaram Emerging Small Cap - Series 4,0,135.70,93.23,0.00,0.00,0.00,0.66,48.0,19.29,0.83

In [47]:
# Top 10 low AuM (Cr) regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 0)]
print("Top 10 low 'AuM (Cr)' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)',
       'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']].nsmallest(10, 'AuM (Cr)')

Top 10 low 'AuM (Cr)' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
0,Quant Small Cap,0,170.27,205.24,27.34,18.09,13.38,0.09,265.00,19.03,0.75
70,HSBC Small Cap Equity Fund,3,313.63,97.22,2.52,11.15,12.68,0.00,22.43,0.00,0.00
59,Union Small Cap Fund - Regular Plan,4,445.28,96.57,11.80,14.14,0.00,0.00,47.00,0.00,0.00
58,Sundaram Small Cap Fund,2,1248.41,106.78,3.57,10.95,13.99,0.00,47.00,0.00,0.00
43,ICICI Prudential Smallcap Fund - Regular Plan,4,2123.12,109.14,9.97,14.86,13.53,0.00,0.00,0.00,0.00
28,Aditya Birla Sun Life Small cap Fund - Regular...,2,2549.64,108.35,2.49,11.95,14.62,0.97,44.00,20.38,0.61
54,Kotak Small Cap Fund,5,3712.14,124.78,15.81,18.39,17.61,0.00,0.00,0.00,0.00
22,Axis Small Cap Fund,4,4853.73,82.20,18.81,18.66,0.00,0.29,51.00,19.68,0.85
50,L&T Emerging Businesses Fund - Regular Plan,1,6057.56,106.75,5.84,17.89,0.00,0.00,44.00,0.00,0.00
52,Franklin India Smaller Companies Fund,3,6234.39,95.90,4.66,11.46,17.31,0.00,46.00,0.00,0.00

In [48]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 0) & (regular_mf['AuM (Cr)'] < 500) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds returns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds returns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs is: 2 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
59,Union Small Cap Fund - Regular Plan,4,445.28,96.57,11.80,14.14,0.00,11.22,0.00,47.0,0.00,0.00
0,Quant Small Cap,0,170.27,205.24,27.34,18.09,13.38,104.58,0.09,265.0,19.03,0.75

In [49]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 500Crs to 1000Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 500) & (regular_mf['AuM (Cr)'] < 1000) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is:", len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is: 0 Funds

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio, Turnover ratio(%), Standard Deviation, Beta]
Index: []

In [50]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 1000) & (regular_mf['AuM (Cr)'] < 1500) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs is: 0 Funds

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio, Turnover ratio(%), Standard Deviation, Beta]
Index: []

In [51]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 1500 to 20000Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 1500) & (regular_mf['AuM (Cr)'] < 20000) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds returns 10% in 3year & 5year period which have AuM in between 1500Crs to 20000Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds returns 10% in 3year & 5year period which have AuM in between 1500Crs to 20000Crs is: 3 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
54,Kotak Small Cap Fund,5,3712.14,124.78,15.81,18.39,17.61,13.29,0.00,0.0,0.00,0.00
22,Axis Small Cap Fund,4,4853.73,82.20,18.81,18.66,0.00,18.68,0.29,51.0,19.68,0.85
56,Nippon India Small Cap Fund,3,13085.04,112.35,12.04,19.86,20.58,13.21,0.00,47.0,0.00,0.00