In [1]:
# Importing respective modules
import pandas as pd

## Value Fund

These mutual funds invest in stocks which are undervalued. The underlying assumption is, stocks may be undervalued due to temporary factors and will provide higher returns compared to peers once valuation is at par.

## Exctracting Value Mutual Fund's Historical Investment Returns Data

Data in this table: Get Absolute historical returns for ₹1000 investment. If 1Y column value is 1234.5 that means, your ₹1000 investment 1 year back would have grown to ₹1234.5.

In [2]:
value_lump_sum_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/returns/value-fund.html")
df1 = pd.DataFrame(value_lump_sum_rtn[0])

In [3]:
#Renaming historical returns column names
df1.rename({'1W': '1W_RTN(%)', '1M': '1M_RTN(%)', '3M': '3M_RTN(%)', '6M': '6M_RTN(%)',
                 'YTD': 'YTD_RTN(%)', '1Y': '1Y_RTN(%)', '2Y': '2Y_RTN(%)', '3Y': '3Y_RTN(%)',
                 '5Y': '5Y_RTN(%)', '10Y': '10Y_RTN(%)'
          }, axis=1, inplace=True)
print("Shape of the dataframe:", df1.shape)
df1.head()

Shape of the dataframe: (50, 13)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%)
0,ICICI Prudential Value Fund - Series 19 - Dire...,-,2433.13,1.48%,9.18%,12.33%,46.69%,8.44%,75.70%,17.83%,13.57%,-,-
1,ICICI Prudential Value Fund - Series 19 - Grow...,-,2433.13,1.46%,9.09%,12.17%,46.37%,8.41%,74.66%,17.14%,12.51%,-,-
2,Sundaram Value Fund - Series VII - Direct Plan...,-,34.40,1.26%,11.20%,13.25%,54.95%,11.06%,124.17%,21.70%,7.36%,-,-
3,Sundaram Value Fund - Series VII - Regular Pla...,-,34.40,1.25%,11.15%,13.10%,54.55%,10.99%,122.99%,21.06%,6.67%,-,-
4,Templeton India Value Fund - Direct - GrowthVa...,3,498.92,0.75%,3.74%,0.47%,34.17%,1.72%,87.96%,16.13%,7.13%,13.07%,-

## Exctracting Value Mutual Fund's Monthly Returns Data

Data in this table: Get monthly returns. If Jan month column value is 5.4% that means, fund has given 5.4% returns in Jan month.

In [4]:
value_monthly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/monthly-returns/value-fund.html")
df2 = pd.DataFrame(value_monthly_rtn[0])

In [5]:
#Renaming df1 column names
df1.rename({"Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            'MTD': 'MTD_RTN(%)', "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)"
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df2.shape)
df2.head()

Shape of the dataframe: (50, 14)

,Scheme Name,Crisil Rank,MTD,Apr'21,Mar'21,Feb'21,Jan'21,Dec'20,Nov'20,Oct'20,Sep'20,Aug'20,Jul'20,Jun'20
0,DSP Value Fund - GrowthValue Fund,-,1.39%,3.54%,1.41%,2.67%,0.39%,0.63%,-,-,-,-,-,-
1,DSP Value Fund - Direct Plan - GrowthValue Fund,-,1.41%,3.60%,1.47%,2.73%,0.45%,0.60%,-,-,-,-,-,-
2,Quantum Long Term Equity Value Fund - Direct P...,2,2.43%,-0.89%,-0.04%,2.67%,0.49%,4.21%,13.04%,2.43%,-0.73%,3.17%,6.86%,3.98%
3,Quantum Long Term Equity Value Fund - GrowthVa...,3,2.42%,-0.93%,-0.09%,2.64%,0.45%,4.18%,12.97%,2.42%,-0.76%,3.12%,6.82%,3.95%
4,Templeton India Value Fund - GrowthValue Fund,3,3.47%,-2.13%,-2.80%,8.07%,3.34%,5.02%,16.57%,1.58%,-4.31%,7.44%,4.31%,4.72%

## Exctracting Value Mutual Fund's Quarterly Returns Data

Data in this table: Get quarterly returns. If Q1 column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Mar.

In [6]:
value_quarterly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/quarterly-returns/value-fund.html")
df3 = pd.DataFrame(value_quarterly_rtn[0])

In [7]:
print("Shape of the dataframe:", df3.shape)
df3.head()

Shape of the dataframe: (50, 14)

,Scheme Name,Crisil Rank,QTD,Q1'21,Q4'20,Q3'20,Q2'20,Q1'20,Q4'19,Q3'19,Q2'19,Q1'19,Q4'18,Q3'18
0,IDFC Sterling Value Fund - Regular Plan - Grow...,5,4.99%,16.80%,21.79%,17.39%,29.01%,-37.30%,5.36%,-9.34%,-3.51%,2.52%,3.09%,-7.30%
1,IDFC Sterling Value Fund - Direct Plan - Growt...,5,5.13%,17.10%,22.12%,17.72%,29.36%,-37.16%,5.63%,-9.09%,-3.21%,2.83%,3.34%,-7.07%
2,Aditya Birla Sun Life Pure Value Fund - Regula...,1,6.30%,9.66%,18.66%,13.59%,22.80%,-30.63%,3.06%,-8.30%,-4.33%,0.54%,-0.01%,-6.71%
3,Aditya Birla Sun Life Pure Value Fund - Direct...,1,6.42%,9.88%,18.98%,13.92%,23.15%,-30.48%,3.36%,-8.03%,-4.04%,0.85%,0.25%,-6.44%
4,L&T India Value Fund - Direct Plan - GrowthVal...,3,1.18%,9.91%,17.99%,13.21%,27.79%,-31.44%,7.05%,-5.26%,0.11%,4.46%,-0.16%,-0.75%

## Exctracting Value Mutual Fund's Annual Investment Returns Data

Data in this table: Get annual returns. If 2018 year column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Dec/Last date.

In [8]:
value_annual_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/annual-returns/value-fund.html")
df4 = pd.DataFrame(value_annual_rtn[0])

In [9]:
#Renaming yearly returns column names
df4.rename({'2020': '2020_RTN(%)', '2019': '2019_RTN(%)', '2018': '2018_RTN(%)', '2017': '2017_RTN(%)',
                 '2016': '2016_RTN(%)', '2015': '2015_RTN(%)', '2014': '2014_RTN(%)', '2013': '2013_RTN(%)',
                 '2012': '2012_RTN(%)', '2011': '2011_RTN(%)', '2010': '2010_RTN(%)'
               }, axis=1, inplace=True)

print("Shape of the dataframe:", df4.shape)
df4.head()

Shape of the dataframe: (48, 14)

,Scheme Name,Crisil Rank,YTD,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%),2015_RTN(%),2014_RTN(%),2013_RTN(%),2012_RTN(%),2011_RTN(%),2010_RTN(%)
0,IDFC Sterling Value Fund - Regular Plan - Grow...,5,23.75%,14.76%,-6.56%,-12.88%,61.34%,0.39%,-0.28%,57.27%,4.07%,44.99%,-22.36%,26.80%
1,IDFC Sterling Value Fund - Direct Plan - Growt...,5,24.22%,15.97%,-5.52%,-11.88%,63.10%,1.12%,0.45%,58.81%,4.21%,-,-,-
2,Aditya Birla Sun Life Pure Value Fund - Regula...,1,17.38%,14.95%,-10.98%,-23.16%,56.04%,7.68%,3.63%,96.14%,4.25%,33.39%,-24.04%,23.72%
3,Aditya Birla Sun Life Pure Value Fund - Direct...,1,17.76%,16.17%,-9.89%,-22.25%,57.89%,8.69%,4.56%,97.64%,4.79%,-,-,-
4,L&T India Value Fund - Direct Plan - Growth Va...,3,11.74%,15.01%,5.68%,-10.22%,42.45%,8.03%,13.21%,75.02%,6.60%,-,-,-

## Exctracting Value Mutual Fund's Rank Within Category Data

Data in this table: Get performance rank within category. If 1Y column value is 3/45 that means, Fund ranked 3rd in terms of performance out of 45 funds in that category.

In [10]:
value_rank_in_category = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/ranks/value-fund.html")
df5 = pd.DataFrame(value_rank_in_category[0])

In [11]:
#Renaming df5 column names
df5.rename({'1W': '1W_Rank', '1M': '1M_Rank', '3M': '3M_Rank', '6M': '6M_Rank', 'YTD': 'YTD_Rank',
            '1Y': '1Y_Rank', '2Y': '2Y_Rank', '3Y': '3Y_Rank', '5Y': '5Y_Rank', '10Y': '10Y_Rank'
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df5.shape)
df5.head()

Shape of the dataframe: (46, 12)

,Scheme Name,Crisil Rank,1W_Rank,1M_Rank,3M_Rank,6M_Rank,YTD_Rank,1Y_Rank,2Y_Rank,3Y_Rank,5Y_Rank,10Y_Rank
0,Sundaram Value Fund - Series VII - Regular Pla...,-,2/24,1/24,1/24,1/23,1/24,1/23,3/23,12/19,0/0,0/0
1,Sundaram Value Fund - Series VII - Direct Plan...,-,2/24,1/24,1/24,1/23,1/24,1/23,3/23,13/19,0/0,0/0
2,IDFC Sterling Value Fund - Regular Plan - Grow...,5,17/24,8/24,3/24,3/23,5/24,2/23,6/23,13/19,2/11,4/10
3,IDFC Sterling Value Fund - Direct Plan - Growt...,5,17/24,8/24,3/24,3/23,4/24,2/23,5/23,12/19,2/12,0/0
4,Templeton India Value Fund - GrowthValue Fund,3,3/24,11/24,15/24,6/23,14/24,3/23,15/23,15/19,9/11,10/10

## Exctracting Value Mutual Fund's Risk Ratios Data

Data in this table: Get values of risk ratios calculated on daily returns for last 3 years.

In [12]:
value_risk_ratio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/risk-ratios/value-fund.html")
df6 = pd.DataFrame(value_risk_ratio[0])

In [13]:
#Droping the 'Category' column
df6.drop('Category', inplace=True, axis=1)
print("Shape of the dataframe:", df6.shape)
df6.head()

Shape of the dataframe: (21, 8)

,Scheme Name,Crisil Rank,AuM (Cr),Standard Deviation,Beta,Sharpe Ratio,Jension's Alpha,Treynor's Ratio
0,Quantum Long Term Equity Value Fund - Growth,3,834.84,19.85,0.88,0.29,-1.68,0.06
1,ICICI Prudential Value Discovery Fund - Growth,4,17824.83,18.76,0.83,0.45,1.33,0.10
2,ICICI Prudential Value Fund - Series 18 - Growth,-,169.88,17.57,0.79,0.47,1.49,0.10
3,ICICI Prudential Value Fund - Series 19 - Growth,-,2433.13,21.27,0.85,0.43,1.92,0.11
4,ICICI Prudential Value Fund - Series 20 - Growth,-,643.69,18.47,0.82,0.28,-1.76,0.06

## Exctracting Value Mutual Fund's Portfolio Data

Data in this table: Compare how schemes have invested money across various asset class and number of instruments.

In [14]:
value_portfolio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/portfolioassets/value-fund.html")
df7 = pd.DataFrame(value_portfolio[0])

In [15]:
#Renaming SIP returns column names
df7.rename({'Turnover ratio': 'Turnover ratio(%)'}, axis=1, inplace=True)

print("Shape of the dataframe:", df7.shape)
df7.head()

Shape of the dataframe: (48, 10)

,Scheme Name,Crisil Rank,Turnover ratio(%),% Equity Holding,No of stocks in portfolio,% Debt Holding,No of instruments in portfolio,% MF Holding,% Cash Holding,% Other Holding
0,L&T India Value Fund - Direct Plan - GrowthVal...,3,34.02%,99.64%,55,-,-,-,0.36%,-
1,L&T India Value Fund - GrowthValue Fund,2,34.02%,99.64%,55,-,-,-,0.36%,-
2,Nippon India Value Fund - GrowthValue Fund,3,-,98.87%,74,-,-,0.29%,0.46%,0.38%
3,Nippon India Value Fund - Direct Plan - Growth...,3,-,98.87%,74,-,-,0.29%,0.46%,0.38%
4,Tata Equity PE Fund - Direct Plan - GrowthValu...,1,-,98.72%,36,-,-,-,1.28%,-

## Exctracting Value Mutual Fund's Latest NAV Data

Data in this table: Get the latest values of NAV for the mutual funds.

In [16]:
value_nav = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/navs/value-fund.html")
df8 = pd.DataFrame(value_nav[0])

In [17]:
df8.rename({'1D Change' : '1D Change(%)'}, axis=1, inplace=True)
print("Shape of the dataframe:", df8.shape)
df8.head()

Shape of the dataframe: (50, 10)

,Scheme Name,Crisil Rank,AuM (Cr),NAV,1D Change(%),NAV Date,52W High,52WH as on,52W Low,52WL as on
0,Sundaram Value Fund - Series VIII - Direct Pla...,-,98.44,13.5855,0.01%,12-May-21,14.4982,03-Mar-21,8.2147,18-May-20
1,Sundaram Value Fund - Series VIII - Regular Pl...,-,98.44,13.1483,0%,12-May-21,14.0405,03-Mar-21,7.9760,18-May-20
2,Sundaram Value Fund - Series VII - Regular Pla...,-,34.40,12.5096,-0.53%,12-May-21,12.5759,11-May-21,5.4365,18-May-20
3,Indiabulls Value Fund - GrowthValue Fund,2,13.98,14.1897,-0.47%,12-May-21,14.6615,03-Mar-21,9.0593,18-May-20
4,Sundaram Value Fund - Series VII - Direct Plan...,-,34.40,12.8532,-0.53%,12-May-21,12.9212,11-May-21,5.5569,18-May-20

## Exctracting Value Mutual Fund's SIP Returns Data

Data in this table: Get absolute SIP returns. If 1Y column value is 10%, that means fund has given 10% returns on your SIP investments started 1 year back from latest NAV date.

In [18]:
value_sip_rtns = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/sip-returns/value-fund.html")
df9 = pd.DataFrame(value_sip_rtns[0])

In [19]:
#Renaming SIP returns column names
df9.rename({'1Y': '1Y_SIP_RTN(%)', '2Y': '2Y_SIP_RTN(%)', '3Y': '3Y_SIP_RTN(%)',
                  '5Y': '5Y_SIP_RTN(%)', '10Y': '10Y_SIP_RTN(%)', 'YTD' : 'YTD_SIP_RTN(%)'
           }, axis=1, inplace=True)

print("Shape of the dataframe:", df9.shape)
df9.head()

Shape of the dataframe: (46, 8)

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,Sundaram Value Fund - Series VII - Direct Plan...,-,34.40,52.60%,55.30%,-,-,-
1,Sundaram Value Fund - Series VII - Regular Pla...,-,34.40,52.14%,54.45%,-,-,-
2,IDFC Sterling Value Fund - Direct Plan - Growt...,5,3334.47,48.25%,52.49%,47.73%,53.63%,-
3,IDFC Sterling Value Fund - Regular Plan - Grow...,5,3334.47,42.52%,47.54%,42.94%,47.29%,121.01%
4,ICICI Prudential Value Fund - Series 19 - Dire...,-,2433.13,41.42%,45.78%,46.07%,-,-

In [20]:
df_final = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9],axis=1,sort=False)
print("Shape of the dataframe:", df_final.shape)

Shape of the dataframe: (50, 103)

In [21]:
# Remove duplicate columns by name in Pandas
df_final = df_final.loc[:,~df_final.columns.duplicated()]

# Removing spaces in the column names
#df_final.columns = df_final.columns.str.replace(' ','_')

print("Shape of the dataframe:", df_final.shape)
df_final.head()

Shape of the dataframe: (50, 84)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,NAV Date,52W High,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,ICICI Prudential Value Fund - Series 19 - Dire...,-,2433.13,1.48%,9.18%,12.33%,46.69%,8.44%,75.70%,17.83%,...,12-May-21,14.4982,03-Mar-21,8.2147,18-May-20,52.60%,55.30%,-,-,-
1,ICICI Prudential Value Fund - Series 19 - Grow...,-,2433.13,1.46%,9.09%,12.17%,46.37%,8.41%,74.66%,17.14%,...,12-May-21,14.0405,03-Mar-21,7.9760,18-May-20,52.14%,54.45%,-,-,-
2,Sundaram Value Fund - Series VII - Direct Plan...,-,34.40,1.26%,11.20%,13.25%,54.95%,11.06%,124.17%,21.70%,...,12-May-21,12.5759,11-May-21,5.4365,18-May-20,48.25%,52.49%,47.73%,53.63%,-
3,Sundaram Value Fund - Series VII - Regular Pla...,-,34.40,1.25%,11.15%,13.10%,54.55%,10.99%,122.99%,21.06%,...,12-May-21,14.6615,03-Mar-21,9.0593,18-May-20,42.52%,47.54%,42.94%,47.29%,121.01%
4,Templeton India Value Fund - Direct - GrowthVa...,3,498.92,0.75%,3.74%,0.47%,34.17%,1.72%,87.96%,16.13%,...,12-May-21,12.9212,11-May-21,5.5569,18-May-20,41.42%,45.78%,46.07%,-,-

In [23]:
#Exporting the consolidated elss mf data as a  csv file
#print("Shape of the dataframe:", df_final.shape)
#df_final.to_csv('value_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + ').csv',
#               index=False)

#Exporting the elss mf data columns with its datatype as a  csv file
#df_dtypes.to_csv('elss_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')