In [1]:
#Importing the required libraries
import pandas as pd

## Dynamic Asset Allocation or Balanced Advantage Fund

These mutual funds invest in both Stocks and Debt/Bonds. Allocation between debt and socks can vary as per market conditions.

## Exctracting Dynamic Asset Allocation or Balanced Advantage Mutual Fund's Historical Investment Returns Data

Data in this table: Get Absolute historical returns for ₹1000 investment. If 1Y column value is 1234.5 that means, your ₹1000 investment 1 year back would have grown to ₹1234.5.

In [2]:
daa_lump_sum_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/returns/dynamic-asset-allocation-or-balanced-advantage.html")
df1 = pd.DataFrame(daa_lump_sum_rtn[0])

In [3]:
#Renaming historical returns column names
df1.rename({'1W': '1W_RTN(%)', '1M': '1M_RTN(%)', '3M': '3M_RTN(%)', '6M': '6M_RTN(%)',
                 'YTD': 'YTD_RTN(%)', '1Y': '1Y_RTN(%)', '2Y': '2Y_RTN(%)', '3Y': '3Y_RTN(%)',
                 '5Y': '5Y_RTN(%)', '10Y': '10Y_RTN(%)'
          }, axis=1, inplace=True)
print("Shape of the dataframe:", df1.shape)
df1.head()

Shape of the dataframe: (47, 13)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%)
0,HDFC Balanced Advantage Fund - Direct Plan - G...,4,39146.35,1.29%,5.88%,1.15%,24.77%,4.34%,58.84%,13.39%,10.83%,14.76%,-
1,ITI Balanced Advantage Fund - Direct Plan - Gr...,-,192.26,0.52%,2.15%,2.41%,11.09%,2.33%,21.12%,-,-,-,-
2,ITI Balanced Advantage Fund - GrowthDynamic As...,-,192.26,0.48%,1.85%,1.76%,9.84%,1.93%,18.51%,-,-,-,-
3,ICICI Prudential Balanced Advantage Fund - Gro...,2,30900.09,0.29%,2.15%,0.65%,10.57%,1.88%,39.63%,13.10%,10.44%,11.37%,12.57%
4,ICICI Prudential Balanced Advantage Fund - Dir...,-,30900.09,0.29%,2.21%,0.80%,10.91%,1.96%,40.45%,13.72%,11.21%,12.43%,-

## Exctracting Dynamic Asset Allocation or Balanced Advantage Mutual Fund's Monthly Returns Data

Data in this table: Get monthly returns. If Jan month column value is 5.4% that means, fund has given 5.4% returns in Jan month.

In [4]:
daa_monthly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/monthly-returns/dynamic-asset-allocation-or-balanced-advantage.html")
df2 = pd.DataFrame(daa_monthly_rtn[0])

In [5]:
#Renaming df1 column names
df1.rename({"Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            'MTD': 'MTD_RTN(%)', "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)"
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df2.shape)
df2.head()

Shape of the dataframe: (47, 14)

,Scheme Name,Crisil Rank,MTD,Apr'21,Mar'21,Feb'21,Jan'21,Dec'20,Nov'20,Oct'20,Sep'20,Aug'20,Jul'20,Jun'20
0,BNP Paribas Dynamic Equity Fund - Regular Plan...,-,0.53%,0.06%,-0.55%,1.07%,-1.05%,2.86%,3.14%,1.02%,-0.24%,0.90%,4.43%,3.00%
1,BNP Paribas Dynamic Equity Fund - Direct Plan ...,-,0.63%,0.21%,-0.39%,1.19%,-0.91%,3.01%,3.29%,1.16%,-0.09%,1.05%,4.59%,3.15%
2,IDFC Balanced Advantage Fund - Regular Plan - ...,-,0.30%,0.37%,0.62%,1.38%,-1.00%,2.98%,2.95%,0.74%,0.20%,0.76%,4.62%,4.69%
3,IDFC Balanced Advantage Fund - Direct Plan - G...,-,0.39%,0.45%,0.74%,1.56%,-0.87%,3.10%,3.09%,0.81%,0.32%,0.89%,4.75%,4.70%
4,Axis Dynamic Equity Fund - GrowthDynamic Asset...,-,0.95%,-1.09%,0.63%,0.64%,-2.72%,2.72%,4.58%,2.12%,-0.44%,0.27%,2.28%,3.02%

## Exctracting Dynamic Asset Allocation or Balanced Advantage Mutual Fund's Quarterly Returns Data

Data in this table: Get quarterly returns. If Q1 column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Mar.

In [6]:
daa_quarterly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/quarterly-returns/dynamic-asset-allocation-or-balanced-advantage.html")
df3 = pd.DataFrame(daa_quarterly_rtn[0])

In [7]:
print("Shape of the dataframe:", df3.shape)
df3.head()

Shape of the dataframe: (47, 14)

,Scheme Name,Crisil Rank,QTD,Q1'21,Q4'20,Q3'20,Q2'20,Q1'20,Q4'19,Q3'19,Q2'19,Q1'19,Q4'18,Q3'18
0,BNP Paribas Dynamic Equity Fund - Regular Plan...,-,0.60%,1.62%,7.68%,5.48%,13.46%,-12.47%,3.42%,2.41%,2.40%,-,-,-
1,BNP Paribas Dynamic Equity Fund - Direct Plan ...,-,0.84%,2.09%,8.16%,5.96%,13.98%,-12.04%,3.90%,2.69%,2.85%,-,-,-
2,IDFC Balanced Advantage Fund - Regular Plan - ...,-,0.67%,2.45%,7.29%,6.21%,19.22%,-15.68%,3.91%,0.96%,1.43%,2.39%,1.09%,-0.87%
3,IDFC Balanced Advantage Fund - Direct Plan - G...,-,0.84%,2.83%,7.66%,6.55%,19.55%,-15.42%,4.21%,1.32%,1.77%,2.77%,1.41%,-0.47%
4,Axis Dynamic Equity Fund - GrowthDynamic Asset...,-,-0.16%,1.92%,10.06%,2.65%,8.12%,-9.52%,1.89%,0.72%,1.00%,1.96%,0.28%,0.19%

## Exctracting Dynamic Asset Allocation or Balanced Advantage Mutual Fund's Annual Investment Returns Data

Data in this table: Get annual returns. If 2018 year column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Dec/Last date.

In [8]:
daa_annual_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/annual-returns/dynamic-asset-allocation-or-balanced-advantage.html")
df4 = pd.DataFrame(daa_annual_rtn[0])

In [9]:
#Renaming yearly returns column names
df4.rename({'2020': '2020_RTN(%)', '2019': '2019_RTN(%)', '2018': '2018_RTN(%)', '2017': '2017_RTN(%)',
                 '2016': '2016_RTN(%)', '2015': '2015_RTN(%)', '2014': '2014_RTN(%)', '2013': '2013_RTN(%)',
                 '2012': '2012_RTN(%)', '2011': '2011_RTN(%)', '2010': '2010_RTN(%)'
               }, axis=1, inplace=True)

print("Shape of the dataframe:", df4.shape)
df4.head()

Shape of the dataframe: (45, 14)

,Scheme Name,Crisil Rank,YTD,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%),2015_RTN(%),2014_RTN(%),2013_RTN(%),2012_RTN(%),2011_RTN(%),2010_RTN(%)
0,BNP Paribas Dynamic Equity Fund - Regular Plan...,-,2.73%,11.20%,10.73%,-,-,-,-,-,-,-,-,-
1,BNP Paribas Dynamic Equity Fund - Direct Plan ...,-,3.46%,13.29%,12.39%,-,-,-,-,-,-,-,-,-
2,IDFC Balanced Advantage Fund - Regular Plan - ...,-,2.89%,12.70%,8.95%,1.52%,17.26%,3.38%,1.54%,3.95%,-,-,-,-
3,IDFC Balanced Advantage Fund - Direct Plan - G...,-,3.93%,14.23%,10.58%,3.05%,18.62%,4.59%,3.03%,4.24%,-,-,-,-
4,Axis Dynamic Equity Fund - Growth Dynamic Asse...,-,2.24%,9.96%,6.16%,2.98%,4.20%,-,-,-,-,-,-,-

## Exctracting Dynamic Asset Allocation or Balanced Advantage Mutual Fund's Rank Within Category Data

Data in this table: Get performance rank within category. If 1Y column value is 3/45 that means, Fund ranked 3rd in terms of performance out of 45 funds in that category.

In [10]:
daa_rank_in_category = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/ranks/dynamic-asset-allocation-or-balanced-advantage.html")
df5 = pd.DataFrame(daa_rank_in_category[0])

In [11]:
#Renaming df5 column names
df5.rename({'1W': '1W_Rank', '1M': '1M_Rank', '3M': '3M_Rank', '6M': '6M_Rank', 'YTD': 'YTD_Rank',
            '1Y': '1Y_Rank', '2Y': '2Y_Rank', '3Y': '3Y_Rank', '5Y': '5Y_Rank', '10Y': '10Y_Rank'
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df5.shape)
df5.head()

Shape of the dataframe: (44, 12)

,Scheme Name,Crisil Rank,1W_Rank,1M_Rank,3M_Rank,6M_Rank,YTD_Rank,1Y_Rank,2Y_Rank,3Y_Rank,5Y_Rank,10Y_Rank
0,HDFC Balanced Advantage Fund - Direct Plan - G...,4,1/23,1/23,7/23,1/22,1/23,1/22,10/19,6/15,1/12,0/0
1,HDFC Balanced Advantage Fund - Direct Plan - G...,-,1/23,1/23,7/23,1/22,1/23,1/22,10/19,6/15,1/12,0/0
2,Baroda Dynamic Equity Fund - GrowthDynamic Ass...,-,13/23,16/23,14/23,11/22,14/23,2/22,1/19,0/0,0/0,0/0
3,Baroda Dynamic Equity Fund - Direct - GrowthDy...,-,10/23,16/23,14/23,12/22,15/23,2/22,1/19,0/0,0/0,0/0
4,Aditya Birla Sun Life Balanced Advantage Fund ...,-,14/23,4/23,5/23,5/22,3/23,3/22,5/19,4/15,4/12,0/0

## Exctracting Dynamic Asset Allocation or Balanced Advantage Mutual Fund's Risk Ratios Data

Data in this table: Get values of risk ratios calculated on daily returns for last 3 years.

In [12]:
daa_risk_ratio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/risk-ratios/dynamic-asset-allocation-or-balanced-advantage.html")
df6 = pd.DataFrame(daa_risk_ratio[0])

In [13]:
#Droping the 'Category' column
df6.drop('Category', inplace=True, axis=1)
print("Shape of the dataframe:", df6.shape)
df6.head()

Shape of the dataframe: (16, 8)

,Scheme Name,Crisil Rank,AuM (Cr),Standard Deviation,Beta,Sharpe Ratio,Jension's Alpha,Treynor's Ratio
0,Aditya Birla Sun Life Balanced Advantage Fund ...,2,3326.87,13.47,0.94,0.47,-1.68,0.07
1,ICICI Prudential Balanced Advantage Fund - Growth,2,30900.09,13.19,1.19,0.50,-2.90,0.06
2,Principal Balanced Advantage Fund - Growth,-,195.71,7.30,-,0.25,-,0.04
3,Kotak Balanced Advantage Fund - Growth,-,8114.06,13.10,-,0.58,-,0.08
4,IDFC Balanced Advantage Fund - Regular Plan - ...,-,1837.30,12.27,-,0.40,-,0.09

## Exctracting Dynamic Asset Allocation or Balanced Advantage Mutual Fund's Portfolio Data

Data in this table: Compare how schemes have invested money across various asset class and number of instruments.

In [14]:
daa_portfolio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/portfolioassets/dynamic-asset-allocation-or-balanced-advantage.html")
df7 = pd.DataFrame(daa_portfolio[0])

In [15]:
#Renaming SIP returns column names
df7.rename({'Turnover ratio': 'Turnover ratio(%)'}, axis=1, inplace=True)

print("Shape of the dataframe:", df7.shape)
df7.head()

Shape of the dataframe: (46, 10)

,Scheme Name,Crisil Rank,Turnover ratio(%),% Equity Holding,No of stocks in portfolio,% Debt Holding,No of instruments in portfolio,% MF Holding,% Cash Holding,% Other Holding
0,Edelweiss Balanced Advantage Fund - Direct Pla...,-,-,77.82%,109,15.41%,11,-,5.39%,0.87%
1,Edelweiss Balanced Advantage Fund - GrowthDyna...,2,-,77.82%,109,15.41%,11,-,5.39%,0.87%
2,HDFC Balanced Advantage Fund - Direct Plan - G...,-,-,74.52%,75,13.56%,35,0.05%,10.73%,1.14%
3,HDFC Balanced Advantage Fund - Direct Plan - G...,4,-,74.52%,75,13.56%,35,0.05%,10.73%,1.14%
4,ITI Balanced Advantage Fund - Direct Plan - Gr...,-,-,72.02%,49,15.15%,3,-,12.83%,-

## Exctracting Dynamic Asset Allocation or Balanced Advantage Mutual Fund's Latest NAV Data

Data in this table: Get the latest values of NAV for the mutual funds.

In [16]:
daa_nav = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/navs/dynamic-asset-allocation-or-balanced-advantage.html")
df8 = pd.DataFrame(daa_nav[0])

In [17]:
df8.rename({'1D Change' : '1D Change(%)'}, axis=1, inplace=True)
print("Shape of the dataframe:", df8.shape)
df8.head()

Shape of the dataframe: (47, 10)

,Scheme Name,Crisil Rank,AuM (Cr),NAV,1D Change(%),NAV Date,52W High,52WH as on,52W Low,52WL as on
0,HDFC Balanced Advantage Fund - Direct Plan - G...,4,39146.35,258.8920,1.19%,17-May-21,260.9690,03-Mar-21,159.7370,22-May-20
1,Nippon India Balanced Advantage Fund - Direct ...,-,3310.28,119.2146,0.77%,17-May-21,119.2146,17-May-21,85.6386,20-May-20
2,Nippon India Balanced Advantage Fund - GrowthD...,-,3310.28,110.9950,0.76%,17-May-21,110.9950,17-May-21,80.8335,20-May-20
3,Aditya Birla Sun Life Balanced Advantage Fund ...,-,3326.87,72.4900,0.66%,17-May-21,72.5500,11-May-21,50.3900,22-May-20
4,Aditya Birla Sun Life Balanced Advantage Fund ...,2,3326.87,67.1000,0.66%,17-May-21,67.1700,11-May-21,47.1800,22-May-20

## Exctracting Dynamic Asset Allocation or Balanced Advantage Mutual Fund's SIP Returns Data

Data in this table: Get absolute SIP returns. If 1Y column value is 10%, that means fund has given 10% returns on your SIP investments started 1 year back from latest NAV date.

In [18]:
daa_sip_rtns = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/sip-returns/dynamic-asset-allocation-or-balanced-advantage.html")
df9 = pd.DataFrame(daa_sip_rtns[0])

In [19]:
#Renaming SIP returns column names
df9.rename({'1Y': '1Y_SIP_RTN(%)', '2Y': '2Y_SIP_RTN(%)', '3Y': '3Y_SIP_RTN(%)',
                  '5Y': '5Y_SIP_RTN(%)', '10Y': '10Y_SIP_RTN(%)', 'YTD' : 'YTD_SIP_RTN(%)'
           }, axis=1, inplace=True)

print("Shape of the dataframe:", df9.shape)
df9.head()

Shape of the dataframe: (43, 8)

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,HDFC Balanced Advantage Fund - Direct Plan - G...,-,39146.35,26.70%,29.21%,30.72%,41.76%,-
1,Edelweiss Balanced Advantage Fund - Direct Pla...,-,3564.04,16.24%,26.85%,32.81%,46.17%,-
2,Aditya Birla Sun Life Balanced Advantage Fund ...,-,3326.87,15.83%,22.66%,26.84%,36.31%,-
3,Nippon India Balanced Advantage Fund - Direct ...,-,3310.28,15.41%,20.50%,24.32%,35.38%,-
4,Edelweiss Balanced Advantage Fund - GrowthDyna...,2,3564.04,15.30%,24.85%,29.76%,41.01%,84.80%

In [20]:
df_final = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9],axis=1,sort=False)
print("Shape of the dataframe:", df_final.shape)

Shape of the dataframe: (47, 103)

In [21]:
# Remove duplicate columns by name in Pandas
df_final = df_final.loc[:,~df_final.columns.duplicated()]

# Removing spaces in the column names
#df_final.columns = df_final.columns.str.replace(' ','_')

print("Shape of the dataframe:", df_final.shape)
df_final.head()

Shape of the dataframe: (47, 84)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,NAV Date,52W High,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,HDFC Balanced Advantage Fund - Direct Plan - G...,4,39146.35,1.29%,5.88%,1.15%,24.77%,4.34%,58.84%,13.39%,...,17-May-21,260.9690,03-Mar-21,159.7370,22-May-20,26.70%,29.21%,30.72%,41.76%,-
1,ITI Balanced Advantage Fund - Direct Plan - Gr...,-,192.26,0.52%,2.15%,2.41%,11.09%,2.33%,21.12%,-,...,17-May-21,119.2146,17-May-21,85.6386,20-May-20,16.24%,26.85%,32.81%,46.17%,-
2,ITI Balanced Advantage Fund - GrowthDynamic As...,-,192.26,0.48%,1.85%,1.76%,9.84%,1.93%,18.51%,-,...,17-May-21,110.9950,17-May-21,80.8335,20-May-20,15.83%,22.66%,26.84%,36.31%,-
3,ICICI Prudential Balanced Advantage Fund - Gro...,2,30900.09,0.29%,2.15%,0.65%,10.57%,1.88%,39.63%,13.10%,...,17-May-21,72.5500,11-May-21,50.3900,22-May-20,15.41%,20.50%,24.32%,35.38%,-
4,ICICI Prudential Balanced Advantage Fund - Dir...,-,30900.09,0.29%,2.21%,0.80%,10.91%,1.96%,40.45%,13.72%,...,17-May-21,67.1700,11-May-21,47.1800,22-May-20,15.30%,24.85%,29.76%,41.01%,84.80%

In [24]:
#Exporting the consolidated Dynamic Asset Allocation or Balanced Advantage mf data as a  csv file
#print("Shape of the dataframe:", df_final.shape)
#df_final.to_csv('daa_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + ').csv',
#               index=False)

#Exporting the Dynamic Asset Allocation or Balanced Advantage mf data columns with its datatype as a  csv file
#df_dtypes.to_csv('daa_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')