In [1]:
import re
import pandas as pd
import numpy as np
%matplotlib inline

## Exctracting Dynamic Bond Mutual Fund's Historical Investment Returns Data

Data in this table: Get Absolute historical returns for ₹1000 investment. If 1Y column value is 1234.5 that means, your ₹1000 investment 1 year back would have grown to ₹1234.5.

In [2]:
db_lump_sum_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/returns/dynamic-bond-fund.html")
df1 = pd.DataFrame(db_lump_sum_rtn[0])

In [3]:
#Renaming historical returns column names
df1.rename({'1W': '1W_RTN(%)', '1M': '1M_RTN(%)', '3M': '3M_RTN(%)', '6M': '6M_RTN(%)',
                 'YTD': 'YTD_RTN(%)', '1Y': '1Y_RTN(%)', '2Y': '2Y_RTN(%)', '3Y': '3Y_RTN(%)',
                 '5Y': '5Y_RTN(%)', '10Y': '10Y_RTN(%)'
          }, axis=1, inplace=True)
print("Shape of the dataframe:", df1.shape)
df1.head()

Shape of the dataframe: (58, 13)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%)
0,IIFL Dynamic Bond Fund - Direct Plan - GrowthD...,3,687.13,0.30%,1.09%,2.32%,2.94%,1.59%,8.58%,7.96%,7.83%,7.51%,-
1,IIFL Dynamic Bond Fund - GrowthDynamic Bond Fund,3,687.13,0.29%,1.06%,2.23%,2.72%,1.56%,8.05%,7.35%,7.19%,6.90%,-
2,UTI Dynamic Bond Fund (Segregated - 17022020) ...,-,6.32,0.23%,1.00%,2.86%,-20.45%,1.37%,-16.98%,-,-,-,-
3,Franklin India Dynamic Accrual Fund - GrowthDy...,1,1446.83,0.23%,1.26%,4.67%,8.27%,2.24%,10.23%,3.88%,5.57%,6.89%,7.90%
4,Franklin India Dynamic Accrual Fund - Direct -...,1,1446.83,0.23%,1.26%,4.74%,8.56%,2.24%,10.96%,4.67%,6.44%,7.81%,-

## Exctracting Dynamic Bond Mutual Fund's Monthly Returns Data

Data in this table: Get monthly returns. If Jan month column value is 5.4% that means, fund has given 5.4% returns in Jan month.

In [4]:
db_monthly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/monthly-returns/dynamic-bond-fund.html")
df2 = pd.DataFrame(db_monthly_rtn[0])

In [5]:
#Renaming df1 column names
df1.rename({"Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            'MTD': 'MTD_RTN(%)', "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)"
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df2.shape)
df2.head()

Shape of the dataframe: (58, 14)

,Scheme Name,Crisil Rank,MTD,Apr'21,Mar'21,Feb'21,Jan'21,Dec'20,Nov'20,Oct'20,Sep'20,Aug'20,Jul'20,Jun'20
0,BNP Paribas Flexi Debt Fund - GrowthDynamic Bo...,3,0.28%,0.81%,0.82%,-0.99%,-0.31%,0.52%,0.43%,1.26%,-0.18%,-1.47%,0.45%,0.43%
1,BNP Paribas Flexi Debt Fund - Direct Plan - Gr...,4,0.32%,0.92%,0.93%,-0.90%,-0.22%,0.62%,0.52%,1.35%,-0.08%,-1.39%,0.53%,0.51%
2,IDFC Dynamic Bond Fund - Regular Plan - Growth...,5,0.36%,1.02%,0.61%,-1.22%,-0.47%,0.73%,0.51%,1.65%,0.12%,-2.03%,0.92%,1.29%
3,IDFC Dynamic Bond Fund - Direct Plan - GrowthD...,5,0.39%,1.09%,0.70%,-1.16%,-0.40%,0.80%,0.58%,1.72%,0.19%,-1.97%,0.99%,1.35%
4,Axis Dynamic Bond Fund - GrowthDynamic Bond Fund,3,0.38%,0.95%,2.20%,-2.02%,0.13%,0.32%,0.41%,2.17%,-0.51%,-1.21%,1.70%,1.73%

## Exctracting Dynamic Bond Mutual Fund's Quarterly Returns Data

Data in this table: Get quarterly returns. If Q1 column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Mar.

In [6]:
db_quarterly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/quarterly-returns/dynamic-bond-fund.html")
df3 = pd.DataFrame(db_quarterly_rtn[0])

In [7]:
print("Shape of the dataframe:", df3.shape)
df3.head()

Shape of the dataframe: (58, 14)

,Scheme Name,Crisil Rank,QTD,Q1'21,Q4'20,Q3'20,Q2'20,Q1'20,Q4'19,Q3'19,Q2'19,Q1'19,Q4'18,Q3'18
0,BNP Paribas Flexi Debt Fund - GrowthDynamic Bo...,3,1.09%,-1.32%,2.20%,0.08%,2.84%,3.29%,1.29%,1.42%,2.37%,2.52%,2.88%,1.03%
1,BNP Paribas Flexi Debt Fund - Direct Plan - Gr...,4,1.24%,-1.01%,2.50%,0.34%,3.06%,3.42%,1.49%,1.72%,2.66%,2.78%,3.13%,1.27%
2,IDFC Dynamic Bond Fund - Regular Plan - Growth...,5,1.38%,-1.83%,2.84%,0.05%,5.16%,3.34%,1.40%,2.95%,3.43%,2.61%,4.62%,1.41%
3,IDFC Dynamic Bond Fund - Direct Plan - GrowthD...,5,1.49%,-1.59%,3.05%,0.25%,5.36%,3.55%,1.59%,3.38%,3.60%,2.75%,4.82%,1.61%
4,Axis Dynamic Bond Fund - GrowthDynamic Bond Fund,3,1.34%,-0.47%,2.81%,0.68%,4.26%,3.74%,2.28%,2.70%,3.30%,2.38%,3.45%,1.53%

## Exctracting Dynamic Bond Mutual Fund's Annual Investment Returns Data

Data in this table: Get annual returns. If 2018 year column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Dec/Last date.

In [8]:
db_annual_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/annual-returns/dynamic-bond-fund.html")
df4 = pd.DataFrame(db_annual_rtn[0])

In [9]:
#Renaming yearly returns column names
df4.rename({'2020': '2020_RTN(%)', '2019': '2019_RTN(%)', '2018': '2018_RTN(%)', '2017': '2017_RTN(%)',
                 '2016': '2016_RTN(%)', '2015': '2015_RTN(%)', '2014': '2014_RTN(%)', '2013': '2013_RTN(%)',
                 '2012': '2012_RTN(%)', '2011': '2011_RTN(%)', '2010': '2010_RTN(%)'
               }, axis=1, inplace=True)

print("Shape of the dataframe:", df4.shape)
df4.head()

Shape of the dataframe: (58, 14)

,Scheme Name,Crisil Rank,YTD,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%),2015_RTN(%),2014_RTN(%),2013_RTN(%),2012_RTN(%),2011_RTN(%),2010_RTN(%)
0,Quantum Dynamic Bond Fund - Direct Plan - Grow...,4,1.02%,9.65%,11.31%,4.08%,6.17%,-,-,-,-,-,-,-
1,Quantum Dynamic Bond Fund - Growth Dynamic Bon...,4,0.98%,9.50%,11.18%,3.97%,4.97%,15.65%,5.51%,-,-,-,-,-
2,Franklin India Dynamic Accrual Fund - Growth D...,1,5.90%,-1.86%,6.32%,8.30%,8.50%,10.00%,10.25%,12.61%,3.90%,9.85%,8.16%,3.38%
3,Franklin India Dynamic Accrual Fund - Direct -...,1,6.06%,-1.06%,7.28%,9.30%,9.49%,10.95%,11.33%,13.17%,4.55%,-,-,-
4,ICICI Prudential All Seasons Bond Fund - Direc...,4,1.84%,12.24%,11.02%,6.95%,5.80%,17.60%,6.57%,19.62%,9.57%,-,-,-

## Exctracting Dynamic Bond Mutual Fund's Rank Within Category Data

Data in this table: Get performance rank within category. If 1Y column value is 3/45 that means, Fund ranked 3rd in terms of performance out of 45 funds in that category.

In [10]:
db_rank_in_category = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/ranks/dynamic-bond-fund.html")
df5 = pd.DataFrame(db_rank_in_category[0])

In [11]:
#Renaming df5 column names
df5.rename({'1W': '1W_Rank', '1M': '1M_Rank', '3M': '3M_Rank', '6M': '6M_Rank', 'YTD': 'YTD_Rank',
            '1Y': '1Y_Rank', '2Y': '2Y_Rank', '3Y': '3Y_Rank', '5Y': '5Y_Rank', '10Y': '10Y_Rank'
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df5.shape)
df5.head()

Shape of the dataframe: (59, 12)

,Scheme Name,Crisil Rank,1W_Rank,1M_Rank,3M_Rank,6M_Rank,YTD_Rank,1Y_Rank,2Y_Rank,3Y_Rank,5Y_Rank,10Y_Rank
0,Franklin India Dynamic Accrual Fund - GrowthDy...,1,3/30,1/30,1/30,1/30,1/30,1/30,25/27,20/25,15/24,12/18
1,Franklin India Dynamic Accrual Fund - Direct -...,1,2/28,1/28,1/28,1/28,1/28,1/28,24/26,20/24,13/22,0/0
2,Aditya Birla Sun Life Dynamic Bond Fund - Dire...,2,8/28,18/28,6/28,3/28,19/28,2/28,23/26,22/24,20/22,0/0
3,Aditya Birla Sun Life Dynamic Bond Fund - Regu...,2,9/30,19/30,7/30,4/30,18/30,3/30,24/27,23/25,22/24,15/18
4,Aditya Birla Sun Life Dynamic Bond Fund - Regu...,-,9/30,19/30,7/30,4/30,18/30,3/30,24/27,23/25,22/24,15/18

## Exctracting Dynamic Bond Mutual Fund's Risk Ratios Data

Data in this table: Get values of risk ratios calculated on daily returns for last 3 years.

In [12]:
db_risk_ratio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/risk-ratios/dynamic-bond-fund.html")
df6 = pd.DataFrame(db_risk_ratio[0])

In [13]:
#Droping the 'Category' column
df6.drop('Category', inplace=True, axis=1)
print("Shape of the dataframe:", df6.shape)
df6.head()

Shape of the dataframe: (21, 8)

,Scheme Name,Crisil Rank,AuM (Cr),Standard Deviation,Beta,Sharpe Ratio,Jension's Alpha,Treynor's Ratio
0,Quantum Dynamic Bond Fund - Growth,4,77.45,2.99,0.78,1.65,0.29,0.06
1,Franklin India Dynamic Accrual Fund - Growth,1,1446.83,3.93,0.34,0.52,0.03,0.06
2,ICICI Prudential All Seasons Bond Fund - Growth,4,5652.43,2.57,0.01,2.14,5.41,4.51
3,Mahindra Manulife Dynamic Bond Yojana - Growth,3,132.78,1.68,0.87,1.36,-2.05,0.03
4,HDFC Dynamic Debt Fund - Growth,1,423.74,2.70,1.06,0.69,-3.41,0.02

## Exctracting Dynamic Bond Mutual Fund's Portfolio Data

Data in this table: Compare how schemes have invested money across various asset class and number of instruments.

In [14]:
db_portfolio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/portfolioassets/dynamic-bond-fund.html")
df7 = pd.DataFrame(db_portfolio[0])

In [15]:
#Renaming SIP returns column names
df7.rename({'Turnover ratio': 'Turnover ratio(%)'}, axis=1, inplace=True)

print("Shape of the dataframe:", df7.shape)
df7.head()

Shape of the dataframe: (58, 10)

,Scheme Name,Crisil Rank,Turnover ratio(%),% Equity Holding,No of stocks in portfolio,% Debt Holding,No of instruments in portfolio,% MF Holding,% Cash Holding,% Other Holding
0,Aditya Birla Sun Life Dynamic Bond Fund - Regu...,-,-,-,-,94.29%,81,-,5.71%,-
1,Aditya Birla Sun Life Dynamic Bond Fund - Segr...,-,-,-,-,-,-,-,100.00%,-
2,Mahindra Manulife Dynamic Bond Yojana - Growth...,3,-,-,-,59.06%,16,-,40.94%,-
3,Mahindra Manulife Dynamic Bond Yojana - Direct...,3,-,-,-,59.06%,16,-,40.94%,-
4,DSP Strategic Bond Fund - Direct Plan - Growth...,4,-,-,-,98.00%,10,-,2.00%,-

## Exctracting Dynamic Bond Mutual Fund's Latest NAV Data

Data in this table: Get the latest values of NAV for the mutual funds.

In [16]:
db_nav = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/navs/dynamic-bond-fund.html")
df8 = pd.DataFrame(db_nav[0])

In [17]:
df8.rename({'1D Change' : '1D Change(%)'}, axis=1, inplace=True)
print("Shape of the dataframe:", df8.shape)
df8.head()

Shape of the dataframe: (58, 10)

,Scheme Name,Crisil Rank,AuM (Cr),NAV,1D Change(%),NAV Date,52W High,52WH as on,52W Low,52WL as on
0,DSP Strategic Bond Fund - Direct Plan - Growth...,4,791.71,2736.6578,0.06%,12-May-21,2739.3275,05-Jan-21,2595.7932,18-May-20
1,PGIM India Dynamic Bond Fund - Direct Plan - G...,3,109.23,2267.8866,0.03%,12-May-21,2267.8866,12-May-21,2140.9778,18-May-20
2,PGIM India Dynamic Bond Fund - GrowthDynamic B...,3,109.23,2102.2884,0.02%,12-May-21,2102.2884,12-May-21,2005.0158,18-May-20
3,Indiabulls Dynamic Bond Fund - Direct Plan - G...,-,28.26,1207.9330,0.04%,12-May-21,1207.9330,12-May-21,1140.9172,18-May-20
4,Indiabulls Dynamic Bond Fund - Regular Plan - ...,-,28.26,1192.8108,0.03%,12-May-21,1192.8108,12-May-21,1132.4082,18-May-20

## Exctracting Dynamic Bond Mutual Fund's SIP Returns Data

Data in this table: Get absolute SIP returns. If 1Y column value is 10%, that means fund has given 10% returns on your SIP investments started 1 year back from latest NAV date.

In [18]:
db_sip_rtns = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/sip-returns/dynamic-bond-fund.html")
df9 = pd.DataFrame(db_sip_rtns[0])

In [19]:
#Renaming SIP returns column names
df9.rename({'1Y': '1Y_SIP_RTN(%)', '2Y': '2Y_SIP_RTN(%)', '3Y': '3Y_SIP_RTN(%)',
                  '5Y': '5Y_SIP_RTN(%)', '10Y': '10Y_SIP_RTN(%)', 'YTD' : 'YTD_SIP_RTN(%)'
           }, axis=1, inplace=True)

print("Shape of the dataframe:", df9.shape)
df9.head()

Shape of the dataframe: (58, 8)

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,Franklin India Dynamic Accrual Fund - Direct -...,1,1446.83,7.16%,7.28%,9.96%,18.36%,-
1,Franklin India Dynamic Accrual Fund - GrowthDy...,1,1446.83,7.39%,6.78%,8.91%,16.08%,46.17%
2,Aditya Birla Sun Life Dynamic Bond Fund - Dire...,2,1595.79,3.89%,6.60%,9.46%,14.50%,-
3,IIFL Dynamic Bond Fund - Direct Plan - GrowthD...,3,687.13,3.85%,7.90%,12.40%,20.80%,-
4,ICICI Prudential All Seasons Bond Fund - Direc...,4,5652.43,4.07%,10.46%,16.80%,27.20%,-

In [20]:
df_final = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9],axis=1,sort=False)
print("Shape of the dataframe:", df_final.shape)

Shape of the dataframe: (59, 103)

In [21]:
# Remove duplicate columns by name in Pandas
df_final = df_final.loc[:,~df_final.columns.duplicated()]

# Removing spaces in the column names
#df_final.columns = df_final.columns.str.replace(' ','_')

print("Shape of the dataframe:", df_final.shape)
df_final.head()

Shape of the dataframe: (59, 84)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,NAV Date,52W High,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,IIFL Dynamic Bond Fund - Direct Plan - GrowthD...,3,687.13,0.30%,1.09%,2.32%,2.94%,1.59%,8.58%,7.96%,...,12-May-21,2739.3275,05-Jan-21,2595.7932,18-May-20,7.16%,7.28%,9.96%,18.36%,-
1,IIFL Dynamic Bond Fund - GrowthDynamic Bond Fund,3,687.13,0.29%,1.06%,2.23%,2.72%,1.56%,8.05%,7.35%,...,12-May-21,2267.8866,12-May-21,2140.9778,18-May-20,7.39%,6.78%,8.91%,16.08%,46.17%
2,UTI Dynamic Bond Fund (Segregated - 17022020) ...,-,6.32,0.23%,1.00%,2.86%,-20.45%,1.37%,-16.98%,-,...,12-May-21,2102.2884,12-May-21,2005.0158,18-May-20,3.89%,6.60%,9.46%,14.50%,-
3,Franklin India Dynamic Accrual Fund - GrowthDy...,1,1446.83,0.23%,1.26%,4.67%,8.27%,2.24%,10.23%,3.88%,...,12-May-21,1207.9330,12-May-21,1140.9172,18-May-20,3.85%,7.90%,12.40%,20.80%,-
4,Franklin India Dynamic Accrual Fund - Direct -...,1,1446.83,0.23%,1.26%,4.74%,8.56%,2.24%,10.96%,4.67%,...,12-May-21,1192.8108,12-May-21,1132.4082,18-May-20,4.07%,10.46%,16.80%,27.20%,-

In [22]:
#Exporting the consolidated db mf data as a  csv file
#print("Shape of the dataframe:", df_final.shape)
#df_final.to_csv('db_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + ').csv',
#               index=False)

#Exporting the db mf data columns with its datatype as a  csv file
#df_dtypes.to_csv('db_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')