In [2]:
#Importing the required libraries
import pandas as pd

## Exctracting Ultra Short Duration Mutual Fund's Historical Investment Returns Data

Data in this table: Get Absolute historical returns for ₹1000 investment. If 1Y column value is 1234.5 that means, your ₹1000 investment 1 year back would have grown to ₹1234.5.

In [3]:
usd_lump_sum_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/returns/ultra-short-duration-fund.html")
df1 = pd.DataFrame(usd_lump_sum_rtn[0])

In [4]:
#Renaming historical returns column names
df1.rename({'1W': '1W_RTN(%)', '1M': '1M_RTN(%)', '3M': '3M_RTN(%)', '6M': '6M_RTN(%)',
                 'YTD': 'YTD_RTN(%)', '1Y': '1Y_RTN(%)', '2Y': '2Y_RTN(%)', '3Y': '3Y_RTN(%)',
                 '5Y': '5Y_RTN(%)', '10Y': '10Y_RTN(%)'
          }, axis=1, inplace=True)
print("Shape of the dataframe:", df1.shape)
df1.head()

Shape of the dataframe: (59, 13)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%)
0,Franklin India Ultra Short Bond Fund - Super I...,1,3785.09,0.20%,1.28%,2.68%,4.18%,1.60%,9.26%,6.69%,7.62%,8.00%,8.95%
1,Franklin India Ultra Short Bond Fund - Super I...,1,3785.09,0.20%,1.28%,2.69%,4.21%,1.60%,9.34%,6.78%,7.71%,8.08%,-
2,Nippon India Ultra Short Duration Fund - Direc...,3,890.84,0.09%,0.45%,1.51%,2.74%,0.62%,6.12%,3.59%,4.93%,5.77%,-
3,ICICI Prudential Ultra Short Term Fund - Direc...,2,9539.16,0.08%,0.43%,1.29%,2.34%,0.59%,6.71%,7.33%,7.76%,8.16%,-
4,Aditya Birla Sun Life Savings Fund - Direct Pl...,4,18187.57,0.08%,0.42%,1.25%,2.05%,0.57%,6.16%,6.98%,7.50%,7.61%,-

## Exctracting Ultra Short Duration Mutual Fund's Monthly Returns Data

Data in this table: Get monthly returns. If Jan month column value is 5.4% that means, fund has given 5.4% returns in Jan month.

In [5]:
usd_monthly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/monthly-returns/ultra-short-duration-fund.html")
df2 = pd.DataFrame(usd_monthly_rtn[0])

In [6]:
#Renaming df1 column names
df1.rename({"Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            'MTD': 'MTD_RTN(%)', "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)",
            "Apr'21": "Apr'21(%)", "Apr'21": "Apr'21(%)"
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df2.shape)
df2.head()

Shape of the dataframe: (59, 14)

,Scheme Name,Crisil Rank,MTD,Apr'21,Mar'21,Feb'21,Jan'21,Dec'20,Nov'20,Oct'20,Sep'20,Aug'20,Jul'20,Jun'20
0,IDFC Ultra Short Term Fund - Regular Plan - Gr...,5,0.10%,0.31%,0.34%,0.22%,0.15%,0.24%,0.30%,0.36%,0.25%,0.28%,0.32%,0.55%
1,IDFC Ultra Short Term Fund - Direct Plan - Gro...,5,0.11%,0.32%,0.35%,0.23%,0.16%,0.25%,0.32%,0.37%,0.26%,0.29%,0.33%,0.56%
2,Axis Ultra Short Term Fund - Regular Plan - Gr...,2,0.08%,0.32%,0.31%,0.25%,0.17%,0.22%,0.34%,0.42%,0.30%,0.34%,0.40%,0.54%
3,Axis Ultra Short Term Fund - Direct Plan - Gro...,3,0.11%,0.40%,0.39%,0.32%,0.24%,0.29%,0.41%,0.49%,0.37%,0.42%,0.47%,0.61%
4,BOI AXA Ultra Short Duration Fund - Regular - ...,3,0.08%,0.29%,0.32%,0.24%,0.11%,0.21%,0.30%,0.35%,0.28%,0.27%,0.31%,0.45%

## Exctracting Ultra Short Duration Mutual Fund's Quarterly Returns Data

Data in this table: Get quarterly returns. If Q1 column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Mar.

In [7]:
usd_quarterly_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/quarterly-returns/ultra-short-duration-fund.html")
df3 = pd.DataFrame(usd_quarterly_rtn[0])

In [8]:
print("Shape of the dataframe:", df3.shape)
df3.head()

Shape of the dataframe: (57, 14)

,Scheme Name,Crisil Rank,QTD,Q1'21,Q4'20,Q3'20,Q2'20,Q1'20,Q4'19,Q3'19,Q2'19,Q1'19,Q4'18,Q3'18
0,YES Ultra Short Term Fund - Direct Plan - Grow...,-,0.35%,1.47%,0.75%,1.27%,0.59%,1.36%,1.39%,1.85%,-,-,-,-
1,YES Ultra Short Term Fund - Regular Plan - Gro...,-,0.29%,1.35%,0.63%,1.14%,0.47%,1.24%,1.24%,1.70%,-,-,-,-
2,Franklin India Ultra Short Bond Fund - Super I...,1,1.54%,1.75%,1.81%,2.26%,1.99%,-2.09%,2.22%,2.18%,2.09%,2.47%,2.65%,1.92%
3,Franklin India Ultra Short Bond Fund - Super I...,1,1.54%,1.76%,1.83%,2.28%,2.01%,-2.06%,2.25%,2.20%,2.11%,2.48%,2.67%,1.94%
4,ICICI Prudential Ultra Short Term Fund - Direc...,2,0.57%,1.12%,1.43%,1.69%,2.06%,1.72%,2.13%,2.04%,2.08%,2.22%,2.31%,1.85%

## Exctracting Ultra Short Duration Mutual Fund's Annual Investment Returns Data

Data in this table: Get annual returns. If 2018 year column value is 5.4% that means, fund has given 5.4% returns from 1st Jan to 31st Dec/Last date.

In [9]:
usd_annual_rtn = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/annual-returns/ultra-short-duration-fund.html")
df4 = pd.DataFrame(usd_annual_rtn[0])

In [10]:
#Renaming yearly returns column names
df4.rename({'2020': '2020_RTN(%)', '2019': '2019_RTN(%)', '2018': '2018_RTN(%)', '2017': '2017_RTN(%)',
                 '2016': '2016_RTN(%)', '2015': '2015_RTN(%)', '2014': '2014_RTN(%)', '2013': '2013_RTN(%)',
                 '2012': '2012_RTN(%)', '2011': '2011_RTN(%)', '2010': '2010_RTN(%)'
               }, axis=1, inplace=True)

print("Shape of the dataframe:", df4.shape)
df4.head()

Shape of the dataframe: (59, 14)

,Scheme Name,Crisil Rank,YTD,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%),2015_RTN(%),2014_RTN(%),2013_RTN(%),2012_RTN(%),2011_RTN(%),2010_RTN(%)
0,ITI Ultra Short Duration Fund - Regular Plan -...,-,0.04%,-,-,-,-,-,-,-,-,-,-,-
1,ITI Ultra Short Duration Fund - Direct Plan - ...,-,0.06%,-,-,-,-,-,-,-,-,-,-,-
2,YES Ultra Short Term Fund - Direct Plan - Grow...,-,1.84%,4.05%,3.75%,-,-,-,-,-,-,-,-,-
3,YES Ultra Short Term Fund - Regular Plan - Gro...,-,1.66%,3.53%,3.40%,-,-,-,-,-,-,-,-,-
4,Franklin India Ultra Short Bond Fund - Super I...,1,3.37%,3.96%,9.44%,8.62%,8.21%,9.64%,9.70%,9.95%,10.00%,10.26%,9.35%,5.88%

## Exctracting Ultra Short Duration Mutual Fund's Rank Within Category Data

Data in this table: Get performance rank within category. If 1Y column value is 3/45 that means, Fund ranked 3rd in terms of performance out of 45 funds in that category.

In [11]:
usd_rank_in_category = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/ranks/ultra-short-duration-fund.html")
df5 = pd.DataFrame(usd_rank_in_category[0])

In [12]:
#Renaming df5 column names
df5.rename({'1W': '1W_Rank', '1M': '1M_Rank', '3M': '3M_Rank', '6M': '6M_Rank', 'YTD': 'YTD_Rank',
            '1Y': '1Y_Rank', '2Y': '2Y_Rank', '3Y': '3Y_Rank', '5Y': '5Y_Rank', '10Y': '10Y_Rank'
          }, axis=1, inplace=True)

print("Shape of the dataframe:", df5.shape)
df5.head()

Shape of the dataframe: (55, 12)

,Scheme Name,Crisil Rank,1W_Rank,1M_Rank,3M_Rank,6M_Rank,YTD_Rank,1Y_Rank,2Y_Rank,3Y_Rank,5Y_Rank,10Y_Rank
0,Franklin India Ultra Short Bond Fund - Super I...,1,1/30,1/29,1/29,1/29,1/29,1/28,4/23,2/18,2/18,1/17
1,Franklin India Ultra Short Bond Fund - Super I...,1,1/29,1/28,1/28,1/28,1/28,1/27,4/22,3/17,3/17,0/0
2,ICICI Prudential Ultra Short Term Fund - Direc...,2,3/29,3/28,3/28,3/28,3/28,2/27,2/22,2/17,2/17,0/0
3,ICICI Prudential Ultra Short Term Fund - Growt...,3,4/30,4/29,4/29,3/29,4/29,2/28,3/23,4/18,4/18,4/17
4,Aditya Birla Sun Life Savings Fund - Regular P...,4,2/30,2/29,3/29,4/29,2/29,3/28,2/23,3/18,3/18,3/17

## Exctracting Ultra Short Duration Mutual Fund's Risk Ratios Data

Data in this table: Get values of risk ratios calculated on daily returns for last 3 years.

In [13]:
usd_risk_ratio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/risk-ratios/ultra-short-duration-fund.html")
df6 = pd.DataFrame(usd_risk_ratio[0])

In [14]:
#Droping the 'Category' column
df6.drop('Category', inplace=True, axis=1)
print("Shape of the dataframe:", df6.shape)
df6.head()

Shape of the dataframe: (3, 8)

,Scheme Name,Crisil Rank,AuM (Cr),Standard Deviation,Beta,Sharpe Ratio,Jension's Alpha,Treynor's Ratio
0,ICICI Prudential Ultra Short Term Fund - Growth,3,9539.16,0.84,0.07,4.17,3.02,0.48
1,Invesco India Ultra Short Term Fund - Growth,2,735.75,0.73,0.30,3.66,1.17,0.09
2,UTI Ultra Short Term Fund - Growth,3,2327.66,1.85,1.88,0.71,-3.10,0.01

## Exctracting Ultra Short Duration Mutual Fund's Portfolio Data

Data in this table: Compare how schemes have invested money across various asset class and number of instruments.

In [15]:
usd_portfolio = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/portfolioassets/ultra-short-duration-fund.html")
df7 = pd.DataFrame(usd_portfolio[0])

In [16]:
#Renaming SIP returns column names
df7.rename({'Turnover ratio': 'Turnover ratio(%)'}, axis=1, inplace=True)

print("Shape of the dataframe:", df7.shape)
df7.head()

Shape of the dataframe: (57, 10)

,Scheme Name,Crisil Rank,Turnover ratio(%),% Equity Holding,No of stocks in portfolio,% Debt Holding,No of instruments in portfolio,% MF Holding,% Cash Holding,% Other Holding
0,Nippon India Ultra Short Duration Fund - Growt...,2,-,-,-,86.99%,24,-,13.03%,-0.02%
1,Tata Ultra Short Term Fund - GrowthUltra Short...,1,-,-,-,92.46%,30,-,7.54%,-
2,IDBI Ultra Short Term Fund - Direct Plan - Gro...,1,-,-,-,69.43%,15,-,30.57%,-
3,Navi Ultra Short Term Fund - Direct Plan - Gro...,-,-,-,-,67.99%,8,-,32.01%,-
4,Axis Ultra Short Term Fund - Regular Plan - Gr...,2,-,-,-,97.69%,95,-,2.31%,-

## Exctracting Ultra Short Duration Mutual Fund's Latest NAV Data

Data in this table: Get the latest values of NAV for the mutual funds.

In [17]:
usd_nav = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/navs/ultra-short-duration-fund.html")
df8 = pd.DataFrame(usd_nav[0])

In [18]:
df8.rename({'1D Change' : '1D Change(%)'}, axis=1, inplace=True)
print("Shape of the dataframe:", df8.shape)
df8.head()

Shape of the dataframe: (59, 10)

,Scheme Name,Crisil Rank,AuM (Cr),NAV,1D Change(%),NAV Date,52W High,52WH as on,52W Low,52WL as on
0,Nippon India Ultra Short Duration Fund - Direc...,3,890.84,3268.5134,0.02%,12-May-21,3268.5134,12-May-21,3088.4368,18-May-20
1,SBI Magnum Ultra Short Duration Fund - Direct ...,2,12342.15,4738.6027,0.01%,12-May-21,4738.6027,12-May-21,4533.0686,18-May-20
2,Nippon India Ultra Short Duration Fund - Growt...,2,890.84,3061.4842,0.01%,12-May-21,3061.4842,12-May-21,2914.8018,18-May-20
3,SBI Magnum Ultra Short Duration Fund - Regular...,3,12342.15,4696.3062,0.01%,12-May-21,4696.3062,12-May-21,4500.3111,18-May-20
4,DSP Ultra Short Fund - Direct Plan - GrowthUlt...,3,3652.81,2866.3543,0.01%,12-May-21,2866.3543,12-May-21,2753.7707,18-May-20

## Exctracting Ultra Short Duration Mutual Fund's SIP Returns Data

Data in this table: Get absolute SIP returns. If 1Y column value is 10%, that means fund has given 10% returns on your SIP investments started 1 year back from latest NAV date.

In [19]:
usd_sip_rtns = pd.read_html(
    "https://www.moneycontrol.com/mutual-funds/performance-tracker/sip-returns/ultra-short-duration-fund.html")
df9 = pd.DataFrame(usd_sip_rtns[0])

In [20]:
#Renaming SIP returns column names
df9.rename({'1Y': '1Y_SIP_RTN(%)', '2Y': '2Y_SIP_RTN(%)', '3Y': '3Y_SIP_RTN(%)',
                  '5Y': '5Y_SIP_RTN(%)', '10Y': '10Y_SIP_RTN(%)', 'YTD' : 'YTD_SIP_RTN(%)'
           }, axis=1, inplace=True)

print("Shape of the dataframe:", df9.shape)
df9.head()

Shape of the dataframe: (55, 8)

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,Franklin India Ultra Short Bond Fund - Super I...,1,3785.09,4.57%,7.45%,11.54%,21.03%,-
1,Franklin India Ultra Short Bond Fund - Super I...,1,3785.09,4.85%,7.61%,11.66%,21.05%,54.75%
2,Nippon India Ultra Short Duration Fund - Direc...,3,890.84,3.12%,5.14%,7.15%,13.90%,-
3,ICICI Prudential Ultra Short Term Fund - Direc...,2,9539.16,2.98%,6.86%,11.47%,21.05%,-
4,Nippon India Ultra Short Duration Fund - Growt...,2,890.84,2.68%,4.29%,5.86%,11.49%,33.72%

In [21]:
df_final = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9],axis=1,sort=False)
print("Shape of the dataframe:", df_final.shape)

Shape of the dataframe: (59, 103)

In [22]:
# Remove duplicate columns by name in Pandas
df_final = df_final.loc[:,~df_final.columns.duplicated()]

# Removing spaces in the column names
#df_final.columns = df_final.columns.str.replace(' ','_')

print("Shape of the dataframe:", df_final.shape)
df_final.head()

Shape of the dataframe: (59, 84)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,NAV Date,52W High,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
0,Franklin India Ultra Short Bond Fund - Super I...,1,3785.09,0.20%,1.28%,2.68%,4.18%,1.60%,9.26%,6.69%,...,12-May-21,3268.5134,12-May-21,3088.4368,18-May-20,4.57%,7.45%,11.54%,21.03%,-
1,Franklin India Ultra Short Bond Fund - Super I...,1,3785.09,0.20%,1.28%,2.69%,4.21%,1.60%,9.34%,6.78%,...,12-May-21,4738.6027,12-May-21,4533.0686,18-May-20,4.85%,7.61%,11.66%,21.05%,54.75%
2,Nippon India Ultra Short Duration Fund - Direc...,3,890.84,0.09%,0.45%,1.51%,2.74%,0.62%,6.12%,3.59%,...,12-May-21,3061.4842,12-May-21,2914.8018,18-May-20,3.12%,5.14%,7.15%,13.90%,-
3,ICICI Prudential Ultra Short Term Fund - Direc...,2,9539.16,0.08%,0.43%,1.29%,2.34%,0.59%,6.71%,7.33%,...,12-May-21,4696.3062,12-May-21,4500.3111,18-May-20,2.98%,6.86%,11.47%,21.05%,-
4,Aditya Birla Sun Life Savings Fund - Direct Pl...,4,18187.57,0.08%,0.42%,1.25%,2.05%,0.57%,6.16%,6.98%,...,12-May-21,2866.3543,12-May-21,2753.7707,18-May-20,2.68%,4.29%,5.86%,11.49%,33.72%

In [23]:
#Exporting the consolidated usd mf data as a  csv file
#print("Shape of the dataframe:", df_final.shape)
#df_final.to_csv('usd_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + ').csv',
#               index=False)

#Exporting the usd mf data columns with its datatype as a  csv file
#df_dtypes.to_csv('usd_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')