In [150]:
# Importing respective modules
import pandas as pd
import re

In [151]:
# Reading elss mutual funds csv file
focused_mf = pd.read_csv('focused_mf_data(11-May-2021 13:34:47).csv')

In [152]:
# Extracting a plan from "Scheme Name" column
scheme_name = list(focused_mf['Scheme Name'])
plan = []
for i in scheme_name:
    #print(type(i))
    plan.append(re.findall("Direct|Regular", str(i)))
#plan
for p in plan:
    if len(p) == 0:
        #print(type(p))
        p.append("Regular")
focused_mf['Plan'] = plan

In [153]:
# Extracting a category from "Scheme Name" column
scheme_name = list(focused_mf['Scheme Name'])
category = []
for i in scheme_name:
    #print(type(i))
    category.append(re.findall("Focused Fund", str(i)))
focused_mf['Category'] = category

In [154]:
# Modifiying 'Scheme Name' column
focused_mf['Scheme Name'] = focused_mf['Scheme Name'].str.replace(' - GrowthFocused Fund', '')

In [155]:
#Replacing "']" & "['" string with "" in Plan columns
focused_mf['Plan'] = focused_mf['Plan'].astype(str).str.replace("\['","", regex=True)
focused_mf['Plan'] = focused_mf['Plan'].astype(str).str.replace("']","", regex=True)

#Replacing "']" & "['" string with "" in Category columns
focused_mf['Category'] = focused_mf['Category'].astype(str).str.replace("\['","", regex=True)
focused_mf['Category'] = focused_mf['Category'].astype(str).str.replace("']","", regex=True)

In [156]:
#Replacing "ELSS', 'ELSS" string with "ELSS" in Category columns
focused_mf['Category'] = focused_mf['Category'].astype(str).str.replace("Focused Fund', 'Focused Fund",
                                                                        "Focused Fund", regex=True)

#Replacing "%" string with "" in Crisil Rank, % Debt Holding, No of instruments in portfolio,
# % MF Holding, % Other Holding, Turnover ratio, MTD, 10Y_SIP_RTN(%) & 5Y_SIP_RTN(%) columns
focused_mf[['% Debt Holding', 'No of instruments in portfolio',
          '% MF Holding', '% Other Holding', 'Turnover ratio(%)',
          'MTD', '10Y_SIP_RTN(%)', '5Y_SIP_RTN(%)'         
         ]] = focused_mf[['% Debt Holding', 'No of instruments in portfolio',
                        '% MF Holding', '% Other Holding', 'Turnover ratio(%)',
                        'MTD', '10Y_SIP_RTN(%)', '5Y_SIP_RTN(%)'
                        ]].replace("%", "", regex=True)

#Replacing "-" string with "0" in Crisil Rank columns
focused_mf[['Crisil Rank', 'No of instruments in portfolio']] = focused_mf[['Crisil Rank', 
                                                                            'No of instruments in portfolio'
                                                                           ]].replace("-", "0", regex=True)

In [157]:
#Replacing "-" string with "0" in Crisil Rank columns
focused_mf['Crisil Rank'] = focused_mf['Crisil Rank'].replace("", "0", regex=True)

#Replacing "%" with '' in the column
focused_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding', '% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)',
         "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20",
         "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19",
         "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)"
         ]] = focused_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)"
                       ]].replace("%", "", regex=True)
print("Shape of the dataframe:", focused_mf.shape)
focused_mf.head()

Shape of the dataframe: (50, 86)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
0,Quant Focused Fund - Direct Plan,0,12.12,5.35,6.08,18.97,46.37,26.48,84.77,29.83,...,10-May-21,129.2597,18-May-20,43.55,55.42,58.62,69.30,-,Direct,Focused Fund
1,Quant Focused Fund,0,12.12,5.24,5.84,18.30,44.85,25.52,81.23,27.71,...,10-May-21,120.9285,18-May-20,41.86,52.41,54.66,63.95,170.41,Regular,Focused Fund
2,ICICI Prudential Focused Equity Fund - Direct ...,4,1316.11,3.55,3.29,2.77,31.28,14.42,66.79,19.13,...,15-Feb-21,156.8961,18-May-20,34.35,41.41,42.88,53.51,-,Direct,Focused Fund
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,3.54,3.18,2.48,30.49,13.92,64.79,17.84,...,15-Feb-21,148.9459,18-May-20,33.82,40.40,41.38,47.45,143.79,Regular,Focused Fund
4,Franklin India Focused Equity Fund - Direct,3,7359.87,2.94,2.96,1.83,31.90,16.62,77.02,17.74,...,03-Mar-21,57.4770,19-May-20,33.51,36.76,39.73,49.43,-,Direct,Focused Fund

In [158]:
#Sorting a focused_mf dataframe by "Crisil Rank Column"
focused_mf.sort_values(by=['Crisil Rank', 'Scheme Name', 'AuM (Cr)'], inplace=True, ascending=False)
print("Shape of the dataframe:", focused_mf.shape)
focused_mf.head()

Shape of the dataframe: (50, 86)

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
25,Nippon India Focused Equity Fund - Direct Plan,5,4897.48,1.51,0.90,1.49,33.89,17.23,81.48,19.00,...,15-Feb-21,19.1210,18-May-20,22.42,28.31,32.16,42.69,-,Direct,Focused Fund
27,Nippon India Focused Equity Fund,5,4897.48,1.50,0.84,1.33,33.44,16.96,80.30,18.22,...,03-Mar-21,14.0375,18-May-20,21.83,26.64,30.67,39.59,-,Regular,Focused Fund
34,IIFL Focused Equity Fund - Direct Plan,5,1675.38,1.10,1.18,-0.37,21.29,7.98,68.12,26.56,...,16-Feb-21,8.3400,18-May-20,19.53,24.12,28.06,42.29,91.85,Direct,Focused Fund
35,IIFL Focused Equity Fund,5,1675.38,1.07,1.07,-0.60,20.66,7.61,66.12,24.88,...,03-Mar-21,7.3076,18-May-20,19.50,25.66,-,-,-,Regular,Focused Fund
42,SBI Focused Equity Fund - Regular Plan,4,14766.83,0.94,2.01,3.43,22.25,10.34,56.74,17.98,...,03-Mar-21,8.1400,18-May-20,16.41,15.14,15.48,23.15,84.66,Regular,Focused Fund

In [159]:
#Replacing "-" with 'None' in the columns
focused_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding', '% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)',
         "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20",
         "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19",
         "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)"
         ]] = focused_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)"]].replace({'-' : None})

In [160]:
#Replacing "" with '0' in the columns

focused_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding','% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)',
         '10Y_SIP_RTN(%)', "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20",
         "Sep'20", "Aug'20", "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20",
         "Q4'19", "Q3'19", "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)",
         "Standard Deviation", "Beta", "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio", 'Crisil Rank'
         ]] = focused_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',\
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)", "Standard Deviation", "Beta",
                       "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio", 'Crisil Rank']].fillna(value='0')

In [161]:
#Changing the datatype of the return & risk ratio columns

focused_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
         '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)', '2018_RTN(%)',
         '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)", "2012_RTN(%)", "2011_RTN(%)",
         "2010_RTN(%)", '% Equity Holding','% Debt Holding', '% MF Holding', '% Cash Holding', '% Other Holding',
         '1D Change(%)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)',
         '10Y_SIP_RTN(%)', "Apr'21", "Mar'21", "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20",
         "Sep'20", "Aug'20", "Jul'20", "Jun'20", "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20",
         "Q4'19", "Q3'19", "Q2'19", "Q1'19", "Q4'18", "Q3'18", "YTD", "MTD", "Turnover ratio(%)",
         "Standard Deviation", "Beta", "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio"
         ]] = focused_mf[['1W_RTN(%)', '1M_RTN(%)', '3M_RTN(%)', '6M_RTN(%)', 'YTD_RTN(%)', '1Y_RTN(%)',
                       '2Y_RTN(%)', '3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', '2020_RTN(%)', '2019_RTN(%)',
                       '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)', '2015_RTN(%)', '2014_RTN(%)', "2013_RTN(%)",
                       "2012_RTN(%)", "2011_RTN(%)", "2010_RTN(%)", '% Equity Holding', '% Debt Holding',
                       '% MF Holding', '% Cash Holding', '% Other Holding', '1D Change(%)', '1Y_SIP_RTN(%)',
                       '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', "Apr'21", "Mar'21",
                       "Feb'21", "Jan'21", "Dec'20", "Nov'20", "Oct'20", "Sep'20", "Aug'20", "Jul'20", "Jun'20",
                       "QTD", "Q1'21", "Q4'20", "Q3'20", "Q2'20", "Q1'20", "Q4'19", "Q3'19", "Q2'19", "Q1'19",
                       "Q4'18", "Q3'18", "YTD",'MTD', "Turnover ratio(%)", "Standard Deviation", "Beta",
                       "Sharpe Ratio", "Jension's Alpha", "Treynor's Ratio"]].apply(pd.to_numeric)

In [162]:
#Changing the datatype of the 'Crisil Rank' columns
focused_mf['Crisil Rank'] = focused_mf['Crisil Rank'].astype('int')

In [163]:
#Removing white spaces at both ends in all over the dataframe:

focused_mf.columns = focused_mf.columns.str.strip()

#Checking the data type of all columns in the DataFrame
focused_mf_dtype = focused_mf.dtypes

df_dtypes = pd.DataFrame(focused_mf_dtype)

In [164]:
#Using pandas dataframe.round()function to round off all the decimal values to 2 decimal places
focused_mf = focused_mf.round(2)

In [165]:
# #Exporting the consolidated elss mf data as a  csv file
# print("Shape of the dataframe:", focused_mf.shape)
focused_mf.to_csv('final_focused_mf_data('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)',
                 index=False)

# #Exporting the elss mf data columns with its datatype as a  csv file
# df_dtypes.to_csv('focused_mf_col_data_types('+ str(pd.to_datetime('today').strftime('%d-%b-%Y %H:%M:%S')) + '.csv)')

In [166]:
#Exctracting regular mutual funds
regular_mf = focused_mf.loc[focused_mf['Plan'] == 'Regular']
regular_mf.head()

,Scheme Name,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),...,52WH as on,52W Low,52WL as on,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),Plan,Category
27,Nippon India Focused Equity Fund,5,4897.48,1.50,0.84,1.33,33.44,16.96,80.30,18.22,...,03-Mar-21,14.04,18-May-20,21.83,26.64,30.67,39.59,0.00,Regular,Focused Fund
35,IIFL Focused Equity Fund,5,1675.38,1.07,1.07,-0.60,20.66,7.61,66.12,24.88,...,03-Mar-21,7.31,18-May-20,19.50,25.66,0.00,0.00,0.00,Regular,Focused Fund
42,SBI Focused Equity Fund - Regular Plan,4,14766.83,0.94,2.01,3.43,22.25,10.34,56.74,17.98,...,03-Mar-21,8.14,18-May-20,16.41,15.14,15.48,23.15,84.66,Regular,Focused Fund
33,Principal Focused Multicap Fund,4,539.05,1.14,2.27,1.47,25.70,11.79,58.25,22.28,...,16-Feb-21,7.96,18-May-20,19.61,28.21,34.35,47.94,0.00,Regular,Focused Fund
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,3.54,3.18,2.48,30.49,13.92,64.79,17.84,...,15-Feb-21,148.95,18-May-20,33.82,40.40,41.38,47.45,143.79,Regular,Focused Fund

In [167]:
# Basic statistics of regular mutual fund df
regular_mf.describe()

,Crisil Rank,AuM (Cr),1W_RTN(%),1M_RTN(%),3M_RTN(%),6M_RTN(%),YTD_RTN(%),1Y_RTN(%),2Y_RTN(%),3Y_RTN(%),...,% Other Holding,NAV,1D Change(%),52W High,52W Low,1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%)
count,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.00000,...,25.0,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.00000,25.000000
mean,1.920000,2757.554000,1.718000,0.943200,0.535200,21.062000,9.443200,52.582400,12.365200,7.30720,...,0.0,48.429600,0.711600,49.582400,29.921200,21.206000,21.460800,22.193600,27.22040,40.564400
std,1.754043,4116.324221,1.066618,1.657693,4.453368,8.321681,5.481478,22.049646,8.873091,5.95476,...,0.0,55.875055,0.286294,57.079641,35.215236,9.838065,15.328129,17.161966,22.60321,58.935254
min,0.000000,12.120000,0.070000,-1.550000,-5.460000,0.000000,0.340000,0.000000,0.000000,0.00000,...,0.0,9.990000,0.000000,10.670000,6.440000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,0.000000,539.050000,1.030000,-0.150000,-2.100000,17.870000,4.990000,49.080000,0.000000,0.00000,...,0.0,13.430000,0.550000,13.930000,9.010000,18.790000,0.000000,0.000000,0.00000,0.000000
50%,2.000000,1217.670000,1.500000,0.490000,-0.470000,19.790000,8.490000,57.240000,15.590000,8.04000,...,0.0,29.790000,0.720000,30.390000,18.090000,22.000000,25.660000,26.060000,32.16000,0.000000
75%,3.000000,1955.630000,1.990000,2.010000,1.470000,22.250000,11.790000,62.350000,17.980000,12.18000,...,0.0,54.390000,0.870000,55.430000,32.260000,26.030000,29.690000,35.230000,46.27000,84.660000
max,5.000000,15007.350000,5.240000,5.840000,18.300000,44.850000,25.520000,81.230000,27.710000,18.49000,...,0.0,231.080000,1.210000,239.780000,148.950000,41.860000,52.410000,54.660000,63.95000,170.410000

In [168]:
# Extracting funds which have 3Y Return', '5Y Return' & '10Y Return' greater than 10%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10) &
                            (regular_mf['10Y_RTN(%)'] > 10)]
print("No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is:", len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV']]

No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is: 8 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV
27,Nippon India Focused Equity Fund,5,4897.48,80.30,11.03,14.79,15.63,24.24
42,SBI Focused Equity Fund - Regular Plan,4,14766.83,56.74,12.18,15.58,17.00,13.49
33,Principal Focused Multicap Fund,4,539.05,58.25,14.59,15.82,12.61,12.56
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,64.79,12.62,13.47,11.52,231.08
16,Sundaram Select Focus,3,1217.67,49.08,11.07,14.24,10.41,51.40
5,Franklin India Focused Equity Fund,3,7359.87,75.57,12.22,14.08,15.70,90.74
19,Aditya Birla Sun Life Focused Equity Fund - Re...,3,4593.49,56.45,10.66,13.06,13.11,38.96
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,193.96

In [169]:
# Extracting  last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'
#greater than 10%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10) &
                            (regular_mf['10Y_RTN(%)'] > 10)]
print("Last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'greater than 10% is:",
      len(mf_rtn_com.index), '\nFunds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

Last five years annual return for funds which have 3Y Return', '5Y Return' & '10Y Return'greater than 10% is: 8
Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
27,Nippon India Focused Equity Fund,5,4897.48,24.24,12.74,9.24,0.00,0.00,0.00
42,SBI Focused Equity Fund - Regular Plan,4,14766.83,13.49,11.65,15.22,1.85,35.87,0.34
33,Principal Focused Multicap Fund,4,539.05,12.56,22.73,20.14,0.00,0.00,0.00
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,231.08,16.96,10.85,-10.97,56.85,3.10
16,Sundaram Select Focus,3,1217.67,51.40,25.96,0.00,0.00,0.00,0.00
5,Franklin India Focused Equity Fund,3,7359.87,90.74,22.34,16.90,2.53,46.86,5.47
19,Aditya Birla Sun Life Focused Equity Fund - Re...,3,4593.49,38.96,19.40,8.49,-2.47,1.80,0.00
1,Quant Focused Fund,0,12.12,193.96,17.01,14.59,-10.46,3.86,0.00

In [170]:
# Extracting funds which have '3Y Return' & '5Y Return' greater than 12%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 12) & (regular_mf['5Y_RTN(%)'] > 12)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 12% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return' & '5Y Return' greater than 12% is: 7 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
35,IIFL Focused Equity Fund,5,1675.38,66.12,18.49,18.09,0.00,12.51,0.00,0.0,0.00,0.00
42,SBI Focused Equity Fund - Regular Plan,4,14766.83,56.74,12.18,15.58,17.00,13.49,0.00,0.0,0.00,0.00
33,Principal Focused Multicap Fund,4,539.05,58.25,14.59,15.82,12.61,12.56,0.00,0.0,0.00,0.00
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,64.79,12.62,13.47,11.52,231.08,0.09,0.0,21.58,0.96
5,Franklin India Focused Equity Fund,3,7359.87,75.57,12.22,14.08,15.70,90.74,0.13,0.0,21.01,0.90
14,Axis Focused 25 Fund,3,15007.35,58.49,12.85,17.47,0.00,41.26,0.46,0.0,20.01,0.87
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,193.96,0.45,841.0,18.58,0.80

In [171]:
# Extracting last five years annual return for funds which have 3Y Return', '5Y Return' greater than 12%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 12) & (regular_mf['5Y_RTN(%)'] > 12)]
print("Last five years annual return for funds which have '5Y Return' & '10Y Return'greater than 10% is:",
      len(mf_rtn_com.index), '\nFunds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

Last five years annual return for funds which have '5Y Return' & '10Y Return'greater than 10% is: 7
Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
35,IIFL Focused Equity Fund,5,1675.38,12.51,18.66,18.66,-2.49,34.04,2.50
42,SBI Focused Equity Fund - Regular Plan,4,14766.83,13.49,11.65,15.22,1.85,35.87,0.34
33,Principal Focused Multicap Fund,4,539.05,12.56,22.73,20.14,0.00,0.00,0.00
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,231.08,16.96,10.85,-10.97,56.85,3.10
5,Franklin India Focused Equity Fund,3,7359.87,90.74,22.34,16.90,2.53,46.86,5.47
14,Axis Focused 25 Fund,3,15007.35,41.26,3.70,3.62,-14.40,38.74,1.18
1,Quant Focused Fund,0,12.12,193.96,17.01,14.59,-10.46,3.86,0.00

In [172]:
# Extracting funds which have '3Y Return' & '5Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 15) & (regular_mf['5Y_RTN(%)'] > 15)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
            'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return' & '5Y Return' greater than 15% is: 2 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
35,IIFL Focused Equity Fund,5,1675.38,66.12,18.49,18.09,0.00,12.51,0.00,0.0,0.00,0.0
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,193.96,0.45,841.0,18.58,0.8

In [173]:
# Extracting last five years annual return for funds which have 3Y Return', '5Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_RTN(%)'] > 15) & (regular_mf['5Y_RTN(%)'] > 15)]
print("No. of funds having '3Y Return' & '5Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

No. of funds having '3Y Return' & '5Y Return' greater than 15% is: 2 Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
35,IIFL Focused Equity Fund,5,1675.38,12.51,18.66,18.66,-2.49,34.04,2.5
1,Quant Focused Fund,0,12.12,193.96,17.01,14.59,-10.46,3.86,0.0

In [174]:
# Extracting funds which have '5Y Return' & '10Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 15) & (regular_mf['10Y_RTN(%)'] > 15)]
print("No. of funds having '5Y Return' & '10Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
            'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '5Y Return' & '10Y Return' greater than 15% is: 2 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
42,SBI Focused Equity Fund - Regular Plan,4,14766.83,56.74,12.18,15.58,17.00,13.49,0.00,0.0,0.00,0.0
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,193.96,0.45,841.0,18.58,0.8

In [175]:
# Extracting last five years annual return for funds which have 5Y Return', '10Y Return' greater than 15%
mf_rtn_com = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 15) & (regular_mf['10Y_RTN(%)'] > 15)]
print("No. of funds having '5Y Return' & '10Y Return' greater than 15% is:", len(mf_rtn_com.index), 'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', 'NAV', '2020_RTN(%)', '2019_RTN(%)',
            '2018_RTN(%)', '2017_RTN(%)', '2016_RTN(%)']]

No. of funds having '5Y Return' & '10Y Return' greater than 15% is: 2 Funds

,Scheme Name,Crisil Rank,AuM (Cr),NAV,2020_RTN(%),2019_RTN(%),2018_RTN(%),2017_RTN(%),2016_RTN(%)
42,SBI Focused Equity Fund - Regular Plan,4,14766.83,13.49,11.65,15.22,1.85,35.87,0.34
1,Quant Focused Fund,0,12.12,193.96,17.01,14.59,-10.46,3.86,0.00

## Portfolio Turnover Ratio(PTR)

Portfolio Turnover Ratio is the frequency in which the assets held under a fund has changed over the years. In simpler words, PTR provides a measurement on how many times the fund managers bought or sold the assets under a fund over a period of time. PTR is often determined by the market conditions and fund management style.

Suppose an equity fund purchased stocks worth Rs. 375 crore and sold stocks worth Rs. 450 crore. The average AUM of the fund is Rs.1500 crore. In this case, the Portfolio turnover ratio of the fund is 25%, which means one-fourth of the stocks were traded.

Funds that have higher turnover ratios, for example, can trigger higher costs for investors. First, a fund thatâ€™s actively managed may charge a higher expense ratio to cover the fund managerâ€™s services. The expense ratio represents the percentage you pay to own the fund on an annualized basis. At the low end, you can find index funds with expense ratios around 0.50% to 0.10%. But the most expensive funds can easily have expense ratios over 1%.

Turnover ratio can also give you an idea of what the fundâ€™s investment strategy is, which is important for choosing funds that align with your goals and objectives. A growth mutual fund, for instance, may have a higher turnover ratio if the fund manager is constantly looking for the best growth stocks to drive returns. But a fund that uses a value investing approach may have a lower turnover ratio if the fund manager is buying assets that have the potential to appreciate over time.

In [176]:
# Top 10 low turnover ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Turnover ratio(%)'] > 0)]
print("Top 10 low turnover ratio regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Turnover ratio(%)']].nsmallest(10, 'Turnover ratio(%)')

Top 10 low turnover ratio regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Turnover ratio(%)
7,HDFC Focused 30 Fund,1,656.96,61.40,4.38,9.69,8.61,59.23,39.35
19,Aditya Birla Sun Life Focused Equity Fund - Re...,3,4593.49,56.45,10.66,13.06,13.11,38.96,76.00
31,DSP Focus Fund - Regular Plan,2,1955.63,57.45,9.64,11.96,11.11,12.59,129.00
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,193.96,841.00

In [177]:
# Top 10 high turnover ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Turnover ratio(%)'] > 0)]
print("Top 10 high turnover ratio regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Turnover ratio(%)']].nlargest(10, 'Turnover ratio(%)')

Top 10 high turnover ratio regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Turnover ratio(%)
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,193.96,841.00
31,DSP Focus Fund - Regular Plan,2,1955.63,57.45,9.64,11.96,11.11,12.59,129.00
19,Aditya Birla Sun Life Focused Equity Fund - Re...,3,4593.49,56.45,10.66,13.06,13.11,38.96,76.00
7,HDFC Focused 30 Fund,1,656.96,61.40,4.38,9.69,8.61,59.23,39.35

## Standard Deviation (SD)

The standard deviation of a stock or a mutual fund represents the riskiness of the stock or the mutual fund.

Standard Deviation is a percentage, expressed as an annualised figure.

Higher the standard Deviation, higher is the volatility of the asset. Higher the volatility, higher is the risk.

Do note, volatility or Standard Deviation should not worry you. Markets are volatile, and equities are volatile, mutual funds are volatile; this is the very nature of markets. So if you canâ€™t fathom watching your investment see-saw between gains and loss, then perhaps you should reconsider your investment decision inequities.

In [178]:
# Top 10 low standard deviation regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Standard Deviation'] > 0)]
print("Top 10 low standard deviation regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Standard Deviation']].nsmallest(10, 'Standard Deviation')

Top 10 low standard deviation regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Standard Deviation
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,193.96,18.58
14,Axis Focused 25 Fund,3,15007.35,58.49,12.85,17.47,0.00,41.26,20.01
9,Mahindra Manulife Focused Equity Yojana - Regu...,0,296.73,0.00,0.00,0.00,0.00,54.39,20.13
11,IDFC Focused Equity Fund - Regular Plan,2,1377.23,49.07,5.46,12.99,9.16,77.44,20.50
16,Sundaram Select Focus,3,1217.67,49.08,11.07,14.24,10.41,51.40,20.66
5,Franklin India Focused Equity Fund,3,7359.87,75.57,12.22,14.08,15.70,90.74,21.01
7,HDFC Focused 30 Fund,1,656.96,61.40,4.38,9.69,8.61,59.23,21.44
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,64.79,12.62,13.47,11.52,231.08,21.58

In [179]:
# Top 10 high standard deviation regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Standard Deviation'] > 0)]
print("Top 10 high standard deviation regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Standard Deviation']].nlargest(10, 'Standard Deviation')

Top 10 high standard deviation regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Standard Deviation
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,64.79,12.62,13.47,11.52,231.08,21.58
7,HDFC Focused 30 Fund,1,656.96,61.40,4.38,9.69,8.61,59.23,21.44
5,Franklin India Focused Equity Fund,3,7359.87,75.57,12.22,14.08,15.70,90.74,21.01
16,Sundaram Select Focus,3,1217.67,49.08,11.07,14.24,10.41,51.40,20.66
11,IDFC Focused Equity Fund - Regular Plan,2,1377.23,49.07,5.46,12.99,9.16,77.44,20.50
9,Mahindra Manulife Focused Equity Yojana - Regu...,0,296.73,0.00,0.00,0.00,0.00,54.39,20.13
14,Axis Focused 25 Fund,3,15007.35,58.49,12.85,17.47,0.00,41.26,20.01
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,193.96,18.58

## Beta Ratios

A Beta Ratio in Mutual Funds offers investors the data on the degree of the volatility a Mutual Fund displays in response to market fluctuations. An investor can determine which fund would be best suited to meet his/her financial objectives.

Suppose, the beta ratio of a specific Mutual Fund is 0.7 or 70%; it means the fund is 0.3 or 30% less volatile than the benchmark index. A Beta ratio value of 1 indicates a lower risk and lower growth potential compared to ratios at par or above 1.

Investors with a low-risk appetite would always prefer a lower beta ratio in Mutual Funds as it indicates a steadier response to a volatile market condition. Similarly, investors with the investment objective of higher returns would prefer beta ratios of 1 or more than 1.

In [180]:
# Top 10 low beta regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 0)]
print("Top 10 low beta regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']].nsmallest(10, 'Beta')

Top 10 low beta regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
16,Sundaram Select Focus,3,1217.67,49.08,11.07,14.24,10.41,51.40,0.80
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,193.96,0.80
14,Axis Focused 25 Fund,3,15007.35,58.49,12.85,17.47,0.00,41.26,0.87
9,Mahindra Manulife Focused Equity Yojana - Regu...,0,296.73,0.00,0.00,0.00,0.00,54.39,0.88
5,Franklin India Focused Equity Fund,3,7359.87,75.57,12.22,14.08,15.70,90.74,0.90
11,IDFC Focused Equity Fund - Regular Plan,2,1377.23,49.07,5.46,12.99,9.16,77.44,0.94
7,HDFC Focused 30 Fund,1,656.96,61.40,4.38,9.69,8.61,59.23,0.95
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,64.79,12.62,13.47,11.52,231.08,0.96

In [181]:
# Top 10 high beta regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 0)]
print("Top 10 high beta regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']].nlargest(10, 'Beta')

Top 10 high beta regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,64.79,12.62,13.47,11.52,231.08,0.96
7,HDFC Focused 30 Fund,1,656.96,61.40,4.38,9.69,8.61,59.23,0.95
11,IDFC Focused Equity Fund - Regular Plan,2,1377.23,49.07,5.46,12.99,9.16,77.44,0.94
5,Franklin India Focused Equity Fund,3,7359.87,75.57,12.22,14.08,15.70,90.74,0.90
9,Mahindra Manulife Focused Equity Yojana - Regu...,0,296.73,0.00,0.00,0.00,0.00,54.39,0.88
14,Axis Focused 25 Fund,3,15007.35,58.49,12.85,17.47,0.00,41.26,0.87
16,Sundaram Select Focus,3,1217.67,49.08,11.07,14.24,10.41,51.40,0.80
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,193.96,0.80

In [182]:
# Funds with 'Beta' lesser than 1.00
mf_tr = regular_mf.loc[(regular_mf['Beta'] < 1.00) & (regular_mf['Beta'] != 0.00)]
print("Funds with 'Beta' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']]

Funds with 'Beta' lesser than 1.00 are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Beta
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,64.79,12.62,13.47,11.52,231.08,0.96
16,Sundaram Select Focus,3,1217.67,49.08,11.07,14.24,10.41,51.40,0.80
5,Franklin India Focused Equity Fund,3,7359.87,75.57,12.22,14.08,15.70,90.74,0.90
14,Axis Focused 25 Fund,3,15007.35,58.49,12.85,17.47,0.00,41.26,0.87
11,IDFC Focused Equity Fund - Regular Plan,2,1377.23,49.07,5.46,12.99,9.16,77.44,0.94
7,HDFC Focused 30 Fund,1,656.96,61.40,4.38,9.69,8.61,59.23,0.95
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,193.96,0.80
9,Mahindra Manulife Focused Equity Yojana - Regu...,0,296.73,0.00,0.00,0.00,0.00,54.39,0.88

In [183]:
# Funds with 'Beta' greater than 1.00
mf_tr = regular_mf.loc[(regular_mf['Beta'] > 1.00) & (regular_mf['Beta'] != 0.00)]
print("Funds with 'Beta' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Beta']]

Funds with 'Beta' lesser than 1.00 are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Beta]
Index: []

## What is Sharpe Ratio?

Sharpe Ratio of a mutual fund reveals its potential risk-adjusted returns. The risk-adjusted returns are the returns earned by an investment over the returns generated by any risk-free asset such as a fixed deposit. However, higher returns indicate extra risk. Higher Sharpe Ratio means greater returns from an investment but with a higher risk level. Therefore, it justifies the underlying volatility of the funds. The investors aiming for higher returns will have to invest in funds with higher risk factors.

Investments with less than 1.00 Sharpe Ratio do not generate high returns. Contrarily, investment with Sharpe Ratio of 1.00 to 3.00 or above have higher returns subsequently.

In [184]:
# Top 10 low sharpe ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 0)]
print("Top 10 low 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']].nsmallest(10, 'Sharpe Ratio')

Top 10 low 'Sharpe Ratio' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,64.79,12.62,13.47,11.52,231.08,0.09
5,Franklin India Focused Equity Fund,3,7359.87,75.57,12.22,14.08,15.70,90.74,0.13
11,IDFC Focused Equity Fund - Regular Plan,2,1377.23,49.07,5.46,12.99,9.16,77.44,0.25
7,HDFC Focused 30 Fund,1,656.96,61.40,4.38,9.69,8.61,59.23,0.39
9,Mahindra Manulife Focused Equity Yojana - Regu...,0,296.73,0.00,0.00,0.00,0.00,54.39,0.42
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,193.96,0.45
14,Axis Focused 25 Fund,3,15007.35,58.49,12.85,17.47,0.00,41.26,0.46
16,Sundaram Select Focus,3,1217.67,49.08,11.07,14.24,10.41,51.40,0.49

In [185]:
# Top 10 high sharpe ratio regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 0)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']].nlargest(10, 'Sharpe Ratio')

Top 10 high 'Sharpe Ratio' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
16,Sundaram Select Focus,3,1217.67,49.08,11.07,14.24,10.41,51.40,0.49
14,Axis Focused 25 Fund,3,15007.35,58.49,12.85,17.47,0.00,41.26,0.46
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,193.96,0.45
9,Mahindra Manulife Focused Equity Yojana - Regu...,0,296.73,0.00,0.00,0.00,0.00,54.39,0.42
7,HDFC Focused 30 Fund,1,656.96,61.40,4.38,9.69,8.61,59.23,0.39
11,IDFC Focused Equity Fund - Regular Plan,2,1377.23,49.07,5.46,12.99,9.16,77.44,0.25
5,Franklin India Focused Equity Fund,3,7359.87,75.57,12.22,14.08,15.70,90.74,0.13
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,64.79,12.62,13.47,11.52,231.08,0.09

In [186]:
# Funds with 'Sharpe Ratio' greater than or equal to 3.00
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] >= 3.00)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [187]:
# Funds with 'Sharpe Ratio' greater than to 2.00 & lesser than 2.99
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 2.00) & (regular_mf['Sharpe Ratio'] < 2.99)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [188]:
# Funds with 'Sharpe Ratio' greater than to 1.00 & lesser than 1.99
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] > 1.00) & (regular_mf['Sharpe Ratio'] < 1.99)]
print("Top 10 high 'Sharpe Ratio' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Top 10 high 'Sharpe Ratio' regular mutual funds are :

Empty DataFrame
Columns: [Scheme Name, Crisil Rank, AuM (Cr), 1Y_RTN(%), 3Y_RTN(%), 5Y_RTN(%), 10Y_RTN(%), NAV, Sharpe Ratio]
Index: []

In [189]:
# Funds with 'Sharpe Ratio' lesser than 1.00
mf_tr = regular_mf.loc[(regular_mf['Sharpe Ratio'] != 0.00) & (regular_mf['Sharpe Ratio'] < 1.00)]
print("Funds with 'Sharpe Ratio' lesser than 1.00 are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)',
            '5Y_RTN(%)', '10Y_RTN(%)', 'NAV', 'Sharpe Ratio']]

Funds with 'Sharpe Ratio' lesser than 1.00 are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,64.79,12.62,13.47,11.52,231.08,0.09
16,Sundaram Select Focus,3,1217.67,49.08,11.07,14.24,10.41,51.40,0.49
5,Franklin India Focused Equity Fund,3,7359.87,75.57,12.22,14.08,15.70,90.74,0.13
14,Axis Focused 25 Fund,3,15007.35,58.49,12.85,17.47,0.00,41.26,0.46
11,IDFC Focused Equity Fund - Regular Plan,2,1377.23,49.07,5.46,12.99,9.16,77.44,0.25
7,HDFC Focused 30 Fund,1,656.96,61.40,4.38,9.69,8.61,59.23,0.39
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,193.96,0.45
9,Mahindra Manulife Focused Equity Yojana - Regu...,0,296.73,0.00,0.00,0.00,0.00,54.39,0.42

In [190]:
# Extracting funds which have 3Y Return', '5Y Return' & '10Y Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_SIP_RTN(%)'] > 25) & (regular_mf['5Y_SIP_RTN(%)'] > 25) &
                            (regular_mf['10Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '3Y SIP Return', '5Y SIP Return' & '10Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y SIP Return', '5Y SIP Return' & '10Y SIP Return' greater than 25% is: 6 Funds

,Scheme Name,Crisil Rank,AuM (Cr),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,41.38,47.45,143.79,231.08,0.09,0.0,21.58,0.96
5,Franklin India Focused Equity Fund,3,7359.87,37.82,45.68,138.56,90.74,0.13,0.0,21.01,0.90
19,Aditya Birla Sun Life Focused Equity Fund - Re...,3,4593.49,35.23,50.76,138.88,38.96,0.00,76.0,0.00,0.00
29,BNP Paribas Focused 25 Equity Fund,2,185.59,28.48,35.94,94.38,12.61,0.00,0.0,0.00,0.00
1,Quant Focused Fund,0,12.12,54.66,63.95,170.41,193.96,0.45,841.0,18.58,0.80
9,Mahindra Manulife Focused Equity Yojana - Regu...,0,296.73,37.77,45.57,98.46,54.39,0.42,0.0,20.13,0.88

In [191]:
# Extracting funds which have 3Y Return' & '5Y Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['3Y_SIP_RTN(%)'] > 25) & (regular_mf['5Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '3Y SIP Return' & '5Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '3Y_SIP_RTN(%)', '5Y_SIP_RTN(%)', '10Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y SIP Return' & '5Y SIP Return' greater than 25% is: 13 Funds

,Scheme Name,Crisil Rank,AuM (Cr),3Y_SIP_RTN(%),5Y_SIP_RTN(%),10Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
27,Nippon India Focused Equity Fund,5,4897.48,30.67,39.59,0.00,24.24,0.00,0.00,0.00,0.00
33,Principal Focused Multicap Fund,4,539.05,34.35,47.94,0.00,12.56,0.00,0.00,0.00,0.00
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,41.38,47.45,143.79,231.08,0.09,0.00,21.58,0.96
5,Franklin India Focused Equity Fund,3,7359.87,37.82,45.68,138.56,90.74,0.13,0.00,21.01,0.90
19,Aditya Birla Sun Life Focused Equity Fund - Re...,3,4593.49,35.23,50.76,138.88,38.96,0.00,76.00,0.00,0.00
11,IDFC Focused Equity Fund - Regular Plan,2,1377.23,26.06,28.72,0.00,77.44,0.25,0.00,20.50,0.94
31,DSP Focus Fund - Regular Plan,2,1955.63,29.93,46.27,0.00,12.59,0.00,129.00,0.00,0.00
29,BNP Paribas Focused 25 Equity Fund,2,185.59,28.48,35.94,94.38,12.61,0.00,0.00,0.00,0.00
7,HDFC Focused 30 Fund,1,656.96,40.21,49.88,0.00,59.23,0.39,39.35,21.44,0.95
17,Tata Focused Equity Fund - Regular Plan,0,1156.11,37.51,55.05,0.00,46.12,0.00,0.00,0.00,0.00
1,Quant Focused Fund,0,12.12,54.66,63.95,170.41,193.96,0.45,841.00,18.58,0.80
9,Mahindra Manulife Focused Equity Yojana - Regu...,0,296.73,37.77,45.57,98.46,54.39,0.42,0.00,20.13,0.88
37,Kotak Focused Equity Fund - Regular Plan,0,1832.53,31.74,42.96,0.00,13.43,0.00,0.00,0.00,0.00

In [192]:
# Extracting funds which have '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25%
mf_rtn_com = regular_mf.loc[(regular_mf['1Y_SIP_RTN(%)'] > 25) & (regular_mf['2Y_SIP_RTN(%)'] > 25) &
                            (regular_mf['3Y_SIP_RTN(%)'] > 25)]
print("No. of funds having '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25% is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_SIP_RTN(%)', '2Y_SIP_RTN(%)', '3Y_SIP_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '1Y SIP Return', '2Y SIP Return' & '3Y SIP Return' greater than 25% is: 6 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_SIP_RTN(%),2Y_SIP_RTN(%),3Y_SIP_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,33.82,40.40,41.38,231.08,0.09,0.00,21.58,0.96
5,Franklin India Focused Equity Fund,3,7359.87,32.85,35.54,37.82,90.74,0.13,0.00,21.01,0.90
11,IDFC Focused Equity Fund - Regular Plan,2,1377.23,26.84,27.22,26.06,77.44,0.25,0.00,20.50,0.94
7,HDFC Focused 30 Fund,1,656.96,27.80,37.92,40.21,59.23,0.39,39.35,21.44,0.95
1,Quant Focused Fund,0,12.12,41.86,52.41,54.66,193.96,0.45,841.00,18.58,0.80
9,Mahindra Manulife Focused Equity Yojana - Regu...,0,296.73,26.91,36.21,37.77,54.39,0.42,0.00,20.13,0.88

In [193]:
# Top 10 high AuM (Cr) regular mutual funds are
#mf_tr = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 0)]
print("Top 10 high 'AuM (Cr)' regular mutual funds are :")
mf_tr =  mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)',
       'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']].nlargest(10, 'AuM (Cr)')
mf_tr

Top 10 high 'AuM (Cr)' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
14,Axis Focused 25 Fund,3,15007.35,58.49,12.85,17.47,0.00,0.46,0.00,20.01,0.87
5,Franklin India Focused Equity Fund,3,7359.87,75.57,12.22,14.08,15.70,0.13,0.00,21.01,0.90
11,IDFC Focused Equity Fund - Regular Plan,2,1377.23,49.07,5.46,12.99,9.16,0.25,0.00,20.50,0.94
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,64.79,12.62,13.47,11.52,0.09,0.00,21.58,0.96
16,Sundaram Select Focus,3,1217.67,49.08,11.07,14.24,10.41,0.49,0.00,20.66,0.80
7,HDFC Focused 30 Fund,1,656.96,61.40,4.38,9.69,8.61,0.39,39.35,21.44,0.95
9,Mahindra Manulife Focused Equity Yojana - Regu...,0,296.73,0.00,0.00,0.00,0.00,0.42,0.00,20.13,0.88
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,0.45,841.00,18.58,0.80

In [194]:
# Top 10 low AuM (Cr) regular mutual funds are
mf_tr = regular_mf.loc[(regular_mf['5Y_RTN(%)'] > 0)]
print("Top 10 low 'AuM (Cr)' regular mutual funds are :")
mf_tr[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)',
       'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']].nsmallest(10, 'AuM (Cr)')

Top 10 low 'AuM (Cr)' regular mutual funds are :

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,0.45,841.00,18.58,0.80
39,JM Core 11 Fund,1,46.12,49.47,5.25,12.62,9.95,0.00,0.00,0.00,0.00
33,Principal Focused Multicap Fund,4,539.05,58.25,14.59,15.82,12.61,0.00,0.00,0.00,0.00
7,HDFC Focused 30 Fund,1,656.96,61.40,4.38,9.69,8.61,0.39,39.35,21.44,0.95
16,Sundaram Select Focus,3,1217.67,49.08,11.07,14.24,10.41,0.49,0.00,20.66,0.80
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,64.79,12.62,13.47,11.52,0.09,0.00,21.58,0.96
11,IDFC Focused Equity Fund - Regular Plan,2,1377.23,49.07,5.46,12.99,9.16,0.25,0.00,20.50,0.94
21,Motilal Oswal Focused 25 Fund,3,1620.69,48.49,11.40,14.36,0.00,0.00,0.00,0.00,0.00
35,IIFL Focused Equity Fund,5,1675.38,66.12,18.49,18.09,0.00,0.00,0.00,0.00,0.00
31,DSP Focus Fund - Regular Plan,2,1955.63,57.45,9.64,11.96,11.11,0.00,129.00,0.00,0.00

In [195]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 0) & (regular_mf['AuM (Cr)'] < 500) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds returns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds returns 10% in 3year & 5year period which have AuM in between 0Crs to 500Crs is: 1 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
1,Quant Focused Fund,0,12.12,81.23,15.09,15.87,16.65,193.96,0.45,841.0,18.58,0.8

In [196]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 500Crs to 1000Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 500) & (regular_mf['AuM (Cr)'] < 1000) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is:", len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds having '3Y Return', '5Y Return' & '10Y Return' greater than 10% is: 1 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
33,Principal Focused Multicap Fund,4,539.05,58.25,14.59,15.82,12.61,12.56,0.0,0.0,0.0,0.0

In [197]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 1000) & (regular_mf['AuM (Cr)'] < 1500) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds returns 10% in 3year & 5year period which have AuM in between 1000Crs to 1500Crs is: 2 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
3,ICICI Prudential Focused Equity Fund - Regular...,4,1316.11,64.79,12.62,13.47,11.52,231.08,0.09,0.0,21.58,0.96
16,Sundaram Select Focus,3,1217.67,49.08,11.07,14.24,10.41,51.40,0.49,0.0,20.66,0.80

In [198]:
# Extracting funds returns 10% in 3year & 5year period which have AuM in between 1500 to 20000Crs
mf_rtn_com = regular_mf.loc[(regular_mf['AuM (Cr)'] > 1500) & (regular_mf['AuM (Cr)'] < 20000) &
                            (regular_mf['3Y_RTN(%)'] > 10) & (regular_mf['5Y_RTN(%)'] > 10)]
print("No. of funds returns 10% in 3year & 5year period which have AuM in between 1500Crs to 20000Crs is:",
      len(mf_rtn_com.index),
      'Funds')
mf_rtn_com[['Scheme Name', 'Crisil Rank', 'AuM (Cr)', '1Y_RTN(%)','3Y_RTN(%)', '5Y_RTN(%)', '10Y_RTN(%)', 'NAV',
           'Sharpe Ratio', 'Turnover ratio(%)', 'Standard Deviation', 'Beta']]

No. of funds returns 10% in 3year & 5year period which have AuM in between 1500Crs to 20000Crs is: 7 Funds

,Scheme Name,Crisil Rank,AuM (Cr),1Y_RTN(%),3Y_RTN(%),5Y_RTN(%),10Y_RTN(%),NAV,Sharpe Ratio,Turnover ratio(%),Standard Deviation,Beta
27,Nippon India Focused Equity Fund,5,4897.48,80.30,11.03,14.79,15.63,24.24,0.00,0.0,0.00,0.00
35,IIFL Focused Equity Fund,5,1675.38,66.12,18.49,18.09,0.00,12.51,0.00,0.0,0.00,0.00
42,SBI Focused Equity Fund - Regular Plan,4,14766.83,56.74,12.18,15.58,17.00,13.49,0.00,0.0,0.00,0.00
21,Motilal Oswal Focused 25 Fund,3,1620.69,48.49,11.40,14.36,0.00,97.84,0.00,0.0,0.00,0.00
5,Franklin India Focused Equity Fund,3,7359.87,75.57,12.22,14.08,15.70,90.74,0.13,0.0,21.01,0.90
14,Axis Focused 25 Fund,3,15007.35,58.49,12.85,17.47,0.00,41.26,0.46,0.0,20.01,0.87
19,Aditya Birla Sun Life Focused Equity Fund - Re...,3,4593.49,56.45,10.66,13.06,13.11,38.96,0.00,76.0,0.00,0.00